/** <module> Queryable misconception registry
 *
 * A misconception registry entry is an attested student move, not just a
 * generated deformation. Each exported entry names its target operation,
 * literature source, commitment made, and entitlement lacked.
 */
:- module(misconception_registry,
          [ misconception_registry_entry/5,
            misconception_term/2,
            misconception_gap/4,
            incompatibility_with/2,
            incompatibility_with_witness/3,
            action_corpus_binding_row_witness/2,
            misconception_batch_row_witness/2,
            csv_rows_with_arity_witness/4
          ]).

:- use_module(library(csv)).
:- use_module(math(action_automata_registry),
              [ action_automaton_pair/4,
                action_automaton_vocabulary/3
              ]).
:- use_module(learner(deontic_scorekeeper), []).
:- use_module(misconceptions(generative_misconceptions),
              [ misconception/1
              ]).
:- use_module(misconceptions(literature_vocabulary), []).
:- use_module(misconceptions(benny), []).
:- use_module(misconceptions(benny_demo), []).
:- use_module(misconceptions(misconceptions_combinatorial), []).
:- use_module(misconceptions(misconceptions_decimal), []).
:- use_module(misconceptions(misconceptions_decimal_batch_1), []).
:- use_module(misconceptions(misconceptions_decimal_batch_2), []).
:- use_module(misconceptions(misconceptions_discrete), []).
:- use_module(misconceptions(misconceptions_extended_arithmetic), []).
:- use_module(misconceptions(misconceptions_fraction), []).
:- use_module(misconceptions(misconceptions_fraction_batch_1), []).
:- use_module(misconceptions(misconceptions_fraction_batch_2), []).
:- use_module(misconceptions(misconceptions_fraction_batch_3), []).
:- use_module(misconceptions(misconceptions_fraction_batch_4), []).
:- use_module(misconceptions(misconceptions_fraction_batch_5), []).
:- use_module(misconceptions(misconceptions_fraction_batch_6), []).
:- use_module(misconceptions(misconceptions_fraction_batch_7), []).
:- use_module(misconceptions(misconceptions_geometry), []).
:- use_module(misconceptions(misconceptions_integer), []).
:- use_module(misconceptions(misconceptions_measurement), []).
:- use_module(misconceptions(misconceptions_measurement_batch_1), []).
:- use_module(misconceptions(misconceptions_measurement_batch_2), []).
:- use_module(misconceptions(misconceptions_percent_batch_1), []).
:- use_module(misconceptions(misconceptions_ratio), []).
:- use_module(misconceptions(misconceptions_rational), []).
:- use_module(misconceptions(misconceptions_whole_number), []).
:- use_module(misconceptions(misconceptions_whole_number_batch_1), []).
:- use_module(misconceptions(misconceptions_whole_number_batch_2), []).
:- use_module(misconceptions(misconceptions_whole_number_batch_3), []).
:- use_module(misconceptions(misconceptions_whole_number_batch_4), []).
:- use_module(misconceptions(misconceptions_whole_number_batch_5), []).

:- dynamic cached_action_corpus_binding_row/1.
:- dynamic cached_action_corpus_binding_row_source/2.
:- dynamic cached_batch_row/1.
:- dynamic cached_batch_row_source/2.
:- multifile deontic_scorekeeper:incompatible/2.


%!  misconception_registry_entry(?Name, ?TargetOperation, ?Citation,
%!                               ?CommitmentMade, ?EntitlementLacked) is nondet.
%
%   True for literature-attested misconceptions that are also generated by
%   the strategy deformation registry.
misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement) :-
    attested_misconception(Name, Operation, Productive, Family, Citation),
    action_automaton_pair(Operation, Productive, Name, Family),
    Commitment = deformed_action(Productive, Name, Family),
    Entitlement = strategy(Operation, Productive),
    misconception(Commitment).
misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement) :-
    harness_backed_misconception(Source,
                                 _Domain,
                                 Name,
                                 Rule,
                                 Input,
                                 Expected,
                                 Operation,
                                 Citation),
    rule_result(Rule, Input, Got),
    Got \=@= Expected,
    Commitment = result_of(Name, Source, Got),
    Entitlement = result_of(Name, Source, Expected).
misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement) :-
    harness_backed_misconception(Source,
                                 _Domain,
                                 Name,
                                 Rule,
                                 Input,
                                 Expected,
                                 Operation,
                                 Citation),
    \+ ( rule_result(Rule, Input, Got),
         Got \=@= Expected
       ),
    Commitment = documented_batch_misconception(Name, Source, Input, Rule),
    Entitlement = expected_result(Name, Source, Expected).
misconception_registry_entry(Name, Operation, citation(BibtexKey, Note), Commitment, Entitlement) :-
    test_harness:arith_misconception(Source, Domain, Name, skip, Input, Expected),
    Source = db_row(_),
    batch_row_for_source(Source, Domain, Operation, BibtexKey, Note),
    BibtexKey \== '',
    Commitment = documented_batch_misconception(Name, Source, Input, skip),
    Entitlement = expected_result(Name, Source, Expected).
misconception_registry_entry(Name, Operation, citation(BibtexKey, Note), Commitment, Entitlement) :-
    misconception_batch_row(row(RowId,
                                ErrorDescription,
                                _Example,
                                Domain,
                                Topic,
                                _Subtopic,
                                _Population,
                                _GradeBand,
                                BibtexKey,
                                _Authors,
                                _Year,
                                _Journal,
                                _Orientation,
                                _Salience,
                                _PageRefs,
                                _LocalPdfPath)),
    BibtexKey \== '',
    row_id_matches(RowId, Id),
    \+ test_harness:arith_misconception(db_row(Id), _, _, _, _, _),
    normalize_operation(Topic, Domain, Operation),
    batch_row_name(Id, Name),
    text_to_string(ErrorDescription, Note),
    Commitment = documented_batch_misconception(Name, db_row(Id), Note, Operation),
    Entitlement = expected_mathematical_control(Name, db_row(Id), Operation).


%!  misconception_term(?Name, ?Commitment) is nondet.
misconception_term(Name, Commitment) :-
    misconception_registry_entry(Name, _, _, Commitment, _).


%!  incompatibility_with(?Move, ?Conflict) is nondet.
%
%   Reports the strategy-level commitment a deformation cannot sustain. This
%   predicate is intentionally grounded in registered productive/deformation
%   pairs, so it fails when the action registry has no conflicting move.
incompatibility_with(Move, Conflict) :-
    incompatibility_with_witness(Move, Conflict, _).


%!  incompatibility_with_witness(?Move, ?Conflict, -Witness) is nondet.
%
%   True when the registry can derive an incompatibility and explain which
%   finite registry surface proved it. This is a closed-world finite registry
%   check over loaded action automata, cited misconception rows, harness rows,
%   and geometry misconception facts; it is not an open-ended semantic
%   incompatibility prover.
incompatibility_with_witness(Name,
                             strategy(Operation, Productive),
                             Witness) :-
    atom(Name),
    action_automaton_pair(Operation, Productive, Name, Family),
    registry_incompatibility_witness(
        action_automaton_deformation,
        Name,
        strategy(Operation, Productive),
        _{ operation: Operation,
           productive: Productive,
           deformation: Name,
           family: Family },
        Witness).
incompatibility_with_witness(Name, Entitlement, Witness) :-
    atom(Name),
    registered_name_entitlement_witness(Name, Entitlement, Evidence),
    registry_incompatibility_witness(
        registered_name_entitlement,
        Name,
        Entitlement,
        Evidence,
        Witness).
incompatibility_with_witness(Name, Entitlement, Witness) :-
    atom(Name),
    misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement),
    Commitment \=@= Entitlement,
    citation_witness(Citation, CitationWitness),
    registry_incompatibility_witness(
        registry_entry_lacked_entitlement,
        Name,
        Entitlement,
        _{ operation: Operation,
           commitment: Commitment,
           entitlement: Entitlement,
           citation: CitationWitness },
        Witness0),
    Witness = Witness0.put(_{name: Name,
                             operation: Operation,
                             citation: CitationWitness}).
incompatibility_with_witness(misconception(Name),
                             strategy(Operation, Productive),
                             Witness) :-
    action_automaton_pair(Operation, Productive, Name, Family),
    registry_incompatibility_witness(
        action_automaton_deformation,
        misconception(Name),
        strategy(Operation, Productive),
        _{ operation: Operation,
           productive: Productive,
           deformation: Name,
           family: Family },
        Witness).
incompatibility_with_witness(misconception(Name), Entitlement, Witness) :-
    registered_name_entitlement_witness(Name, Entitlement, Evidence),
    registry_incompatibility_witness(
        registered_name_entitlement,
        misconception(Name),
        Entitlement,
        Evidence,
        Witness).
incompatibility_with_witness(misconception(Name), Entitlement, Witness) :-
    misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement),
    Commitment \=@= Entitlement,
    citation_witness(Citation, CitationWitness),
    registry_incompatibility_witness(
        registry_entry_lacked_entitlement,
        misconception(Name),
        Entitlement,
        _{ operation: Operation,
           commitment: Commitment,
           entitlement: Entitlement,
           citation: CitationWitness },
        Witness0),
    Witness = Witness0.put(_{name: Name,
                             operation: Operation,
                             citation: CitationWitness}).
incompatibility_with_witness(deformed_action(Productive, Deformation, Family),
                             strategy(Operation, Productive),
                             Witness) :-
    action_automaton_pair(Operation, Productive, Deformation, Family),
    registry_incompatibility_witness(
        deformed_action_lacks_productive_strategy,
        deformed_action(Productive, Deformation, Family),
        strategy(Operation, Productive),
        _{ operation: Operation,
           productive: Productive,
           deformation: Deformation,
           family: Family },
        Witness).
incompatibility_with_witness(strategy(Operation, Deformation),
                             strategy(Operation, Productive),
                             Witness) :-
    action_automaton_pair(Operation, Productive, Deformation, Family),
    registry_incompatibility_witness(
        strategy_deformation_lacks_productive_strategy,
        strategy(Operation, Deformation),
        strategy(Operation, Productive),
        _{ operation: Operation,
           productive: Productive,
           deformation: Deformation,
           family: Family },
        Witness).
incompatibility_with_witness(strategy(Operation, Productive),
                             misconception(Deformation),
                             Witness) :-
    action_automaton_pair(Operation, Productive, Deformation, Family),
    registry_incompatibility_witness(
        productive_strategy_conflicts_with_deformation,
        strategy(Operation, Productive),
        misconception(Deformation),
        _{ operation: Operation,
           productive: Productive,
           deformation: Deformation,
           family: Family },
        Witness).
incompatibility_with_witness(Commitment, Entitlement, Witness) :-
    registry_commitment_name(Commitment, Name),
    misconception_registry_entry(Name, Operation, Citation, Commitment, Entitlement),
    Commitment \=@= Entitlement,
    citation_witness(Citation, CitationWitness),
    registry_incompatibility_witness(
        registry_entry_lacked_entitlement,
        Commitment,
        Entitlement,
        _{ operation: Operation,
           commitment: Commitment,
           entitlement: Entitlement,
           citation: CitationWitness },
        Witness0),
    Witness = Witness0.put(_{name: Name,
                             operation: Operation,
                             citation: CitationWitness}).
incompatibility_with_witness(strategy(Operation, Kind),
                             missing_entitlement(strategy(Operation, Kind),
                                                 vocabulary(Vocabulary)),
                             Witness) :-
    action_automaton_vocabulary(Operation, Kind, Vocabulary),
    \+ action_automaton_pair(Operation, Kind, _, _),
    \+ action_automaton_pair(Operation, _, Kind, _),
    registry_incompatibility_witness(
        strategy_kind_without_registered_pair,
        strategy(Operation, Kind),
        missing_entitlement(strategy(Operation, Kind), vocabulary(Vocabulary)),
        _{ operation: Operation,
           kind: Kind,
           vocabulary: Vocabulary },
        Witness).
incompatibility_with_witness(result_of(Name, Source, Got),
                             result_of(Name, Source, Expected),
                             Witness) :-
    Got \=@= Expected,
    registry_incompatibility_witness(
        harness_result_mismatch,
        result_of(Name, Source, Got),
        result_of(Name, Source, Expected),
        _{ name: Name,
           source: Source,
           got: Got,
           expected: Expected },
        Witness).
incompatibility_with_witness(documented_batch_misconception(Name, Source, Input, Rule),
                             expected_result(Name, Source, Expected),
                             Witness) :-
    nonvar(Expected),
    registry_incompatibility_witness(
        documented_batch_expected_result,
        documented_batch_misconception(Name, Source, Input, Rule),
        expected_result(Name, Source, Expected),
        _{ name: Name,
           source: Source,
           input: Input,
           rule: Rule,
           expected: Expected },
        Witness).
incompatibility_with_witness(documented_batch_misconception(Name, Source, Note, Operation),
                             expected_mathematical_control(Name, Source, Operation),
                             Witness) :-
    registry_incompatibility_witness(
        documented_batch_expected_control,
        documented_batch_misconception(Name, Source, Note, Operation),
        expected_mathematical_control(Name, Source, Operation),
        _{ name: Name,
           source: Source,
           note: Note,
           operation: Operation },
        Witness).
incompatibility_with_witness(geometry_misconception(Name),
                             geometry_concept(ConceptId),
                             Witness) :-
    geometry_misconception_concept(Name, ConceptId),
    registry_incompatibility_witness(
        geometry_misconception_concept_conflict,
        geometry_misconception(Name),
        geometry_concept(ConceptId),
        _{ misconception: Name,
           concept: ConceptId },
        Witness).
incompatibility_with_witness(geometry_concept(ConceptId),
                             geometry_misconception(Name),
                             Witness) :-
    geometry_misconception_concept(Name, ConceptId),
    registry_incompatibility_witness(
        geometry_concept_misconception_conflict,
        geometry_concept(ConceptId),
        geometry_misconception(Name),
        _{ misconception: Name,
           concept: ConceptId },
        Witness).


deontic_scorekeeper:incompatible(Move, Conflict) :-
    deontic_registry_incompatibility_witness(Move, Conflict, _).


deontic_registry_incompatibility_witness(deformed_action(Productive, Deformation, Family),
                                         strategy(Operation, Productive),
                                         Witness) :-
    incompatibility_with_witness(deformed_action(Productive, Deformation, Family),
                                 strategy(Operation, Productive),
                                 Witness).
deontic_registry_incompatibility_witness(misconception(Name), Entitlement, Witness) :-
    incompatibility_with_witness(misconception(Name), Entitlement, Witness),
    Witness.rule == registry_entry_lacked_entitlement.
deontic_registry_incompatibility_witness(Name, Entitlement, Witness) :-
    atom(Name),
    incompatibility_with_witness(Name, Entitlement, Witness),
    memberchk(Witness.rule,
              [registered_name_entitlement, registry_entry_lacked_entitlement]).
deontic_registry_incompatibility_witness(strategy(Operation, Kind),
                                         missing_entitlement(strategy(Operation, Kind),
                                                             vocabulary(Vocabulary)),
                                         Witness) :-
    incompatibility_with_witness(strategy(Operation, Kind),
                                 missing_entitlement(strategy(Operation, Kind),
                                                     vocabulary(Vocabulary)),
                                 Witness).
deontic_registry_incompatibility_witness(documented_batch_misconception(Name, Source, Input, Rule),
                                         expected_result(Name, Source, Expected),
                                         Witness) :-
    incompatibility_with_witness(documented_batch_misconception(Name, Source, Input, Rule),
                                 expected_result(Name, Source, Expected),
                                 Witness).
deontic_registry_incompatibility_witness(documented_batch_misconception(Name, Source, Note, Operation),
                                         expected_mathematical_control(Name, Source, Operation),
                                         Witness) :-
    incompatibility_with_witness(documented_batch_misconception(Name, Source, Note, Operation),
                                 expected_mathematical_control(Name, Source, Operation),
                                 Witness).
deontic_registry_incompatibility_witness(geometry_misconception(Name),
                                         geometry_concept(ConceptId),
                                         Witness) :-
    incompatibility_with_witness(geometry_misconception(Name),
                                 geometry_concept(ConceptId),
                                 Witness).


registry_incompatibility_witness(Rule, Move, Conflict, Evidence,
                                 _{ kind: misconception_registry_incompatibility,
                                    rule: Rule,
                                    move: Move,
                                    conflict: Conflict,
                                    source: closed_world_finite_misconception_registry,
                                    evidence: Evidence }).


registered_name_entitlement_witness(Name, result_of(Name, Source, Expected),
                                    _{ rule: executable_harness_expected_result,
                                       name: Name,
                                       source: Source,
                                       expected: Expected,
                                       harness_rule: Rule }) :-
    nonvar(Source),
    nonvar(Expected),
    test_harness:arith_misconception(Source, _Domain, Name, Rule, _Input, Expected),
    Rule \== skip.
registered_name_entitlement_witness(Name, expected_result(Name, Source, Expected),
                                    _{ rule: documented_harness_expected_result,
                                       name: Name,
                                       source: Source,
                                       expected: Expected }) :-
    nonvar(Source),
    nonvar(Expected),
    test_harness:arith_misconception(Source, _Domain, Name, _Rule, _Input, Expected).
registered_name_entitlement_witness(Name,
                                    expected_mathematical_control(Name, db_row(Id), Operation),
                                    _{ rule: batch_row_expected_control,
                                       name: Name,
                                       source: db_row(Id),
                                       operation: Operation,
                                       citation_source: BibtexKey }) :-
    nonvar(Id),
    nonvar(Operation),
    batch_row_name(Id, Name),
    batch_row_for_source(db_row(Id), _Domain, Operation, BibtexKey, _Note),
    BibtexKey \== '',
    \+ test_harness:arith_misconception(db_row(Id), _, _, _, _, _).


citation_witness(citation(Source, Note), _{source: Source, note: Note}) :-
    !.
citation_witness(Citation, _{source: unknown, note: Citation}).


registry_commitment_name(deformed_action(_Productive, Name, _Family), Name).
registry_commitment_name(result_of(Name, _Source, _Got), Name).


geometry_misconception_concept(Name, ConceptId) :-
    current_predicate(Module:geom_misconception/6),
    call(Module:geom_misconception(Name, ConceptId, _Title, _Triggers, _Repair, _Citation)).


%!  misconception_gap(?Name, ?Operation, ?GapKind, ?Note) is semidet.
%
%   @deprecated historical empty review hook retained for compatibility with
%   older lesson-monitoring callers. Current registry gaps are not principled
%   limits, so no misconception is intentionally held here; use
%   misconception_registry_entry/5 for active, cited registry rows.
misconception_gap(_, _, _, _) :-
    fail.


attested_misconception(count_all_when_count_on_available,
                       addition,
                       count_on_from_larger,
                       count_all_when_count_on_available,
                       citation('ESM_Gray_1999_Knowledge',
                                "Gray et al. 1999 corpus bindings ground count-all/count-on divergence in action/object focus and procedural counting.")).
attested_misconception(compare_returns_larger_count,
                       subtraction,
                       compare_by_matching_difference,
                       larger_count_as_difference,
                       citation('JMTE_Rowland_2005_Elementary',
                                "Rowland, Huckstep, and Thwaites 2005 document Leo answering a how-many-more comparison with the larger set count, six, rather than the difference between six and four.")).
attested_misconception(additive_extension_of_ratio,
                       ratio,
                       scale_ratio_unit,
                       additive_comparison_in_proportion,
                       citation('ESM_Markovits_1997_Relative',
                                "Markovits 1997 documents children continuing to apply absolute-error additive judgment in relative-error situations where proportional comparison is needed.")).
attested_misconception(equiprobable_endpoint_counting,
                       probability,
                       terminal_tree_endpoint_probability_sum,
                       equiprobability_bias_over_terminal_paths,
                       citation('ESM_Chernoff_2011_From',
                                "Chernoff and Zazkis 2011 document prospective teachers counting ten interrupted-game endpoints as equally likely and splitting the stake 60/40 instead of weighting terminal branch probabilities.")).
attested_misconception(guess_and_check_rule,
                       algebraic,
                       linear_pattern_contextual_rule,
                       empirical_rule_without_contextual_generalization,
                       citation('MTL_Lannin_2005_Generalization',
                                "Lannin 2005 documents sixth-grade students fitting algebraic rules by guess-and-check against early cases without preserving the contextual relation, then failing when the rate of change changed.")).
attested_misconception(drop_carry_to_next_column,
                       addition,
                       column_addition_with_carrying,
                       omitted_carry_to_next_column,
                       citation('JMB_Ebby_2005_Powers',
                                "Ebby 2005 documents a student computing 24 + 37 as 611 by adding each column independently and writing partial sums side by side, omitting the carry to the next column.")).
attested_misconception(dropped_ones_chunk,
                       addition,
                       base_ones_chunking,
                       dropped_remainder_chunk,
                       citation('MERJ_EllemorCollins_2009_Structuring',
                                "Ellemor-Collins and Wright 2009 document a student who cannot perceive the 1-and-X structure needed to add 9 via a jump-through-ten, failing to carry the ones-chunk remainder through to the final sum.")).
attested_misconception(make_ten_drop_leftover,
                       addition,
                       make_ten_split_leftover,
                       dropped_leftover_after_make_ten,
                       citation('MERJ_EllemorCollins_2009_Structuring',
                                "Ellemor-Collins and Wright 2009 document a student who cannot perceive the 1-and-X structure needed to add 9 via a jump-through-ten, failing to carry the ones-chunk remainder through to the final sum.")).
attested_misconception(unbalanced_make_base_compensation,
                       addition,
                       make_base_transfer,
                       compensation_without_conservation,
                       citation('JRME_Schoen_1990_Outcomes',
                                "Schoen et al. 1990 document students confusing the direction of compensating adjustments in estimation, adding to one term without the corresponding subtraction from the other, breaking conservation.")).
attested_misconception(slide_subtrahend_only,
                       subtraction,
                       sliding_constant_difference,
                       nonconstant_difference_shift,
                       citation('IJMEST_Herrera_2011_Addition',
                                "Herrera et al. 2011 document students applying equal-additions subtraction by adjusting only the minuend and omitting the corresponding adjustment to the subtrahend; for 34 - 17 this produces 27 instead of 17.")).
attested_misconception(drop_ones_after_base_takeaway,
                       subtraction,
                       take_away_base_ones,
                       dropped_subtrahend_remainder,
                       citation('MTL_Gravemeijer_2016_Shortcomings',
                                "Gravemeijer et al. 2016 document students miscoordinating the splitting of a subtrahend into base and ones components when subtracting across ten, dropping the ones remainder after the base portion is removed.")).
attested_misconception(sum_dividend_and_divisor,
                       division,
                       long_division,
                       division_replaced_by_digit_sum,
                       citation('JMB_Leatham_2014_Case',
                                "Erlwanger 1973 documents Benny's Rule 1 as a fraction-to-decimal rule (N/D -> the sum N+D, then a heuristic decimal point). This automaton transplants only its division-by-addition core onto whole-number long division: it produces the bare sum N+D and omits Benny's decimal-placement step. Reviewed in Leatham and Winiecke 2014.")).
attested_misconception(Name, Operation, Productive, Family, citation(BibtexKey, Note)) :-
    csv_backed_misconception(Name, Operation, BibtexKey, Note),
    action_automaton_pair(Operation, Productive, Name, Family).


harness_backed_misconception(Source,
                             Domain,
                             Name,
                             Rule,
                             Input,
                             Expected,
                             Operation,
                             citation(BibtexKey, Note)) :-
    test_harness:arith_misconception(Source, Domain, Name, Rule, Input, Expected),
    Source = db_row(_),
    Rule \== skip,
    batch_row_for_source(Source, Domain, Operation, BibtexKey, Note),
    BibtexKey \== ''.
harness_backed_misconception(Source,
                             Domain,
                             Name,
                             Rule,
                             Input,
                             Expected,
                             Operation,
                             Citation) :-
    test_harness:arith_misconception(Source, Domain, Name, Rule, Input, Expected),
    Source \= db_row(_),
    Rule \== skip,
    source_backed_harness_citation(Source, Name, Citation),
    Operation = Domain.


csv_backed_misconception(Name, Operation, BibtexKey, Note) :-
    action_corpus_binding_row(row(_BindingId,
                                  misconception,
                                  _RowId,
                                  BibtexKey,
                                  Operation,
                                  Name,
                                  _AutomatonId,
                                  deformation_misconception,
                                  _Source,
                                  _LinkedStrategyIds,
                                  _LinkedErrorIds,
                                  _LinkIds,
                                  Evidence)),
    BibtexKey \== '',
    text_to_string(Evidence, Note).


action_corpus_binding_row(Row) :-
    action_corpus_binding_row_witness(Row, _).


action_corpus_binding_row_witness(Row, Witness) :-
    ensure_action_corpus_bindings_loaded,
    cached_action_corpus_binding_row(Row),
    (   cached_action_corpus_binding_row_source(Row, Path)
    ->  true
    ;   action_corpus_bindings_path(Path)
    ),
    csv_row_witness(action_corpus_bindings, Path, 13, Row, Witness).


action_corpus_bindings_path(Path) :-
    action_corpus_bindings_root(Root),
    directory_file_path(
        Root,
        'data/research_assets/research/2026-05-11-action-automata-corpus-bindings.csv',
        Path
    ),
    exists_file(Path),
    !.
action_corpus_bindings_path(Path) :-
    absolute_file_name(
        'data/research_assets/research/2026-05-11-action-automata-corpus-bindings.csv',
        Path,
        [access(read)]
    ).


action_corpus_bindings_root(Root) :-
    getenv('UMEDCTA_DATA_ROOT', Root0),
    !,
    atom_string(Root, Root0).
action_corpus_bindings_root(Root) :-
    getenv('UMEDCTA_ROOT', Root0),
    !,
    atom_string(Root, Root0).
action_corpus_bindings_root(Root) :-
    module_property(misconception_registry, file(File)),
    file_directory_name(File, MisconceptionsDir),
    file_directory_name(MisconceptionsDir, KnowledgeDir),
    file_directory_name(KnowledgeDir, Root).


ensure_action_corpus_bindings_loaded :-
    cached_action_corpus_binding_row(_),
    !.
ensure_action_corpus_bindings_loaded :-
    action_corpus_bindings_path(Path),
    csv_rows_with_arity(Path, 13, Rows),
    forall(member(Row, Rows),
           ( assertz(cached_action_corpus_binding_row(Row)),
             assertz(cached_action_corpus_binding_row_source(Row, Path))
           )).


batch_row_for_source(db_row(Id), Domain, Operation, BibtexKey, Note) :-
    misconception_batch_row(row(RowId,
                                ErrorDescription,
                                _Example,
                                _MathematicalDomain,
                                Topic,
                                _Subtopic,
                                _Population,
                                _GradeBand,
                                BibtexKey,
                                _Authors,
                                _Year,
                                _Journal,
                                _Orientation,
                                _Salience,
                                _PageRefs,
                                _LocalPdfPath)),
    row_id_matches(RowId, Id),
    normalize_operation(Topic, Domain, Operation),
    text_to_string(ErrorDescription, Note).


source_backed_harness_citation(erlwanger_1973,
                               benny_rule4_2_plus_0_3,
                               citation('ESM_Byers_1984_Content',
                                        "Byers and Erlwanger 1984 document Benny treating decimal place-value regimes as method-indexed, including 2 + .3 -> .5.")).
source_backed_harness_citation(erlwanger_1973,
                               benny_rule4_1_plus_0_5,
                               citation('ESM_Byers_1984_Content',
                                        "Byers and Erlwanger 1984 document Benny's decimal-addition place-value deformation.")).
source_backed_harness_citation(erlwanger_1973,
                               benny_rule4_0_7_plus_0_5,
                               citation('ESM_Byers_1984_Content',
                                        "Byers and Erlwanger 1984 document Benny's decimal-addition place-value deformation.")).
source_backed_harness_citation(erlwanger_1973,
                               _Name,
                               citation('JMB_Leatham_2014_Case',
                                        "Leatham and Winiecke 2014 review the Case of Benny and document the cited fraction-to-decimal and fraction-equivalence rule deformations.")).


misconception_batch_row(Row) :-
    misconception_batch_row_witness(Row, _).


misconception_batch_row_witness(Row, Witness) :-
    ensure_batch_rows_loaded,
    cached_batch_row(Row),
    (   cached_batch_row_source(Row, Path)
    ->  true
    ;   Path = unknown_misconception_batch_csv
    ),
    csv_row_witness(misconception_batch, Path, 16, Row, Witness).


ensure_batch_rows_loaded :-
    cached_batch_row(_),
    !.
ensure_batch_rows_loaded :-
    forall(misconception_batch_path(Path),
           load_batch_rows(Path)).


load_batch_rows(Path) :-
    csv_rows_with_arity(Path, 16, Rows),
    forall(member(Row, Rows),
           ( assertz(cached_batch_row(Row)),
             assertz(cached_batch_row_source(Row, Path))
           )).


csv_rows_with_arity(Path, ExpectedArity, Rows) :-
    csv_rows_with_arity_witness(Path, ExpectedArity, Rows, _).


csv_rows_with_arity_witness(Path, ExpectedArity, Rows, Witness) :-
    csv_read_file(Path, Rows, [functor(row), convert(false)]),
    (   forall(member(Row, Rows), functor(Row, row, ExpectedArity))
    ->  length(Rows, RowCount),
        Witness = _{ kind: csv_rows_with_arity,
                     path: Path,
                     expected_arity: ExpectedArity,
                     row_count: RowCount }
    ;   domain_error(csv_row_arity(ExpectedArity), Path)
    ).


csv_row_witness(SourceKind, Path, ExpectedArity, Row, Witness) :-
    functor(Row, row, RowArity),
    Witness = _{ kind: misconception_registry_csv_row,
                 source_kind: SourceKind,
                 path: Path,
                 expected_arity: ExpectedArity,
                 row_arity: RowArity,
                 row: Row }.


misconception_batch_path(Path) :-
    absolute_file_name(misconceptions('.'), Dir,
                       [file_type(directory), access(read)]),
    directory_file_path(Dir, '*_batch_*.csv', Pattern),
    expand_file_name(Pattern, Paths),
    member(Path, Paths).


row_id_matches(RowId, Id) :-
    text_to_string(RowId, RowIdString),
    number_string(Id, RowIdString).


batch_row_name(Id, Name) :-
    format(atom(Name), 'batch_row_~w', [Id]).


rule_result(Module:LocalName, Input, Got) :-
    !,
    Goal =.. [LocalName, Input, Got],
    safe_call_rule(Module:Goal).
rule_result(LocalName, Input, Got) :-
    Goal =.. [LocalName, Input, Got],
    safe_call_rule(Goal).


safe_call_rule(Goal) :-
    catch(call_with_inference_limit(Goal, 10_000, Status),
          _Error,
          fail),
    Status \== inference_limit_exceeded.


normalize_operation(Topic, Domain, Operation) :-
    text_to_string(Topic, TopicString0),
    (   TopicString0 == ""
    ->  text_to_string(Domain, TopicString)
    ;   TopicString = TopicString0
    ),
    string_lower(TopicString, Lower),
    split_string(Lower, " /-,.;:?!()[]\"'", " /-,.;:?!()[]\"'", Parts),
    exclude(=(""), Parts, NonEmptyParts),
    (   NonEmptyParts == []
    ->  Operation = Domain
    ;   atomic_list_concat(NonEmptyParts, '_', Operation)
    ).


text_to_string(Text, String) :-
    (   string(Text)
    ->  String = Text
    ;   atom(Text)
    ->  atom_string(Text, String)
    ;   term_string(Text, String)
    ).
