:- module(pml_wire, [misconception_pml/2]).

%! misconception_pml(+SourceTag, -Operator) is nondet.
%
%  Generated from % CONNECTS TO comments in knowledge/misconceptions/*.pl.
%  SourceTag is db_row(N) | asktm(Code), matching the harness Source field.

misconception_pml(db_row(149), s(comp_nec(unlicensed(smaller_from_larger_columnwise)))).
misconception_pml(db_row(152), s(comp_nec(unlicensed(juxtapose_column_sums)))).
misconception_pml(db_row(156), s(comp_nec(unlicensed(add_factors_for_multiplication)))).
misconception_pml(db_row(181), s(comp_nec(unlicensed(remainder_as_decimal_tail)))).
misconception_pml(db_row(192), s(comp_nec(unlicensed(switch_digits_to_avoid_borrowing)))).
misconception_pml(db_row(193), s(comp_nec(unlicensed(addition_must_make_larger)))).
misconception_pml(db_row(198), s(comp_nec(unlicensed(remainder_context_ignored)))).
misconception_pml(db_row(210), s(comp_nec(unlicensed(top_from_bottom_subtraction)))).
misconception_pml(db_row(211), s(comp_nec(unlicensed(carry_as_adjacent_digit)))).
misconception_pml(db_row(215), s(comp_nec(unlicensed(zero_minus_n_equals_n)))).
misconception_pml(db_row(218), s(comp_nec(unlicensed(multiply_by_eleven_as_double)))).
misconception_pml(db_row(222), s(comp_nec(unlicensed(split_subtract_smaller_from_larger)))).
misconception_pml(db_row(236), s(comp_nec(unlicensed(fractional_bus_answer)))).
misconception_pml(db_row(242), s(comp_nec(unlicensed(group_addends_after_minus)))).
misconception_pml(db_row(287), s(comp_nec(unlicensed(zero_place_addition_drop_ones)))).
misconception_pml(db_row(37434), s(comp_nec(unlicensed(add_denominators_unit)))).
misconception_pml(db_row(37436), s(comp_nec(unlicensed(name_by_length)))).
misconception_pml(db_row(37437), s(comp_nec(unlicensed(iteration_count_as_numerator)))).
misconception_pml(db_row(37438), s(comp_nec(unlicensed(additive_for_multiplicative)))).
misconception_pml(db_row(37440), s(comp_nec(unlicensed(swap_part_whole_on_improper)))).
misconception_pml(db_row(37443), s(comp_nec(unlicensed(guess_denominator_from_prior)))).
misconception_pml(db_row(37444), s(comp_nec(unlicensed(denominator_follows_total_pieces)))).
misconception_pml(db_row(37445), s(comp_nec(unlicensed(partition_by_largest_numeral)))).
misconception_pml(db_row(37446), s(comp_nec(unlicensed(reciprocal_to_stay_proper)))).
misconception_pml(db_row(37450), s(comp_nec(unlicensed(iterate_instead_of_compose)))).
misconception_pml(db_row(37451), s(comp_nec(unlicensed(intermediate_unit_as_denominator)))).
misconception_pml(db_row(37453), s(comp_nec(unlicensed(componentwise_fraction_addition)))).
misconception_pml(db_row(37454), s(comp_nec(unlicensed(n_out_of_m_fixed_whole)))).
misconception_pml(db_row(37455), s(comp_nec(unlicensed(benchmark_as_estimate)))).
misconception_pml(db_row(37457), s(comp_nec(unlicensed(group_size_as_unit_denominator)))).
misconception_pml(db_row(37460), s(comp_nec(unlicensed(visual_miscount_unit_parts)))).
misconception_pml(db_row(37461), s(comp_nec(unlicensed(cartesian_product_as_one_to_one)))).
misconception_pml(db_row(37463), s(comp_nec(unlicensed(drop_dimension_in_cartesian_product)))).
misconception_pml(db_row(37470), s(comp_nec(unlicensed(over_round_leading_power)))).
misconception_pml(db_row(37471), s(comp_nec(unlicensed(ignore_fractional_parts)))).
misconception_pml(db_row(37472), s(comp_nec(unlicensed(compensation_direction_reversed)))).
misconception_pml(db_row(37476), s(comp_nec(unlicensed(piece_count_as_amount)))).
misconception_pml(db_row(37478), s(comp_nec(unlicensed(referent_whole_shift)))).
misconception_pml(db_row(37483), s(comp_nec(unlicensed(decimal_operator_must_be_whole)))).
misconception_pml(db_row(37484), s(comp_nec(unlicensed(reverse_for_larger_divisor)))).
misconception_pml(db_row(37485), s(comp_nec(unlicensed(multiply_when_divide)))).
misconception_pml(db_row(37486), s(comp_nec(unlicensed(mult_num_add_denom)))).
misconception_pml(db_row(37487), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(37488), s(comp_nec(unlicensed(add_across_numer_and_denom)))).
misconception_pml(db_row(37489), s(comp_nec(unlicensed(equivalent_by_adding)))).
misconception_pml(db_row(37490), s(comp_nec(unlicensed(parity_by_group_count)))).
misconception_pml(db_row(37496), s(comp_nec(unlicensed(numeral_concatenation)))).
misconception_pml(db_row(37497), s(comp_nec(unlicensed(missing_addend_as_sum)))).
misconception_pml(db_row(37500), s(comp_nec(unlicensed(density_denial(consecutive_numerators))))).
misconception_pml(db_row(37502), s(comp_nec(unlicensed(mult_always_grows)))).
misconception_pml(db_row(37503), s(comp_nec(unlicensed(blind_place_by_digit_count)))).
misconception_pml(db_row(37506), s(comp_nec(unlicensed(divide_by_half_as_divide_by_two)))).
misconception_pml(db_row(37507), s(comp_nec(unlicensed(divide_by_zero_yields_zero)))).
misconception_pml(db_row(37508), s(comp_nec(unlicensed(partitive_model_only_fraction_division)))).
misconception_pml(db_row(37510), s(comp_nec(unlicensed(whole_num_denom_compare)))).
misconception_pml(db_row(37511), s(comp_nec(unlicensed(unit_collapse(merge_wholes))))).
misconception_pml(db_row(37512), s(comp_nec(unlicensed(rote_add_across_same_denom)))).
misconception_pml(db_row(37514), s(comp_nec(unlicensed(equal_outputs_inverse_drop)))).
misconception_pml(db_row(37515), s(comp_nec(unlicensed(estimate_as_exact_calculation)))).
misconception_pml(db_row(37517), s(comp_nec(unlicensed(add_num_avg_denom)))).
misconception_pml(db_row(37518), s(comp_nec(unlicensed(decimal_shrinks_by_ten)))).
misconception_pml(db_row(37519), s(comp_nec(unlicensed(referent_whole_fixed)))).
misconception_pml(db_row(37520), s(comp_nec(unlicensed(referent_whole_shift)))).
misconception_pml(db_row(37521), s(comp_nec(unlicensed(total_pieces_as_num_and_denom)))).
misconception_pml(db_row(37525), s(comp_nec(unlicensed(scale_both_parts)))).
misconception_pml(db_row(37527), s(comp_nec(unlicensed(truncate_remainder)))).
misconception_pml(db_row(37528), s(comp_nec(unlicensed(area_as_perimeter_count)))).
misconception_pml(db_row(37529), s(comp_nec(unlicensed(constraint_independence)))).
misconception_pml(db_row(37542), s(comp_nec(unlicensed(sum_terms_for_decimal)))).
misconception_pml(db_row(37545), s(comp_nec(unlicensed(base10_regroup_on_time)))).
misconception_pml(db_row(37546), s(comp_nec(unlicensed(bad_power_of_ten)))).
misconception_pml(db_row(37547), s(comp_nec(unlicensed(invert_dividend)))).
misconception_pml(db_row(37548), s(comp_nec(unlicensed(div_must_shrink_swap_for_mult)))).
misconception_pml(db_row(37549), s(comp_nec(unlicensed(division_commutative)))).
misconception_pml(db_row(37556), s(comp_nec(unlicensed(division_always_smaller)))).
misconception_pml(db_row(37557), s(comp_nec(unlicensed(force_smaller_quotient)))).
misconception_pml(db_row(37562), s(comp_nec(unlicensed(referent_whole_displacement)))).
misconception_pml(db_row(37571), s(comp_nec(unlicensed(partial_scaling_numerator)))).
misconception_pml(db_row(37572), s(comp_nec(unlicensed(count_marks_not_intervals)))).
misconception_pml(db_row(37573), s(comp_nec(unlicensed(consecutive_unit_denoms)))).
misconception_pml(db_row(37574), s(comp_nec(unlicensed(primes_closed_under_multiplication)))).
misconception_pml(db_row(37575), s(comp_nec(unlicensed(small_prime_check_only)))).
misconception_pml(db_row(37577), s(comp_nec(unlicensed(digit_sum_primality)))).
misconception_pml(db_row(37578), s(comp_nec(unlicensed(odd_implies_prime)))).
misconception_pml(db_row(37581), s(comp_nec(unlicensed(numerator_as_piece_count)))).
misconception_pml(db_row(37582), s(comp_nec(unlicensed(syntactic_sum_for_fraction_of_whole)))).
misconception_pml(db_row(37583), s(comp_nec(unlicensed(fraction_as_complement)))).
misconception_pml(db_row(37584), s(comp_nec(unlicensed(complement_for_part)))).
misconception_pml(db_row(37586), s(comp_nec(unlicensed(denominator_only_compare)))).
misconception_pml(db_row(37587), s(comp_nec(unlicensed(more_pieces_larger)))).
misconception_pml(db_row(37588), s(comp_nec(unlicensed(rewrite_denominator_freely)))).
misconception_pml(db_row(37589), s(comp_nec(unlicensed(missing_cross_products)))).
misconception_pml(db_row(37591), s(comp_nec(unlicensed(integer_order_by_absolute_value)))).
misconception_pml(db_row(37592), s(comp_nec(unlicensed(negative_compare_by_magnitude)))).
misconception_pml(db_row(37593), s(comp_nec(unlicensed(larger_absolute_negative_is_greater)))).
misconception_pml(db_row(37594), s(comp_nec(unlicensed(unary_minus_as_subtraction)))).
misconception_pml(db_row(37596), s(comp_nec(unlicensed(longer_is_larger)))).
misconception_pml(db_row(37597), s(comp_nec(unlicensed(both_sides_of_dot)))).
misconception_pml(db_row(37599), s(comp_nec(unlicensed(denom_to_tenths)))).
misconception_pml(db_row(37603), s(comp_nec(unlicensed(rtl_digit_misalignment)))).
misconception_pml(db_row(37605), s(comp_nec(unlicensed(no_square_for_fraction_scale)))).
misconception_pml(db_row(37607), s(comp_nec(unlicensed(digit_face_value_for_place_value)))).
misconception_pml(db_row(37608), s(comp_nec(unlicensed(under_carry_multi_addition)))).
misconception_pml(db_row(37613), s(comp_nec(unlicensed(decimal_digits_as_fraction_terms)))).
misconception_pml(db_row(37615), s(comp_nec(unlicensed(longer_decimal_is_larger)))).
misconception_pml(db_row(37616), s(comp_nec(unlicensed(more_places_smaller)))).
misconception_pml(db_row(37617), s(comp_nec(unlicensed(leading_zero_smallest)))).
misconception_pml(db_row(37618), s(comp_nec(unlicensed(numerator_as_decimal)))).
misconception_pml(db_row(37619), s(comp_nec(unlicensed(encode_denom_only)))).
misconception_pml(db_row(37620), s(comp_nec(unlicensed(fraction_bar_as_point)))).
misconception_pml(db_row(37626), s(comp_nec(unlicensed(drop_trailing_zero)))).
misconception_pml(db_row(37627), s(comp_nec(unlicensed(cover_by_sum_of_sides)))).
misconception_pml(db_row(37635), s(comp_nec(unlicensed(bad_zero_regroup)))).
misconception_pml(db_row(37636), s(comp_nec(unlicensed(decimal_as_separator)))).
misconception_pml(db_row(37637), s(comp_nec(unlicensed(whole_num_rule_tenths)))).
misconception_pml(db_row(37638), s(comp_nec(unlicensed(ignore_decimal_then_insert)))).
misconception_pml(db_row(37640), s(comp_nec(unlicensed(subtract_parts_separately)))).
misconception_pml(db_row(37641), s(comp_nec(unlicensed(algorithm_substitution(reciprocal_for_multiply))))).
misconception_pml(db_row(37642), s(comp_nec(unlicensed(converse_of_conditional)))).
misconception_pml(db_row(37647), s(comp_nec(unlicensed(sample_size_changes_intensive_quantity)))).
misconception_pml(db_row(37649), s(comp_nec(unlicensed(numerical_overrides_intensive_invariance)))).
misconception_pml(db_row(37652), s(comp_nec(unlicensed(compute_then_round)))).
misconception_pml(db_row(37655), s(comp_nec(unlicensed(smaller_from_larger_columnwise)))).
misconception_pml(db_row(37657), s(comp_nec(unlicensed(rigid_denominator)))).
misconception_pml(db_row(37658), s(comp_nec(unlicensed(operation_substitution(divide_for_multiply))))).
misconception_pml(db_row(37659), s(comp_nec(unlicensed(percent_total_not_100)))).
misconception_pml(db_row(37661), s(comp_nec(unlicensed(reverse_percent_equation)))).
misconception_pml(db_row(37664), s(comp_nec(unlicensed(whole_num_denom_compare)))).
misconception_pml(db_row(37666), s(comp_nec(unlicensed(product_inverse_order)))).
misconception_pml(db_row(37669), s(comp_nec(unlicensed(smaller_from_larger)))).
misconception_pml(db_row(37670), s(comp_nec(unlicensed(false_distribution_no_cross_terms)))).
misconception_pml(db_row(37674), s(comp_nec(unlicensed(procedural_grid_fraction_division)))).
misconception_pml(db_row(37680), s(comp_nec(unlicensed(half_counted_as_whole)))).
misconception_pml(db_row(37688), s(comp_nec(unlicensed(add_irrelevant_counts)))).
misconception_pml(db_row(37693), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(37708), s(comp_nec(unlicensed(negative_not_number)))).
misconception_pml(db_row(37709), s(comp_nec(unlicensed(subtraction_floor_at_zero)))).
misconception_pml(db_row(37710), s(comp_nec(unlicensed(addition_must_increase)))).
misconception_pml(db_row(37713), s(comp_nec(unlicensed(half_mapped_to_30)))).
misconception_pml(db_row(37752), s(comp_nec(unlicensed(division_story_as_multiplication)))).
misconception_pml(db_row(37759), s(comp_nec(unlicensed(numerical_pattern_guess)))).
misconception_pml(db_row(37760), s(comp_nec(unlicensed(denom_magnitude_direct)))).
misconception_pml(db_row(37761), s(comp_nec(unlicensed(partition_by_numerator)))).
misconception_pml(db_row(37768), s(comp_nec(unlicensed(pull_then_subpull)))).
misconception_pml(db_row(37769), s(comp_nec(unlicensed(more_parts_means_bigger)))).
misconception_pml(db_row(37770), s(comp_nec(unlicensed(unit_whole_conflation)))).
misconception_pml(db_row(37771), s(comp_nec(unlicensed(swap_numer_denom_roles)))).
misconception_pml(db_row(37781), s(comp_nec(unlicensed(count_pieces_ignore_size)))).
misconception_pml(db_row(37782), s(comp_nec(unlicensed(blind_arithmetic_no_remainders)))).
misconception_pml(db_row(37787), s(comp_nec(unlicensed(extra_zero_multiplication)))).
misconception_pml(db_row(37794), s(comp_nec(unlicensed(double_first_add_one)))).
misconception_pml(db_row(37796), s(comp_nec(unlicensed(flip_subtraction_order)))).
misconception_pml(db_row(37799), s(comp_nec(unlicensed(div_instead_of_mult)))).
misconception_pml(db_row(37800), s(comp_nec(unlicensed(divide_for_decimal_of)))).
misconception_pml(db_row(37801), s(comp_nec(unlicensed(swap_dividend_divisor)))).
misconception_pml(db_row(37802), s(comp_nec(unlicensed(swap_to_integer_divisor)))).
misconception_pml(db_row(37803), s(comp_nec(unlicensed(division_is_commutative)))).
misconception_pml(db_row(37804), s(comp_nec(unlicensed(decompose_composite_units)))).
misconception_pml(db_row(37813), s(comp_nec(unlicensed(raw_quotient_with_remainder)))).
misconception_pml(db_row(37814), s(comp_nec(unlicensed(round_down_containers)))).
misconception_pml(db_row(37815), s(comp_nec(unlicensed(longer_digits_larger)))).
misconception_pml(db_row(37816), s(comp_nec(unlicensed(ragged_decimal_addition)))).
misconception_pml(db_row(37818), s(comp_nec(unlicensed(digit_sum_rule_overgeneralized)))).
misconception_pml(db_row(37819), s(comp_nec(unlicensed(last_digit_div_rule_overgen)))).
misconception_pml(db_row(37820), s(comp_nec(unlicensed(pf_distributive_over_sum)))).
misconception_pml(db_row(37823), s(comp_nec(unlicensed(larger_denom_larger_fraction)))).
misconception_pml(db_row(37825), s(comp_nec(unlicensed(part_whole_ceiling)))).
misconception_pml(db_row(37829), s(comp_nec(unlicensed(whole_number_on_denominator)))).
misconception_pml(db_row(37830), s(comp_nec(unlicensed(scale_both_terms_on_iteration)))).
misconception_pml(db_row(37831), s(comp_nec(unlicensed(additive_difference_for_ratio)))).
misconception_pml(db_row(37833), s(comp_nec(unlicensed(add_common_denominators)))).
misconception_pml(db_row(37842), s(comp_nec(unlicensed(smaller_from_larger_column)))).
misconception_pml(db_row(37843), s(comp_nec(unlicensed(incomplete_decomposition)))).
misconception_pml(db_row(37848), s(comp_nec(unlicensed(containment_yields_zero)))).
misconception_pml(db_row(37855), s(comp_nec(unlicensed(estimate_via_exact_then_round)))).
misconception_pml(db_row(37857), s(comp_nec(unlicensed(denominator_as_magnitude)))).
misconception_pml(db_row(37858), s(comp_nec(unlicensed(equal_residual_strategy)))).
misconception_pml(db_row(37859), s(comp_nec(unlicensed(componentwise_subtract_add_denom)))).
misconception_pml(db_row(37863), s(comp_nec(unlicensed(reference_whole_shift_iterate)))).
misconception_pml(db_row(37870), s(comp_nec(unlicensed(leftover_pieces_for_comparison)))).
misconception_pml(db_row(37871), s(comp_nec(unlicensed(jumbled_cross_cancel_add)))).
misconception_pml(db_row(37872), s(comp_nec(unlicensed(sketch_count_addition)))).
misconception_pml(db_row(37873), s(comp_nec(unlicensed(denom_only_compare)))).
misconception_pml(db_row(37874), s(comp_nec(unlicensed(square_parts_independently)))).
misconception_pml(db_row(37875), s(comp_nec(unlicensed(triangle_angle_sum_scales_with_size)))).
misconception_pml(db_row(37876), s(comp_nec(unlicensed(reversal_multiply_instead_of_divide)))).
misconception_pml(db_row(37877), s(comp_nec(unlicensed(multiply_by_seven_spurious)))).
misconception_pml(db_row(37879), s(comp_nec(unlicensed(whole_as_num_same_denom)))).
misconception_pml(db_row(37880), s(comp_nec(unlicensed(numerator_only_sum)))).
misconception_pml(db_row(37881), s(comp_nec(unlicensed(lose_track_hidden)))).
misconception_pml(db_row(37883), s(comp_nec(unlicensed(open_addition_no_negative_solution)))).
misconception_pml(db_row(37884), s(comp_nec(unlicensed(negative_subtraction_no_solution)))).
misconception_pml(db_row(37898), s(comp_nec(unlicensed(no_shift_partial_products)))).
misconception_pml(db_row(37900), s(comp_nec(unlicensed(total_over_equipartition)))).
misconception_pml(db_row(37901), s(comp_nec(unlicensed(adjust_dividend_to_multiple)))).
misconception_pml(db_row(37902), s(comp_nec(unlicensed(partial_products_no_shift)))).
misconception_pml(db_row(37903), s(comp_nec(unlicensed(additive_factor_decomposition)))).
misconception_pml(db_row(37906), s(comp_nec(unlicensed(whole_number_order_on_denominator)))).
misconception_pml(db_row(37907), s(comp_nec(unlicensed(inverted_same_denom)))).
misconception_pml(db_row(37908), s(comp_nec(unlicensed(additive_equivalence)))).
misconception_pml(db_row(37909), s(comp_nec(unlicensed(partial_scale_missing_numer)))).
misconception_pml(db_row(37910), s(comp_nec(unlicensed(componentwise_order)))).
misconception_pml(db_row(37917), s(comp_nec(unlicensed(add_across_numer_and_denom)))).
misconception_pml(db_row(37918), s(comp_nec(unlicensed(numerator_only_comparison)))).
misconception_pml(db_row(37921), s(comp_nec(unlicensed(natural_number_bias)))).
misconception_pml(db_row(37934), s(comp_nec(unlicensed(smaller_from_larger_columnwise)))).
misconception_pml(db_row(37940), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(37961), s(comp_nec(unlicensed(reference_unit_drift)))).
misconception_pml(db_row(37974), s(comp_nec(unlicensed(add_across_like_denoms)))).
misconception_pml(db_row(37979), s(comp_nec(unlicensed(larger_cannot_fit)))).
misconception_pml(db_row(37983), s(comp_nec(unlicensed(unit_mixing_across_dot)))).
misconception_pml(db_row(37984), s(comp_nec(unlicensed(no_borrow_across_point)))).
misconception_pml(db_row(37985), s(comp_nec(unlicensed(subtrahend_minuend_swap)))).
misconception_pml(db_row(37991), s(comp_nec(unlicensed(additive_gap_as_ratio_equivalence)))).
misconception_pml(db_row(38000), s(comp_nec(unlicensed(rect_not_parallelogram)))).
misconception_pml(db_row(38006), s(comp_nec(unlicensed(shaded_count_as_whole)))).
misconception_pml(db_row(38011), s(comp_nec(unlicensed(number_line_origin_one)))).
misconception_pml(db_row(38012), s(comp_nec(unlicensed(negative_order_by_absolute_value)))).
misconception_pml(db_row(38015), s(comp_nec(unlicensed(percent_as_absolute_amount)))).
misconception_pml(db_row(38034), s(comp_nec(unlicensed(additive_ratio)))).
misconception_pml(db_row(38055), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(38056), s(comp_nec(unlicensed(longer_is_larger)))).
misconception_pml(db_row(38059), s(comp_nec(unlicensed(phonetic_numeral_transcription)))).
misconception_pml(db_row(38060), s(comp_nec(unlicensed(no_carry_concatenate)))).
misconception_pml(db_row(38063), s(comp_nec(unlicensed(same_change_same_perimeter)))).
misconception_pml(db_row(38068), s(comp_nec(unlicensed(gap_thinking)))).
misconception_pml(db_row(38105), s(comp_nec(unlicensed(idiosyncratic_nexus_division)))).
misconception_pml(db_row(38111), s(comp_nec(unlicensed(commute_division)))).
misconception_pml(db_row(38113), s(comp_nec(unlicensed(mult_both_by_whole)))).
misconception_pml(db_row(38114), s(comp_nec(unlicensed(finite_subset_rule_for_infinite_sets)))).
misconception_pml(db_row(38121), s(comp_nec(unlicensed(juxtapose_unit_totals)))).
misconception_pml(db_row(38122), s(comp_nec(unlicensed(drop_higher_unit)))).
misconception_pml(db_row(38126), s(comp_nec(unlicensed(wrong_cross_product)))).
misconception_pml(db_row(38127), s(comp_nec(unlicensed(largest_components_bias)))).
misconception_pml(db_row(38128), s(comp_nec(unlicensed(compare_by_pieces_left)))).
misconception_pml(db_row(38131), s(comp_nec(unlicensed(denominator_whole_number_order)))).
misconception_pml(db_row(38138), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(38143), s(comp_nec(unlicensed(mult_performed_as_add)))).
misconception_pml(db_row(38144), s(comp_nec(unlicensed(times_more_as_multiplication)))).
misconception_pml(db_row(38146), s(comp_nec(unlicensed(nat_num_magnitude_on_decimal)))).
misconception_pml(db_row(38149), s(comp_nec(unlicensed(add_percent_rates_on_original_base)))).
misconception_pml(db_row(38155), s(comp_nec(unlicensed(part_to_part_as_percent)))).
misconception_pml(db_row(38166), s(comp_nec(unlicensed(primes_are_small)))).
misconception_pml(db_row(38168), s(comp_nec(unlicensed(gap_rule_smaller_means_larger_gap)))).
misconception_pml(db_row(38213), s(comp_nec(unlicensed(ignore_whole_value)))).
misconception_pml(db_row(38214), s(comp_nec(unlicensed(referent_drift(to_operand))))).
misconception_pml(db_row(38219), s(comp_nec(unlicensed(overlap_overcount_combinatorics)))).
misconception_pml(db_row(38223), s(comp_nec(unlicensed(wrong_referent_unit)))).
misconception_pml(db_row(38227), s(comp_nec(unlicensed(count_back_off_by_one)))).
misconception_pml(db_row(38228), s(comp_nec(unlicensed(forget_carried_ten)))).
misconception_pml(db_row(38238), s(comp_nec(unlicensed(missing_piece_equality)))).
misconception_pml(db_row(38242), s(comp_nec(unlicensed(smaller_from_larger_columnwise)))).
misconception_pml(db_row(38243), s(comp_nec(unlicensed(equal_by_missing_count)))).
misconception_pml(db_row(38244), s(comp_nec(unlicensed(change_amount_as_endpoint)))).
misconception_pml(db_row(38252), s(comp_nec(unlicensed(truncate_instead_of_ceiling)))).
misconception_pml(db_row(38255), s(comp_nec(unlicensed(divisor_dividend_reversal)))).
misconception_pml(db_row(38256), s(comp_nec(unlicensed(fraction_of_as_division)))).
misconception_pml(db_row(38269), s(comp_nec(unlicensed(remainder_is_unmeasurable)))).
misconception_pml(db_row(38282), s(comp_nec(unlicensed(linear_interpolate_divisor)))).
misconception_pml(db_row(38284), s(comp_nec(unlicensed(subparts_count_in_bar)))).
misconception_pml(db_row(38285), s(comp_nec(unlicensed(scale_factor_as_denom)))).
misconception_pml(db_row(38291), s(comp_nec(unlicensed(radian_as_length)))).
misconception_pml(db_row(38296), s(comp_nec(unlicensed(equivalent_fraction_as_larger)))).
misconception_pml(db_row(38297), s(comp_nec(unlicensed(building_up_changes_value)))).
misconception_pml(db_row(38300), s(comp_nec(unlicensed(denominator_as_tens_grid_count)))).
misconception_pml(db_row(38301), s(comp_nec(unlicensed(ignore_referent_whole_size)))).
misconception_pml(db_row(38302), s(comp_nec(unlicensed(product_sign_from_larger_factor)))).
misconception_pml(db_row(38305), s(comp_nec(unlicensed(longer_is_larger_ordering)))).
misconception_pml(db_row(38308), s(comp_nec(unlicensed(numer_as_groups)))).
misconception_pml(db_row(38313), s(comp_nec(unlicensed(denom_size_theorem)))).
misconception_pml(db_row(38315), s(comp_nec(unlicensed(bigger_numer_bigger_frac)))).
misconception_pml(db_row(38334), s(comp_nec(unlicensed(partitive_scheme_swap)))).
misconception_pml(db_row(38336), s(comp_nec(unlicensed(two_dimensional_for_three_dimensional_product)))).
misconception_pml(db_row(38338), s(comp_nec(unlicensed(blind_combine_numbers)))).
misconception_pml(db_row(38344), s(comp_nec(unlicensed(iteration_count_as_magnitude)))).
misconception_pml(db_row(38345), s(comp_nec(unlicensed(iterate_composite)))).
misconception_pml(db_row(38346), s(comp_nec(unlicensed(non_unit_to_unit_collapse)))).
misconception_pml(db_row(38367), s(comp_nec(unlicensed(guess_from_visual)))).
misconception_pml(db_row(38368), s(comp_nec(unlicensed(compensation_wrong_direction)))).
misconception_pml(db_row(38373), s(comp_nec(unlicensed(complement_count_as_size)))).
misconception_pml(db_row(38374), s(comp_nec(unlicensed(denom_size_magnitude)))).
misconception_pml(db_row(38376), s(comp_nec(unlicensed(digitwise_add_concat)))).
misconception_pml(db_row(38389), s(comp_nec(unlicensed(parallelogram_is_rectangle)))).
misconception_pml(db_row(38393), s(comp_nec(unlicensed(omit_zero_quotient_digit)))).
misconception_pml(db_row(38394), s(comp_nec(unlicensed(operate_on_denominators)))).
misconception_pml(db_row(38395), s(comp_nec(unlicensed(total_count_as_denom)))).
misconception_pml(db_row(38396), s(comp_nec(unlicensed(one_as_unit_fraction)))).
misconception_pml(db_row(38397), s(comp_nec(unlicensed(mirror_place_value)))).
misconception_pml(db_row(38398), s(comp_nec(unlicensed(place_name_inflation)))).
misconception_pml(db_row(38399), s(comp_nec(unlicensed(more_places_is_larger)))).
misconception_pml(db_row(38400), s(comp_nec(unlicensed(denominator_analogy_shorter_larger)))).
misconception_pml(db_row(38401), s(comp_nec(unlicensed(decimal_is_negative)))).
misconception_pml(db_row(38402), s(comp_nec(unlicensed(iteration_count_overwrites_denominator)))).
misconception_pml(db_row(38403), s(comp_nec(unlicensed(iterate_for_split)))).
misconception_pml(db_row(38405), s(comp_nec(unlicensed(numer_as_whole_numbers)))).
misconception_pml(db_row(38411), s(comp_nec(unlicensed(rectangle_not_parallelogram)))).
misconception_pml(db_row(38416), s(comp_nec(unlicensed(neg_decimal_translate)))).
misconception_pml(db_row(38421), s(comp_nec(unlicensed(reverse_partition_by_denominator)))).
misconception_pml(db_row(38422), s(comp_nec(unlicensed(fraction_of_always_smaller)))).
misconception_pml(db_row(38423), s(comp_nec(unlicensed(numerator_as_partition_count)))).
misconception_pml(db_row(38424), s(comp_nec(unlicensed(of_as_subtract)))).
misconception_pml(db_row(38431), s(comp_nec(unlicensed(referent_unit_switch_difference)))).
misconception_pml(db_row(38452), s(comp_nec(unlicensed(reversal_by_multiplication)))).
misconception_pml(db_row(38453), s(comp_nec(unlicensed(unequal_as_equal_parts)))).
misconception_pml(db_row(38454), s(comp_nec(unlicensed(name_by_count_present)))).
misconception_pml(db_row(38455), s(comp_nec(unlicensed(whole_as_unit_fraction)))).
misconception_pml(db_row(38456), s(comp_nec(unlicensed(piece_count_denom)))).
misconception_pml(db_row(38464), s(comp_nec(unlicensed(fold_as_add_two)))).
misconception_pml(db_row(38465), s(comp_nec(unlicensed(additive_fold_sequence)))).
misconception_pml(db_row(38471), s(comp_nec(unlicensed(empty_set_as_singleton)))).
misconception_pml(db_row(38477), s(comp_nec(unlicensed(unit_fraction_componentwise_add)))).
misconception_pml(db_row(38487), s(comp_nec(unlicensed(subtract_unit_group_for_ratio)))).
misconception_pml(db_row(38488), s(comp_nec(unlicensed(additive_ratio_extension)))).
misconception_pml(db_row(38491), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(38498), s(comp_nec(unlicensed(left_to_right_no_precedence)))).
misconception_pml(db_row(38499), s(comp_nec(unlicensed(longer_longer_rule)))).
misconception_pml(db_row(38500), s(comp_nec(unlicensed(double_minus_impossible)))).
misconception_pml(db_row(38502), s(comp_nec(unlicensed(add_ratio_parts_keep_one_whole)))).
misconception_pml(db_row(38518), s(comp_nec(unlicensed(double_count_new_intersection)))).
misconception_pml(db_row(38534), s(comp_nec(unlicensed(prime_definition_includes_one)))).
misconception_pml(db_row(38555), s(comp_nec(unlicensed(denom_as_iterating_unit)))).
misconception_pml(db_row(38556), s(comp_nec(unlicensed(unit_frac_as_subtract_denom)))).
misconception_pml(db_row(38558), s(comp_nec(unlicensed(swap_num_denom_for_proper)))).
misconception_pml(db_row(38559), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(38563), s(comp_nec(unlicensed(natural_number_order_on_denominator)))).
misconception_pml(db_row(38564), s(comp_nec(unlicensed(shorter_is_larger)))).
misconception_pml(db_row(38565), s(comp_nec(unlicensed(decimal_length_rule)))).
misconception_pml(db_row(38567), s(comp_nec(unlicensed(zero_neither_parity)))).
misconception_pml(db_row(38571), s(comp_nec(unlicensed(mc1_part_count)))).
misconception_pml(db_row(38582), s(comp_nec(unlicensed(tile_side_as_linear_unit)))).
misconception_pml(db_row(38583), s(comp_nec(unlicensed(linear_scaling_for_area)))).
misconception_pml(db_row(38584), s(comp_nec(unlicensed(raw_piece_sum)))).
misconception_pml(db_row(38594), s(comp_nec(unlicensed(decompose_by_denominator)))).
misconception_pml(db_row(38596), s(comp_nec(unlicensed(missing_cross_products)))).
misconception_pml(db_row(38605), s(comp_nec(unlicensed(congruent_shape_required_for_fraction)))).
misconception_pml(db_row(38606), s(comp_nec(unlicensed(didactical_contract_add)))).
misconception_pml(db_row(38607), s(comp_nec(unlicensed(subset_as_disjoint)))).
misconception_pml(db_row(38608), s(comp_nec(unlicensed(decade_cross_subtract_ten_add_one)))).
misconception_pml(db_row(38613), s(comp_nec(unlicensed(sum_terms_for_decimal)))).
misconception_pml(db_row(38616), s(comp_nec(unlicensed(default_to_addition)))).
misconception_pml(db_row(38624), s(comp_nec(unlicensed(keyword_surface_addition)))).
misconception_pml(db_row(38625), s(comp_nec(unlicensed(tenths_as_tens)))).
misconception_pml(db_row(38634), s(comp_nec(unlicensed(linear_factor_for_area_scale)))).
misconception_pml(db_row(38638), s(comp_nec(unlicensed(number_line_requires_whole_number)))).
misconception_pml(db_row(38658), s(comp_nec(unlicensed(denom_partitions_known)))).
misconception_pml(db_row(38659), s(comp_nec(unlicensed(no_reversal_of_multiplier)))).
misconception_pml(db_row(38664), s(comp_nec(unlicensed(length_over_iteration_count)))).
misconception_pml(db_row(38665), s(comp_nec(unlicensed(count_pieces_plus_half)))).
misconception_pml(db_row(38666), s(comp_nec(unlicensed(add_across_rejected_on_reflection)))).
misconception_pml(db_row(38668), s(comp_nec(unlicensed(double_count_overlap)))).
misconception_pml(db_row(38675), s(comp_nec(unlicensed(area_via_length)))).
misconception_pml(db_row(38679), s(comp_nec(unlicensed(second_of_whole_not_first)))).
misconception_pml(db_row(38681), s(comp_nec(unlicensed(half_of_left_as_all_of_left)))).
misconception_pml(db_row(38684), s(comp_nec(unlicensed(minus_as_label)))).
misconception_pml(db_row(38689), s(comp_nec(unlicensed(base10_regroup_on_time)))).
misconception_pml(db_row(38691), s(comp_nec(unlicensed(remainder_as_decimal)))).
misconception_pml(db_row(38694), s(comp_nec(unlicensed(diagonal_as_unit)))).
misconception_pml(db_row(38704), s(comp_nec(unlicensed(complement_magnitude_reasoning)))).
misconception_pml(db_row(38706), s(comp_nec(unlicensed(arrangement_as_combination_sum)))).
misconception_pml(db_row(38707), s(comp_nec(unlicensed(square_initial_term_for_sum)))).
misconception_pml(db_row(38717), s(comp_nec(unlicensed(partition_given_by_denominator)))).
misconception_pml(db_row(38718), s(comp_nec(unlicensed(redefine_whole_as_total)))).
misconception_pml(db_row(38725), s(comp_nec(unlicensed(tens_column_uncompressed)))).
misconception_pml(db_row(38727), s(comp_nec(unlicensed(div_instead_of_mult)))).
misconception_pml(db_row(38731), s(comp_nec(unlicensed(unit_fraction_as_denominator_count)))).
misconception_pml(db_row(38732), s(comp_nec(unlicensed(both_terms_larger_is_bigger)))).
misconception_pml(db_row(38733), s(comp_nec(unlicensed(divide_by_numerator)))).
misconception_pml(db_row(38734), s(comp_nec(unlicensed(unrealistic_remainder)))).
misconception_pml(db_row(38753), s(comp_nec(unlicensed(bigger_both_bigger_frac)))).
misconception_pml(db_row(38761), s(comp_nec(unlicensed(ignore_zero_factor)))).
misconception_pml(db_row(38790), s(comp_nec(unlicensed(divide_for_smaller)))).
misconception_pml(db_row(38794), s(comp_nec(unlicensed(denominator_only_comparison)))).
misconception_pml(db_row(38805), s(comp_nec(unlicensed(stefan_rule_componentwise)))).
misconception_pml(db_row(38806), s(comp_nec(unlicensed(denom_is_marked_count)))).
misconception_pml(db_row(38809), s(comp_nec(unlicensed(scale_percent_with_container)))).
misconception_pml(db_row(38810), s(comp_nec(unlicensed(percent_as_subtracted_units)))).
misconception_pml(db_row(38811), s(comp_nec(unlicensed(same_percent_after_base_change)))).
misconception_pml(db_row(38813), s(comp_nec(unlicensed(visible_partition_required_for_equivalence)))).
misconception_pml(db_row(38814), s(comp_nec(unlicensed(part_to_part_as_part_whole)))).
misconception_pml(db_row(38815), s(comp_nec(unlicensed(count_unequal_parts_as_equal)))).
misconception_pml(db_row(38817), s(comp_nec(unlicensed(combination_complement_symmetry_missed)))).
misconception_pml(db_row(38822), s(comp_nec(unlicensed(factor_retrieval_error)))).
misconception_pml(db_row(38824), s(comp_nec(unlicensed(drop_geometric_context)))).
misconception_pml(db_row(38825), s(comp_nec(unlicensed(finite_endpoint_for_infinite_process)))).
misconception_pml(db_row(38827), s(comp_nec(unlicensed(infinite_member_in_finite_stage_union)))).
misconception_pml(db_row(38834), s(comp_nec(unlicensed(ltr_eval_ignores_precedence)))).
misconception_pml(db_row(38835), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(38837), s(comp_nec(unlicensed(count_parts_twice)))).
misconception_pml(db_row(38838), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(38851), s(comp_nec(unlicensed(superficial_primality_check)))).
misconception_pml(db_row(38853), s(comp_nec(unlicensed(remainder_tenths_division)))).
misconception_pml(db_row(38854), s(comp_nec(unlicensed(dividend_quotient_same_rate)))).
misconception_pml(db_row(38856), s(comp_nec(unlicensed(swap_for_convention)))).
misconception_pml(db_row(38863), s(comp_nec(unlicensed(addition_cannot_decrease)))).
misconception_pml(db_row(38865), s(comp_nec(unlicensed(negative_not_number)))).
misconception_pml(db_row(38866), s(comp_nec(unlicensed(cannot_add_negative)))).
misconception_pml(db_row(38868), s(comp_nec(unlicensed(equal_missing_count_is_equal)))).
misconception_pml(db_row(38879), s(comp_nec(unlicensed(always_common_unit_by_refinement)))).
misconception_pml(db_row(38898), s(comp_nec(unlicensed(denominator_only_compare)))).
misconception_pml(db_row(38908), s(comp_nec(unlicensed(takeaway_model_blocks_negative_result)))).
misconception_pml(db_row(38910), s(comp_nec(unlicensed(procedure_steps_as_reasonableness)))).
misconception_pml(db_row(38911), s(comp_nec(unlicensed(decimal_point_digit_count_only)))).
misconception_pml(db_row(38913), s(comp_nec(unlicensed(lowest_denom_greatest)))).
misconception_pml(db_row(38921), s(comp_nec(unlicensed(buggy_borrow_smaller_minuend)))).
misconception_pml(db_row(38922), s(comp_nec(unlicensed(div_as_mul)))).
misconception_pml(db_row(38927), s(comp_nec(unlicensed(div_instead_of_mult)))).
misconception_pml(db_row(38928), s(comp_nec(unlicensed(swap_for_division)))).
misconception_pml(db_row(38946), s(comp_nec(unlicensed(add_across_even_common_denom)))).
misconception_pml(db_row(38947), s(comp_nec(unlicensed(integer_subtraction_absolute_difference)))).
misconception_pml(db_row(38957), s(comp_nec(unlicensed(digit_div_floats)))).
misconception_pml(db_row(38958), s(comp_nec(unlicensed(digit_wise_division)))).
misconception_pml(db_row(38960), s(comp_nec(unlicensed(denominator_natural_order_sign)))).
misconception_pml(db_row(38964), s(comp_nec(unlicensed(decimal_tail_as_whole_number)))).
misconception_pml(db_row(38965), s(comp_nec(unlicensed(visible_faces_as_volume)))).
misconception_pml(db_row(38967), s(comp_nec(unlicensed(prior_block_name_overrides_decimal_unit)))).
misconception_pml(db_row(38972), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(38973), s(comp_nec(unlicensed(natural_number_bias)))).
misconception_pml(db_row(38975), s(comp_nec(unlicensed(subtract_larger_impossible)))).
misconception_pml(db_row(38977), s(comp_nec(unlicensed(half_as_diminutive)))).
misconception_pml(db_row(38980), s(comp_nec(unlicensed(notation_half_appends_2)))).
misconception_pml(db_row(38982), s(comp_nec(unlicensed(disjunction_requires_both_parts_true)))).
misconception_pml(db_row(38983), s(comp_nec(unlicensed(pragmatic_rejection_of_true_disjunction)))).
misconception_pml(db_row(38985), s(comp_nec(unlicensed(exclusive_or_for_inclusive_or)))).
misconception_pml(db_row(38986), s(comp_nec(unlicensed(digit_count_magnitude)))).
misconception_pml(db_row(38989), s(comp_nec(unlicensed(median_for_addition)))).
misconception_pml(db_row(38992), s(comp_nec(unlicensed(area_in_linear_units)))).
misconception_pml(db_row(38993), s(comp_nec(unlicensed(linear_area_conversion)))).
misconception_pml(db_row(38999), s(comp_nec(unlicensed(times_equals_as_double)))).
misconception_pml(db_row(39003), s(comp_nec(unlicensed(triangle_abc_product)))).
misconception_pml(db_row(39007), s(comp_nec(unlicensed(loss_of_whole_pooled_denom)))).
misconception_pml(db_row(39010), s(comp_nec(unlicensed(share_count_as_denominator)))).
misconception_pml(db_row(39012), s(comp_nec(unlicensed(circumference_growth_overestimated)))).
misconception_pml(db_row(39044), s(comp_nec(unlicensed(common_property_required_for_set)))).
misconception_pml(db_row(39045), s(comp_nec(unlicensed(singleton_not_set)))).
misconception_pml(db_row(39046), s(comp_nec(unlicensed(empty_set_not_set)))).
misconception_pml(db_row(39047), s(comp_nec(unlicensed(set_equality_by_cardinality)))).
misconception_pml(db_row(39048), s(comp_nec(unlicensed(repeated_elements_counted_in_set)))).
misconception_pml(db_row(39052), s(comp_nec(unlicensed(one_sig_fig_leading_one)))).
misconception_pml(db_row(39053), s(comp_nec(unlicensed(round_divisor_1_sigfig)))).
misconception_pml(db_row(39054), s(comp_nec(unlicensed(orientation_changes_half_size)))).
misconception_pml(db_row(39060), s(comp_nec(unlicensed(nonbase_place_value_as_decimal)))).
misconception_pml(db_row(39062), s(comp_nec(unlicensed(decimal_overgen)))).
misconception_pml(db_row(39066), s(comp_nec(unlicensed(zero_division_conflation)))).
misconception_pml(db_row(39077), s(comp_nec(unlicensed(mult_instead_of_div)))).
misconception_pml(db_row(39078), s(comp_nec(unlicensed(reverse_for_division)))).
misconception_pml(db_row(39081), s(comp_nec(unlicensed(subtract_for_divide)))).
misconception_pml(db_row(39089), s(comp_nec(unlicensed(gap_thinking)))).
misconception_pml(db_row(39090), s(comp_nec(unlicensed(whole_number_dominance_denom)))).
misconception_pml(db_row(39095), s(comp_nec(unlicensed(incomplete_reduction)))).
misconception_pml(db_row(39097), s(comp_nec(unlicensed(negative_bound_order_failure)))).
misconception_pml(db_row(39100), s(comp_nec(unlicensed(euclidean_division_as_factorization)))).
misconception_pml(db_row(39101), s(comp_nec(unlicensed(coprime_by_lcm_one)))).
misconception_pml(db_row(39105), s(comp_nec(unlicensed(rhombus_not_parallelogram)))).
misconception_pml(db_row(39106), s(comp_nec(unlicensed(visual_contour_overrides_area_equivalence)))).
misconception_pml(db_row(39109), s(comp_nec(unlicensed(part_whole_rule_for_infinite_sets)))).
misconception_pml(db_row(39110), s(comp_nec(unlicensed(smaller_from_larger_per_column)))).
misconception_pml(db_row(39124), s(comp_nec(unlicensed(zero_no_substitute)))).
misconception_pml(db_row(39125), s(comp_nec(unlicensed(borrow_no_compensation)))).
misconception_pml(db_row(39126), s(comp_nec(unlicensed(numerical_fact_slip)))).
misconception_pml(db_row(39127), s(comp_nec(unlicensed(persistence_of_digit)))).
misconception_pml(db_row(39128), s(comp_nec(unlicensed(match_whole_digits)))).
misconception_pml(db_row(39130), s(comp_nec(unlicensed(cross_multiply_for_multiply)))).
misconception_pml(db_row(39134), s(comp_nec(unlicensed(order_of_appearance_ratio)))).
misconception_pml(db_row(39137), s(comp_nec(unlicensed(minus_misread_as_minutes)))).
misconception_pml(db_row(39138), s(comp_nec(unlicensed(operation_doubling)))).
misconception_pml(db_row(39140), s(comp_nec(unlicensed(drop_decimal_unit)))).
misconception_pml(db_row(39141), s(comp_nec(unlicensed(area_equivalence_requires_congruence)))).
misconception_pml(db_row(39143), s(comp_nec(unlicensed(additive_compensation_preserves_area)))).
misconception_pml(db_row(39162), s(comp_nec(unlicensed(add_tops_and_bottoms)))).
misconception_pml(db_row(39165), s(comp_nec(unlicensed(divide_for_smaller_answer)))).
misconception_pml(db_row(39166), s(comp_nec(unlicensed(swap_when_dividend_smaller)))).
misconception_pml(db_row(39171), s(comp_nec(unlicensed(cue_word_fewer_subtracts)))).
misconception_pml(db_row(39178), s(comp_nec(unlicensed(random_arithmetic_recombination)))).
misconception_pml(db_row(39179), s(comp_nec(unlicensed(multiply_by_numerator_for_divide)))).
misconception_pml(db_row(39181), s(comp_nec(unlicensed(multiply_for_add)))).
misconception_pml(db_row(39183), s(comp_nec(unlicensed(area_model_count_addition)))).
misconception_pml(db_row(39184), s(comp_nec(unlicensed(unconstrained_remainder)))).
misconception_pml(db_row(39199), s(comp_nec(unlicensed(cuts_equal_pieces)))).
misconception_pml(db_row(39213), s(comp_nec(unlicensed(parity_last_digit_any_base)))).
misconception_pml(db_row(39214), s(comp_nec(unlicensed(even_exponent_even_power)))).
misconception_pml(db_row(39215), s(comp_nec(unlicensed(perfect_square_requires_even)))).
misconception_pml(db_row(39236), s(comp_nec(unlicensed(equals_as_separator)))).
misconception_pml(db_row(39237), s(comp_nec(unlicensed(nominal_same_blank)))).
misconception_pml(db_row(39240), s(comp_nec(unlicensed(composite_divisibility_as_prime_rule)))).
misconception_pml(db_row(39257), s(comp_nec(unlicensed(large_number_line_overplacement)))).
misconception_pml(db_row(39258), s(comp_nec(unlicensed(division_by_zero_infinity)))).
misconception_pml(db_row(39265), s(comp_nec(unlicensed(single_geographic_equator_on_sphere)))).
misconception_pml(db_row(39266), s(comp_nec(unlicensed(spherical_triangle_plane_sum)))).
misconception_pml(db_row(39299), s(comp_nec(unlicensed(smaller_from_larger_column)))).
misconception_pml(db_row(39318), s(comp_nec(unlicensed(bigger_denom_is_bigger)))).
misconception_pml(db_row(39319), s(comp_nec(unlicensed(product_of_primes_prime)))).
misconception_pml(db_row(39320), s(comp_nec(unlicensed(small_prime_divisibility_only)))).
misconception_pml(db_row(39321), s(comp_nec(unlicensed(gap_as_inverse_magnitude)))).
misconception_pml(db_row(39322), s(comp_nec(unlicensed(mult_for_divide_sub_one)))).
misconception_pml(db_row(39341), s(comp_nec(unlicensed(percent_estimate_order_error)))).
misconception_pml(db_row(39346), s(comp_nec(unlicensed(forget_decimal_point_mult)))).
misconception_pml(db_row(39347), s(comp_nec(unlicensed(multiply_without_invert)))).
misconception_pml(db_row(39348), s(comp_nec(unlicensed(mul_instead_of_div)))).
misconception_pml(db_row(39357), s(comp_nec(unlicensed(off_by_one_composite_unit)))).
misconception_pml(db_row(39366), s(comp_nec(unlicensed(drop_negative_in_subtraction)))).
misconception_pml(db_row(39374), s(comp_nec(unlicensed(divide_by_percent_number)))).
misconception_pml(db_row(39375), s(comp_nec(unlicensed(percent_as_absolute_amount)))).
misconception_pml(db_row(39378), s(comp_nec(unlicensed(contextual_componentwise_addition)))).
misconception_pml(db_row(39392), s(comp_nec(unlicensed(imperial_notation_collapse)))).
misconception_pml(db_row(39395), s(comp_nec(unlicensed(bedmas_strict_order)))).
misconception_pml(db_row(39396), s(comp_nec(unlicensed(acronym_order_reification)))).
misconception_pml(db_row(39407), s(comp_nec(unlicensed(mult_makes_bigger_belief)))).
misconception_pml(db_row(39408), s(comp_nec(unlicensed(div_makes_smaller_pst)))).
misconception_pml(db_row(39413), s(comp_nec(unlicensed(surface_action_subtracts)))).
misconception_pml(db_row(39422), s(comp_nec(unlicensed(less_cue_subtracts)))).
misconception_pml(db_row(39424), s(comp_nec(unlicensed(greater_than_as_difference)))).
misconception_pml(db_row(39430), s(comp_nec(unlicensed(shape_overrides_equal_area)))).
misconception_pml(db_row(39432), s(comp_nec(unlicensed(pick_easier_quotient)))).
misconception_pml(db_row(39433), s(comp_nec(unlicensed(fair_share_reciprocal)))).
misconception_pml(db_row(39438), s(comp_nec(unlicensed(whole_number_string_compare)))).
misconception_pml(db_row(39439), s(comp_nec(unlicensed(farther_from_dot_bigger)))).
misconception_pml(db_row(39441), s(comp_nec(unlicensed(trailing_zeros_inflate)))).
misconception_pml(db_row(39442), s(comp_nec(unlicensed(point_as_fraction_bar)))).
misconception_pml(db_row(39450), s(comp_nec(unlicensed(divide_for_smaller_result)))).
misconception_pml(db_row(39460), s(comp_nec(unlicensed(longer_is_larger)))).
misconception_pml(db_row(39461), s(comp_nec(unlicensed(shorter_is_bigger_fraction)))).
misconception_pml(db_row(39462), s(comp_nec(unlicensed(longer_is_larger_with_zero_rule)))).
misconception_pml(db_row(39465), s(comp_nec(unlicensed(fraction_as_decimal_point_five)))).
misconception_pml(db_row(39469), s(comp_nec(unlicensed(denom_larger_is_larger)))).
misconception_pml(db_row(39486), s(comp_nec(unlicensed(forward_for_reverse)))).
misconception_pml(db_row(39495), s(comp_nec(unlicensed(digit_sum_magnitude)))).
misconception_pml(db_row(39496), s(comp_nec(unlicensed(numeral_as_count_trace)))).
misconception_pml(db_row(39498), s(comp_nec(unlicensed(detach_sign_group_terms)))).
misconception_pml(db_row(39499), s(comp_nec(unlicensed(jump_posterior_operation)))).
misconception_pml(db_row(39501), s(comp_nec(unlicensed(left_to_right_add_first)))).
misconception_pml(db_row(39516), s(comp_nec(unlicensed(additive_similarity)))).
misconception_pml(db_row(39517), s(comp_nec(unlicensed(subtract_negative_as_add_negative)))).
misconception_pml(db_row(39523), s(comp_nec(unlicensed(compare_as_whole_number)))).
misconception_pml(db_row(39524), s(comp_nec(unlicensed(face_count_for_volume)))).
misconception_pml(db_row(39533), s(comp_nec(unlicensed(percent_as_absolute_amount)))).
misconception_pml(db_row(39534), s(comp_nec(unlicensed(divide_larger_by_smaller)))).
misconception_pml(db_row(39551), s(comp_nec(unlicensed(decimal_time_as_absolute_minutes)))).
misconception_pml(db_row(39554), s(comp_nec(unlicensed(componentwise_add)))).
misconception_pml(db_row(39556), s(comp_nec(unlicensed(unequal_wholes)))).
misconception_pml(db_row(39557), s(comp_nec(unlicensed(division_commutative)))).
misconception_pml(db_row(39575), s(comp_nec(unlicensed(more_digits_smaller)))).
misconception_pml(db_row(39576), s(comp_nec(unlicensed(compare_sides_independently)))).
misconception_pml(db_row(39578), s(comp_nec(unlicensed(compute_first_lose_structure)))).
misconception_pml(db_row(39585), s(comp_nec(unlicensed(area_scales_linearly)))).
misconception_pml(db_row(39591), s(comp_nec(unlicensed(count_as_unit_fraction)))).
misconception_pml(db_row(39594), s(comp_nec(unlicensed(count_as_unit_size)))).
misconception_pml(db_row(39604), s(comp_nec(unlicensed(denominator_as_group_size)))).
misconception_pml(db_row(39606), s(comp_nec(unlicensed(nonunit_as_one_subset)))).
misconception_pml(db_row(39607), s(comp_nec(unlicensed(decimal_hours_direct)))).
misconception_pml(db_row(39618), s(comp_nec(unlicensed(add_as_whole_prepend_dot)))).
misconception_pml(db_row(39619), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(39621), s(comp_nec(unlicensed(area_as_perimeter_value)))).
misconception_pml(db_row(39622), s(comp_nec(unlicensed(add_givens_for_missing_addend)))).
misconception_pml(db_row(39623), s(comp_nec(unlicensed(longer_is_larger)))).
misconception_pml(db_row(39624), s(comp_nec(unlicensed(shorter_is_larger_inverted)))).
misconception_pml(db_row(39625), s(comp_nec(unlicensed(money_place_truncation)))).
misconception_pml(db_row(39629), s(comp_nec(unlicensed(division_must_make_smaller)))).
misconception_pml(db_row(39630), s(comp_nec(unlicensed(divide_by_fraction_denominator)))).
misconception_pml(db_row(39631), s(comp_nec(unlicensed(whole_number_rule_ordering)))).
misconception_pml(db_row(39632), s(comp_nec(unlicensed(tenths_always_larger)))).
misconception_pml(db_row(39633), s(comp_nec(unlicensed(zero_rule_plus_wn)))).
misconception_pml(db_row(39635), s(comp_nec(unlicensed(count_marks_as_intervals)))).
misconception_pml(db_row(39636), s(comp_nec(unlicensed(additive_equivalence_pattern)))).
misconception_pml(db_row(39637), s(comp_nec(unlicensed(multiply_fraction_by_whole_for_equivalence)))).
misconception_pml(db_row(39638), s(comp_nec(unlicensed(additive_gap_as_same_flavour)))).
misconception_pml(db_row(39641), s(comp_nec(unlicensed(money_notation_preference)))).
misconception_pml(db_row(39646), s(comp_nec(unlicensed(ignore_zero_in_product)))).
misconception_pml(db_row(39647), s(comp_nec(unlicensed(more_digits_greater)))).
misconception_pml(db_row(39657), s(comp_nec(unlicensed(negate_conditional_as_inverse)))).
misconception_pml(db_row(39658), s(comp_nec(unlicensed(demorgan_connective_unchanged)))).
misconception_pml(db_row(39661), s(comp_nec(unlicensed(repeating_nines_less_than_one)))).
misconception_pml(db_row(39662), s(comp_nec(unlicensed(linear_factor_for_volume_scale)))).
misconception_pml(db_row(39678), s(comp_nec(unlicensed(division_by_zero_has_value)))).
misconception_pml(db_row(39679), s(comp_nec(unlicensed(div_by_zero_is_infinity)))).
misconception_pml(db_row(39689), s(comp_nec(unlicensed(keyword_add_ignore_unit)))).
misconception_pml(db_row(39690), s(comp_nec(unlicensed(round_wrong_place)))).
misconception_pml(db_row(39691), s(comp_nec(unlicensed(round_wrong_direction)))).
misconception_pml(db_row(39693), s(comp_nec(unlicensed(misplace_decimal_div)))).
misconception_pml(db_row(39694), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(39695), s(comp_nec(unlicensed(floor_instead_of_ceiling)))).
misconception_pml(db_row(39698), s(comp_nec(unlicensed(add_across_unlike_denom)))).
misconception_pml(db_row(39699), s(comp_nec(unlicensed(denominator_as_share_count)))).
misconception_pml(db_row(39701), s(comp_nec(unlicensed(first_component_only_ratio_compare)))).
misconception_pml(db_row(39708), s(comp_nec(unlicensed(subtract_ignore_point)))).
misconception_pml(db_row(39710), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(39712), s(comp_nec(unlicensed(ignore_whole_add_parts)))).
misconception_pml(db_row(39714), s(comp_nec(unlicensed(context_ignored_for_ratio)))).
misconception_pml(db_row(39718), s(comp_nec(unlicensed(unit_count_collapse)))).
misconception_pml(db_row(39719), s(comp_nec(unlicensed(teen_digit_reversal)))).
misconception_pml(db_row(39722), s(comp_nec(unlicensed(componentwise_add_3_7)))).
misconception_pml(db_row(39727), s(comp_nec(unlicensed(factor_adjust_wrong)))).
misconception_pml(db_row(39728), s(comp_nec(unlicensed(distributive_recombination)))).
misconception_pml(db_row(39730), s(comp_nec(unlicensed(subtraction_commutative)))).
misconception_pml(db_row(39732), s(comp_nec(unlicensed(closer_to_zero_by_integer)))).
misconception_pml(db_row(39734), s(comp_nec(unlicensed(gap_thinking_ordering)))).
misconception_pml(db_row(39735), s(comp_nec(unlicensed(inverse_scaling_on_terms)))).
misconception_pml(db_row(39736), s(comp_nec(unlicensed(denom_size_common_num)))).
misconception_pml(db_row(39740), s(comp_nec(unlicensed(fractional_bus_answer)))).
misconception_pml(db_row(39746), s(comp_nec(unlicensed(horizontal_sum_all_digits)))).
misconception_pml(db_row(39747), s(comp_nec(unlicensed(minus_as_plus)))).
misconception_pml(db_row(39749), s(comp_nec(unlicensed(equal_additions_asymmetric)))).
misconception_pml(db_row(39756), s(comp_nec(unlicensed(final_base_for_decrease)))).
misconception_pml(db_row(39764), s(comp_nec(unlicensed(order_by_numerator)))).
misconception_pml(db_row(39765), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(39766), s(comp_nec(unlicensed(mul_keep_denom)))).
misconception_pml(db_row(39767), s(comp_nec(unlicensed(common_denom_for_multiply)))).
misconception_pml(db_row(39768), s(comp_nec(unlicensed(slotwise_abs_subtract)))).
misconception_pml(db_row(39769), s(comp_nec(unlicensed(times_as_add_k_over_d)))).
misconception_pml(db_row(39776), s(comp_nec(unlicensed(familiar_whole_rule)))).
misconception_pml(db_row(39782), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(db_row(39791), s(comp_nec(unlicensed(mmb_teacher_copies_larger)))).
misconception_pml(db_row(39792), s(comp_nec(unlicensed(div_smaller_teacher)))).
misconception_pml(db_row(39793), s(comp_nec(unlicensed(more_places_smaller_teacher)))).
misconception_pml(db_row(39794), s(comp_nec(unlicensed(denominator_only_rule)))).
misconception_pml(db_row(39795), s(comp_nec(unlicensed(scaling_changes_value)))).
misconception_pml(db_row(39811), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(39812), s(comp_nec(unlicensed(denominator_as_answer)))).
misconception_pml(db_row(39814), s(comp_nec(unlicensed(bigger_denom_more_sweets)))).
misconception_pml(db_row(39821), s(comp_nec(unlicensed(multiplication_always_increases)))).
misconception_pml(db_row(39836), s(comp_nec(unlicensed(smaller_denom_smaller_frac)))).
misconception_pml(db_row(39841), s(comp_nec(unlicensed(additive_decomp_estimate)))).
misconception_pml(db_row(39842), s(comp_nec(unlicensed(leading_digit_truncation)))).
misconception_pml(db_row(39843), s(comp_nec(unlicensed(find_percent_as_find_part)))).
misconception_pml(db_row(39851), s(comp_nec(unlicensed(proposition_as_expression_value)))).
misconception_pml(db_row(39852), s(comp_nec(unlicensed(add_denominators_only)))).
misconception_pml(db_row(39855), s(comp_nec(unlicensed(mult_before_div)))).
misconception_pml(db_row(39864), s(comp_nec(unlicensed(proximity_by_absolute_gap)))).
misconception_pml(db_row(39873), s(comp_nec(unlicensed(quadrilateral_is_parallelogram)))).
misconception_pml(db_row(39874), s(comp_nec(unlicensed(square_not_rectangle)))).
misconception_pml(db_row(39885), s(comp_nec(unlicensed(whole_number_interference_fraction_addition)))).
misconception_pml(db_row(39886), s(comp_nec(unlicensed(denominator_as_decimal_digit)))).
misconception_pml(db_row(39890), s(comp_nec(unlicensed(swap_numer_denom_notation)))).
misconception_pml(db_row(39891), s(comp_nec(unlicensed(sort_by_gap)))).
misconception_pml(db_row(39892), s(comp_nec(unlicensed(componentwise_addition_same_denom)))).
misconception_pml(db_row(39897), s(comp_nec(unlicensed(forget_shift_divisor)))).
misconception_pml(db_row(39898), s(comp_nec(unlicensed(invert_both_operands)))).
misconception_pml(db_row(39899), s(comp_nec(unlicensed(divide_as_multiply)))).
misconception_pml(db_row(39900), s(comp_nec(unlicensed(left_to_right_no_precedence)))).
misconception_pml(db_row(39905), s(comp_nec(unlicensed(consecutive_profit_balances)))).
misconception_pml(db_row(39906), s(comp_nec(unlicensed(endpoint_profit_only)))).
misconception_pml(db_row(39907), s(comp_nec(unlicensed(transaction_role_swap)))).
misconception_pml(db_row(39919), s(comp_nec(unlicensed(componentwise_between)))).
misconception_pml(db_row(39931), s(comp_nec(unlicensed(original_base_compound_increase)))).
misconception_pml(db_row(39932), s(comp_nec(unlicensed(rate_equals_reciprocal_loss)))).
misconception_pml(db_row(39933), s(comp_nec(unlicensed(shorter_decimal_as_larger)))).
misconception_pml(db_row(39934), s(comp_nec(unlicensed(decimal_tail_distance)))).
misconception_pml(db_row(39935), s(comp_nec(unlicensed(decimal_scale_subunit_ignored)))).
misconception_pml(db_row(39936), s(comp_nec(unlicensed(decimal_add_no_carry)))).
misconception_pml(db_row(39948), s(comp_nec(unlicensed(add_across_unlike)))).
misconception_pml(db_row(39956), s(comp_nec(unlicensed(markup_as_find_percent)))).
misconception_pml(db_row(39957), s(comp_nec(unlicensed(discount_as_increase)))).
misconception_pml(db_row(39958), s(comp_nec(unlicensed(increase_amount_as_final_price)))).
misconception_pml(db_row(39963), s(comp_nec(unlicensed(add_across_rational_expressions)))).
misconception_pml(db_row(39964), s(comp_nec(unlicensed(left_to_right_no_precedence)))).
misconception_pml(db_row(39967), s(comp_nec(unlicensed(choose_notation_as_fraction)))).
misconception_pml(db_row(39974), s(comp_nec(unlicensed(opposites_not_cancelled)))).
misconception_pml(db_row(39986), s(comp_nec(unlicensed(part_to_part_for_part_whole)))).
misconception_pml(db_row(39993), s(comp_nec(unlicensed(literal_order_sentence)))).
misconception_pml(db_row(40005), s(comp_nec(unlicensed(remainder_wrong_unit)))).
misconception_pml(db_row(40010), s(comp_nec(unlicensed(diameter_for_area)))).
misconception_pml(db_row(40011), s(comp_nec(unlicensed(volume_scales_linearly)))).
misconception_pml(db_row(40024), s(comp_nec(unlicensed(mislabel_grid)))).
misconception_pml(db_row(40025), s(comp_nec(unlicensed(subtract_fraction_of_current_amount)))).
misconception_pml(db_row(40026), s(comp_nec(unlicensed(unlike_denominator_componentwise_addition)))).
misconception_pml(db_row(40027), s(comp_nec(unlicensed(denominator_pattern_ordering)))).
misconception_pml(db_row(40042), s(comp_nec(unlicensed(dimensional_collapse_area_to_linear)))).
misconception_pml(db_row(40043), s(comp_nec(unlicensed(total_area_div_card_area)))).
misconception_pml(db_row(40044), s(comp_nec(unlicensed(count_on_off_by_one)))).
misconception_pml(db_row(40048), s(comp_nec(unlicensed(double_decimal_shift)))).
misconception_pml(db_row(40051), s(comp_nec(unlicensed(zero_not_in_parity)))).
misconception_pml(db_row(40063), s(comp_nec(unlicensed(juxtapose_unit_totals)))).
misconception_pml(db_row(40066), s(comp_nec(unlicensed(exponent_as_multiplier)))).
misconception_pml(db_row(40067), s(comp_nec(unlicensed(add_instead_of_mult)))).
misconception_pml(db_row(40075), s(comp_nec(unlicensed(common_denom_in_mult)))).
misconception_pml(db_row(40082), s(comp_nec(unlicensed(round_both_up_wildly)))).
misconception_pml(db_row(40083), s(comp_nec(unlicensed(distribute_denom_over_product)))).
misconception_pml(db_row(40085), s(comp_nec(unlicensed(count_for_proportion)))).
misconception_pml(db_row(40091), s(comp_nec(unlicensed(fractional_remainder_as_whole_remainder)))).
misconception_pml(db_row(40103), s(comp_nec(unlicensed(smaller_denom_always_larger)))).
misconception_pml(db_row(40112), s(comp_nec(unlicensed(pieces_instead_of_fraction)))).
misconception_pml(db_row(40113), s(comp_nec(unlicensed(referent_whole_aggregate)))).
misconception_pml(db_row(40123), s(comp_nec(unlicensed(gap_thinking_pst)))).
misconception_pml(db_row(40124), s(comp_nec(unlicensed(same_numer_smaller_denom_smaller)))).
misconception_pml(db_row(40126), s(comp_nec(unlicensed(benchmark_distance_flipped)))).
misconception_pml(db_row(40128), s(comp_nec(unlicensed(smaller_from_larger_column)))).
misconception_pml(db_row(40138), s(comp_nec(unlicensed(reciprocal_analogy)))).
misconception_pml(db_row(40139), s(comp_nec(unlicensed(longer_is_larger_pst)))).
misconception_pml(db_row(40140), s(comp_nec(unlicensed(zero_larger_than_decimal)))).
misconception_pml(db_row(40141), s(comp_nec(unlicensed(columnwise_absdiff)))).
misconception_pml(db_row(40142), s(comp_nec(unlicensed(no_cross_multiply_digits)))).
misconception_pml(db_row(40143), s(comp_nec(unlicensed(multiply_keeps_common_denominator)))).
misconception_pml(db_row(40144), s(comp_nec(unlicensed(componentwise_add)))).
misconception_pml(db_row(40147), s(comp_nec(unlicensed(divide_as_take_fraction_of)))).
misconception_pml(db_row(40154), s(comp_nec(unlicensed(local_unit_collapses_fraction)))).
misconception_pml(db_row(40155), s(comp_nec(unlicensed(remainder_in_original_unit)))).
misconception_pml(db_row(40162), s(comp_nec(unlicensed(tens_as_ones)))).
misconception_pml(db_row(40167), s(comp_nec(unlicensed(compare_returns_larger)))).
misconception_pml(db_row(40168), s(comp_nec(unlicensed(difference_as_sum)))).
misconception_pml(db_row(40169), s(comp_nec(unlicensed(additive_divisor_decomposition)))).
misconception_pml(db_row(40175), s(comp_nec(unlicensed(denominator_dominance)))).
misconception_pml(db_row(40181), s(comp_nec(unlicensed(longer_decimal_smaller)))).
misconception_pml(db_row(40182), s(comp_nec(unlicensed(count_zeroes_ignore_decimal_point)))).
misconception_pml(db_row(40197), s(comp_nec(unlicensed(smaller_denom_larger_fraction)))).
misconception_pml(db_row(40200), s(comp_nec(unlicensed(more_pieces_wins)))).
misconception_pml(db_row(40207), s(comp_nec(unlicensed(parallelogram_not_quadrilateral)))).
misconception_pml(db_row(40209), s(comp_nec(unlicensed(digits_as_ones_blocks)))).
misconception_pml(db_row(40210), s(comp_nec(unlicensed(square_not_rectangle)))).
misconception_pml(db_row(40217), s(comp_nec(unlicensed(context_ignores_rounding_constraint)))).
misconception_pml(db_row(40226), s(comp_nec(unlicensed(appended_zero_makes_decimal_larger)))).
misconception_pml(db_row(40227), s(comp_nec(unlicensed(decimal_tail_as_named_unit)))).
misconception_pml(db_row(40230), s(comp_nec(unlicensed(add_for_multiply_components)))).
misconception_pml(db_row(40231), s(comp_nec(unlicensed(fraction_of_whole_as_int_div)))).
misconception_pml(db_row(40234), s(comp_nec(unlicensed(remainder_not_ceiling)))).
misconception_pml(db_row(40235), s(comp_nec(unlicensed(remainder_count_as_denom)))).
misconception_pml(db_row(40236), s(comp_nec(unlicensed(drop_place_value_scaling)))).
misconception_pml(db_row(40240), s(comp_nec(unlicensed(numerator_as_percent)))).
misconception_pml(db_row(40241), s(comp_nec(unlicensed(square_side_area_halved)))).
misconception_pml(db_row(40243), s(comp_nec(unlicensed(transfer_full_difference)))).
misconception_pml(db_row(40244), s(comp_nec(unlicensed(pythagorean_as_triangle_area)))).
misconception_pml(db_row(40254), s(comp_nec(unlicensed(perimeter_two_sides)))).
misconception_pml(db_row(40261), s(comp_nec(unlicensed(triangle_area_no_half)))).
misconception_pml(db_row(40263), s(comp_nec(unlicensed(distance_to_denominator_as_size)))).
misconception_pml(db_row(40264), s(comp_nec(unlicensed(denom_size_pst)))).
misconception_pml(db_row(40265), s(comp_nec(unlicensed(rectangle_angle_sum_three_triangles)))).
misconception_pml(db_row(40269), s(comp_nec(unlicensed(digit_swap_equal)))).
misconception_pml(db_row(40272), s(comp_nec(unlicensed(always_add_in_word_problem)))).
misconception_pml(db_row(40273), s(comp_nec(unlicensed(commutativity_transferred_to_subtraction)))).
misconception_pml(db_row(40283), s(comp_nec(unlicensed(inconsistent_partial_products)))).
misconception_pml(db_row(40284), s(comp_nec(unlicensed(add_instead_of_multiply_word)))).
misconception_pml(db_row(40285), s(comp_nec(unlicensed(add_num_denom_1_4_1_16)))).
misconception_pml(db_row(40296), s(comp_nec(unlicensed(parallelogram_is_rhombus)))).
misconception_pml(db_row(40305), s(comp_nec(unlicensed(divisor_remainder_as_decimal)))).
misconception_pml(db_row(40312), s(comp_nec(unlicensed(additive_for_multiplicative_scale)))).
misconception_pml(db_row(40320), s(comp_nec(unlicensed(equal_diff_equal_product)))).
misconception_pml(db_row(40321), s(comp_nec(unlicensed(miscount_decimal_places)))).
misconception_pml(db_row(40323), s(comp_nec(unlicensed(divide_by_percent_number)))).
misconception_pml(db_row(40324), s(comp_nec(unlicensed(inverted_division_rule)))).
misconception_pml(db_row(40343), s(comp_nec(unlicensed(denominator_as_other_constituent)))).
misconception_pml(db_row(40350), s(comp_nec(unlicensed(square_not_rhombus)))).
misconception_pml(db_row(40354), s(comp_nec(unlicensed(mult_grows_sub_one)))).
misconception_pml(db_row(40360), s(comp_nec(unlicensed(equal_difference_equal_fraction)))).
misconception_pml(db_row(40364), s(comp_nec(unlicensed(larger_denom_larger_frac)))).
misconception_pml(db_row(40378), s(comp_nec(unlicensed(zero_numerator_bumped)))).
misconception_pml(db_row(40379), s(comp_nec(unlicensed(add_num_denom_for_missing)))).
misconception_pml(db_row(40380), s(comp_nec(unlicensed(add_fracs_subtract_wholes)))).
misconception_pml(db_row(40381), s(comp_nec(unlicensed(mul_orig_num_denom)))).
misconception_pml(db_row(40382), s(comp_nec(unlicensed(negative_sign_affixed_to_result)))).
misconception_pml(db_row(40384), s(comp_nec(unlicensed(decimal_percent_inverted)))).
misconception_pml(db_row(40385), s(comp_nec(unlicensed(decimal_not_shifted_to_percent)))).
misconception_pml(db_row(40387), s(comp_nec(unlicensed(drop_negative_base_sign)))).
misconception_pml(db_row(40403), s(comp_nec(unlicensed(negative_subtraction_count_error)))).
misconception_pml(db_row(40405), s(comp_nec(unlicensed(equal_gap_means_equal)))).
misconception_pml(db_row(40406), s(comp_nec(unlicensed(blind_place_rule)))).
misconception_pml(db_row(40412), s(comp_nec(unlicensed(mirror_place_last_ones)))).
misconception_pml(db_row(40413), s(comp_nec(unlicensed(shorter_is_larger)))).
misconception_pml(db_row(40414), s(comp_nec(unlicensed(decimal_as_nat_sequence)))).
misconception_pml(db_row(40441), s(comp_nec(unlicensed(sort_by_distance_larger_means_smaller)))).
misconception_pml(db_row(40442), s(comp_nec(unlicensed(sum_dp_no_trailing_zero_account)))).
misconception_pml(db_row(40446), s(comp_nec(unlicensed(symbolic_pattern_number_line)))).
misconception_pml(db_row(40447), s(comp_nec(unlicensed(total_tick_count_as_denominator)))).
misconception_pml(db_row(40449), s(comp_nec(unlicensed(same_numer_bigger_denom_bigger)))).
misconception_pml(db_row(40450), s(comp_nec(unlicensed(componentwise_estimate)))).
misconception_pml(db_row(40451), s(comp_nec(unlicensed(gap_thinking)))).
misconception_pml(db_row(40452), s(comp_nec(unlicensed(smaller_components_larger)))).
misconception_pml(db_row(40454), s(comp_nec(unlicensed(componentwise_estimate)))).
misconception_pml(db_row(40455), s(comp_nec(unlicensed(numerator_only_addition)))).
misconception_pml(db_row(40456), s(comp_nec(unlicensed(same_numer_bigger_denom_bigger)))).
misconception_pml(db_row(40465), s(comp_nec(unlicensed(one_for_one_exchange)))).
misconception_pml(db_row(40469), s(comp_nec(unlicensed(div_to_add_then_across)))).
misconception_pml(db_row(40472), s(comp_nec(unlicensed(no_point_placement)))).
misconception_pml(db_row(40473), s(comp_nec(unlicensed(decimal_for_discrete)))).
misconception_pml(db_row(40480), s(comp_nec(unlicensed(same_numer_larger_denom_larger)))).
misconception_pml(db_row(40483), s(comp_nec(unlicensed(part_over_remaining)))).
misconception_pml(db_row(40484), s(comp_nec(unlicensed(two_minuses_make_plus_overapplied)))).
misconception_pml(db_row(40486), s(comp_nec(unlicensed(pool_across_wholes)))).
misconception_pml(db_row(40490), s(comp_nec(unlicensed(whole_line_as_unit)))).
misconception_pml(db_row(40491), s(comp_nec(unlicensed(part_whole_default_to_one)))).
misconception_pml(db_row(40493), s(comp_nec(unlicensed(mean_squared_as_area)))).
misconception_pml(db_row(40496), s(comp_nec(unlicensed(area_model_miscount_div)))).
misconception_pml(db_row(40497), s(comp_nec(unlicensed(refine_estimate_wrong_unit)))).
misconception_pml(db_row(40500), s(comp_nec(unlicensed(decimal_as_unit_fraction)))).
misconception_pml(db_row(40501), s(comp_nec(unlicensed(zero_as_smallest_integer)))).
misconception_pml(db_row(40502), s(comp_nec(unlicensed(decimal_incr_as_whole)))).
misconception_pml(db_row(40512), s(comp_nec(unlicensed(times_table_memory_slip)))).
misconception_pml(db_row(40515), s(comp_nec(unlicensed(fraction_symbol_as_and_half)))).
misconception_pml(db_row(40527), s(comp_nec(unlicensed(decimal_part_as_integer)))).
misconception_pml(db_row(40528), s(comp_nec(unlicensed(square_not_rectangle)))).
misconception_pml(db_row(40531), s(comp_nec(unlicensed(times_table_as_unit_fraction)))).
misconception_pml(db_row(40539), s(comp_nec(unlicensed(bigger_means_more_factors)))).
misconception_pml(db_row(40544), s(comp_nec(unlicensed(single_digit_percent_as_tenths)))).
misconception_pml(db_row(40551), s(comp_nec(unlicensed(subtract_fraction_of_total_collection)))).
misconception_pml(db_row(40552), s(comp_nec(unlicensed(components_as_whole_numbers)))).
misconception_pml(db_row(40585), s(comp_nec(unlicensed(failed_regrouping)))).
misconception_pml(db_row(40587), s(comp_nec(unlicensed(buggy_split_bridging_ten)))).
misconception_pml(db_row(40588), s(comp_nec(unlicensed(inverse_not_recognized)))).
misconception_pml(db_row(40592), s(comp_nec(unlicensed(smaller_from_larger_columnwise)))).
misconception_pml(db_row(40597), s(comp_nec(unlicensed(hundredths_bigger_than_thousandths)))).
misconception_pml(db_row(40622), s(comp_nec(unlicensed(guess_total_parts_for_fraction_of_fraction)))).
misconception_pml(db_row(40624), s(comp_nec(unlicensed(endpoint_counting_on_number_line)))).
misconception_pml(db_row(40630), s(comp_nec(unlicensed(mult_produces_bigger)))).
misconception_pml(db_row(40632), s(comp_nec(unlicensed(always_larger_over_smaller)))).
misconception_pml(db_row(40638), s(comp_nec(unlicensed(first_foot_uncounted)))).
misconception_pml(db_row(40641), s(comp_nec(unlicensed(count_marks_not_intervals)))).
misconception_pml(db_row(40662), s(comp_nec(unlicensed(denom_follows_piece_count)))).
misconception_pml(db_row(40671), s(comp_nec(unlicensed(partial_products_like_place_only)))).
misconception_pml(db_row(40672), s(comp_nec(unlicensed(single_partial_area)))).
misconception_pml(db_row(40673), s(comp_nec(unlicensed(size_rank_as_dimension)))).
misconception_pml(db_row(40674), s(comp_nec(unlicensed(compensation_failure)))).
misconception_pml(asktm('06-03'), s(comp_nec(unlicensed(magnitude_transfer(from_prior_pair, wrong_sign))))).
misconception_pml(asktm('06-03'), s(comp_nec(unlicensed(mutation(scale(8->24, 9->18)))))).
misconception_pml(asktm('06-03'), s(comp_nec(unlicensed(skip_pair(frac(2,3), frac(3,8)))))).
misconception_pml(asktm(g4q3_common), s(comp_nec(unlicensed(partial_scaling(numerator_only))))).
misconception_pml(asktm(g4q7_common), s(comp_nec(unlicensed(operation_substitution(add_for_multiply))))).
misconception_pml(asktm(g5q1_common), s(comp_nec(unlicensed(componentwise_addition)))).
misconception_pml(asktm(g5q7_common), s(comp_nec(unlicensed(referent_drop(outer_scalar))))).
misconception_pml(vocabulary(container_schema), s(comp_nec(unlicensed(formula_substitution(area_for_perimeter))))).
misconception_pml(vocabulary(container_schema), s(comp_nec(unlicensed(formula_substitution(perimeter_for_area))))).
misconception_pml(vocabulary(container_schema), s(comp_nec(unlicensed(partial_boundary_traversal)))).
misconception_pml(vocabulary(container_schema), s(comp_nec(unlicensed(schema_substitution(boundary_for_interior))))).
misconception_pml(vocabulary(measuring_stick_schema), s(comp_nec(unlicensed(base_substitution(base10_for_base60))))).
