/** <module> cw_calculus_claim -- mechanical crosswalk family data. */
:- module(cw_calculus_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_calculus_claim).
cw_rule(cc(limit_process_evaluation, c_calculus_limit_process_definition, "Limits, continuity, and convergence are read as limiting processes.", ['action_automaton_cluster/3(calculus,direct_substitution)', 'action_automaton_cluster/3(calculus,factor_cancel_substitute)', 'action_automaton_cluster/3(calculus,bounded_numerator_over_diverging_denominator)'])).
cw_rule(cc(rate_of_change_covariation, c_rate_of_change_covariation, "Rates of change and slopes coordinate covarying quantities.", ['action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)', 'action_automaton_vocabulary/3(algebraic,guess_and_check_rule)'])).
cw_rule(cc(accumulation_rate_distinction, c_accumulation_rate_distinction, "Accumulation and rate of change are distinct quantities.", ['action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)'])).
cw_rule((claim_literature_atom(A, B):-cc(A, B, _, _))).
cw_rule((legacy_list(A, B):-cc(A, C, _, D), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', C, ')'], E), append([[E], D], B))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((calculus_claim_unified(A, B, C):-calculus_claim_witness(A, B, C, _))).
cw_rule((calculus_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(calculus_claim_crosswalk, closed_world_finite_verified_calculus_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), cc(A, B, _, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((calculus_claim_witness(A, edge(B), B, C):-witness_dict:witness_dict(calculus_claim_crosswalk, closed_world_finite_verified_calculus_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge(B), legacy_functor:B, projection:verified_legacy_edge, source:B, source_witness:D}, C), cc(A, _, _, E), member(B, E), calculus_claim_edge_source_witness(B, D))).
cw_rule((calculus_claim_edge_source_witness('action_automaton_cluster/3(calculus,direct_substitution)', _{action_kind:direct_substitution, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(calculus, direct_substitution, A), _, fail))).
cw_rule((calculus_claim_edge_source_witness('action_automaton_cluster/3(calculus,factor_cancel_substitute)', _{action_kind:factor_cancel_substitute, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(calculus, factor_cancel_substitute, A), _, fail))).
cw_rule((calculus_claim_edge_source_witness('action_automaton_cluster/3(calculus,bounded_numerator_over_diverging_denominator)', _{action_kind:bounded_numerator_over_diverging_denominator, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(calculus, bounded_numerator_over_diverging_denominator, A), _, fail))).
cw_rule((calculus_claim_edge_source_witness('action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)', _{action_kind:linear_pattern_contextual_rule, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:algebraic, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(algebraic, linear_pattern_contextual_rule, A), _, fail))).
cw_rule((calculus_claim_edge_source_witness('action_automaton_vocabulary/3(algebraic,guess_and_check_rule)', _{action_kind:guess_and_check_rule, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:algebraic, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(algebraic, guess_and_check_rule, A), _, fail))).
