/** <module> cw_executable_practice -- crosswalk family data. */
:-module(cw_executable_practice,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(learner(more_machine_learner),[]).
:-use_module(learner(oracle_server),[]).
:-use_module(pml(mua_relations),[]).
cw_family(cw_executable_practice).
edge(more_machine_learner,run_learned_strategy/5,[addition,2,3],[4,5],call_once_bind_out).
cw_rule((executable_practice_unified(A,B,C,D):-executable_practice_witness(A,B,C,D,_15266))).
cw_rule((executable_practice_witness(A,B,C,D,E):-witness_dict:witness_dict(executable_practice_registry_entry,closed_world_finite_loaded_executable_practice_registry,_15376{invocation_policy:H,legacy_functor:G,practice_kind:C,predicate:B,source:D,source_witness:I,variant:A},E),source_executable_practice_witness(A,B,C,D,G,H,I))).
cw_rule((source_executable_practice_witness(mml_run_learned_strategy,more_machine_learner:run_learned_strategy/5,executor,more_machine_learner,'more_machine_learner:run_learned_strategy/5',registry_only_no_strategy_execution,_15606{dynamic:true,kind:dynamic_executor_presence,learned_clause_count:C,module:more_machine_learner,predicate:run_learned_strategy/5,properties:B,visibility:exported_predicate}):-predicate_presence_witness(more_machine_learner,run_learned_strategy,5,B),count_learned_strategy_clauses(C))).
cw_rule((source_executable_practice_witness(oracle_list_available_strategies,oracle_server:list_available_strategies/2,name_catalogue,oracle_server,'oracle_server:list_available_strategies/2',read_only_catalogue_query,_15762{catalogue_size:D,kind:oracle_strategy_catalogue,module:oracle_server,operations:C,predicate:list_available_strategies/2,properties:B,sample_operation:add,sample_strategies:E}):-predicate_presence_witness(oracle_server,list_available_strategies,2,B),findall(F-G,catch(oracle_server:list_available_strategies(F,G),_,fail),I),pairs_keys(I,C),length(I,D),memberchk(add-E,I))).
cw_rule((source_executable_practice_witness(mua_practice,mua_relations:practice/2,registry_fact,mua_relations,'mua_relations:practice/2',read_only_registry_fact_query,_16078{kind:mua_practice_registry,mapped_practice_count:G,module:mua_relations,practice_count:F,predicate:practice/2,properties:B,sample_action_kind:E,sample_description:D,sample_operation:C,sample_practice:p_count_on_from_larger}):-predicate_presence_witness(mua_relations,practice,2,B),catch(mua_relations:practice(p_count_on_from_larger,D),_,fail),catch(mua_relations:practice_kind(p_count_on_from_larger,C,E),_,fail),findall(J,catch(mua_relations:practice(J,_),_,fail),M),sort(M,N),length(N,F),findall(O,catch(mua_relations:practice_kind(O,_,_),_,fail),S),sort(S,T),length(T,G))).
cw_rule((predicate_presence_witness(A,B,C,D):-catch(current_predicate(A:B/C),_16706,fail),findall(F,predicate_presence_property(A,B,C,F),G),sort(G,D))).
cw_rule((predicate_presence_property(A,B,C,defined):-functor(D,B,C),predicate_property(A:D,defined))).
cw_rule((predicate_presence_property(A,B,C,exported):-functor(D,B,C),predicate_property(A:D,exported))).
cw_rule((predicate_presence_property(A,B,C,dynamic):-functor(D,B,C),predicate_property(A:D,dynamic))).
cw_rule((count_learned_strategy_clauses(A):-findall(1,catch(clause(more_machine_learner:run_learned_strategy(_17260,_,_,_,_),_),_,fail),I),length(I,A))).
cw_rule(canonical_concept('more_machine_learner:run_learned_strategy/5',executable_practice)).
cw_rule(canonical_concept('oracle_server:list_available_strategies/2',executable_practice)).
cw_rule(canonical_concept('mua_relations:practice/2',executable_practice)).
cw_rule(vocabulary_source(executable_practice,['more_machine_learner:run_learned_strategy/5','oracle_server:list_available_strategies/2','mua_relations:practice/2'])).
