/** <module> cw_integer_signed_claim -- mechanical crosswalk family data. */
:- module(cw_integer_signed_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_integer_signed_claim).
cw_rule(isc(directed_signed_quantity_operations, c_signed_number_order_and_operations, [edge('action_automata_registry:action_automaton_cluster/3(integer,signed_addition_with_sign_relation)', "Productive integer action automaton coordinating sign and magnitude; the sign-sensitive signed_number_combination cluster."), edge('grounding_metaphors:grounds_inference/3(arithmetic_is_motion_along_a_path,negative_numbers)', "Negatives grounded as directed point-locations ordered on a path (Motion Along a Path)."), edge('grounding_metaphors:grounds_inference/3(multiplication_by_minus_one_is_rotation_by_180_degrees,product_of_two_negatives)', "Sign-sensitive multiplication grounded as rotation: two 180-degree rotations compose to identity."), edge('misconception_registry:incompatibility_with/2(drop_sign_use_magnitude_sum)', "Derived incompatibility: dropping the sign and summing magnitudes violates the sign-sensitive combination commitment.")])).
cw_rule(isc(algebraic_term_sign_attachment, c_signed_term_structure, [edge('misconception_registry:incompatibility_with/2(detach_sign_group_terms)', "Registered misconception: detaching a number from its preceding operation sign and regrouping by sign violates 'each term carries its operation sign'.")])).
cw_rule((claim_literature_atom(A, B):-isc(A, B, _))).
cw_rule((legacy_list(A, [B|C]):-isc(A, D, E), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', D, ')'], B), findall(F, member(edge(F, _), E), C))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((integer_signed_claim_unified(A, B, C):-integer_signed_claim_witness(A, B, C, _))).
cw_rule((integer_signed_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(integer_signed_claim_crosswalk, closed_world_finite_verified_integer_signed_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), isc(A, B, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((integer_signed_claim_witness(A, edge_surface(B), C, D):-witness_dict:witness_dict(integer_signed_claim_crosswalk, closed_world_finite_verified_integer_signed_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge_surface(B), legacy_functor:C, projection:verified_legacy_edge_surface, source:C, source_witness:E}, D), isc(A, _, F), member(edge(C, B), F), integer_signed_edge_source_witness(C, E))).
cw_rule((integer_signed_edge_source_witness('action_automata_registry:action_automaton_cluster/3(integer,signed_addition_with_sign_relation)', _{action_kind:signed_addition_with_sign_relation, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:integer, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(integer, signed_addition_with_sign_relation, A), _, fail))).
cw_rule((integer_signed_edge_source_witness('grounding_metaphors:grounds_inference/3(arithmetic_is_motion_along_a_path,negative_numbers)', _{grounding_path:A, grounding_witness:B, kind:grounding_metaphor_inference_edge, metaphor:arithmetic_is_motion_along_a_path, module:grounding_metaphors, predicate:grounds_inference_witness/4, target_inference:negative_numbers}):-catch(grounding_metaphors:grounds_inference_witness(arithmetic_is_motion_along_a_path, negative_numbers, A, B), _, fail))).
cw_rule((integer_signed_edge_source_witness('grounding_metaphors:grounds_inference/3(multiplication_by_minus_one_is_rotation_by_180_degrees,product_of_two_negatives)', _{grounding_path:A, grounding_witness:B, kind:grounding_metaphor_inference_edge, metaphor:multiplication_by_minus_one_is_rotation_by_180_degrees, module:grounding_metaphors, predicate:grounds_inference_witness/4, target_inference:product_of_two_negatives}):-catch(grounding_metaphors:grounds_inference_witness(multiplication_by_minus_one_is_rotation_by_180_degrees, product_of_two_negatives, A, B), _, fail))).
cw_rule((integer_signed_edge_source_witness('misconception_registry:incompatibility_with/2(drop_sign_use_magnitude_sum)', _{conflict:strategy(integer, signed_addition_with_sign_relation), kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:drop_sign_use_magnitude_sum, predicate:incompatibility_with_witness/3, registry_witness:A}):-catch(once(misconception_registry:incompatibility_with_witness(drop_sign_use_magnitude_sum, strategy(integer, signed_addition_with_sign_relation), A)), _, fail))).
cw_rule((integer_signed_edge_source_witness('misconception_registry:incompatibility_with/2(detach_sign_group_terms)', _{conflict:result_of(detach_sign_group_terms, db_row(39498), 60), kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:detach_sign_group_terms, predicate:incompatibility_with_witness/3, registry_witness:A}):-catch(once(misconception_registry:incompatibility_with_witness(detach_sign_group_terms, result_of(detach_sign_group_terms, db_row(39498), 60), A)), _, fail))).
