/** <module> cw_multiplication_division_claim -- mechanical crosswalk family data. */
:- module(cw_multiplication_division_claim,
          [ cw_family/1,
            cw_rule/1,
            edge/5
          ]).

:- use_module(standards('indiana/standard_3_ca_3_4'), []).

cw_family(cw_multiplication_division_claim).
edge(standard_3_ca_3_4,mult_div_family_witness/5,[recollection([tally,tally,tally]),recollection([tally,tally,tally,tally])],[3,4,5],call_once_bind_out).
cw_rule(md(equal_groups_composite_unit, c_equal_groups_equal_size, [edge(cluster(multiplication, coordinate_groups_items), 'action_automata_registry:action_automaton_cluster/3(multiplication,coordinate_groups_items)'), edge(cluster(multiplication, repeat_equal_groups), 'action_automata_registry:action_automaton_cluster/3(multiplication,repeat_equal_groups)')])).
cw_rule(md(fair_share_partition_grouping, c_equal_sharing_partition_model, [edge(cluster(division, fair_share_equal_groups), 'action_automata_registry:action_automaton_cluster/3(division,fair_share_equal_groups)')])).
cw_rule(md(division_quotient_remainder_coordination, c_division_structure_and_remainder, [edge(cluster(division, share_into_divisor_groups), 'action_automata_registry:action_automaton_cluster/3(division,share_into_divisor_groups)'), edge(vocabulary(division, measure_groups_of_size), 'action_automata_registry:action_automaton_vocabulary/3(division,measure_groups_of_size)')])).
cw_rule(md(division_by_zero_undefined_deontic, c_division_by_zero_undefined, [edge(incompatibility(division_by_zero_numerical), 'misconception_registry:incompatibility_with/2(division_by_zero_numerical)')])).
cw_rule(md(partial_product_not_additive_reduction, c_multiplicative_structure_not_additive, [edge(vocabulary(multiplication, distribute_group_size_split), 'action_automata_registry:action_automaton_vocabulary/3(multiplication,distribute_group_size_split)'), edge(cluster(multiplication, add_counts_without_composite_unit), 'action_automata_registry:action_automaton_cluster/3(multiplication,add_counts_without_composite_unit)')])).
cw_rule(md(number_factor_multiple_structure, c_number_multiplicative_structure, [edge(is_prime, 'formal/formalization/axioms_number_theory:is_prime/1'), edge(find_prime_factor, 'formal/formalization/axioms_number_theory:find_prime_factor/2')])).
cw_rule((claim_literature_atom(A, B):-md(A, B, _))).
cw_rule((legacy_list(A, B):-md(A, C, D), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', C, ')'], E), findall(F, member(edge(_, F), D), G), append([[E], G], B))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((multiplication_division_claim_unified(A, commitment(B, C), literature_commitment):-multiplication_division_claim_witness(A, commitment(B, C), literature_commitment, _))).
cw_rule((multiplication_division_claim_unified(A, edge(B), C):-multiplication_division_claim_witness(A, edge(B), C, _))).
cw_rule((multiplication_division_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(multiplication_division_claim_crosswalk, closed_world_finite_verified_multiplication_division_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), md(A, B, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((multiplication_division_claim_witness(A, edge(B), C, D):-witness_dict:witness_dict(multiplication_division_claim_crosswalk, closed_world_finite_verified_multiplication_division_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge(B), legacy_functor:C, projection:verified_legacy_edge, source:C, source_witness:E}, D), md(A, _, F), member(edge(B, C), F), multiplication_division_edge_source_witness(B, E))).
cw_rule((multiplication_division_edge_source_witness(cluster(A, B), _{action_kind:B, cluster:D, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:A, predicate:action_automaton_cluster/3, vocabulary:C}):-catch(action_automata_registry:action_automaton_cluster(A, B, D), _, fail), catch(action_automata_registry:action_automaton_vocabulary(A, B, C), _, fail))).
cw_rule((multiplication_division_edge_source_witness(vocabulary(A, B), _{action_kind:B, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:A, predicate:action_automaton_vocabulary/3, vocabulary:C}):-catch(action_automata_registry:action_automaton_vocabulary(A, B, C), _, fail))).
cw_rule((multiplication_division_edge_source_witness(incompatibility(division_by_zero_numerical), _{conflict:A, incompatibility_witness:B, kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:division_by_zero_numerical, predicate:incompatibility_with/2}):-catch(once(misconception_registry:incompatibility_with_witness(division_by_zero_numerical, A, B)), _, fail))).
cw_rule((multiplication_division_edge_source_witness(is_prime, _{kind:number_theory_prime_case_edge, legacy_predicate:is_prime/1, module:sequent_engine, number_theory_witness:C, prime_fact:B, sample_list:[2, 3, 5], sample_prime:A, source_file:'formal/formalization/axioms_number_theory.pl'}):-catch(sequent_engine:number_theory_self_defeat_witness([2, 3, 5], C), _, fail), get_dict(prime_case, C, D), get_dict(prime, D, A), get_dict(prime_fact, D, B))).
cw_rule((multiplication_division_edge_source_witness(find_prime_factor, _{divides:C, kind:number_theory_factor_edge, legacy_predicate:find_prime_factor/2, module:sequent_engine, number_theory_witness:A, prime_factor:B, sample_integer:111, sample_list:[2, 5, 11], source_file:'formal/formalization/axioms_number_theory.pl'}):-catch(sequent_engine:number_theory_factor_witness(111, [2, 5, 11], A), _, fail), get_dict(prime_factor, A, B), get_dict(divides, A, C))).
