/** <module> cw_misconception_hook -- crosswalk family data. */
:-module(cw_misconception_hook,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(strategies('math/action_automata_registry'),[]).
:-use_module(strategies('math/fraction_action_pairs'),[]).
:-use_module(misconceptions(misconception_registry),[]).
cw_family(cw_misconception_hook).
edge(action_automata_registry,action_automaton_hook/4,[addition,count_all],[3,4],registry_projection).
edge(sar_sub_action_pairs,subtractive_action_misconception_hook/3,[action_outcome(take_away_base_ones,[classification(productive),vocabulary([minuend,subtrahend,base_chunk,ones_chunk,running_difference])])],[2,3],call_bind_out).
edge(smr_mult_action_pairs,multiplicative_action_misconception_hook/3,[action_outcome(coordinate_groups_items,[classification(productive),vocabulary([group_count,item_count,composite_unit,total_items])])],[2,3],call_bind_out).
edge(smr_div_action_pairs,division_action_misconception_hook/3,[action_outcome(measure_groups_of_size,[classification(productive),vocabulary([total,group_size,measured_group,quotient,remainder])])],[2,3],call_bind_out).
edge(fraction_action_pairs,fraction_action_misconception_hook/3,[action_outcome(unit_fraction_iteration,[classification(productive),vocabulary([referent_whole,unit_fraction,iteration_count,denominator,completion_marker,beyond_whole])])],[2,3],call_bind_out).
edge(decimal_action_pairs,decimal_action_misconception_hook/3,[action_outcome(positional_decimal_reading,[classification(productive),vocabulary([decimal_mark,whole_part,fractional_part,place_value,tenths,hundredths,scale_unit])])],[2,3],call_bind_out).
edge(integer_action_pairs,integer_action_misconception_hook/3,[action_outcome(signed_addition_with_sign_relation,[classification(productive),vocabulary([signed_addend,sign,magnitude,sign_relation,same_sign_combination,opposite_sign_cancellation,signed_sum])])],[2,3],call_bind_out).
edge(ratio_action_pairs,ratio_action_misconception_hook/3,[action_outcome(scale_ratio_unit,[classification(productive),vocabulary([ratio_pair,unit_ratio,scale_factor,multiplicative_scaling,equivalent_ratio,first_term,second_term])])],[2,3],call_bind_out).
edge(diagnostic_validation_action_pairs,diagnostic_action_misconception_hook/3,[action_outcome(multiplicative_bound_invalidation,[classification(productive),subfamily(validation),vocabulary([proposed_quotient,dividend,divisor,inverse_multiplication,multiplicative_bound,upper_bound_check,invalidate_quotient,consistency_check]),verdict(valid)])],[2,3],call_bind_out).
edge(calculus_limits_action_pairs,calculus_action_misconception_hook/3,[action_outcome(factor_cancel_substitute,[classification(productive),vocabulary([removable_discontinuity,common_factor,cancel,reduced_expression,substitution,function_value])])],[2,3],call_bind_out).
edge(algebraic_action_pairs,algebraic_action_misconception_hook/3,[action_outcome(linear_pattern_contextual_rule,[classification(productive),vocabulary([linear_pattern,first_value,row_number,constant_rate_of_change,accumulated_change,explicit_rule,contextual_generalization,initial_value,far_term_prediction])])],[2,3],call_bind_out).
edge(probability_action_pairs,probability_action_misconception_hook/3,[action_outcome(terminal_tree_endpoint_probability_sum,[classification(productive),vocabulary([tree_diagram,terminal_branch,terminal_endpoint,stopping_condition,branch_probability,disjoint_outcomes,probability_sum,stake_split,non_equiprobable_terminal_paths])])],[2,3],call_bind_out).
cw_rule((misconception_hook_unified(A,B,C,D,action_registry):-misconception_hook_witness(A,B,C,D,action_registry,_2388))).
cw_rule((misconception_hook_unified(fraction,A,B,C,fraction_action):-misconception_hook_witness(fraction,A,B,C,fraction_action,_2508))).
cw_rule((misconception_hook_unified(A,misconception(B),C,D,literature_registry):-misconception_hook_witness(A,misconception(B),C,D,literature_registry,_2624))).
cw_rule((misconception_hook_witness(A,B,C,D,E,F):-witness_dict:witness_dict(misconception_hook_crosswalk,closed_world_finite_loaded_misconception_hook_sources,_2736{derivation:I,family:C,hook:D,legacy_functor:H,operation:A,outcome:B,projection:K,source:E,source_witness:J},F),source_misconception_hook_witness(E,A,B,C,D,H,K,I,J))).
cw_rule((source_misconception_hook_witness(action_registry,A,B,C,D,'action_automata_registry:action_automaton_hook/4',action_outcome_hook_extraction,registry_operation_dispatch,_2984{dispatched_legacy_functor:F,family:C,hook_fields:H,kind:action_automata_hook_dispatch,operation:A,outcome_kind:G,registry_predicate:'action_automata_registry:action_automaton_hook/4'}):-catch(action_automata_registry:action_automaton_hook(A,B,C,D),_,fail),action_hook_dispatch(A,F),outcome_kind(B,G),hook_fields(D,H))).
cw_rule((source_misconception_hook_witness(fraction_action,fraction,A,B,C,'fraction_action_pairs:fraction_action_misconception_hook/3',action_outcome_hook_extraction,direct_fraction_hook_extraction,_3256{family:B,hook_fields:F,kind:direct_fraction_hook_extraction,module:fraction_action_pairs,outcome_kind:E,predicate:fraction_action_misconception_hook/3}):-catch(fraction_action_pairs:fraction_action_misconception_hook(A,B,C),_,fail),outcome_kind(A,E),hook_fields(C,F))).
cw_rule((source_misconception_hook_witness(literature_registry,A,misconception(B),A,registry_hook(C,D,E),'misconception_registry:misconception_registry_entry/5',registry_entry_projected_to_hook,bounded_literature_registry_projection,_3498{citation:E,commitment:C,entitlement:D,kind:literature_registry_misconception_hook,module:misconception_registry,name:B,operation:A,predicate:misconception_registry_entry/5}):-catch(once(misconception_registry:misconception_registry_entry(B,A,E,C,D)),_,fail))).
cw_rule(outcome_kind(action_outcome(A,_3716),A)).
cw_rule((outcome_kind(A,unknown):-nonvar(A),A\=action_outcome(_3788,_))).
cw_rule((hook_fields(action_misconception_hook(A),A):-!)).
cw_rule(hook_fields(A,A)).
cw_rule(action_hook_dispatch(addition,'sar_add_action_pairs:action_misconception_hook/3')).
cw_rule(action_hook_dispatch(subtraction,'sar_sub_action_pairs:subtractive_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(multiplication,'smr_mult_action_pairs:multiplicative_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(division,'smr_div_action_pairs:division_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(fraction,'fraction_action_pairs:fraction_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(decimal,'decimal_action_pairs:decimal_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(integer,'integer_action_pairs:integer_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(ratio,'ratio_action_pairs:ratio_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(diagnostic,'diagnostic_validation_action_pairs:diagnostic_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(calculus,'calculus_limits_action_pairs:calculus_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(algebraic,'algebraic_action_pairs:algebraic_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(probability,'probability_action_pairs:probability_action_misconception_hook/3')).
cw_rule(canonical_concept('action_automata_registry:action_automaton_hook/4',misconception_hook)).
cw_rule(canonical_concept('fraction_action_pairs:fraction_action_misconception_hook/3',misconception_hook)).
cw_rule(canonical_concept('misconception_registry:misconception_registry_entry/5',misconception_hook)).
cw_rule(vocabulary_source(misconception_hook,['action_automata_registry:action_automaton_hook/4','fraction_action_pairs:fraction_action_misconception_hook/3','misconception_registry:misconception_registry_entry/5'])).
