/** <module> cw_modal_context -- crosswalk family data. */
:-module(cw_modal_context,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(learner(meta_interpreter),[]).
:-use_module(sequent(embodied_prover),[]).
cw_family(cw_modal_context).
edge(meta_interpreter,is_modal_operator/2,[necessarily],[2],call_bind_out).
cw_rule((modal_context_unified(A,B,meta_interpreter):-modal_context_witness(A,B,meta_interpreter,_5308))).
cw_rule((modal_context_unified(A,B,embodied_prover):-modal_context_witness(A,B,embodied_prover,_5396))).
cw_rule((modal_context_unified(A,B,pml_modality):-modal_context_witness(A,B,pml_modality,_5484))).
cw_rule((modal_context_witness(A,B,C,D):-witness_dict:witness_dict(modal_context,closed_world_finite_loaded_modal_sources,_5568{context:B,derivation:G,legacy_functor:F,polarity:H,shape:I,source:C,term:A},D),modal_context_source(C,F),source_modal_context_witness(C,A,B,H,I,G))).
cw_rule(modal_context_source(meta_interpreter,'meta_interpreter:is_modal_operator/2')).
cw_rule(modal_context_source(embodied_prover,'embodied_prover:determine_modal_context/2')).
cw_rule(modal_context_source(pml_modality,'embodied_prover:is_pml_modality/1')).
cw_rule((source_modal_context_witness(meta_interpreter,A,B,C,bare_polarized_operator,fact_table_lookup):-catch(meta_interpreter:is_modal_operator(A,B),_5956,fail),modal_operator_polarity(A,C))).
cw_rule((source_modal_context_witness(embodied_prover,A,B,C,bare_polarized_operator,functor_dispatch):-catch(embodied_prover:determine_modal_context(A,B),_6084,fail),modal_operator_polarity(A,C))).
cw_rule((source_modal_context_witness(pml_modality,A,B,C,mode_wrapped_pml_operator,mode_wrapper_recognizer_plus_inner_polarity):-catch((embodied_prover:is_pml_modality(A),A=..[_6210,E],functor(E,F,_),operator_context(F,B)),_,fail),modal_operator_polarity(E,C))).
cw_rule((modal_operator_polarity(A,B):-nonvar(A),functor(A,C,_6448),operator_polarity(C,B))).
cw_rule(operator_polarity(comp_nec,compressive_necessity)).
cw_rule(operator_polarity(comp_poss,compressive_possibility)).
cw_rule(operator_polarity(exp_nec,expansive_necessity)).
cw_rule(operator_polarity(exp_poss,expansive_possibility)).
cw_rule(polarity_context(compressive_necessity,compressive)).
cw_rule(polarity_context(compressive_possibility,compressive)).
cw_rule(polarity_context(expansive_necessity,expansive)).
cw_rule(polarity_context(expansive_possibility,expansive)).
cw_rule((operator_context(A,B):-operator_polarity(A,C),polarity_context(C,B))).
cw_rule(canonical_concept('meta_interpreter:is_modal_operator/2',modal_context_unified)).
cw_rule(canonical_concept('embodied_prover:determine_modal_context/2',modal_context_unified)).
cw_rule(canonical_concept('embodied_prover:is_pml_modality/1',modal_context_unified)).
cw_rule(vocabulary_source(modal_context_unified,['meta_interpreter:is_modal_operator/2','embodied_prover:determine_modal_context/2','embodied_prover:is_pml_modality/1'])).
