/** <module> cw_normative_crisis -- crosswalk family data. */
:-module(cw_normative_crisis,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(sequent(sequent_engine),[]).
:-use_module(learner(reorganization_engine),[]).
cw_family(cw_normative_crisis).
edge(sequent_engine,prohibition/2,[natural_numbers,subtract(1,2,-1)],[],call_once_bind_out).
cw_rule((normative_crisis_unified(A,B,prohibition):-normative_crisis_witness(A,B,prohibition,_9514))).
cw_rule((normative_crisis_witness(A,B,C,D):-witness_dict:witness_dict(normative_crisis,closed_world_finite_live_domain_configuration,_9598{context:A,derivation:G,goal:B,goal_family:I,legacy_functor:F,source:C,support:H},D),normative_crisis_source(C,F),source_normative_crisis_witness(C,A,B,I,G,H))).
cw_rule(normative_crisis_source(prohibition,'sequent_engine:prohibition/2')).
cw_rule((source_normative_crisis_witness(prohibition,A,B,C,non_mutating_prohibition_query,_9866{current_context:G,current_domain:E,domains_pack_enabled:F}):-catch(once(sequent_engine:prohibition(A,B)),_,fail),domains_pack_enabled(F),catch(sequent_engine:current_domain(E),_,E=unknown),catch(sequent_engine:current_domain_context(G),_,G=unknown),goal_family(B,C))).
cw_rule((domains_pack_enabled(true):-catch(sequent_engine:enabled_axiom_pack(domains),_10208,fail),!)).
cw_rule(domains_pack_enabled(false)).
cw_rule((goal_family(subtract(A,B,_10314),subtract_larger_from_smaller_in_naturals):-number(A),number(B),B>A,!)).
cw_rule((goal_family(subtract(_10426,_,_),subtraction_not_closed_in_current_domain):-!)).
cw_rule((goal_family(divide(_10534,_,_),division_not_closed_in_current_domain):-!)).
cw_rule((goal_family(A,other_core_operation):-nonvar(A))).
cw_rule(normative_crisis_variant(prohibition/2,'sequent_engine:prohibition/2':queryable_fact)).
cw_rule(normative_crisis_variant(normative_crisis/2,'sequent_engine:normative_crisis/2':exception_term)).
cw_rule(normative_crisis_variant(check_norms/1,'sequent_engine:check_norms/1':executor)).
cw_rule(normative_crisis_variant(handle_normative_crisis/2,'reorganization_engine:handle_normative_crisis/2':executor)).
cw_rule(canonical_concept('sequent_engine:prohibition/2',normative_crisis)).
cw_rule(canonical_concept('sequent_engine:normative_crisis/2',normative_crisis)).
cw_rule(canonical_concept('sequent_engine:check_norms/1',normative_crisis)).
cw_rule(canonical_concept('reorganization_engine:handle_normative_crisis/2',normative_crisis)).
cw_rule(vocabulary_source(normative_crisis,['sequent_engine:prohibition/2','sequent_engine:normative_crisis/2','sequent_engine:check_norms/1','reorganization_engine:handle_normative_crisis/2'])).
