/** <module> cw_orr_entry -- crosswalk family data. */
:-module(cw_orr_entry,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(learner(execution_handler),[]).
:-use_module(dialectic(dialectical_engine),[]).
cw_family(cw_orr_entry).
edge(execution_handler,run_computation/2,[add(1,1)],[2],call_once_bind_out).
cw_rule((orr_entry_unified(A,B,C,D):-orr_entry_witness(A,B,C,D,_11746))).
cw_rule((orr_entry_witness(A,B,C,D,E):-witness_dict:witness_dict(orr_entry_registry_entry,closed_world_finite_loaded_orr_entry_registry,_11856{invocation_policy:registry_only_no_orr_execution,legacy_functor:G,predicate:B,role:C,side_effect_boundary:H,source:D,target_visibility:J,target_witness:I,variant:A},E),registry(A,B,C,D,G,H,J),target_presence_witness(B,J,I))).
cw_rule(registry(eh_run_computation,execution_handler:run_computation/2,entry,learner_execution_handler,'execution_handler:run_computation/2',bounded_meta_interpreter_event_log_teacher_recovery,exported_predicate)).
cw_rule(registry(eh_handle_perturbation,execution_handler:handle_perturbation/5,perturbation_handler,learner_execution_handler,'execution_handler:handle_perturbation/5',crisis_classification_recovery_state_and_teacher_path,module_internal_clause)).
cw_rule(registry(de_run_computation,dialectical_engine:run_computation/2,entry,dialectic_engine,'dialectical_engine:run_computation/2',bounded_embodied_prover_critique_retry_loop,exported_predicate)).
cw_rule(registry(de_handle_perturbation,dialectical_engine:handle_perturbation/3,perturbation_handler,dialectic_engine,'dialectical_engine:handle_perturbation/3',critique_accommodation_retry_loop,module_internal_clause)).
cw_rule((target_presence_witness(A:B/C,D,_12386{arity:C,kind:loaded_orr_entry_target,module:A,name:B,properties:F,visibility:D}):-once(target_present(A,B,C,D)),findall(G,target_property(A,B,C,G),H),sort(H,F))).
cw_rule((target_present(A,B,C,exported_predicate):-catch(current_predicate(A:B/C),_12630,fail),functor(E,B,C),catch(predicate_property(A:E,exported),_,fail))).
cw_rule((target_present(A,B,C,module_internal_clause):-functor(D,B,C),catch(clause(A:D,_12820),_,fail))).
cw_rule((target_property(A,B,C,defined):-functor(D,B,C),predicate_property(A:D,defined))).
cw_rule((target_property(A,B,C,exported):-functor(D,B,C),predicate_property(A:D,exported))).
cw_rule(canonical_concept('execution_handler:run_computation/2',orr_entry)).
cw_rule(canonical_concept('execution_handler:handle_perturbation/5',orr_entry)).
cw_rule(canonical_concept('dialectical_engine:run_computation/2',orr_entry)).
cw_rule(canonical_concept('dialectical_engine:handle_perturbation/3',orr_entry)).
cw_rule(vocabulary_source(orr_entry,['execution_handler:run_computation/2','execution_handler:handle_perturbation/5','dialectical_engine:run_computation/2','dialectical_engine:handle_perturbation/3'])).
