/** <module> cw_ratio_proportion_claim -- mechanical crosswalk family data. */
:- module(cw_ratio_proportion_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_ratio_proportion_claim).
cw_rule(rp(multiplicative_proportional_scaling, c_proportionality_requires_zero_intercept, "Proportional relationships scale by multiplication; extending a ratio is valid only when no additive constant is injected (the zero-intercept condition).", ['action_automata_registry:action_automaton_pair/4(ratio,scale_ratio_unit,additive_extension_of_ratio)', 'misconception_registry:incompatibility_with/2(additive_extension_of_ratio)'])).
cw_rule((claim_literature_atom(A, B):-rp(A, B, _, _))).
cw_rule((legacy_list(A, B):-rp(A, C, _, D), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', C, ')'], E), append([[E], D], B))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((ratio_proportion_claim_unified(A, B, C):-ratio_proportion_claim_witness(A, B, C, _))).
cw_rule((ratio_proportion_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(ratio_proportion_claim_crosswalk, closed_world_finite_verified_ratio_proportion_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), rp(A, B, _, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((ratio_proportion_claim_witness(A, edge(B), B, C):-witness_dict:witness_dict(ratio_proportion_claim_crosswalk, closed_world_finite_verified_ratio_proportion_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge(B), legacy_functor:B, projection:verified_legacy_edge, source:B, source_witness:D}, C), rp(A, _, _, E), member(B, E), ratio_proportion_edge_source_witness(A, B, D))).
cw_rule((ratio_proportion_edge_source_witness(multiplicative_proportional_scaling, 'action_automata_registry:action_automaton_pair/4(ratio,scale_ratio_unit,additive_extension_of_ratio)', _{deformation_kind:additive_extension_of_ratio, deformation_vocabulary:B, family:additive_comparison_in_proportion, kind:action_automaton_pair_edge, module:action_automata_registry, operation:ratio, predicate:action_automaton_pair/4, productive_kind:scale_ratio_unit, productive_vocabulary:A}):-catch(action_automata_registry:action_automaton_pair(ratio, scale_ratio_unit, additive_extension_of_ratio, additive_comparison_in_proportion), _, fail), catch(action_automata_registry:action_automaton_vocabulary(ratio, scale_ratio_unit, A), _, fail), catch(action_automata_registry:action_automaton_vocabulary(ratio, additive_extension_of_ratio, B), _, fail))).
cw_rule((ratio_proportion_edge_source_witness(multiplicative_proportional_scaling, 'misconception_registry:incompatibility_with/2(additive_extension_of_ratio)', _{conflict:strategy(ratio, scale_ratio_unit), incompatibility_witness:A, kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:additive_extension_of_ratio, predicate:incompatibility_with/2}):-catch(once(misconception_registry:incompatibility_with_witness(additive_extension_of_ratio, strategy(ratio, scale_ratio_unit), A)), _, fail))).
