/** <module> Mechanisms of Critique (Analysis of Pathology and Sublation)
 *
 *  This module implements the mechanisms for identifying and critiquing
 *  pathologies (Fixation, Alienation, Bad Infinite) and the process of
 *  Sublation (Letting Go, Accommodation).
 *
 *  This is the formal dialectic detection-and-accommodation machinery, built for
 *  the dialectical/sublation context. It runs parallel to the learner's ORR-cycle
 *  modules (formal/learner/reflective_monitor.pl for detection, formal/learner/reorganization_engine.pl
 *  for accommodation), which remain live in the crisis-cycle subsystem — this module
 *  does NOT replace them. The two implementations share predicate names
 *  (reflect/2, accommodate/1, get_stress_map/1, the stress map) because they model the
 *  same activity in two distinct registers; they are reconciled, not merged, by
 *  crosswalk/families/cw_stress_map.pl, cw_accommodation.pl, and cw_normative_crisis.pl,
 *  each of which use_modules both sides.
 *
 *  (Synthesis_1, Chapter 4.5)
 */
:- module(critique,
          [
            reflect/2,
            reflect_witness/3,
            detect_pathology_witness/3,
            bad_infinite_witness/2,
            accommodate/1,
            accommodation_record/2,
            accommodation_incoherence_witness/2,
            retract_accommodation/1,
            reset_accommodations/0,
            with_accommodation/2,
            get_stress_map/1,
            reset_stress_map/0
          ]).

% Import operators - must be declared before use
:- op(1050, xfy, =>).
:- op(500, fx, comp_nec).
:- op(500, fx, exp_nec).
:- op(500, fx, exp_poss).
:- op(500, fx, comp_poss).
:- op(500, fx, neg).

:- use_module(sequent(sequent_engine), [incoherent_witness/2]).
:- use_module(pml(pml_operators)).
% Used for identifying the structure of the Bad Infinite.
:- use_module(pml(utils), [select/3]).

:- dynamic stress/2.
:- dynamic accommodation_record/2.
:- meta_predicate with_accommodation(+, 0).

% =================================================================
% Part 1: Reflection (Detection of Disequilibrium and Pathology)
% =================================================================

%!      reflect(+Proof, -DisequilibriumTrigger) is semidet.
%
%       Analyzes a proof structure to detect disequilibrium or pathology.
%       Succeeds if a trigger is found.
%
%       @param Proof The proof structure generated by the prover.
%       @param DisequilibriumTrigger A term describing the issue.
reflect(Proof, Trigger) :-
    reflect_witness(Proof, Trigger, _).

%!      reflect_witness(+Proof, -DisequilibriumTrigger, -Witness) is semidet.
%
%       Reflection with an inspectable reason. A trigger should not be a bare
%       label: the witness records the path that made the label true.
reflect_witness(Proof, Trigger, Witness) :-
    % 1. Analyze the proof structure for pathologies (e.g., Bad Infinite).
    ( detect_pathology_witness(Proof, Trigger, Witness) -> true
    ;
    % 2. Extract commitments and check for incoherence.
      extract_commitments(Proof, Commitments),
      incoherent_witness(Commitments, IncoherenceWitness),
      Trigger = incoherence(Commitments),
      Witness = _{ kind: incoherence_reflection,
                   commitments: Commitments,
                   incoherence_witness: IncoherenceWitness }
    ).

% --- Pathology Detection ---

%!  detect_pathology_witness(+Proof, -Pathology, -Witness) is semidet.
%
%   Detects a known pathology and returns the evidence that made the diagnosis
%   legitimate.
detect_pathology_witness(Proof, pathology(bad_infinite, Cycle), Witness) :-
    bad_infinite_witness(Proof, Witness),
    Cycle = Witness.cycle.

%!  bad_infinite_witness(+Proof, -Witness) is semidet.
%
%   A bad infinite is not merely any repeated proof node. It is a closed cycle
%   whose proof steps are all compressive-necessity PML rhythm transitions.
bad_infinite_witness(Proof,
                        _{ kind: bad_infinite,
                        cycle_kind: closed_compressive_necessity_cycle,
                        repeated_node: RepeatedNode,
                        cycle: Cycle,
                        closed_cycle: ClosedCycle,
                        compressive_steps: StepWitnesses,
                        reason: repeated_state_mediated_only_by_compressive_necessity }) :-
    find_proof_cycle_witness(Proof, CycleWitness),
    Cycle = CycleWitness.cycle,
    RepeatedNode = CycleWitness.repeated_node,
    Cycle \= [],
    append(Cycle, [RepeatedNode], ClosedCycle),
    maplist(compressive_necessity_node_witness, Cycle, StepWitnesses).

%!  find_proof_cycle_witness(+Proof, -Witness) is nondet.
%
%   Detects cycles in a proof tree by tracking ancestor nodes. The witness keeps
%   the repeated node visible instead of returning an opaque cycle list.
find_proof_cycle_witness(Proof,
                         _{ kind: proof_cycle,
                            repeated_node: RepeatedNode,
                            cycle: Cycle }) :-
    find_cycle_impl_witness(Proof, [], RepeatedNode, Cycle).

find_cycle_impl_witness(proof(RuleName, Sequent, SubProofs), Visited, RepeatedNode, Cycle) :-
    Node = node(RuleName, Sequent),
    ( member(Node, Visited) ->
        RepeatedNode = Node,
        extract_cycle(Node, Visited, Cycle)
    ;
        member(SubProof, SubProofs),
        find_cycle_impl_witness(SubProof, [Node|Visited], RepeatedNode, Cycle)
    ).
find_cycle_impl_witness(hollow(_), _, _, _) :- fail.

%!  extract_cycle(+StartNode, +Path, -Cycle) is det.
%
%   Extracts the cycle portion from the path.
extract_cycle(Node, Path, Cycle) :-
    extract_cycle_impl(Node, Path, [], Cycle).

extract_cycle_impl(Node, [Node|_], Acc, Cycle) :-
    Cycle = [Node|Acc].
extract_cycle_impl(TargetNode, [Node|Rest], Acc, Cycle) :-
    Node \= TargetNode,
    extract_cycle_impl(TargetNode, Rest, [Node|Acc], Cycle).

compressive_necessity_node_witness(node(RuleName, Sequent),
                                   _{ kind: compressive_necessity_step,
                                      modality: comp_nec,
                                      from: From,
                                      to: To,
                                      node: node(RuleName, Sequent),
                                      rule: RuleName,
                                      sequent: Sequent,
                                      rule_witness: RuleWitness,
                                      sequent_witness: SequentWitness }) :-
    pml_rhythm_rule_comp_nec_witness(RuleName, From, To, RuleWitness),
    sequent_comp_nec_witness(Sequent, From, To, SequentWitness).

pml_rhythm_rule_comp_nec_witness(pml_rhythm(s(From) => s(comp_nec(To))),
                                 From,
                                 To,
                                 _{ kind: pml_rhythm_rule,
                                    source: rule_name,
                                    premise: s(From),
                                    conclusion: s(comp_nec(To)) }).

sequent_comp_nec_witness((Premises => Conclusions),
                         From,
                         To,
                         _{ kind: sequent_transition,
                            source: sequent_shape,
                            premise: s(From),
                            conclusion: s(comp_nec(To)),
                            premises: Premises,
                            conclusions: Conclusions }) :-
    member(s(From), Premises),
    member(s(comp_nec(To)), Conclusions).


% --- Commitment Extraction ---

% Extracts the set of axioms (material inferences) used in the proof.
extract_commitments(Proof, Commitments) :-
    extract_commitments_recursive(Proof, C_Nested),
    flatten(C_Nested, C_Flat),
    list_to_set(C_Flat, Commitments).

extract_commitments_recursive(hollow(_), []). % Hollow proofs have no commitments.
extract_commitments_recursive(proof(RuleName, _Sequent, SubProofs), Commitments) :-
    % If the rule is a Modus Ponens (MMP), the axiom used is the commitment.
    ( RuleName = mmp(Axiom) -> Commitment = [Axiom] ; Commitment = [] ),
    maplist(extract_commitments_recursive, SubProofs, SubCommitments),
    append(Commitment, SubCommitments, Commitments).


% =================================================================
% Part 2: Accommodation (Sublation and Reorganization)
% =================================================================

%!      accommodate(+Trigger:term) is semidet.
%
%       Attempts to accommodate a state of disequilibrium by modifying the
%       system's state or knowledge base. This is the process of Sublation (Aufhebung).
%
%       For incoherence triggers, the resulting block is recorded in
%       accommodation_record/2; remove it with retract_accommodation/1,
%       or use with_accommodation/2 for a transactional scope. See
%       Part 2b below for the lifecycle.
%
%       @param Trigger The term describing the disequilibrium.
accommodate(perturbation(resource_exhaustion)) :-
    !,
    accommodate(perturbation(resource_exhaustion, unknown_sequent)).

accommodate(perturbation(resource_exhaustion, Sequent)) :-
    !,
    format('Handling Resource Exhaustion for: ~w~n', [Sequent]),
    % Strategy 1: Record the failure for learning
    term_string(Sequent, SeqStr),
    increment_stress(SeqStr),
    format('  Incremented stress for: ~w~n', [SeqStr]),
    % Strategy 2: Try to introduce a lemma (caching the result)
    % For now, we just acknowledge and fail to trigger external handling
    writeln('  Resource exhaustion recorded. External intervention required.'),
    fail.

accommodate(incoherence(Commitments)) :-
    !,
    format('Handling Incoherence in Commitments: ~w~n', [Commitments]),
    % Strategy: Belief Revision. Identify and retract the "weakest" commitment.
    % Weakness can be determined by the conceptual stress map.
    handle_incoherence(Commitments).

accommodate(pathology(bad_infinite, Cycle)) :-
    !,
    format('Handling Bad Infinite (Pathological Cycle): ~w~n', [Cycle]),
    % Strategy: Sublation (Aufhebung) - Introduce a higher-level concept
    % that subsumes the oscillation (e.g., Hegel's "Becoming" subsumes Being/Nothing)

    % Extract the oscillating elements from the cycle
    findall(Sequent, member(node(_, Sequent), Cycle), Sequents),
    format('  Detected oscillation between: ~w~n', [Sequents]),

    % For now: Record the pathology and suggest the need for conceptual elevation
    writeln('  SUBLATION REQUIRED: Introduce higher-level concept to resolve oscillation'),
    writeln('  Example: Being <-> Nothing requires "Becoming"'),
    writeln('  System cannot auto-generate new concepts yet.'),

    % Record each transition as problematic
    forall(member(node(RuleName, Seq), Cycle),
           (term_string(Seq, SeqStr),
            increment_stress(SeqStr),
            format('    Marked as stressed: ~w via ~w~n', [SeqStr, RuleName]))),

    % Fail to signal external intervention needed
    writeln('  External conceptual intervention required.'),
    fail.

accommodate(Trigger) :-
    format('Unknown trigger type: ~w. Cannot accommodate.~n', [Trigger]),
    fail.

% --- Incoherence Handling (Belief Revision) ---

handle_incoherence(Commitments) :-
    % 1. Identify the most stressed commitment.
    identify_stressed_commitment(Commitments, StressedCommitment),
    % 2. Retract/Modify the problematic commitment.
    format('Retracting/Modifying stressed commitment: ~w~n', [StressedCommitment]),
    retract_commitment(StressedCommitment).

identify_stressed_commitment(Commitments, StressedCommitment) :-
    % Score each commitment by its stress level
    findall(score(Stress, Commitment),
            (member(Commitment, Commitments),
             commitment_stress(Commitment, Stress)),
            Scores),
    % Sort by stress (highest first)
    ( Scores \= [] ->
        sort(1, @>=, Scores, [score(_, StressedCommitment)|_])
    ;
        % Fallback: pick first commitment if no stress data
        Commitments = [StressedCommitment|_]
    ).

%!  commitment_stress(+Commitment, -Stress) is det.
%
%   Calculate stress for a commitment based on failure history.
commitment_stress((Antecedents => Consequent), Stress) :-
    % Create a signature for this commitment
    term_string(Antecedents, AntStr),
    term_string(Consequent, ConsStr),
    atomic_list_concat([AntStr, ' => ', ConsStr], Signature),
    % Look up stress
    ( stress(Signature, Stress) -> true ; Stress = 0 ).

retract_commitment(Commitment) :-
    format('Blocking problematic commitment: ~w~n', [Commitment]),
    Commitment = (Antecedents => _Consequent),
    record_accommodation(Commitment, Antecedents),
    format('  Recorded accommodation: blocked antecedents ~w~n', [Antecedents]).

% =================================================================
% Part 2b: Accommodation Lifecycle (record, retract, scope)
% =================================================================
% An accommodation persisting for the session is a legitimate default:
% a blocked commitment stays blocked until someone decides otherwise.
% The defect this lifecycle repairs is that no cleanup path existed —
% not that persistence is wrong. (The earlier code also asserted into
% sequent_engine:is_incoherent/1, a static predicate, so the block
% raised a permission error instead of taking effect at all.)
%
% Every block now lives in this module's own dynamic table,
% accommodation_record/2, where it is queryable and retractable.

%!  record_accommodation(+Commitment, +Antecedents) is det.
%
%   Records that Commitment was blocked by accommodation: any context
%   equal to Antecedents now counts as incoherent (via the hook below).
%   Idempotent — re-accommodating the same commitment does not stack
%   duplicate records.
record_accommodation(Commitment, Antecedents) :-
    (   accommodation_record(Commitment, blocked_antecedents(Antecedents))
    ->  true
    ;   assertz(accommodation_record(Commitment, blocked_antecedents(Antecedents)))
    ).

%!  retract_accommodation(+Commitment) is semidet.
%
%   Removes the block recorded for Commitment. Fails when no
%   accommodation is on record, so a caller can tell a real removal
%   from a no-op.
retract_accommodation(Commitment) :-
    retract(accommodation_record(Commitment, blocked_antecedents(_))).

%!  reset_accommodations is det.
%
%   Clears every accommodation record (mirror of reset_stress_map/0).
reset_accommodations :-
    retractall(accommodation_record(_, _)).

%!  with_accommodation(+Trigger, :Goal) is semidet.
%
%   Transactional variant for callers that do not want the session-long
%   default: accommodate Trigger, run Goal, and retract whatever
%   accommodation records the accommodation added — whether Goal
%   succeeds, fails, or throws (setup_call_cleanup/3). Records that
%   existed before the call are left alone.
with_accommodation(Trigger, Goal) :-
    findall(C-A, accommodation_record(C, A), Before),
    setup_call_cleanup(
        accommodate(Trigger),
        Goal,
        retract_accommodations_not_in(Before)).

retract_accommodations_not_in(Before) :-
    forall(( accommodation_record(C, A),
             \+ memberchk(C-A, Before)
           ),
           retract(accommodation_record(C, A))).

% --- Engine-visible face of an accommodation ---
%
% sequent_engine declares axiom_incoherence_witness/2 multifile; this
% clause is contributed once at load time (no runtime mutation of
% sequent_engine) and delegates to the dynamic table above. A context
% whose antecedents were blocked by accommodation is thereby queryable
% as incoherent through sequent_engine's incoherent/1 and
% incoherent_witness/2, with a witness naming the blocked commitment.
%
% Boundary, named precisely: the prover's explosion clause consults the
% static is_incoherent/1, which this module does not mutate. A blocked
% context is therefore visible as incoherence but does not become a
% source of explosion proofs.
:- multifile sequent_engine:axiom_incoherence_witness/2.

sequent_engine:axiom_incoherence_witness(Context, Witness) :-
    accommodation_incoherence_witness(Context, Witness).

%!  accommodation_incoherence_witness(?Context, -Witness) is nondet.
%
%   Witness that Context is incoherent because an accommodation blocked
%   a commitment with exactly these antecedents.
accommodation_incoherence_witness(Context,
                                  _{ kind: accommodation_block,
                                     source: critique_accommodation,
                                     blocked_commitment: Commitment,
                                     blocked_antecedents: Context,
                                     context: Context }) :-
    accommodation_record(Commitment, blocked_antecedents(Context)).

% =================================================================
% Part 3: Conceptual Stress Map (Failure Tracking)
% =================================================================
% (Salvaged from reflective_monitor.pl)

increment_stress(Signature) :-
    (   retract(stress(Signature, Count))
    ->  NewCount is Count + 1
    ;   NewCount = 1
    ),
    assertz(stress(Signature, NewCount)).

get_stress_map(Map) :-
    findall(stress(Signature, Count), stress(Signature, Count), Map).

reset_stress_map :-
    retractall(stress(_, _)).
