% formal/tools/carving/rationalizations.pl
%
% Proof rules for INCORRECT arithmetic facts. Each rule corresponds to a
% coherent-but-flawed procedure. These are misconceptions made explicit
% as clause bodies: the head is a wrong answer, the body is the procedure
% that produces it.
%
% The deontic-scorekeeper read: a fact with a rationalization clause is
% committed-to but the entitlement is materially defective. The
% scorekeeper can mark it as commitment_without_entitlement(reason) where
% reason names the misconception pattern.
%
% Activated only when Config.rationalize == true.

:- module(carving_rationalizations, []).
:- use_module(synthesizer).

:- multifile(carving_synthesizer:prove/3).
:- discontiguous(carving_synthesizer:prove/3).

% ----- Off-by-one in count-on (small smaller-addend case) -----
% Pattern: kid started counting AT the larger addend instead of just after.
% So 8 + 5 is counted "8, 9, 10, 11, 12" (saying five numbers, ending at 12)
% rather than "8 -> 9, 10, 11, 12, 13" (five successors after 8, ending at 13).
%
% Adjacent literature (not claiming identification): there are well-documented
% off-by-one and double-count phenomena in the math-ed corpus. We are not
% asserting this rule captures any of those constructs; the rule is our own
% formalization of the Z = X+Y-1 pattern, and the cognitive frame is open.
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(off_by_one_col),
                                [comment('Counted AT the larger addend instead of after it'),
                                 start(L),
                                 successor_n_off_by_one(M, Z)])) :-
    Config.rationalize == true,
    Z =:= X + Y - 1,
    Z >= 0,
    M is min(X, Y),
    L is max(X, Y),
    M >= 1,
    M =< Config.tolerance.

% ----- Zero-as-position (polysemy of numerals) -----
% Pattern: 0 is treated as a position-name to start counting FROM rather
% than as a cardinal "no count" identity element. So "0 + 5" is read as
% "starting at position 0, count to 5" but the count "0, 1, 2, 3, 4" ends
% at 4 — naming five positions but landing on N-1.
% This is the polysemous-numeral reading of the same Z = X + Y - 1 pattern,
% but specifically for cases where one addend is zero. Distinguished from
% the off-by-one rule because the cognitive content is different: this is
% about WHAT 0 IS (a name vs. an empty count), not about counting technique.
%
% Adjacent (not anchoring) literature exists on zero-polysemy and operational
% opacity. We are not claiming identification with any specific construct
% from that literature.
%
% Note: the "two zeros = 2 then backtrack by 2" reading is a related but
% distinct pattern — counting-numeral-tokens regardless of value. It is not
% currently generated by plausible_wrong_answer/4. Adding it would test
% whether the polysemy extends beyond zero to other numerals.
carving_synthesizer:prove(fact(add, 0, Y, Z), Config,
                          proof(rationalization(zero_as_position),
                                [comment('Treated 0 as a position name; counted Y positions starting at 0, landing on Y-1'),
                                 start_at_position(0),
                                 enumerate_positions(Y, Z)])) :-
    Config.rationalize == true,
    Y >= 1,
    Z =:= Y - 1.
carving_synthesizer:prove(fact(add, X, 0, Z), Config,
                          proof(rationalization(zero_as_position),
                                [comment('Treated 0 as a position name; counted X positions starting at 0, landing on X-1'),
                                 start_at_position(0),
                                 enumerate_positions(X, Z)])) :-
    Config.rationalize == true,
    X >= 1,
    Z =:= X - 1.

% ----- Off-by-one extended to larger smaller-addend (relaxed tolerance) -----
% Even for larger M the off-by-one pattern can fire if the kid is counting
% via a sequence of count-on chunks and miscounts at one transition.
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(off_by_one_extended),
                                [comment('Miscounted by one across a multi-step count-on'),
                                 start(L),
                                 successor_n_off_by_one(M, Z)])) :-
    Config.rationalize == true,
    Z =:= X + Y - 1,
    Z >= 0,
    M is min(X, Y),
    L is max(X, Y),
    M > Config.tolerance.    % the case the strict off_by_one_col couldn't reach

% ----- Missed carry (place-value-column-as-independent) -----
% Pattern: treated tens and ones columns as if they were independent
% single-digit sums. When ones-sum >= base, kept the modulus but dropped
% the carry into the tens column. Base-parametric.
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(missed_carry(Base)),
                                [comment('Added columns separately, dropped the carry'),
                                 split_place(X, [TensX, OnesX]),
                                 split_place(Y, [TensY, OnesY]),
                                 add_ones_no_carry(OnesX, OnesY, FlawedOnes),
                                 add_tens(TensX, TensY, FlawedTens),
                                 recompose([FlawedTens, FlawedOnes], Base, Z)])) :-
    Config.rationalize == true,
    Base = Config.base,
    X >= Base, Y >= Base,
    OnesX is X mod Base, TensX is X div Base,
    OnesY is Y mod Base, TensY is Y div Base,
    OnesSum is OnesX + OnesY,
    OnesSum >= Base,
    FlawedOnes is OnesSum mod Base,
    FlawedTens is TensX + TensY,
    Z =:= FlawedTens * Base + FlawedOnes.

% ----- Digit concatenation -----
% Pattern: wrote the digits of X followed by the digits of Y, treating
% "addition" syntactically (as if the operation were string-join).
% This is part of the Benny family of syntactic-instead-of-semantic moves.
% Base 10 specific (the misconception is about decimal notation).
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(digit_concat),
                                [comment('Concatenated digits of X and Y as if addition were string-join'),
                                 number_codes(X, CX),
                                 number_codes(Y, CY),
                                 append(CX, CY, CZ),
                                 number_codes(Z, CZ)])) :-
    Config.rationalize == true,
    Config.base =:= 10,
    X >= 1, Y >= 1,
    number_codes(Y, CY),
    length(CY, NumDigitsY),
    Mult is 10 ^ NumDigitsY,
    Z is X * Mult + Y,
    Z =< 200.

% ----- Subtraction instead of addition -----
% Pattern: kid read or processed the operation as subtraction.
% Mostly relevant for word problems with "more than" / "fewer than" confusion.
% Only fires for facts where Z = |X-Y|.
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(subtraction_substitution),
                                [comment('Operated as subtraction (sign or word-problem confusion)'),
                                 swap_operation(add, subtract),
                                 subtract(X, Y, Z_raw),
                                 absolute_value(Z_raw, Z)])) :-
    Config.rationalize == true,
    Z =:= abs(X - Y),
    Z \== X + Y,
    Z >= 0,
    (X \= 0 ; Y \= 0).

% ----- Rounding-without-adjustment (the missing-correction misconception) -----
% Pattern: kid substituted L with the nearest base (e.g., 8 -> 10) and
% added M to that substituted base, but FORGOT to count back K to correct
% for the over-shoot. So 8+5 -> "use 10 instead of 8" -> 10+5 = 15.
% This is exactly the rounding strategy with the adjustment step elided.
carving_synthesizer:prove(fact(add, X, Y, Z), Config,
                          proof(rationalization(round_without_adjust(Base)),
                                [comment('Substituted L for nearest base but forgot to subtract the adjustment K'),
                                 identify_candidate_base(L, NextBase),
                                 substitute(L, NextBase),
                                 add_substituted(NextBase, M, Z),
                                 missing_step(count_back_to_correct(Z, K))])) :-
    Config.rationalize == true,
    Base = Config.base,
    L is max(X, Y),
    M is min(X, Y),
    M >= 1,
    K is (Base - (L mod Base)) mod Base,
    K > 0, K =< Config.tolerance,
    NextBase is L + K,
    Z =:= NextBase + M,
    Z =\= X + Y.

% ============================================================================
% SUBTRACTION rationalizations
% ============================================================================

% ----- Wrong-way borrow (subtract smaller from larger column-wise) -----
% Pattern: per column, kid takes the smaller digit from the larger,
% regardless of which is minuend/subtrahend. 32 - 17 -> ones: 7-2=5;
% tens: 3-1=2 -> 25. The borrow step is skipped because the kid
% rearranges the operands instead.
carving_synthesizer:prove(fact(sub, X, Y, Z), Config,
                          proof(rationalization(wrong_way_borrow(Base)),
                                [comment('Per column, took smaller-from-larger regardless of minuend/subtrahend'),
                                 split_place(X, [TensX, OnesX]),
                                 split_place(Y, [TensY, OnesY]),
                                 sub_min_from_max(OnesX, OnesY, FlawedOnes),
                                 sub_tens(TensX, TensY, FlawedTens),
                                 recompose([FlawedTens, FlawedOnes], Base, Z)])) :-
    Config.rationalize == true,
    Base = Config.base,
    X >= Base, Y >= 1,
    OnesX is X mod Base, TensX is X div Base,
    OnesY is Y mod Base, TensY is Y div Base,
    OnesY > OnesX,
    TensY =< TensX,
    FlawedOnes is OnesY - OnesX,
    FlawedTens is TensX - TensY,
    Z =:= FlawedTens * Base + FlawedOnes,
    Z =\= X - Y.

% ----- Off-by-one count-back -----
% Pattern: counted Y-1 successors backward instead of Y (the mirror of
% the addition off-by-one, applied to subtraction).
carving_synthesizer:prove(fact(sub, X, Y, Z), Config,
                          proof(rationalization(off_by_one_count_back),
                                [comment('Counted Y-1 backwards instead of Y'),
                                 start(X),
                                 predecessor_n_off_by_one(Y, Z)])) :-
    Config.rationalize == true,
    Y >= 1,
    Z =:= X - Y + 1,
    Z >= 0, Z =< X,
    Y =< Config.tolerance.

% ----- Forgotten borrow (clamp ones at zero) -----
% Pattern: kid couldn't subtract OnesY from OnesX, so just wrote 0 in
% the ones column and proceeded with the tens subtraction.
carving_synthesizer:prove(fact(sub, X, Y, Z), Config,
                          proof(rationalization(forgotten_borrow(Base)),
                                [comment('Ones-of-S exceeded ones-of-M; kid wrote 0 instead of borrowing'),
                                 split_place(X, [TensX, OnesX]),
                                 split_place(Y, [TensY, OnesY]),
                                 unable_to_subtract(OnesX, OnesY),
                                 clamp_ones(0),
                                 sub_tens(TensX, TensY, FlawedTens),
                                 recompose([FlawedTens, 0], Base, Z)])) :-
    Config.rationalize == true,
    Base = Config.base,
    X >= Base, Y >= 1,
    OnesX is X mod Base, TensX is X div Base,
    OnesY is Y mod Base, TensY is Y div Base,
    OnesY > OnesX,
    TensY =< TensX,
    FlawedTens is TensX - TensY,
    Z =:= FlawedTens * Base + 0,
    Z =\= X - Y.

% ============================================================================
% MULTIPLICATION rationalizations
% ============================================================================

% ----- Additive-for-multiplicative -----
% Pattern: kid treats × as +. Classic young-child error before composite
% units form. N + S = N * S only when one is zero (and that case is
% handled elsewhere by zero_annihilator); the rule fires only when the
% sum is genuinely wrong.
carving_synthesizer:prove(fact(mult, X, Y, Z), Config,
                          proof(rationalization(additive_for_multiplicative),
                                [comment('Treated × as + (composite unit not yet formed)'),
                                 swap_operation(mult, add),
                                 add(X, Y, Z),
                                 missing(coordinate_units)])) :-
    Config.rationalize == true,
    X >= 1, Y >= 1,
    Z =:= X + Y,
    Z \== X * Y.

% ----- Zero-as-identity in multiplication -----
% Pattern: kid imports the additive identity 0 into multiplication, so
% N * 0 = N (and 0 * N = N). The polysemy of "0" again, in a different
% operation.
carving_synthesizer:prove(fact(mult, X, 0, X), Config,
                          proof(rationalization(zero_as_identity_mult),
                                [comment('Treated 0 as additive identity in multiplication; result = X'),
                                 import_rule_from(add, x_plus_zero_is_x),
                                 apply_to(mult, X, 0, X)])) :-
    Config.rationalize == true,
    X >= 1.
carving_synthesizer:prove(fact(mult, 0, Y, Y), Config,
                          proof(rationalization(zero_as_identity_mult),
                                [comment('Treated 0 as additive identity in multiplication; result = Y'),
                                 import_rule_from(add, zero_plus_y_is_y),
                                 apply_to(mult, 0, Y, Y)])) :-
    Config.rationalize == true,
    Y >= 1.

% ----- Digit-wise multiplication (multiply columns independently) -----
% Pattern: tens-times-tens, ones-times-ones, recombine. The same shape
% as missed-carry but for multiplication.
carving_synthesizer:prove(fact(mult, X, Y, Z), Config,
                          proof(rationalization(digit_wise_mult(Base)),
                                [comment('Multiplied tens and ones columns independently; no cross-terms'),
                                 split_place(X, [TensX, OnesX]),
                                 split_place(Y, [TensY, OnesY]),
                                 mult_ones(OnesX, OnesY, FlawedOnesProd),
                                 take_mod(FlawedOnesProd, Base, FlawedOnes),
                                 mult_tens(TensX, TensY, FlawedTens),
                                 recompose([FlawedTens, FlawedOnes], Base, Z),
                                 missing(distributive_cross_terms)])) :-
    Config.rationalize == true,
    Base = Config.base,
    X >= Base, Y >= Base,
    OnesX is X mod Base, TensX is X div Base,
    OnesY is Y mod Base, TensY is Y div Base,
    FlawedOnes is (OnesX * OnesY) mod Base,
    FlawedTens is TensX * TensY,
    Z =:= FlawedTens * Base + FlawedOnes,
    Z \== X * Y, Z >= 0.

% ============================================================================
% DIVISION rationalizations
% ============================================================================

% ----- Divide-larger-by-smaller-always -----
% Pattern: kid takes T/S to mean "the big one divided by the small one,"
% regardless of which is dividend/divisor. So when T < S, they compute
% S/T instead. This is the multiplicative analog of wrong-way-borrow.
carving_synthesizer:prove(fact(div, T, S, Q), Config,
                          proof(rationalization(larger_over_smaller),
                                [comment('Interpreted T/S as max/min regardless of operand role'),
                                 swap_roles_if_needed(T, S, Hi, Lo),
                                 div(Hi, Lo, Q)])) :-
    Config.rationalize == true,
    S >= 1,
    Hi is max(T, S),
    Lo is min(T, S),
    Lo >= 1,
    0 =:= Hi mod Lo,
    Q =:= Hi // Lo,
    Q \== T // S.

% ----- Subtract-instead-of-divide -----
% Pattern: kid swaps the operation; result is T - S.
carving_synthesizer:prove(fact(div, T, S, Q), Config,
                          proof(rationalization(subtract_for_divide),
                                [comment('Operated as subtraction; missed the per-group/measurement frame'),
                                 swap_operation(div, sub),
                                 sub(T, S, Q)])) :-
    Config.rationalize == true,
    S >= 1, T >= S,
    Q =:= T - S,
    Q \== T // S.

% ============================================================================
% FRACTION rationalizations
% ============================================================================

% ----- Whole-number grab -----
% Classic deformation: kid pulls the numerator as a whole number, ignoring
% the denominator entirely. The "answer" (whole-number value of N) is not
% the fraction fraction(N, D); the deformation produces a non-equivalent
% claim. Only fires when D >= 2 (because 1/1 actually equals the whole).
% Encoded as a fact-shape disagreement: the rationalization claim is
% that fact(frac, N, D, N) holds, but in the fact table the head is
% fraction(N, D), so this rule cannot carve any correct fact. We surface
% it as a proof against the WRONG outcome.
% This rationalization fires against bare facts of shape
% fact(frac, N, D, fraction(N, D)) and instead carves them as
% inferentially defective when read through the deformation.
carving_synthesizer:prove(fact(frac, N, D, fraction(N, D)), Config,
                          proof(rationalization(whole_number_grab),
                                [comment('Read fraction as whole number; denominator ignored'),
                                 grab(N),
                                 drop(D),
                                 emit_claim(value_is(N)),
                                 missing(referent_whole)])) :-
    Config.rationalize == true,
    N >= 1, D >= 2.

% ----- Denominator addition (procedural pattern from fraction_action_pairs) -----
% A deformation specific to fraction operation, but we surface it here as
% a "covert" reading of the construction itself: kid would later add
% N/D + N/D as 2N/2D. We model the deformation as: the equivalence-class
% reading is replaced with a syntactic doubling rule.
% This rule fires on N/D with N >= 2 — interprets it as 1/D doubled
% syntactically rather than iterated semantically.
carving_synthesizer:prove(fact(frac, N, D, fraction(N, D)), Config,
                          proof(rationalization(syntactic_iteration),
                                [comment('Wrote N copies of 1/D; iterated the symbol N rather than gathered the parts'),
                                 stamp_unit_fraction(D, fraction(1, D)),
                                 syntactic_repeat(N),
                                 missing(gather_step)])) :-
    Config.rationalize == true,
    N >= 2, D >= 2.

% ----- Cross-multiplication WITHOUT ground (procedurally-correct-but-hollow) -----
% (a/b) * (c/d) = (a*c)/(b*d) carried out as a multiply-across rule
% with no cite of the area-model justification. The numeric output is
% correct; the inferential structure is deformed because the rule is
% applied as a syntactic pattern rather than as the conclusion of a
% partitioning argument. The productive twin is cross_multiply_with_ground
% in primitives.pl.
%
% This is the Brandomian "commitment without entitlement" case — the
% answer is right but no inferential ground is offered.
carving_synthesizer:prove(fact(frac_of, fraction(A, B), fraction(C, D),
                               fraction(P, Q)),
                          Config,
                          proof(rationalization(cross_multiply_without_ground),
                                [comment('Multiplied across with no cite of the area-model justification'),
                                 apply_pattern(numerator_times_numerator,
                                               denominator_times_denominator),
                                 missing(ground_in_partition_argument),
                                 numeric_result(fraction(P, Q))])) :-
    Config.rationalize == true,
    B >= 2, D >= 2,
    A >= 1, C >= 1,
    P =:= A * C, Q =:= B * D.

% ----- Improper fraction collapse (the "more than the whole is impossible") -----
% Deformation specific to improper fractions: kid refuses to iterate
% past the whole and reports the whole as the answer when N >= D.
% A two-level-unit-coordination misfire.
carving_synthesizer:prove(fact(frac, N, D, fraction(N, D)), Config,
                          proof(rationalization(refuse_past_whole),
                                [comment('Iteration halted at the whole boundary; refused to persist 1/D past the D-th iteration'),
                                 iterate_until_whole(D),
                                 stop_at(whole),
                                 emit_claim(value_is(1)),
                                 missing(persist_unit_past_whole)])) :-
    Config.rationalize == true,
    N > D, D >= 2.
