% Generated by scripts/research/build_transition_tables.py.
% Static extraction only; each transition retains its source location.
:- multifile automaton_tuple/6.
:- multifile automaton_transition/6.

automaton_tuple(counting, compare_cardinalities_one_to_one, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([establish_collections, match_objects_one_to_one, inspect_unmatched_surplus, conclude_count_relation]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, compare_ones_digits_only, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([inscribe_in_common_base, discard_higher_place_digits, compare_ones_digits, conclude_count_relation]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, inscribe_cardinality, states([q_start, q_step_1, q_step_2, q_accept]), actions([establish_cardinality, choose_base, project_counting_cycles_into_digits]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, omit_highest_place_regrouping, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([establish_positional_numeral, select_highest_regrouped_place, omit_regrouping_action, read_deformed_cardinality]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, place_value_comparison, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([inscribe_in_common_base, align_places_by_unit, locate_highest_differing_place, compare_digits_at_that_place, conclude_count_relation]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, recursive_place_value_inscription, states([q_start, q_step_1, q_step_2, q_accept]), actions([establish_cardinality, establish_base, recollect_completed_base_cycles]), start(q_start), accepting([q_accept])).
automaton_tuple(counting, spatial_extent_as_cardinality, states([q_start, q_step_1, q_step_2, q_accept]), actions([ignore_one_to_one_correspondence, compare_spatial_extents, substitute_extent_relation_for_count_relation]), start(q_start), accepting([q_accept])).

automaton_transition(counting, compare_cardinalities_one_to_one, q_start, establish_collections, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:177'))).
automaton_transition(counting, compare_cardinalities_one_to_one, q_step_1, match_objects_one_to_one, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:177'))).
automaton_transition(counting, compare_cardinalities_one_to_one, q_step_2, inspect_unmatched_surplus, q_step_3, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:177'))).
automaton_transition(counting, compare_cardinalities_one_to_one, q_step_3, conclude_count_relation, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:177'))).

automaton_transition(counting, compare_ones_digits_only, q_start, inscribe_in_common_base, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:152'))).
automaton_transition(counting, compare_ones_digits_only, q_step_1, discard_higher_place_digits, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:152'))).
automaton_transition(counting, compare_ones_digits_only, q_step_2, compare_ones_digits, q_step_3, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:152'))).
automaton_transition(counting, compare_ones_digits_only, q_step_3, conclude_count_relation, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:152'))).

automaton_transition(counting, inscribe_cardinality, q_start, establish_cardinality, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:52'))).
automaton_transition(counting, inscribe_cardinality, q_step_1, choose_base, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:52'))).
automaton_transition(counting, inscribe_cardinality, q_step_2, project_counting_cycles_into_digits, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:52'))).

automaton_transition(counting, omit_highest_place_regrouping, q_start, establish_positional_numeral, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:96'))).
automaton_transition(counting, omit_highest_place_regrouping, q_step_1, select_highest_regrouped_place, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:96'))).
automaton_transition(counting, omit_highest_place_regrouping, q_step_2, omit_regrouping_action, q_step_3, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:96'))).
automaton_transition(counting, omit_highest_place_regrouping, q_step_3, read_deformed_cardinality, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:96'))).

automaton_transition(counting, place_value_comparison, q_start, inscribe_in_common_base, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:127'))).
automaton_transition(counting, place_value_comparison, q_step_1, align_places_by_unit, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:127'))).
automaton_transition(counting, place_value_comparison, q_step_2, locate_highest_differing_place, q_step_3, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:127'))).
automaton_transition(counting, place_value_comparison, q_step_3, compare_digits_at_that_place, q_step_4, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:127'))).
automaton_transition(counting, place_value_comparison, q_step_4, conclude_count_relation, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:127'))).

automaton_transition(counting, recursive_place_value_inscription, q_start, establish_cardinality, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:72'))).
automaton_transition(counting, recursive_place_value_inscription, q_step_1, establish_base, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:72'))).
automaton_transition(counting, recursive_place_value_inscription, q_step_2, recollect_completed_base_cycles, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:72'))).

automaton_transition(counting, spatial_extent_as_cardinality, q_start, ignore_one_to_one_correspondence, q_step_1, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:200'))).
automaton_transition(counting, spatial_extent_as_cardinality, q_step_1, compare_spatial_extents, q_step_2, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:200'))).
automaton_transition(counting, spatial_extent_as_cardinality, q_step_2, substitute_extent_relation_for_count_relation, q_accept, provenance(static('knowledge/strategies/math/counting_action_pairs.pl:200'))).
