% Generated by scripts/research/build_transition_tables.py.
% Static extraction and bounded live observations; each transition retains its provenance.
:- multifile automaton_tuple/6.
:- multifile automaton_transition/6.

automaton_tuple(fraction, add_numerator_denominator_comparison, states([q_init, q_common_partition, q_add_numerator_denominator, q_add_numerator_denominator, q_measure_with_co_unit, q_compare_same_denominator, q_emit_order, q_accept]), actions([init, no_common_unit_constructed, first, second, omitted, compare_unlike_sums, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, area_model_fraction_comparison, states([q_init, q_unitize_whole, q_verify_same_size_whole, q_partition, q_disembed, q_iterate_count_parts, q_compare_relative_size, q_emit, q_accept]), actions([init, congruent_unit_regions, same_size_wholes_certified, equal_partitions, shaded_parts, iterations, co_measure, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, area_model_part_of_part, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_step_5, q_step_6, q_step_7, q_accept]), actions([establish_referent_whole, partition_unit_square_vertically, select_first_fraction_strip, partition_each_strip_horizontally, select_part_of_part_in_strip, count_small_rectangles_in_whole, count_small_rectangles_selected, read_off_part_of_part]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, area_model_unequal_partition_piece_count, states([q_init, q_unitize_whole, q_verify_same_size_whole, q_partition, q_unequal_partition_piece_count, q_disembed, q_iterate_count_parts, q_compare_relative_size, q_emit, q_accept]), actions([init, drawn_regions_treated_as_wholes, same_size_wholes_not_checked, unequal_partitions_accepted_without_equality_check, treat_unequal_pieces_as_equal_counts, shaded_pieces_removed_from_partition_structure, raw_piece_counts, whole_number_dominance, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, benchmark_fraction_comparison, states([q_init, q_select_benchmark, q_benchmark_first, q_benchmark_second, q_residual_compare, q_emit, q_accept]), actions([init, selected, judgment, judgment, residual, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, co_denominator_count_on_from_larger, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_step_5, q_accept]), actions([confirm_same_denominator, hold_referent_whole_at, hold_unit_fraction_at, dispatch_to_cgi, cgi_kernel_outcome, attach_three_level_units_coordination]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, co_denominator_make_base_transfer, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_step_5, q_accept]), actions([confirm_same_denominator, hold_referent_whole_at, hold_unit_fraction_at, dispatch_to_cgi, cgi_kernel_outcome, attach_three_level_units_coordination]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, common_unit_fraction_comparison, states([q_init, q_common_numerator, q_transform_commensurate_1, q_transform_commensurate_2, q_measure_with_co_unit, q_compare_same_numerator, q_emit_order, q_accept]), actions([init, shared_numerator, unchanged, unchanged, same_count_different_unit_sizes, inverse_denominator_relation, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, gap_thinking_fraction_comparison, states([q_init, q_select_benchmark, q_benchmark_first, q_benchmark_second, q_gap_thinking, q_transitive_compare, q_residual_compare, q_emit, q_accept]), actions([init, selected, numerator_denominator_gap, numerator_denominator_gap, compare_absolute_gaps, omitted_external_value_relation, unscaled_residuals, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, improper_fraction_chain_loss, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_step_5, q_accept]), actions([establish_referent_whole, iterate_unit_past_whole, lose_original_referent_whole_chain, reset_completion_norm, rename_result_to_new_whole, kernel_trace]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, measurement_division, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([establish_dividend_and_divisor, co_measure_both_with_a_shared_fractional_unit, count_how_many_group_sizes_fit, name_leftover_as_a_fraction_of_the_group_size, name_quotient_and_remainder]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, number_line_count_marks_not_intervals, states([q_init, q_identify_unit, q_partition_interval, q_count_marks_not_intervals, q_locate_endpoint, q_measure_with_unit_fraction, q_compare_positions, q_emit, q_accept]), actions([init, unit_interval, partitions, overcount, mislocated_endpoints, co_measure, compare, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, number_line_fraction_comparison, states([q_init, q_identify_unit, q_partition_interval, q_mark_off_lengths, q_locate_endpoint, q_measure_with_unit_fraction, q_compare_positions, q_emit, q_accept]), actions([init, unit_interval, partitions, iterations, endpoints, co_measure, compare, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, reversible_measurement_division, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([establish_dividend_and_divisor, recover_the_unit_generator_of_the_divisor, measure_the_total_in_generator_scale, form_one_group_from_the_generator_units, read_quotient_as_total_ticks_over_group_ticks]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, set_model_fraction_comparison, states([q_init, q_unitize_set, q_verify_same_whole, q_partition_set, q_count_equal_sets, q_disembed_subset, q_compare_relative_size, q_emit, q_accept]), actions([init, collections_as_single_wholes, commensurable_collections_certified, equal_shares, denominator_counts, selected_shares, co_measure, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, set_model_subset_size_focus, states([q_init, q_unitize_set, q_verify_same_whole, q_partition_set, q_count_equal_sets, q_disembed_subset, q_subset_size_focus, q_compare_relative_size, q_emit, q_accept]), actions([init, collections_as_single_wholes, commensurable_collections_not_checked, equal_share_structure_ignored, confuse_counters_with_share_name, focus_on_subset_counts, subset_count_replaces_fractional_share, compare_raw_subset_sizes, emit]), start(q_init), accepting([q_accept])).
automaton_tuple(fraction, unit_fraction_iteration, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([establish_referent_whole, recover_unit_fraction, iterate_unit_fraction, coordinate_iteration_with_completion_marker, kernel_trace]), start(q_start), accepting([q_accept])).
automaton_tuple(fraction, unit_fraction_partition, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([establish_referent_whole, partition_whole_into_equal_units, select_one_partition_as_unit_fraction, preserve_inside_and_iterable_status, kernel_trace]), start(q_start), accepting([q_accept])).

automaton_transition(fraction, add_numerator_denominator_comparison, q_init, init, q_common_partition, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_common_partition, no_common_unit_constructed, q_add_numerator_denominator, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, first, q_add_numerator_denominator, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, second, q_measure_with_co_unit, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_measure_with_co_unit, omitted, q_compare_same_denominator, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_compare_same_denominator, compare_unlike_sums, q_emit_order, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_emit_order, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:43'))).

automaton_transition(fraction, area_model_fraction_comparison, q_init, init, q_unitize_whole, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_unitize_whole, congruent_unit_regions, q_verify_same_size_whole, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_verify_same_size_whole, same_size_wholes_certified, q_partition, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_partition, equal_partitions, q_disembed, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_disembed, shaded_parts, q_iterate_count_parts, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_iterate_count_parts, iterations, q_compare_relative_size, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).
automaton_transition(fraction, area_model_fraction_comparison, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:13'))).

automaton_transition(fraction, area_model_part_of_part, q_start, establish_referent_whole, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_1, partition_unit_square_vertically, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_2, select_first_fraction_strip, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_3, partition_each_strip_horizontally, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_4, select_part_of_part_in_strip, q_step_5, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_5, count_small_rectangles_in_whole, q_step_6, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_6, count_small_rectangles_selected, q_step_7, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).
automaton_transition(fraction, area_model_part_of_part, q_step_7, read_off_part_of_part, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:678'))).

automaton_transition(fraction, area_model_unequal_partition_piece_count, q_init, init, q_unitize_whole, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unitize_whole, drawn_regions_treated_as_wholes, q_verify_same_size_whole, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_verify_same_size_whole, same_size_wholes_not_checked, q_partition, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_partition, unequal_partitions_accepted_without_equality_check, q_unequal_partition_piece_count, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unequal_partition_piece_count, treat_unequal_pieces_as_equal_counts, q_disembed, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_disembed, shaded_pieces_removed_from_partition_structure, q_iterate_count_parts, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_iterate_count_parts, raw_piece_counts, q_compare_relative_size, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_compare_relative_size, whole_number_dominance, q_emit, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_area_compare.pl:33'))).

automaton_transition(fraction, benchmark_fraction_comparison, q_init, init, q_select_benchmark, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).
automaton_transition(fraction, benchmark_fraction_comparison, q_select_benchmark, selected, q_benchmark_first, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).
automaton_transition(fraction, benchmark_fraction_comparison, q_benchmark_first, judgment, q_benchmark_second, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).
automaton_transition(fraction, benchmark_fraction_comparison, q_benchmark_second, judgment, q_residual_compare, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).
automaton_transition(fraction, benchmark_fraction_comparison, q_residual_compare, residual, q_emit, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).
automaton_transition(fraction, benchmark_fraction_comparison, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:11'))).

automaton_transition(fraction, co_denominator_count_on_from_larger, q_start, confirm_same_denominator, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).
automaton_transition(fraction, co_denominator_count_on_from_larger, q_step_1, hold_referent_whole_at, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).
automaton_transition(fraction, co_denominator_count_on_from_larger, q_step_2, hold_unit_fraction_at, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).
automaton_transition(fraction, co_denominator_count_on_from_larger, q_step_3, dispatch_to_cgi, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).
automaton_transition(fraction, co_denominator_count_on_from_larger, q_step_4, cgi_kernel_outcome, q_step_5, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).
automaton_transition(fraction, co_denominator_count_on_from_larger, q_step_5, attach_three_level_units_coordination, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:817'))).

automaton_transition(fraction, co_denominator_make_base_transfer, q_start, confirm_same_denominator, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).
automaton_transition(fraction, co_denominator_make_base_transfer, q_step_1, hold_referent_whole_at, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).
automaton_transition(fraction, co_denominator_make_base_transfer, q_step_2, hold_unit_fraction_at, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).
automaton_transition(fraction, co_denominator_make_base_transfer, q_step_3, dispatch_to_cgi, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).
automaton_transition(fraction, co_denominator_make_base_transfer, q_step_4, cgi_kernel_outcome, q_step_5, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).
automaton_transition(fraction, co_denominator_make_base_transfer, q_step_5, attach_three_level_units_coordination, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:875'))).

automaton_transition(fraction, common_unit_fraction_comparison, q_init, init, q_common_numerator, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_common_numerator, shared_numerator, q_transform_commensurate_1, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_transform_commensurate_1, unchanged, q_transform_commensurate_2, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_transform_commensurate_2, unchanged, q_measure_with_co_unit, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_measure_with_co_unit, same_count_different_unit_sizes, q_compare_same_numerator, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_compare_same_numerator, inverse_denominator_relation, q_emit_order, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).
automaton_transition(fraction, common_unit_fraction_comparison, q_emit_order, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_common_unit_compare.pl:11'))).

automaton_transition(fraction, gap_thinking_fraction_comparison, q_init, init, q_select_benchmark, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_select_benchmark, selected, q_benchmark_first, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_benchmark_first, numerator_denominator_gap, q_benchmark_second, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_benchmark_second, numerator_denominator_gap, q_gap_thinking, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_gap_thinking, compare_absolute_gaps, q_transitive_compare, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_transitive_compare, omitted_external_value_relation, q_residual_compare, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_residual_compare, unscaled_residuals, q_emit, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_benchmark_compare.pl:35'))).

automaton_transition(fraction, improper_fraction_chain_loss, q_start, establish_referent_whole, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_1, iterate_unit_past_whole, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_2, lose_original_referent_whole_chain, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_3, reset_completion_norm, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_4, rename_result_to_new_whole, q_step_5, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_5, kernel_trace, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:318'))).

automaton_transition(fraction, measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:904'))).
automaton_transition(fraction, measurement_division, q_step_1, co_measure_both_with_a_shared_fractional_unit, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:904'))).
automaton_transition(fraction, measurement_division, q_step_2, count_how_many_group_sizes_fit, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:904'))).
automaton_transition(fraction, measurement_division, q_step_3, name_leftover_as_a_fraction_of_the_group_size, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:904'))).
automaton_transition(fraction, measurement_division, q_step_4, name_quotient_and_remainder, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:904'))).

automaton_transition(fraction, number_line_count_marks_not_intervals, q_init, init, q_identify_unit, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_identify_unit, unit_interval, q_partition_interval, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_partition_interval, partitions, q_count_marks_not_intervals, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_count_marks_not_intervals, overcount, q_locate_endpoint, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_locate_endpoint, mislocated_endpoints, q_measure_with_unit_fraction, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_compare_positions, compare, q_emit, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:65'))).

automaton_transition(fraction, number_line_fraction_comparison, q_init, init, q_identify_unit, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_identify_unit, unit_interval, q_partition_interval, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_partition_interval, partitions, q_mark_off_lengths, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_mark_off_lengths, iterations, q_locate_endpoint, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_locate_endpoint, endpoints, q_measure_with_unit_fraction, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_compare_positions, compare, q_emit, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).
automaton_transition(fraction, number_line_fraction_comparison, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_nl_compare.pl:29'))).

automaton_transition(fraction, reversible_measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:943'))).
automaton_transition(fraction, reversible_measurement_division, q_step_1, recover_the_unit_generator_of_the_divisor, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:943'))).
automaton_transition(fraction, reversible_measurement_division, q_step_2, measure_the_total_in_generator_scale, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:943'))).
automaton_transition(fraction, reversible_measurement_division, q_step_3, form_one_group_from_the_generator_units, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:943'))).
automaton_transition(fraction, reversible_measurement_division, q_step_4, read_quotient_as_total_ticks_over_group_ticks, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:943'))).

automaton_transition(fraction, set_model_fraction_comparison, q_init, init, q_unitize_set, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_verify_same_whole, commensurable_collections_certified, q_partition_set, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_partition_set, equal_shares, q_count_equal_sets, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_count_equal_sets, denominator_counts, q_disembed_subset, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_disembed_subset, selected_shares, q_compare_relative_size, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).
automaton_transition(fraction, set_model_fraction_comparison, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:13'))).

automaton_transition(fraction, set_model_subset_size_focus, q_init, init, q_unitize_set, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_verify_same_whole, commensurable_collections_not_checked, q_partition_set, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_partition_set, equal_share_structure_ignored, q_count_equal_sets, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_count_equal_sets, confuse_counters_with_share_name, q_disembed_subset, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_disembed_subset, focus_on_subset_counts, q_subset_size_focus, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_subset_size_focus, subset_count_replaces_fractional_share, q_compare_relative_size, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_compare_relative_size, compare_raw_subset_sizes, q_emit, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).
automaton_transition(fraction, set_model_subset_size_focus, q_emit, emit, q_accept, provenance(static('knowledge/strategies/math/smr_frac_set_compare.pl:32'))).

automaton_transition(fraction, unit_fraction_iteration, q_start, establish_referent_whole, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:137'))).
automaton_transition(fraction, unit_fraction_iteration, q_step_1, recover_unit_fraction, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:137'))).
automaton_transition(fraction, unit_fraction_iteration, q_step_2, iterate_unit_fraction, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:137'))).
automaton_transition(fraction, unit_fraction_iteration, q_step_3, coordinate_iteration_with_completion_marker, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:137'))).
automaton_transition(fraction, unit_fraction_iteration, q_step_4, kernel_trace, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:137'))).

automaton_transition(fraction, unit_fraction_partition, q_start, establish_referent_whole, q_step_1, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:110'))).
automaton_transition(fraction, unit_fraction_partition, q_step_1, partition_whole_into_equal_units, q_step_2, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:110'))).
automaton_transition(fraction, unit_fraction_partition, q_step_2, select_one_partition_as_unit_fraction, q_step_3, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:110'))).
automaton_transition(fraction, unit_fraction_partition, q_step_3, preserve_inside_and_iterable_status, q_step_4, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:110'))).
automaton_transition(fraction, unit_fraction_partition, q_step_4, kernel_trace, q_accept, provenance(static('knowledge/strategies/math/fraction_action_pairs.pl:110'))).

% Bounded live traces reconstructed from returned step labels.
automaton_transition(fraction, add_numerator_denominator_comparison, q_init, init, q_common_partition, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_common_partition, no_common_unit_constructed, q_add_numerator_denominator, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, first, q_add_numerator_denominator, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, second, q_measure_with_co_unit, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_measure_with_co_unit, omitted, q_compare_same_denominator, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_compare_same_denominator, compare_unlike_sums, q_emit_order, provenance(observed(contract_example))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_emit_order, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, add_numerator_denominator_comparison, q_init, init, q_common_partition, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_common_partition, no_common_unit_constructed, q_add_numerator_denominator, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, first, q_add_numerator_denominator, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_add_numerator_denominator, second, q_measure_with_co_unit, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_measure_with_co_unit, omitted, q_compare_same_denominator, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_compare_same_denominator, compare_unlike_sums, q_emit_order, provenance(observed(derived_template))).
automaton_transition(fraction, add_numerator_denominator_comparison, q_emit_order, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, area_model_fraction_comparison, q_init, init, q_unitize_whole, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_unitize_whole, congruent_unit_regions, q_verify_same_size_whole, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_verify_same_size_whole, same_size_wholes_certified, q_partition, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_partition, equal_partitions, q_disembed, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_disembed, shaded_parts, q_iterate_count_parts, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_iterate_count_parts, iterations, q_compare_relative_size, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_fraction_comparison, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, area_model_fraction_comparison, q_init, init, q_unitize_whole, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_unitize_whole, congruent_unit_regions, q_verify_same_size_whole, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_verify_same_size_whole, same_size_wholes_certified, q_partition, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_partition, equal_partitions, q_disembed, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_disembed, shaded_parts, q_iterate_count_parts, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_iterate_count_parts, iterations, q_compare_relative_size, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_fraction_comparison, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, area_model_part_of_part, q_start, establish_referent_whole, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_1, partition_unit_square_vertically, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_2, select_first_fraction_strip, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_3, partition_each_strip_horizontally, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_4, select_part_of_part_in_strip, q_step_5, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_5, count_small_rectangles_in_whole, q_step_6, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_6, count_small_rectangles_selected, q_step_7, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_part_of_part, q_step_7, read_off_part_of_part, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, area_model_part_of_part, q_start, establish_referent_whole, q_step_1, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_1, partition_unit_square_vertically, q_step_2, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_2, select_first_fraction_strip, q_step_3, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_3, partition_each_strip_horizontally, q_step_4, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_4, select_part_of_part_in_strip, q_step_5, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_5, count_small_rectangles_in_whole, q_step_6, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_6, count_small_rectangles_selected, q_step_7, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_part_of_part, q_step_7, read_off_part_of_part, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, area_model_unequal_partition_piece_count, q_init, init, q_unitize_whole, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unitize_whole, drawn_regions_treated_as_wholes, q_verify_same_size_whole, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_verify_same_size_whole, same_size_wholes_not_checked, q_partition, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_partition, unequal_partitions_accepted_without_equality_check, q_unequal_partition_piece_count, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unequal_partition_piece_count, treat_unequal_pieces_as_equal_counts, q_disembed, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_disembed, shaded_pieces_removed_from_partition_structure, q_iterate_count_parts, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_iterate_count_parts, raw_piece_counts, q_compare_relative_size, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_compare_relative_size, whole_number_dominance, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, area_model_unequal_partition_piece_count, q_init, init, q_unitize_whole, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unitize_whole, drawn_regions_treated_as_wholes, q_verify_same_size_whole, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_verify_same_size_whole, same_size_wholes_not_checked, q_partition, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_partition, unequal_partitions_accepted_without_equality_check, q_unequal_partition_piece_count, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_unequal_partition_piece_count, treat_unequal_pieces_as_equal_counts, q_disembed, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_disembed, shaded_pieces_removed_from_partition_structure, q_iterate_count_parts, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_iterate_count_parts, raw_piece_counts, q_compare_relative_size, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_compare_relative_size, whole_number_dominance, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, area_model_unequal_partition_piece_count, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, benchmark_fraction_comparison, q_init, init, q_observed_1, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_1, selected, q_observed_2, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_2, judgment, q_observed_3, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_3, judgment, q_observed_4, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_4, same_side_requires_residual, q_observed_5, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_5, residual, q_observed_6, provenance(observed(contract_example))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_6, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, benchmark_fraction_comparison, q_init, init, q_observed_1, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_1, selected, q_observed_2, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_2, judgment, q_observed_3, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_3, judgment, q_observed_4, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_4, opposite_sides, q_observed_5, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_5, residual, q_observed_6, provenance(observed(derived_template))).
automaton_transition(fraction, benchmark_fraction_comparison, q_observed_6, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, common_unit_fraction_comparison, q_init, init, q_observed_1, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_1, common_denominator, q_observed_2, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_2, transformed, q_observed_3, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_3, transformed, q_observed_4, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_4, co_measure, q_observed_5, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_5, compare_counts, q_observed_6, provenance(observed(contract_example))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_6, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, common_unit_fraction_comparison, q_init, init, q_observed_1, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_1, common_denominator, q_observed_2, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_2, transformed, q_observed_3, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_3, transformed, q_observed_4, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_4, co_measure, q_observed_5, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_5, compare_counts, q_observed_6, provenance(observed(derived_template))).
automaton_transition(fraction, common_unit_fraction_comparison, q_observed_6, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, gap_thinking_fraction_comparison, q_init, init, q_observed_1, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_1, selected, q_observed_2, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_2, numerator_denominator_gap, q_observed_3, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_3, numerator_denominator_gap, q_observed_4, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_4, compare_absolute_gaps, q_observed_5, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_5, omitted_external_value_relation, q_observed_6, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_6, unscaled_residuals, q_observed_7, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_7, viability, q_observed_8, provenance(observed(contract_example))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_8, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, gap_thinking_fraction_comparison, q_init, init, q_observed_1, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_1, selected, q_observed_2, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_2, numerator_denominator_gap, q_observed_3, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_3, numerator_denominator_gap, q_observed_4, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_4, compare_absolute_gaps, q_observed_5, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_5, omitted_external_value_relation, q_observed_6, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_6, unscaled_residuals, q_observed_7, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_7, viability, q_observed_8, provenance(observed(derived_template))).
automaton_transition(fraction, gap_thinking_fraction_comparison, q_observed_8, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, improper_fraction_chain_loss, q_start, establish_referent_whole, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_1, iterate_unit_past_whole, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_2, lose_original_referent_whole_chain, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_3, reset_completion_norm, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_4, rename_result_to_new_whole, q_step_5, provenance(observed(contract_example))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_5, kernel_trace, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, improper_fraction_chain_loss, q_start, establish_referent_whole, q_step_1, provenance(observed(derived_template))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_1, iterate_unit_past_whole, q_step_2, provenance(observed(derived_template))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_2, lose_original_referent_whole_chain, q_step_3, provenance(observed(derived_template))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_3, reset_completion_norm, q_step_4, provenance(observed(derived_template))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_4, rename_result_to_new_whole, q_step_5, provenance(observed(derived_template))).
automaton_transition(fraction, improper_fraction_chain_loss, q_step_5, kernel_trace, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, measurement_division, q_step_1, co_measure_both_with_a_shared_fractional_unit, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, measurement_division, q_step_2, count_how_many_group_sizes_fit, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, measurement_division, q_step_3, name_leftover_as_a_fraction_of_the_group_size, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, measurement_division, q_step_4, name_quotient_and_remainder, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(observed(derived_template))).
automaton_transition(fraction, measurement_division, q_step_1, co_measure_both_with_a_shared_fractional_unit, q_step_2, provenance(observed(derived_template))).
automaton_transition(fraction, measurement_division, q_step_2, count_how_many_group_sizes_fit, q_step_3, provenance(observed(derived_template))).
automaton_transition(fraction, measurement_division, q_step_3, name_leftover_as_a_fraction_of_the_group_size, q_step_4, provenance(observed(derived_template))).
automaton_transition(fraction, measurement_division, q_step_4, name_quotient_and_remainder, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, number_line_count_marks_not_intervals, q_init, init, q_identify_unit, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_identify_unit, unit_interval, q_partition_interval, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_partition_interval, partitions, q_count_marks_not_intervals, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_count_marks_not_intervals, overcount, q_locate_endpoint, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_locate_endpoint, mislocated_endpoints, q_measure_with_unit_fraction, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_compare_positions, compare, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, number_line_count_marks_not_intervals, q_init, init, q_identify_unit, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_identify_unit, unit_interval, q_partition_interval, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_partition_interval, partitions, q_count_marks_not_intervals, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_count_marks_not_intervals, overcount, q_locate_endpoint, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_locate_endpoint, mislocated_endpoints, q_measure_with_unit_fraction, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_compare_positions, compare, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_count_marks_not_intervals, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, number_line_fraction_comparison, q_init, init, q_identify_unit, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_identify_unit, unit_interval, q_partition_interval, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_partition_interval, partitions, q_mark_off_lengths, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_mark_off_lengths, iterations, q_locate_endpoint, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_locate_endpoint, endpoints, q_measure_with_unit_fraction, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_compare_positions, compare, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, number_line_fraction_comparison, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, number_line_fraction_comparison, q_init, init, q_identify_unit, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_identify_unit, unit_interval, q_partition_interval, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_partition_interval, partitions, q_mark_off_lengths, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_mark_off_lengths, iterations, q_locate_endpoint, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_locate_endpoint, endpoints, q_measure_with_unit_fraction, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_measure_with_unit_fraction, co_measure, q_compare_positions, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_compare_positions, compare, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, number_line_fraction_comparison, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, reversible_measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, reversible_measurement_division, q_step_1, recover_the_unit_generator_of_the_divisor, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, reversible_measurement_division, q_step_2, measure_the_total_in_generator_scale, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, reversible_measurement_division, q_step_3, form_one_group_from_the_generator_units, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, reversible_measurement_division, q_step_4, read_quotient_as_total_ticks_over_group_ticks, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, reversible_measurement_division, q_start, establish_dividend_and_divisor, q_step_1, provenance(observed(derived_template))).
automaton_transition(fraction, reversible_measurement_division, q_step_1, recover_the_unit_generator_of_the_divisor, q_step_2, provenance(observed(derived_template))).
automaton_transition(fraction, reversible_measurement_division, q_step_2, measure_the_total_in_generator_scale, q_step_3, provenance(observed(derived_template))).
automaton_transition(fraction, reversible_measurement_division, q_step_3, form_one_group_from_the_generator_units, q_step_4, provenance(observed(derived_template))).
automaton_transition(fraction, reversible_measurement_division, q_step_4, read_quotient_as_total_ticks_over_group_ticks, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, set_model_fraction_comparison, q_init, init, q_unitize_set, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_verify_same_whole, commensurable_collections_certified, q_partition_set, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_partition_set, equal_shares, q_count_equal_sets, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_count_equal_sets, denominator_counts, q_disembed_subset, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_disembed_subset, selected_shares, q_compare_relative_size, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_fraction_comparison, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, set_model_fraction_comparison, q_init, init, q_unitize_set, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_verify_same_whole, commensurable_collections_certified, q_partition_set, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_partition_set, equal_shares, q_count_equal_sets, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_count_equal_sets, denominator_counts, q_disembed_subset, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_disembed_subset, selected_shares, q_compare_relative_size, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_compare_relative_size, co_measure, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_fraction_comparison, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, set_model_subset_size_focus, q_init, init, q_unitize_set, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_verify_same_whole, commensurable_collections_not_checked, q_partition_set, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_partition_set, equal_share_structure_ignored, q_count_equal_sets, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_count_equal_sets, confuse_counters_with_share_name, q_disembed_subset, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_disembed_subset, focus_on_subset_counts, q_subset_size_focus, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_subset_size_focus, subset_count_replaces_fractional_share, q_compare_relative_size, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_compare_relative_size, compare_raw_subset_sizes, q_emit, provenance(observed(contract_example))).
automaton_transition(fraction, set_model_subset_size_focus, q_emit, emit, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, set_model_subset_size_focus, q_init, init, q_unitize_set, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_unitize_set, collections_as_single_wholes, q_verify_same_whole, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_verify_same_whole, commensurable_collections_not_checked, q_partition_set, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_partition_set, equal_share_structure_ignored, q_count_equal_sets, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_count_equal_sets, confuse_counters_with_share_name, q_disembed_subset, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_disembed_subset, focus_on_subset_counts, q_subset_size_focus, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_subset_size_focus, subset_count_replaces_fractional_share, q_compare_relative_size, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_compare_relative_size, compare_raw_subset_sizes, q_emit, provenance(observed(derived_template))).
automaton_transition(fraction, set_model_subset_size_focus, q_emit, emit, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, unit_fraction_iteration, q_start, establish_referent_whole, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_iteration, q_step_1, recover_unit_fraction, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_iteration, q_step_2, iterate_unit_fraction, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_iteration, q_step_3, coordinate_iteration_with_completion_marker, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_iteration, q_step_4, kernel_trace, q_accept, provenance(observed(contract_example))).

automaton_transition(fraction, unit_fraction_iteration, q_start, establish_referent_whole, q_step_1, provenance(observed(derived_template))).
automaton_transition(fraction, unit_fraction_iteration, q_step_1, recover_unit_fraction, q_step_2, provenance(observed(derived_template))).
automaton_transition(fraction, unit_fraction_iteration, q_step_2, iterate_unit_fraction, q_step_3, provenance(observed(derived_template))).
automaton_transition(fraction, unit_fraction_iteration, q_step_3, coordinate_iteration_with_completion_marker, q_step_4, provenance(observed(derived_template))).
automaton_transition(fraction, unit_fraction_iteration, q_step_4, kernel_trace, q_accept, provenance(observed(derived_template))).

automaton_transition(fraction, unit_fraction_partition, q_start, establish_referent_whole, q_step_1, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_partition, q_step_1, partition_whole_into_equal_units, q_step_2, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_partition, q_step_2, select_one_partition_as_unit_fraction, q_step_3, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_partition, q_step_3, preserve_inside_and_iterable_status, q_step_4, provenance(observed(contract_example))).
automaton_transition(fraction, unit_fraction_partition, q_step_4, kernel_trace, q_accept, provenance(observed(contract_example))).
