% Generated by scripts/research/build_transition_tables.py.
% Static extraction and bounded live observations; each transition retains its provenance.
:- multifile automaton_tuple/6.
:- multifile automaton_transition/6.

automaton_tuple(multiplication, add_numbers_as_common_multiple, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([read_two_numbers, substitute_addition_for_multiple_generation, add_inputs, omit_divisibility_check]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, common_factor_intersection, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([enumerate_positive_divisors, enumerate_positive_divisors, intersect_factor_sets, select_greatest_common_factor]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, common_multiple_sequence, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([coordinate_multiples_of, locate_least_common_multiple, retain_lcm_as_composite_iteration_unit, iterate_common_multiple_generator]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, commute_factors_preserve_product, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([compare_factor_orders, compute_original_product, commute_factors, compute_commuted_product, preserve_product_under_commutation]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, coordinate_groups_items, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([form_equal_groups, coordinate_group_count_with_item_count, iterate_composite_unit, name_total_items]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, distribute_group_size_split, states([q_start, q_step_1, q_step_2, q_step_3, q_step_4, q_accept]), actions([split_group_size, compute_partial_product, compute_partial_product, recompose_partial_products, preserve_distributed_groups]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, factors_of_first_number_only, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([enumerate_positive_divisors, omit_divisor_search_for, omit_factor_set_intersection, report_first_factor_set_as_common]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, multiplication_fact_retrieval, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([recognize_factor_pair, retrieve_known_multiplication_fact, bind_product_to_factor_pair, preserve_referent_units_for_product]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, regroup_to_base_preserving_total, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([form_equal_groups, regroup_total_as_base_bundles, preserve_leftover_after_regrouping, name_total_from_bundles_and_leftover]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, repeat_equal_groups, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([hold_group_size_as_repeated_addend, hold_number_of_groups_as_iterations, add_equal_group_repeatedly, name_accumulated_total]), start(q_start), accepting([q_accept])).
automaton_tuple(multiplication, repeat_group_size_by_itself, states([q_start, q_step_1, q_step_2, q_step_3, q_accept]), actions([hold_group_size_as_repeated_addend, use_group_size_as_iteration_count, add_equal_group_repeatedly, lose_group_count_role]), start(q_start), accepting([q_accept])).

automaton_transition(multiplication, add_numbers_as_common_multiple, q_start, read_two_numbers, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:260'))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_1, substitute_addition_for_multiple_generation, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:260'))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_2, add_inputs, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:260'))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_3, omit_divisibility_check, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:260'))).

automaton_transition(multiplication, common_factor_intersection, q_start, enumerate_positive_divisors, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:178'))).
automaton_transition(multiplication, common_factor_intersection, q_step_1, enumerate_positive_divisors, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:178'))).
automaton_transition(multiplication, common_factor_intersection, q_step_2, intersect_factor_sets, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:178'))).
automaton_transition(multiplication, common_factor_intersection, q_step_3, select_greatest_common_factor, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:178'))).

automaton_transition(multiplication, common_multiple_sequence, q_start, coordinate_multiples_of, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:236'))).
automaton_transition(multiplication, common_multiple_sequence, q_step_1, locate_least_common_multiple, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:236'))).
automaton_transition(multiplication, common_multiple_sequence, q_step_2, retain_lcm_as_composite_iteration_unit, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:236'))).
automaton_transition(multiplication, common_multiple_sequence, q_step_3, iterate_common_multiple_generator, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:236'))).

automaton_transition(multiplication, commute_factors_preserve_product, q_start, compare_factor_orders, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:441'))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_1, compute_original_product, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:441'))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_2, commute_factors, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:441'))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_3, compute_commuted_product, q_step_4, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:441'))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_4, preserve_product_under_commutation, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:441'))).

automaton_transition(multiplication, coordinate_groups_items, q_start, form_equal_groups, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:61'))).
automaton_transition(multiplication, coordinate_groups_items, q_step_1, coordinate_group_count_with_item_count, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:61'))).
automaton_transition(multiplication, coordinate_groups_items, q_step_2, iterate_composite_unit, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:61'))).
automaton_transition(multiplication, coordinate_groups_items, q_step_3, name_total_items, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:61'))).

automaton_transition(multiplication, distribute_group_size_split, q_start, split_group_size, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:289'))).
automaton_transition(multiplication, distribute_group_size_split, q_step_1, compute_partial_product, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:289'))).
automaton_transition(multiplication, distribute_group_size_split, q_step_2, compute_partial_product, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:289'))).
automaton_transition(multiplication, distribute_group_size_split, q_step_3, recompose_partial_products, q_step_4, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:289'))).
automaton_transition(multiplication, distribute_group_size_split, q_step_4, preserve_distributed_groups, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:289'))).

automaton_transition(multiplication, factors_of_first_number_only, q_start, enumerate_positive_divisors, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:207'))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_1, omit_divisor_search_for, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:207'))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_2, omit_factor_set_intersection, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:207'))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_3, report_first_factor_set_as_common, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:207'))).

automaton_transition(multiplication, multiplication_fact_retrieval, q_start, recognize_factor_pair, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:514'))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_1, retrieve_known_multiplication_fact, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:514'))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_2, bind_product_to_factor_pair, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:514'))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_3, preserve_referent_units_for_product, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:514'))).

automaton_transition(multiplication, regroup_to_base_preserving_total, q_start, form_equal_groups, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:339'))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_1, regroup_total_as_base_bundles, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:339'))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_2, preserve_leftover_after_regrouping, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:339'))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_3, name_total_from_bundles_and_leftover, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:339'))).

automaton_transition(multiplication, repeat_equal_groups, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:130'))).
automaton_transition(multiplication, repeat_equal_groups, q_step_1, hold_number_of_groups_as_iterations, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:130'))).
automaton_transition(multiplication, repeat_equal_groups, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:130'))).
automaton_transition(multiplication, repeat_equal_groups, q_step_3, name_accumulated_total, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:130'))).

automaton_transition(multiplication, repeat_group_size_by_itself, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:154'))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_1, use_group_size_as_iteration_count, q_step_2, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:154'))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:154'))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_3, lose_group_count_role, q_accept, provenance(static('knowledge/strategies/math/smr_mult_action_pairs.pl:154'))).

% Bounded live traces reconstructed from returned step labels.
automaton_transition(multiplication, add_numbers_as_common_multiple, q_start, read_two_numbers, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_1, substitute_addition_for_multiple_generation, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_2, add_inputs, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_3, omit_divisibility_check, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, add_numbers_as_common_multiple, q_start, read_two_numbers, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_1, substitute_addition_for_multiple_generation, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_2, add_inputs, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, add_numbers_as_common_multiple, q_step_3, omit_divisibility_check, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, common_factor_intersection, q_start, enumerate_positive_divisors, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, common_factor_intersection, q_step_1, enumerate_positive_divisors, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, common_factor_intersection, q_step_2, intersect_factor_sets, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, common_factor_intersection, q_step_3, select_greatest_common_factor, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, common_factor_intersection, q_start, enumerate_positive_divisors, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, common_factor_intersection, q_step_1, enumerate_positive_divisors, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, common_factor_intersection, q_step_2, intersect_factor_sets, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, common_factor_intersection, q_step_3, select_greatest_common_factor, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, common_multiple_sequence, q_start, coordinate_multiples_of, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, common_multiple_sequence, q_step_1, locate_least_common_multiple, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, common_multiple_sequence, q_step_2, retain_lcm_as_composite_iteration_unit, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, common_multiple_sequence, q_step_3, iterate_common_multiple_generator, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, common_multiple_sequence, q_start, coordinate_multiples_of, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, common_multiple_sequence, q_step_1, locate_least_common_multiple, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, common_multiple_sequence, q_step_2, retain_lcm_as_composite_iteration_unit, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, common_multiple_sequence, q_step_3, iterate_common_multiple_generator, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, commute_factors_preserve_product, q_start, compare_factor_orders, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_1, compute_original_product, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_2, commute_factors, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_3, compute_commuted_product, q_step_4, provenance(observed(contract_example))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_4, preserve_product_under_commutation, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, commute_factors_preserve_product, q_start, compare_factor_orders, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_1, compute_original_product, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_2, commute_factors, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_3, compute_commuted_product, q_step_4, provenance(observed(derived_template))).
automaton_transition(multiplication, commute_factors_preserve_product, q_step_4, preserve_product_under_commutation, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, coordinate_groups_items, q_start, form_equal_groups, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, coordinate_groups_items, q_step_1, coordinate_group_count_with_item_count, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, coordinate_groups_items, q_step_2, iterate_composite_unit, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, coordinate_groups_items, q_step_3, name_total_items, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, coordinate_groups_items, q_start, form_equal_groups, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, coordinate_groups_items, q_step_1, coordinate_group_count_with_item_count, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, coordinate_groups_items, q_step_2, iterate_composite_unit, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, coordinate_groups_items, q_step_3, name_total_items, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, distribute_group_size_split, q_start, split_group_size, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, distribute_group_size_split, q_step_1, compute_partial_product, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, distribute_group_size_split, q_step_2, compute_partial_product, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, distribute_group_size_split, q_step_3, recompose_partial_products, q_step_4, provenance(observed(contract_example))).
automaton_transition(multiplication, distribute_group_size_split, q_step_4, preserve_distributed_groups, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, distribute_group_size_split, q_start, split_group_size, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, distribute_group_size_split, q_step_1, compute_partial_product, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, distribute_group_size_split, q_step_2, compute_partial_product, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, distribute_group_size_split, q_step_3, recompose_partial_products, q_step_4, provenance(observed(derived_template))).
automaton_transition(multiplication, distribute_group_size_split, q_step_4, preserve_distributed_groups, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, factors_of_first_number_only, q_start, enumerate_positive_divisors, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_1, omit_divisor_search_for, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_2, omit_factor_set_intersection, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_3, report_first_factor_set_as_common, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, factors_of_first_number_only, q_start, enumerate_positive_divisors, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_1, omit_divisor_search_for, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_2, omit_factor_set_intersection, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, factors_of_first_number_only, q_step_3, report_first_factor_set_as_common, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, multiplication_fact_retrieval, q_start, recognize_factor_pair, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_1, retrieve_known_multiplication_fact, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_2, bind_product_to_factor_pair, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_3, preserve_referent_units_for_product, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, multiplication_fact_retrieval, q_start, recognize_factor_pair, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_1, retrieve_known_multiplication_fact, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_2, bind_product_to_factor_pair, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, multiplication_fact_retrieval, q_step_3, preserve_referent_units_for_product, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, regroup_to_base_preserving_total, q_start, form_equal_groups, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_1, regroup_total_as_base_bundles, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_2, preserve_leftover_after_regrouping, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_3, name_total_from_bundles_and_leftover, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, regroup_to_base_preserving_total, q_start, form_equal_groups, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_1, regroup_total_as_base_bundles, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_2, preserve_leftover_after_regrouping, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, regroup_to_base_preserving_total, q_step_3, name_total_from_bundles_and_leftover, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, repeat_equal_groups, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_equal_groups, q_step_1, hold_number_of_groups_as_iterations, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_equal_groups, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_equal_groups, q_step_3, name_accumulated_total, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, repeat_equal_groups, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_equal_groups, q_step_1, hold_number_of_groups_as_iterations, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_equal_groups, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_equal_groups, q_step_3, name_accumulated_total, q_accept, provenance(observed(derived_template))).

automaton_transition(multiplication, repeat_group_size_by_itself, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_1, use_group_size_as_iteration_count, q_step_2, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(observed(contract_example))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_3, lose_group_count_role, q_accept, provenance(observed(contract_example))).

automaton_transition(multiplication, repeat_group_size_by_itself, q_start, hold_group_size_as_repeated_addend, q_step_1, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_1, use_group_size_as_iteration_count, q_step_2, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_2, add_equal_group_repeatedly, q_step_3, provenance(observed(derived_template))).
automaton_transition(multiplication, repeat_group_size_by_itself, q_step_3, lose_group_count_role, q_accept, provenance(observed(derived_template))).
