/** <module> Execution-verified JSON inputs for action automata
 *
 * Each row is admitted after the Hermes worker's strategy_trace seam returns
 * ok:true for its concrete JSON example.  The registry signature remains the
 * broad type declaration; these facts record runnable JSON at the boundary.
 */
%
% Separating examples (2026-08-03). Five deformation kinds carried
% examples on which the deformation's result equals the true answer, so
% the example could not witness the bug it models (audit:
% scripts/checks/audit_purported_validity.pl; coincidence data:
% knowledge/strategies/deformation_coincidence.pl). Their examples were
% replaced with separating inputs -- division/stop_after_first_partial_quotient,
% fraction/add_numerator_denominator_comparison,
% fraction/area_model_unequal_partition_piece_count,
% fraction/set_model_subset_size_focus, decimal/decimal_scale_loss_comparison --
% and every row below was re-run through the worker's strategy_trace
% seam on that date.
:- module(automaton_input_contracts,
          [ automaton_input_contract/5,
            automaton_observed_input_contract/3
          ]).

automaton_input_contract(addition, base_ones_chunking, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, column_addition_with_carrying, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_all_instead_of_known_fact, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_all_when_count_on_available, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_on_from_larger, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, known_fact_retrieval, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_base_transfer, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_ten_drop_leftover, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_ten_split_leftover, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, round_then_adjust, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, round_without_adjusting, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_add_unaligned_numerals, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_addition_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_comparison_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_fraction_place_value_comparison, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_multiplication_rule, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_numeral_comparison_without_scale_alignment, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_point_rule_misapplication, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_scale_loss_comparison, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":3,\"scale\":10},\"right\":{\"numeral\":25,\"scale\":100}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_subtract_unaligned_numerals, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_subtraction_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_whole_number_reading, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":347,\"b\":100}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, ecuadorian_decimal_long_division, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"positive_integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":45,\"scale\":10},\"right\":{\"numeral\":15,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, positional_decimal_reading, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":347,\"b\":100}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, recalled_result_scaling, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"positive_integer\",\"scale\":1},\"right\":{\"numeral\":\"positive_integer\",\"scale\":1}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":600,\"scale\":1},\"right\":{\"numeral\":5,\"scale\":1}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, change_decimal_place_name_without_regrouping, '{\"kind\":\"decimal_unit_conversion\",\"count\":\"integer\",\"from_scale\":\"positive_integer\",\"to_scale\":\"positive_integer\"}', '{\"kind\":\"decimal_unit_conversion\",\"count\":7,\"from_scale\":10,\"to_scale\":100}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_place_unit_regrouping, '{\"kind\":\"decimal_unit_conversion\",\"count\":\"integer\",\"from_scale\":\"positive_integer\",\"to_scale\":\"positive_integer\"}', '{\"kind\":\"decimal_unit_conversion\",\"count\":7,\"from_scale\":10,\"to_scale\":100}', verified(strategy_trace_ok)).
automaton_input_contract(division, fair_share_equal_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, divide_larger_by_smaller, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":15,\"b\":100}', verified(strategy_trace_ok)).
automaton_input_contract(division, long_division, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, measure_groups_of_size, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, missing_factor_repeated_addition, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, name_group_count_as_share_size, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, name_reached_total_as_quotient, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, partial_quotient_chunking, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, share_into_divisor_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, stop_after_first_partial_quotient, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":96,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, add_numerator_denominator_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":2,\"d\":3},\"right\":{\"n\":3,\"d\":8}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_part_of_part, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_unequal_partition_piece_count, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":2,\"d\":3},\"right\":{\"n\":3,\"d\":8}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, benchmark_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, co_denominator_count_on_from_larger, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":47,\"d\":100},\"right\":{\"n\":28,\"d\":100}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, co_denominator_make_base_transfer, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":47,\"d\":100},\"right\":{\"n\":28,\"d\":100}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, co_denominator_make_ten_split_leftover, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":7,\"d\":10},\"right\":{\"n\":8,\"d\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, common_unit_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, gap_thinking_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, improper_fraction_chain_loss, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, measurement_division, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, number_line_count_marks_not_intervals, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, number_line_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, reversible_measurement_division, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, set_model_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, set_model_subset_size_focus, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":2,\"d\":3},\"right\":{\"n\":3,\"d\":8}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, unit_fraction_iteration, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, unit_fraction_denominator_product_rule, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":1,\"d\":3},\"right\":{\"n\":1,\"d\":4}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, unit_fraction_partition, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":1,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, area_as_perimeter_count, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_area_unit_iteration, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, area_unit_covering, '{\"kind\":\"covered_cells\",\"cells\":[{\"x\":\"integer\",\"y\":\"integer\"}],\"unit\":\"atom\"}', '{\"kind\":\"covered_cells\",\"cells\":[{\"x\":0,\"y\":0},{\"x\":1,\"y\":0},{\"x\":0,\"y\":1}],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, area_unit_scale_selection, '{\"kind\":\"area_unit_candidates\",\"extent\":\"atom\",\"candidates\":[{\"unit\":\"atom\",\"extent\":\"atom\"}]}', '{\"kind\":\"area_unit_candidates\",\"extent\":\"medium\",\"candidates\":[{\"unit\":\"square_inch\",\"extent\":\"small\"},{\"unit\":\"square_foot\",\"extent\":\"medium\"},{\"unit\":\"square_meter\",\"extent\":\"large\"}]}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, choose_first_area_unit_without_scale, '{\"kind\":\"area_unit_candidates\",\"extent\":\"atom\",\"candidates\":[{\"unit\":\"atom\",\"extent\":\"atom\"}]}', '{\"kind\":\"area_unit_candidates\",\"extent\":\"medium\",\"candidates\":[{\"unit\":\"square_inch\",\"extent\":\"small\"},{\"unit\":\"square_foot\",\"extent\":\"medium\"},{\"unit\":\"square_meter\",\"extent\":\"large\"}]}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, count_overlapping_area_tiles, '{\"kind\":\"placed_tiles\",\"cells\":[{\"x\":\"integer\",\"y\":\"integer\"}],\"unit\":\"atom\"}', '{\"kind\":\"placed_tiles\",\"cells\":[{\"x\":0,\"y\":0},{\"x\":1,\"y\":0},{\"x\":0,\"y\":0}],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, ignore_perimeter_rectangle_constraint, '{\"kind\":\"rectangle_constraints\",\"area\":\"positive_integer\",\"perimeter\":\"positive_integer\"}', '{\"kind\":\"rectangle_constraints\",\"area\":24,\"perimeter\":22}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, ignore_symmetry_multiplicity, '{\"kind\":\"symmetry_side_orbits\",\"known_orbits\":[{\"copies\":\"positive_integer\",\"length\":\"positive_integer\"}],\"unknown_orbit\":{\"copies\":\"positive_integer\",\"name\":\"atom\"},\"perimeter\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"symmetry_side_orbits\",\"known_orbits\":[{\"copies\":2,\"length\":5}],\"unknown_orbit\":{\"copies\":2,\"name\":\"slanted_side\"},\"perimeter\":26,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, omit_unlabeled_boundary_side, '{\"kind\":\"polygon_sides_with_unit\",\"sides\":[\"positive_number\"],\"unit\":\"atom\"}', '{\"kind\":\"polygon_sides_with_unit\",\"sides\":[5,7,4,6],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, perimeter_two_sides_only, '{\"kind\":\"rectangle_with_unit\",\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"rectangle_with_unit\",\"length\":7,\"width\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, perimeter_uses_area_formula, '{\"kind\":\"rectangle_with_unit\",\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"rectangle_with_unit\",\"length\":7,\"width\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, polygon_perimeter_boundary_accumulation, '{\"kind\":\"polygon_sides_with_unit\",\"sides\":[\"positive_number\"],\"unit\":\"atom\"}', '{\"kind\":\"polygon_sides_with_unit\",\"sides\":[5,7,4,6],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_area_perimeter_constraint_search, '{\"kind\":\"rectangle_constraints\",\"area\":\"positive_integer\",\"perimeter\":\"positive_integer\"}', '{\"kind\":\"rectangle_constraints\",\"area\":24,\"perimeter\":22}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_factor_pair_search, '{\"kind\":\"area_scope\",\"area\":\"positive_integer\",\"scope\":\"atom\"}', '{\"kind\":\"area_scope\",\"area\":24,\"scope\":\"all\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_missing_side_from_area, '{\"kind\":\"area_known_side\",\"area\":\"positive_integer\",\"known_side\":\"positive_integer\"}', '{\"kind\":\"area_known_side\",\"area\":28,\"known_side\":4}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_missing_side_from_perimeter, '{\"kind\":\"perimeter_known_side\",\"perimeter\":\"positive_integer\",\"known_side\":\"positive_integer\"}', '{\"kind\":\"perimeter_known_side\",\"perimeter\":22,\"known_side\":4}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_perimeter_boundary_traversal, '{\"kind\":\"rectangle_with_unit\",\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"rectangle_with_unit\",\"length\":7,\"width\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_perimeter_side_pair_search, '{\"kind\":\"perimeter_scope\",\"perimeter\":\"positive_integer\",\"scope\":\"atom\"}', '{\"kind\":\"perimeter_scope\",\"perimeter\":22,\"scope\":\"all\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, subtract_side_from_area, '{\"kind\":\"area_known_side\",\"area\":\"positive_integer\",\"known_side\":\"positive_integer\"}', '{\"kind\":\"area_known_side\",\"area\":28,\"known_side\":4}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, symmetry_constrained_side_reconstruction, '{\"kind\":\"symmetry_side_orbits\",\"known_orbits\":[{\"copies\":\"positive_integer\",\"length\":\"positive_integer\"}],\"unknown_orbit\":{\"copies\":\"positive_integer\",\"name\":\"atom\"},\"perimeter\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"symmetry_side_orbits\",\"known_orbits\":[{\"copies\":2,\"length\":5}],\"unknown_orbit\":{\"copies\":2,\"name\":\"slanted_side\"},\"perimeter\":26,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, compare_solid_volume_by_cube_count, '{\"kind\":\"solid_volume_comparison\",\"count_a\":\"positive_integer\",\"count_b\":\"positive_integer\",\"extent_a\":\"positive_number\",\"extent_b\":\"positive_number\"}', '{\"kind\":\"solid_volume_comparison\",\"count_a\":12,\"count_b\":10,\"extent_a\":5,\"extent_b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, compare_solid_volume_by_visible_extent, '{\"kind\":\"solid_volume_comparison\",\"count_a\":\"positive_integer\",\"count_b\":\"positive_integer\",\"extent_a\":\"positive_number\",\"extent_b\":\"positive_number\"}', '{\"kind\":\"solid_volume_comparison\",\"count_a\":12,\"count_b\":10,\"extent_a\":5,\"extent_b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, composite_prism_volume_sum, '{\"kind\":\"disjoint_prisms\",\"prisms\":[{\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"height\":\"positive_integer\"}],\"unit\":\"atom\"}', '{\"kind\":\"disjoint_prisms\",\"prisms\":[{\"length\":2,\"width\":3,\"height\":4},{\"length\":1,\"width\":2,\"height\":5}],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, divide_volume_by_one_dimension, '{\"kind\":\"volume_known_base\",\"volume\":\"positive_integer\",\"length\":\"positive_integer\",\"width\":\"positive_integer\"}', '{\"kind\":\"volume_known_base\",\"volume\":60,\"length\":4,\"width\":3}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, polyhedron_surface_area_from_net, '{\"kind\":\"solid_net\",\"solid\":\"atom\",\"face_areas\":[\"positive_integer\"],\"unit\":\"atom\"}', '{\"kind\":\"solid_net\",\"solid\":\"cube\",\"face_areas\":[12,12,8,8,6,6],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangular_prism_missing_dimension_from_volume, '{\"kind\":\"volume_known_base\",\"volume\":\"positive_integer\",\"length\":\"positive_integer\",\"width\":\"positive_integer\"}', '{\"kind\":\"volume_known_base\",\"volume\":60,\"length\":4,\"width\":3}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangular_prism_volume_layer_iteration, '{\"kind\":\"rectangular_prism\",\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"height\":\"positive_integer\"}', '{\"kind\":\"rectangular_prism\",\"length\":4,\"width\":3,\"height\":5}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, sum_overlapping_prism_volumes, '{\"kind\":\"overlapping_prisms\",\"prisms\":[{\"length\":\"positive_integer\",\"width\":\"positive_integer\",\"height\":\"positive_integer\"}],\"overlap_volume\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"overlapping_prisms\",\"prisms\":[{\"length\":2,\"width\":3,\"height\":4},{\"length\":1,\"width\":2,\"height\":5}],\"overlap_volume\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, visible_faces_only_surface_area, '{\"kind\":\"solid_net\",\"solid\":\"atom\",\"face_areas\":[\"positive_integer\"],\"unit\":\"atom\"}', '{\"kind\":\"solid_net\",\"solid\":\"cube\",\"face_areas\":[12,12,8,8,6,6],\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, angle_additive_composition, '{\"kind\":\"angle_parts\",\"parts\":[\"positive_integer\"],\"whole\":\"positive_integer\"}', '{\"kind\":\"angle_parts\",\"parts\":[35,50,45],\"whole\":130}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, angle_as_ray_length, '{\"kind\":\"angle_measure\",\"degrees\":\"positive_integer\"}', '{\"kind\":\"angle_measure\",\"degrees\":65}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, angle_turn_measurement, '{\"kind\":\"angle_measure\",\"degrees\":\"positive_integer\"}', '{\"kind\":\"angle_measure\",\"degrees\":65}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, area_preserving_polygon_decomposition, '{\"kind\":\"polygon_partition\",\"vertices\":[{\"x\":\"integer\",\"y\":\"integer\"}],\"pieces\":[[{\"x\":\"integer\",\"y\":\"integer\"}]],\"certification\":\"atom\"}', '{\"kind\":\"polygon_partition\",\"vertices\":[{\"x\":0,\"y\":0},{\"x\":6,\"y\":0},{\"x\":6,\"y\":4},{\"x\":0,\"y\":4}],\"pieces\":[[{\"x\":0,\"y\":0},{\"x\":6,\"y\":0},{\"x\":6,\"y\":4}],[{\"x\":0,\"y\":0},{\"x\":6,\"y\":4},{\"x\":0,\"y\":4}]],\"certification\":\"certified\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, axis_aligned_coordinate_distance, '{\"kind\":\"coordinate_point_pair\",\"first\":{\"x\":\"number\",\"y\":\"number\"},\"second\":{\"x\":\"number\",\"y\":\"number\"},\"unit\":\"atom\"}', '{\"kind\":\"coordinate_point_pair\",\"first\":{\"x\":7,\"y\":3},\"second\":{\"x\":2,\"y\":3},\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, decomposition_with_gap_or_overlap, '{\"kind\":\"polygon_partition\",\"vertices\":[{\"x\":\"integer\",\"y\":\"integer\"}],\"pieces\":[[{\"x\":\"integer\",\"y\":\"integer\"}]],\"certification\":\"atom\"}', '{\"kind\":\"polygon_partition\",\"vertices\":[{\"x\":0,\"y\":0},{\"x\":6,\"y\":0},{\"x\":6,\"y\":4},{\"x\":0,\"y\":4}],\"pieces\":[[{\"x\":0,\"y\":0},{\"x\":6,\"y\":0},{\"x\":6,\"y\":4}]],\"certification\":\"unchecked\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, dimensional_measure_unit_coordination, '{\"kind\":\"dimensional_measure\",\"dimension\":\"atom\",\"value\":\"number\",\"unit\":\"atom\"}', '{\"kind\":\"dimensional_measure\",\"dimension\":\"two_dimensional\",\"value\":28,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, directed_difference_as_coordinate_distance, '{\"kind\":\"coordinate_point_pair\",\"first\":{\"x\":\"number\",\"y\":\"number\"},\"second\":{\"x\":\"number\",\"y\":\"number\"},\"unit\":\"atom\"}', '{\"kind\":\"coordinate_point_pair\",\"first\":{\"x\":7,\"y\":3},\"second\":{\"x\":2,\"y\":3},\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, linear_unit_for_area_or_volume, '{\"kind\":\"dimensional_measure\",\"dimension\":\"atom\",\"value\":\"number\",\"unit\":\"atom\"}', '{\"kind\":\"dimensional_measure\",\"dimension\":\"two_dimensional\",\"value\":28,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, omit_half_in_triangle_area, '{\"kind\":\"triangle_with_unit\",\"base\":\"positive_integer\",\"height\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"triangle_with_unit\",\"base\":7,\"height\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, ordered_pair_coordinate_plot, '{\"kind\":\"coordinate_points\",\"points\":[{\"x\":\"number\",\"y\":\"number\"}]}', '{\"kind\":\"coordinate_points\",\"points\":[{\"x\":-3,\"y\":2},{\"x\":1,\"y\":4},{\"x\":5,\"y\":-1}]}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, orientation_bound_shape_classification, '{\"kind\":\"shape_attributes\",\"shape\":\"atom\",\"attributes\":[{\"name\":\"atom\",\"value\":\"integer\"}],\"quarter_turns\":\"integer\"}', '{\"kind\":\"shape_attributes\",\"shape\":\"square\",\"attributes\":[{\"name\":\"straight_sides\",\"value\":4},{\"name\":\"vertices\",\"value\":4},{\"name\":\"right_angles\",\"value\":4},{\"name\":\"equal_sides\",\"value\":4}],\"quarter_turns\":1}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, parallelogram_area_base_height, '{\"kind\":\"parallelogram_with_unit\",\"base\":\"positive_integer\",\"height\":\"positive_integer\",\"slanted_side\":\"positive_integer\",\"offset\":\"integer\",\"unit\":\"atom\"}', '{\"kind\":\"parallelogram_with_unit\",\"base\":6,\"height\":4,\"slanted_side\":5,\"offset\":3,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rigid_shape_composition, '{\"kind\":\"rigid_shape_composition\",\"columns\":\"positive_integer\",\"rows\":\"positive_integer\",\"pieces\":[{\"id\":\"atom\",\"cells\":[{\"x\":\"integer\",\"y\":\"integer\"}]}]}', '{\"kind\":\"rigid_shape_composition\",\"columns\":3,\"rows\":2,\"pieces\":[{\"id\":\"top_row\",\"cells\":[{\"x\":0,\"y\":0},{\"x\":1,\"y\":0},{\"x\":2,\"y\":0}]},{\"id\":\"bottom_row\",\"cells\":[{\"x\":0,\"y\":1},{\"x\":1,\"y\":1},{\"x\":2,\"y\":1}]}]}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, shape_classification_by_defining_attributes, '{\"kind\":\"shape_attributes\",\"shape\":\"atom\",\"attributes\":[{\"name\":\"atom\",\"value\":\"integer\"}],\"quarter_turns\":\"integer\"}', '{\"kind\":\"shape_attributes\",\"shape\":\"square\",\"attributes\":[{\"name\":\"straight_sides\",\"value\":4},{\"name\":\"vertices\",\"value\":4},{\"name\":\"right_angles\",\"value\":4},{\"name\":\"equal_sides\",\"value\":4}],\"quarter_turns\":1}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, slanted_side_as_parallelogram_height, '{\"kind\":\"parallelogram_with_unit\",\"base\":\"positive_integer\",\"height\":\"positive_integer\",\"slanted_side\":\"positive_integer\",\"offset\":\"integer\",\"unit\":\"atom\"}', '{\"kind\":\"parallelogram_with_unit\",\"base\":6,\"height\":4,\"slanted_side\":5,\"offset\":3,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, triangle_area_half_base_height, '{\"kind\":\"triangle_with_unit\",\"base\":\"positive_integer\",\"height\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"triangle_with_unit\",\"base\":7,\"height\":4,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(integer, drop_sign_use_magnitude_sum, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":-7,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(integer, signed_addition_with_sign_relation, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(integer, inequality_as_boundary_point, '{\"kind\":\"inequality\",\"variable\":\"atom\",\"relation\":\"atom\",\"bound\":\"integer\"}', '{\"kind\":\"inequality\",\"variable\":\"x\",\"relation\":\"lt\",\"bound\":4}', verified(strategy_trace_ok)).
automaton_input_contract(integer, inequality_solution_set_representation, '{\"kind\":\"inequality\",\"variable\":\"atom\",\"relation\":\"atom\",\"bound\":\"integer\"}', '{\"kind\":\"inequality\",\"variable\":\"x\",\"relation\":\"lt\",\"bound\":4}', verified(strategy_trace_ok)).
automaton_input_contract(integer, order_by_magnitude_ignore_sign, '{\"kind\":\"signed_number_list\",\"values\":[\"integer\"]}', '{\"kind\":\"signed_number_list\",\"values\":[-7,3,-2,5]}', verified(strategy_trace_ok)).
automaton_input_contract(integer, signed_number_location_and_order, '{\"kind\":\"signed_number_list\",\"values\":[\"integer\"]}', '{\"kind\":\"signed_number_list\",\"values\":[-7,3,-2,5]}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, add_numbers_as_common_multiple, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, common_factor_intersection, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, common_multiple_sequence, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, commute_factors_preserve_product, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, coordinate_groups_items, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, distribute_group_size_split, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, factors_of_first_number_only, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, multiplication_fact_retrieval, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, regroup_to_base_preserving_total, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, repeat_equal_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, repeat_group_size_by_itself, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, additive_extension_of_ratio, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, scale_ratio_unit, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, construct_referent_ratio_diagram, '{\"kind\":\"referent_pair\",\"first\":{\"label\":\"atom\",\"count\":\"positive_integer\"},\"second\":{\"label\":\"atom\",\"count\":\"positive_integer\"}}', '{\"kind\":\"referent_pair\",\"first\":{\"label\":\"red_tiles\",\"count\":3},\"second\":{\"label\":\"blue_tiles\",\"count\":5}}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, reverse_ratio_referent_order, '{\"kind\":\"referent_pair\",\"first\":{\"label\":\"atom\",\"count\":\"positive_integer\"},\"second\":{\"label\":\"atom\",\"count\":\"positive_integer\"}}', '{\"kind\":\"referent_pair\",\"first\":{\"label\":\"red_tiles\",\"count\":3},\"second\":{\"label\":\"blue_tiles\",\"count\":5}}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, balance_preserving_linear_solution, '{\"kind\":\"linear_equation\",\"a\":\"integer\",\"b\":\"integer\",\"c\":\"integer\"}', '{\"kind\":\"linear_equation\",\"a\":3,\"b\":2,\"c\":20}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, contextual_linear_equation_construction, '{\"kind\":\"linear_context\",\"unknown\":\"atom\",\"coefficient\":\"number\",\"offset\":\"number\",\"total\":\"number\",\"referent_roles\":[\"atom\"]}', '{\"kind\":\"linear_context\",\"unknown\":\"x\",\"coefficient\":3,\"offset\":2,\"total\":20,\"referent_roles\":[\"groups\",\"loose_items\",\"total\"]}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, distributive_expression_rewrite, '{\"kind\":\"expression_rewrite\",\"expression\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":\"integer\"},\"right\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}}},\"direction\":\"atom\"}', '{\"kind\":\"expression_rewrite\",\"expression\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":3},\"right\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":4}}},\"direction\":\"expand\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, drop_distributed_term, '{\"kind\":\"expression_rewrite\",\"expression\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":\"integer\"},\"right\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}}},\"direction\":\"atom\"}', '{\"kind\":\"expression_rewrite\",\"expression\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":3},\"right\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":4}}},\"direction\":\"expand\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, equation_truth_by_substitution, '{\"kind\":\"equation_assignment\",\"left\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}},\"right\":{\"node\":\"int\",\"value\":\"integer\"},\"assignments\":[{\"variable\":\"atom\",\"value\":\"integer\"}]}', '{\"kind\":\"equation_assignment\",\"left\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":2}},\"right\":{\"node\":\"int\",\"value\":7},\"assignments\":[{\"variable\":\"x\",\"value\":5}]}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, exponent_as_multiplier, '{\"kind\":\"power_notation\",\"base\":{\"node\":\"int\",\"value\":\"integer\"},\"exponent\":\"integer\"}', '{\"kind\":\"power_notation\",\"base\":{\"node\":\"int\",\"value\":3},\"exponent\":4}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, exponent_as_repeated_factor, '{\"kind\":\"power_notation\",\"base\":{\"node\":\"int\",\"value\":\"integer\"},\"exponent\":\"integer\"}', '{\"kind\":\"power_notation\",\"base\":{\"node\":\"int\",\"value\":3},\"exponent\":4}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, exponential_equivalence_by_expansion, '{\"kind\":\"expression_pair\",\"left\":{\"node\":\"power\",\"base\":{\"node\":\"int\",\"value\":\"integer\"},\"exponent\":\"integer\"},\"right\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":\"integer\"},\"right\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":\"integer\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}}}}', '{\"kind\":\"expression_pair\",\"left\":{\"node\":\"power\",\"base\":{\"node\":\"int\",\"value\":2},\"exponent\":3},\"right\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":2},\"right\":{\"node\":\"mult\",\"left\":{\"node\":\"int\",\"value\":2},\"right\":{\"node\":\"int\",\"value\":2}}}}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, guess_and_check_rule, '{\"kind\":\"linear_pattern_empirical_rule\",\"first\":\"integer\",\"change\":\"integer\",\"row\":\"positive_integer\",\"multiplier\":\"integer\",\"constant\":\"integer\",\"checked_rows\":[\"integer\"]}', '{\"kind\":\"linear_pattern_empirical_rule\",\"first\":4,\"change\":3,\"row\":6,\"multiplier\":2,\"constant\":1,\"checked_rows\":[1,2,3]}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, linear_pattern_contextual_rule, '{\"kind\":\"linear_pattern_context\",\"first\":\"integer\",\"change\":\"integer\",\"row\":\"positive_integer\",\"context\":\"atom\"}', '{\"kind\":\"linear_pattern_context\",\"first\":4,\"change\":3,\"row\":6,\"context\":\"tile_pattern\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, one_sided_equation_operation, '{\"kind\":\"linear_equation\",\"a\":\"integer\",\"b\":\"integer\",\"c\":\"integer\"}', '{\"kind\":\"linear_equation\",\"a\":3,\"b\":2,\"c\":20}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, operational_equals_left_value, '{\"kind\":\"equation_assignment\",\"left\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}},\"right\":{\"node\":\"int\",\"value\":\"integer\"},\"assignments\":[{\"variable\":\"atom\",\"value\":\"integer\"}]}', '{\"kind\":\"equation_assignment\",\"left\":{\"node\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":2}},\"right\":{\"node\":\"int\",\"value\":7},\"assignments\":[{\"variable\":\"x\",\"value\":5}]}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, programming_expression_evaluation, '{\"kind\":\"expression_assignment\",\"expression\":{\"node\":\"add\",\"left\":{\"node\":\"mult\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"}},\"right\":{\"node\":\"int\",\"value\":\"integer\"}},\"assignments\":[{\"variable\":\"atom\",\"value\":\"integer\"}]}', '{\"kind\":\"expression_assignment\",\"expression\":{\"node\":\"add\",\"left\":{\"node\":\"mult\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":3}},\"right\":{\"node\":\"int\",\"value\":2}},\"assignments\":[{\"variable\":\"x\",\"value\":4}]}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, symbolic_expression_construction, '{\"kind\":\"quantity_relation\",\"operator\":\"atom\",\"left\":{\"node\":\"var\",\"name\":\"atom\"},\"right\":{\"node\":\"int\",\"value\":\"integer\"},\"referent_roles\":[\"atom\"],\"declared_variables\":[\"atom\"]}', '{\"kind\":\"quantity_relation\",\"operator\":\"add\",\"left\":{\"node\":\"var\",\"name\":\"x\"},\"right\":{\"node\":\"int\",\"value\":4},\"referent_roles\":[\"unknown_quantity\",\"constant_offset\"],\"declared_variables\":[\"x\"]}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, change_unit_label_without_scaling, '{\"kind\":\"quantity_conversion\",\"count\":\"integer\",\"from_unit\":\"atom\",\"to_unit\":\"atom\",\"factor\":\"positive_integer\"}', '{\"kind\":\"quantity_conversion\",\"count\":3,\"from_unit\":\"yard\",\"to_unit\":\"foot\",\"factor\":3}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, count_marks_not_intervals, '{\"kind\":\"measure_with_unit\",\"interval_count\":\"positive_integer\",\"subdivisions\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"measure_with_unit\",\"interval_count\":7,\"subdivisions\":4,\"unit\":\"inch\"}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, drop_unit_from_measured_quantity_change, '{\"kind\":\"measured_change\",\"operation\":\"atom\",\"a\":\"integer\",\"b\":\"integer\",\"unit\":\"atom\"}', '{\"kind\":\"measured_change\",\"operation\":\"add\",\"a\":7,\"b\":5,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, linear_unit_iteration, '{\"kind\":\"measure_with_unit\",\"interval_count\":\"positive_integer\",\"subdivisions\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"measure_with_unit\",\"interval_count\":7,\"subdivisions\":4,\"unit\":\"inch\"}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, liquid_volume_count_marks_not_intervals, '{\"kind\":\"measure_with_unit\",\"interval_count\":\"positive_integer\",\"subdivisions\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"measure_with_unit\",\"interval_count\":5,\"subdivisions\":4,\"unit\":\"liter\"}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, liquid_volume_scale_reading, '{\"kind\":\"measure_with_unit\",\"interval_count\":\"positive_integer\",\"subdivisions\":\"positive_integer\",\"unit\":\"atom\"}', '{\"kind\":\"measure_with_unit\",\"interval_count\":5,\"subdivisions\":4,\"unit\":\"liter\"}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, unit_conversion_by_iteration, '{\"kind\":\"quantity_conversion\",\"count\":\"integer\",\"from_unit\":\"atom\",\"to_unit\":\"atom\",\"factor\":\"positive_integer\"}', '{\"kind\":\"quantity_conversion\",\"count\":3,\"from_unit\":\"yard\",\"to_unit\":\"foot\",\"factor\":3}', verified(strategy_trace_ok)).
automaton_input_contract(measurement, unit_preserving_measured_quantity_change, '{\"kind\":\"measured_change\",\"operation\":\"atom\",\"a\":\"integer\",\"b\":\"integer\",\"unit\":\"atom\"}', '{\"kind\":\"measured_change\",\"operation\":\"add\",\"a\":7,\"b\":5,\"unit\":\"centimeter\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, box_plot_from_five_number_summary, '{\"kind\":\"box_plot_data\",\"values\":[\"integer\"],\"display\":\"box_plot\"}', '{\"kind\":\"box_plot_data\",\"values\":[2,4,5,7,9],\"display\":\"box_plot\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, categorical_frequency_bar_representation, '{\"kind\":\"categorical_frequencies\",\"pairs\":[{\"category\":\"atom\",\"count\":\"integer\"}],\"display\":\"bar_chart\"}', '{\"kind\":\"categorical_frequencies\",\"pairs\":[{\"category\":\"red\",\"count\":4},{\"category\":\"blue\",\"count\":6}],\"display\":\"bar_chart\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, distribution_summary_selection, '{\"kind\":\"distribution_data\",\"values\":[\"integer\"],\"profile\":\"atom\"}', '{\"kind\":\"distribution_data\",\"values\":[2,4,6,8],\"profile\":\"symmetric_without_outliers\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, dot_plot_frequency_representation, '{\"kind\":\"numeric_data_display\",\"values\":[\"integer\"],\"display\":\"dot_plot\"}', '{\"kind\":\"numeric_data_display\",\"values\":[2,3,3,5],\"display\":\"dot_plot\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, five_number_summary_and_iqr, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,5,7,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, histogram_equal_interval_representation, '{\"kind\":\"histogram_data\",\"values\":[\"integer\"],\"bin_width\":\"positive_integer\"}', '{\"kind\":\"histogram_data\",\"values\":[2,3,5,7,8,9],\"bin_width\":2}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, mean_absolute_deviation, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,4,6,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, mean_as_balance_point, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,4,6,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, mean_as_fair_share, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,4,6,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, mean_deviation_without_absolute_value, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,4,6,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, median_as_ordered_middle, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,4,5,7,9],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, mode_as_maximal_frequency, '{\"kind\":\"numeric_data_with_unit\",\"values\":[\"integer\"],\"unit\":\"atom\"}', '{\"kind\":\"numeric_data_with_unit\",\"values\":[2,3,3,5,7],\"unit\":\"minutes\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, question_without_variability, '{\"kind\":\"statistical_question\",\"variable\":\"atom\",\"population\":\"atom\"}', '{\"kind\":\"statistical_question\",\"variable\":\"commute_time\",\"population\":\"students\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, statistical_question_variability_classification, '{\"kind\":\"statistical_question\",\"variable\":\"atom\",\"population\":\"atom\"}', '{\"kind\":\"statistical_question\",\"variable\":\"commute_time\",\"population\":\"students\"}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, add_instead_of_subtract_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, answer_as_endpoint_count_up, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, compare_by_matching_difference, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, count_up_missing_addend, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, decompose_base_for_ones, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, smaller_from_larger_in_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, take_away_base_ones, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).

automaton_input_contract(addition, append_column_sum_without_carrying, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, derived_fact_adjustment, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":8,\"b\":6}', verified(strategy_trace_ok)).
automaton_input_contract(addition, drop_carry_to_next_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, dropped_ones_chunk, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, rote_derived_fact_rule_misfire, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":8,\"b\":6}', verified(strategy_trace_ok)).
automaton_input_contract(addition, unbalanced_make_base_compensation, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, wrong_carry_amount_to_next_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, borrow_across_zero_cascade, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":102,\"b\":7}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, borrow_across_zero_no_cascade, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":102,\"b\":7}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, borrow_without_reducing_bases, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":53,\"b\":27}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, compare_returns_larger_count, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":9,\"b\":5}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, drop_ones_after_base_takeaway, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":53,\"b\":27}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, slide_subtrahend_only, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":53,\"b\":27}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, sliding_constant_difference, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":53,\"b\":27}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, add_counts_without_composite_unit, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, add_instead_of_multiply, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, context_free_fact_family_guess, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, drop_regrouping_remainder, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, drop_second_partial_product, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, known_product_adjustment, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, known_product_without_adjustment, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, rigid_factor_order_roles, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, sequential_recompute_commuted_products, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":7,\"b\":8}', verified(strategy_trace_ok)).
automaton_input_contract(division, inverse_fact_decomposition, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":47,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, missing_factor_known_product_search, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":48,\"b\":6}', verified(strategy_trace_ok)).
automaton_input_contract(division, reject_known_product_match, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":48,\"b\":6}', verified(strategy_trace_ok)).
automaton_input_contract(division, stop_after_one_known_fact, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":47,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, stop_at_nearby_product_in_search, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":48,\"b\":6}', verified(strategy_trace_ok)).
automaton_input_contract(division, sum_dividend_and_divisor, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":96,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, clear_inner_referent, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":3,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, cross_multiplication_rule_from_pattern, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":5}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, cross_multiplication_rule_without_ground, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":5}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, improper_fraction_iteration, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":7,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, iterate_given_overshoot, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":7,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, iterate_only_no_reverse, '{\"kind\":\"fraction_solve\",\"coefficient\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"},\"total\":\"positive_integer\"}', '{\"kind\":\"fraction_solve\",\"coefficient\":{\"n\":2,\"d\":3},\"total\":12}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, recursive_partition, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":3,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, solve_for_unit, '{\"kind\":\"fraction_solve\",\"coefficient\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"},\"total\":\"positive_integer\"}', '{\"kind\":\"fraction_solve\",\"coefficient\":{\"n\":2,\"d\":3},\"total\":12}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, splitting, '{\"a\":\"integer\",\"b\":\"positive_integer\"}', '{\"a\":1,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, whole_number_grab, '{\"a\":\"positive_integer\",\"b\":\"positive_integer\"}', '{\"a\":3,\"b\":4}', verified(strategy_trace_ok)).
automaton_input_contract(calculus, factor_cancel_substitute, '{\"kind\":\"rational_limit\",\"numerator\":{\"coefficients\":[\"integer\"]},\"denominator\":{\"coefficients\":[\"integer\"]},\"at\":\"integer\"}', '{\"kind\":\"rational_limit\",\"numerator\":{\"coefficients\":[-2,1,1]},\"denominator\":{\"coefficients\":[-1,1]},\"at\":1}', verified(strategy_trace_ok)).
automaton_input_contract(calculus, factor_cancel_without_common_factor, '{\"kind\":\"rational_limit\",\"numerator\":{\"coefficients\":[\"integer\"]},\"denominator\":{\"coefficients\":[\"integer\"]},\"at\":\"integer\"}', '{\"kind\":\"rational_limit\",\"numerator\":{\"coefficients\":[1,1]},\"denominator\":{\"coefficients\":[2,1]},\"at\":1}', verified(strategy_trace_ok)).
automaton_input_contract(calculus, direct_substitution, '{\"kind\":\"polynomial_limit\",\"coefficients\":[\"integer\"],\"at\":\"integer\"}', '{\"kind\":\"polynomial_limit\",\"coefficients\":[1,2,3],\"at\":2}', verified(strategy_trace_ok)).
automaton_input_contract(calculus, bounded_numerator_over_diverging_denominator, '{\"kind\":\"bounded_sequence_limit\",\"numerator\":\"atom\",\"bound\":\"positive_integer\",\"denominator\":\"atom\"}', '{\"kind\":\"bounded_sequence_limit\",\"numerator\":\"cosine_of_n_x\",\"bound\":1,\"denominator\":\"linear_in_n\"}', verified(strategy_trace_ok)).
automaton_input_contract(probability, equiprobable_endpoint_counting, '{\"kind\":\"terminal_path_tree\",\"paths\":[{\"winner\":\"atom\",\"probability\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"},\"events\":[\"atom\"]}],\"stake\":\"positive_number\"}', '{\"kind\":\"terminal_path_tree\",\"paths\":[{\"winner\":\"alice\",\"probability\":{\"n\":1,\"d\":2},\"events\":[\"alice_wins_first\"]},{\"winner\":\"bob\",\"probability\":{\"n\":1,\"d\":4},\"events\":[\"alice_wins_then_bob\",\"bob_wins\"]},{\"winner\":\"bob\",\"probability\":{\"n\":1,\"d\":4},\"events\":[\"bob_wins_then_bob\",\"bob_wins\"]}],\"stake\":60}', verified(strategy_trace_ok)).
automaton_input_contract(probability, terminal_tree_endpoint_probability_sum, '{\"kind\":\"terminal_path_tree\",\"paths\":[{\"winner\":\"atom\",\"probability\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"},\"events\":[\"atom\"]}],\"stake\":\"positive_number\"}', '{\"kind\":\"terminal_path_tree\",\"paths\":[{\"winner\":\"alice\",\"probability\":{\"n\":1,\"d\":2},\"events\":[\"alice_wins_first\"]},{\"winner\":\"bob\",\"probability\":{\"n\":1,\"d\":4},\"events\":[\"alice_wins_then_bob\",\"bob_wins\"]},{\"winner\":\"bob\",\"probability\":{\"n\":1,\"d\":4},\"events\":[\"bob_wins_then_bob\",\"bob_wins\"]}],\"stake\":60}', verified(strategy_trace_ok)).

% Fraction operands arrive as printed.  The published shape below is the
% fraction/fraction case ({"n","d"} per side, nonnegativity enforced by
% the machine's valid_fraction guard).  The runtime decoder also accepts
% {"whole","n","d"} (a mixed number) and {"whole"} (a whole number) per
% side; the checker's one-example-per-kind grammar has no union form, so
% those shapes are documented here and witnessed in the task-192 report
% rather than declared.  Subtraction's kind string names the
% minuend/subtrahend compound that keeps the two directions from ever
% routing into each other's machine.
automaton_input_contract(fraction, common_denominator_fraction_addition, '{\"kind\":\"fraction_addend_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_addend_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":7,\"d\":8}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, common_denominator_fraction_subtraction, '{\"kind\":\"fraction_minuend_subtrahend\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_minuend_subtrahend\",\"left\":{\"n\":2,\"d\":3},\"right\":{\"n\":1,\"d\":6}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, add_numerator_denominator_sum, '{\"kind\":\"fraction_addend_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_addend_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":7,\"d\":8}}', verified(strategy_trace_ok)).
% The eight counting rows entered in 2026-08-01. They were registered
% signatures with no contract because trace_inputs/3 had no decoder for the
% counting operand terms, so the seam handed each clause head bare integers
% and every run failed. The decoder landed with these rows.
automaton_input_contract(counting, enumerate_collection_one_to_one, '{\"base\":\"positive_integer\",\"count\":\"positive_integer\",\"kind\":\"cardinality\"}', '{\"base\":10,\"count\":5,\"kind\":\"cardinality\"}', verified(strategy_trace_ok)).
automaton_input_contract(counting, inscribe_cardinality, '{\"base\":\"positive_integer\",\"count\":\"positive_integer\",\"kind\":\"cardinality\"}', '{\"base\":10,\"count\":7,\"kind\":\"cardinality\"}', verified(strategy_trace_ok)).
automaton_input_contract(counting, recursive_place_value_inscription, '{\"base\":\"positive_integer\",\"count\":\"integer\",\"kind\":\"cardinality\"}', '{\"base\":10,\"count\":347,\"kind\":\"cardinality\"}', verified(strategy_trace_ok)).
automaton_input_contract(counting, omit_highest_place_regrouping, '{\"base\":\"positive_integer\",\"count\":\"integer\",\"kind\":\"cardinality\"}', '{\"base\":10,\"count\":263,\"kind\":\"cardinality\"}', verified(strategy_trace_ok)).
automaton_input_contract(counting, place_value_comparison, '{\"base\":\"positive_integer\",\"kind\":\"count_pair\",\"left\":\"integer\",\"right\":\"integer\"}', '{\"base\":10,\"kind\":\"count_pair\",\"left\":56,\"right\":26}', verified(strategy_trace_ok)).
automaton_input_contract(counting, compare_ones_digits_only, '{\"base\":\"positive_integer\",\"kind\":\"count_pair\",\"left\":\"integer\",\"right\":\"integer\"}', '{\"base\":10,\"kind\":\"count_pair\",\"left\":39,\"right\":41}', verified(strategy_trace_ok)).
automaton_input_contract(counting, compare_cardinalities_one_to_one, '{\"kind\":\"collection_pair\",\"left\":\"positive_integer\",\"left_extent\":\"positive_integer\",\"right\":\"positive_integer\",\"right_extent\":\"positive_integer\"}', '{\"kind\":\"collection_pair\",\"left\":5,\"left_extent\":5,\"right\":4,\"right_extent\":4}', verified(strategy_trace_ok)).
automaton_input_contract(counting, spatial_extent_as_cardinality, '{\"kind\":\"collection_pair\",\"left\":\"positive_integer\",\"left_extent\":\"positive_integer\",\"right\":\"positive_integer\",\"right_extent\":\"positive_integer\"}', '{\"kind\":\"collection_pair\",\"left\":4,\"left_extent\":9,\"right\":5,\"right_extent\":3}', verified(strategy_trace_ok)).

% The Grade 7 action-automaton wave entered on 2026-08-06 with role-bearing
% operands. These examples retain the lane reports' accepting-run values and
% were admitted only after the worker decoder returned a nonempty trace.
automaton_input_contract(integer, signed_subtraction_as_additive_inverse, '{\"kind\":\"signed_subtraction\",\"minuend\":\"integer\",\"subtrahend\":\"integer\"}', '{\"kind\":\"signed_subtraction\",\"minuend\":3,\"subtrahend\":5}', verified(strategy_trace_ok)).
automaton_input_contract(integer, swap_subtraction_operands_to_preserve_nonnegative_result, '{\"kind\":\"signed_subtraction\",\"minuend\":\"integer\",\"subtrahend\":\"integer\"}', '{\"kind\":\"signed_subtraction\",\"minuend\":3,\"subtrahend\":5}', verified(strategy_trace_ok)).
automaton_input_contract(integer, conflate_signed_difference_with_distance, '{\"kind\":\"signed_subtraction\",\"minuend\":\"integer\",\"subtrahend\":\"integer\"}', '{\"kind\":\"signed_subtraction\",\"minuend\":3,\"subtrahend\":5}', verified(strategy_trace_ok)).
automaton_input_contract(integer, signed_multiplication_by_sign_rule, '{\"kind\":\"signed_multiplication\",\"multiplier\":\"integer\",\"multiplicand\":\"integer\"}', '{\"kind\":\"signed_multiplication\",\"multiplier\":-5,\"multiplicand\":8}', verified(strategy_trace_ok)).
automaton_input_contract(integer, reverse_signed_multiplication_sign_rule, '{\"kind\":\"signed_multiplication\",\"multiplier\":\"integer\",\"multiplicand\":\"integer\"}', '{\"kind\":\"signed_multiplication\",\"multiplier\":-5,\"multiplicand\":8}', verified(strategy_trace_ok)).
automaton_input_contract(integer, signed_division_by_sign_rule, '{\"kind\":\"signed_division\",\"dividend\":\"integer\",\"divisor\":\"integer\"}', '{\"kind\":\"signed_division\",\"dividend\":-12,\"divisor\":3}', verified(strategy_trace_ok)).
automaton_input_contract(integer, reverse_signed_division_sign_rule, '{\"kind\":\"signed_division\",\"dividend\":\"integer\",\"divisor\":\"integer\"}', '{\"kind\":\"signed_division\",\"dividend\":-12,\"divisor\":3}', verified(strategy_trace_ok)).

automaton_input_contract(ratio, compute_unit_rate_from_ratio_pair, '{\"kind\":\"ratio_pair_unit_rate\",\"first\":\"positive_number\",\"second\":\"positive_number\",\"referent\":\"atom\"}', '{\"kind\":\"ratio_pair_unit_rate\",\"first\":2,\"second\":6,\"referent\":\"first_per_second\"}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, divide_larger_by_smaller_for_unit_rate, '{\"kind\":\"ratio_pair_unit_rate\",\"first\":\"positive_number\",\"second\":\"positive_number\",\"referent\":\"atom\"}', '{\"kind\":\"ratio_pair_unit_rate\",\"first\":2,\"second\":6,\"referent\":\"first_per_second\"}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, test_relation_for_proportionality, '{\"kind\":\"ratio_pairs_proportionality_test\",\"pairs\":[{\"first\":\"positive_number\",\"second\":\"positive_number\"}],\"test\":\"proportionality_test\"}', '{\"kind\":\"ratio_pairs_proportionality_test\",\"pairs\":[{\"first\":1,\"second\":3},{\"first\":2,\"second\":6},{\"first\":4,\"second\":12}],\"test\":\"proportionality_test\"}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, inscribe_proportional_equation, '{\"kind\":\"ratio_pair_solve_at_x\",\"first\":\"positive_number\",\"second\":\"positive_number\",\"target_x\":\"number\"}', '{\"kind\":\"ratio_pair_solve_at_x\",\"first\":3,\"second\":12,\"target_x\":7}', verified(strategy_trace_ok)).

automaton_input_contract(geometry, circle_circumference_diameter_co_measurement, '{\"kind\":\"circle_co_measurement\",\"given_measure\":\"atom\",\"value\":\"positive_number\",\"unit\":\"atom\",\"requested_measure\":\"atom\",\"pi\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"circle_co_measurement\",\"given_measure\":\"diameter\",\"value\":10,\"unit\":\"cm\",\"requested_measure\":\"circumference\",\"pi\":{\"n\":22,\"d\":7}}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, use_diameter_as_radius_in_circumference, '{\"kind\":\"circle_co_measurement\",\"given_measure\":\"atom\",\"value\":\"positive_number\",\"unit\":\"atom\",\"requested_measure\":\"atom\",\"pi\":{\"n\":\"positive_integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"circle_co_measurement\",\"given_measure\":\"diameter\",\"value\":10,\"unit\":\"cm\",\"requested_measure\":\"circumference\",\"pi\":{\"n\":22,\"d\":7}}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, triangle_three_measure_determination, '{\"kind\":\"triangle_conditions\",\"condition\":\"atom\",\"measures\":[\"positive_number\"]}', '{\"kind\":\"triangle_conditions\",\"condition\":\"sss\",\"measures\":[3,4,5]}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, angle_relation_unknown_measure, '{\"kind\":\"angle_relation\",\"whole\":\"positive_number\",\"known_parts\":[\"positive_number\"],\"unknown\":\"atom\"}', '{\"kind\":\"angle_relation\",\"whole\":180,\"known_parts\":[110,30],\"unknown\":\"x\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, estimate_probability_from_observed_frequency, '{\"kind\":\"frequency_record\",\"event\":\"atom\",\"successes\":\"integer\",\"trials\":\"positive_integer\",\"context\":\"repeated_experiment\"}', '{\"kind\":\"frequency_record\",\"event\":\"win\",\"successes\":6,\"trials\":20,\"context\":\"repeated_experiment\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, finite_frequency_as_exact_probability, '{\"kind\":\"frequency_record\",\"event\":\"atom\",\"successes\":\"integer\",\"trials\":\"positive_integer\",\"context\":\"repeated_experiment\"}', '{\"kind\":\"frequency_record\",\"event\":\"win\",\"successes\":6,\"trials\":20,\"context\":\"repeated_experiment\"}', verified(strategy_trace_ok)).
automaton_input_contract(statistics, sample_population_distribution_judgment, '{\"kind\":\"sample_population_distribution\",\"sample\":{\"values\":[\"integer\"],\"shape\":\"atom\"},\"population\":{\"values\":[\"integer\"],\"shape\":\"atom\"},\"tolerances\":{\"center\":\"number\",\"spread\":\"number\"}}', '{\"kind\":\"sample_population_distribution\",\"sample\":{\"values\":[1,2,3,4,5],\"shape\":\"symmetric\"},\"population\":{\"values\":[1,2,3,4,5,6],\"shape\":\"symmetric\"},\"tolerances\":{\"center\":1,\"spread\":1}}', verified(strategy_trace_ok)).

automaton_input_contract(algebraic, translate_diagram_to_equation, '{\"kind\":\"diagram_relation\",\"representation\":\"atom\",\"groups\":\"positive_integer\",\"group_expression\":{\"node\":\"var\",\"name\":\"atom\"},\"additional\":\"number\",\"total\":\"number\",\"equation_form\":\"atom\"}', '{\"kind\":\"diagram_relation\",\"representation\":\"tape\",\"groups\":3,\"group_expression\":{\"node\":\"var\",\"name\":\"x\"},\"additional\":5,\"total\":50,\"equation_form\":\"px_plus_q_equals_r\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, split_repeated_diagram_variable, '{\"kind\":\"diagram_relation\",\"representation\":\"atom\",\"groups\":\"positive_integer\",\"group_expression\":{\"node\":\"var\",\"name\":\"atom\"},\"additional\":\"number\",\"total\":\"number\",\"equation_form\":\"atom\"}', '{\"kind\":\"diagram_relation\",\"representation\":\"tape\",\"groups\":3,\"group_expression\":{\"node\":\"var\",\"name\":\"x\"},\"additional\":5,\"total\":50,\"equation_form\":\"px_plus_q_equals_r\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, percent_change_composition, '{\"kind\":\"percent_change\",\"amount_role\":\"atom\",\"amount\":\"number\",\"rate_percent\":\"number\",\"direction\":\"atom\",\"target\":\"atom\"}', '{\"kind\":\"percent_change\",\"amount_role\":\"original_amount\",\"amount\":18.5,\"rate_percent\":20,\"direction\":\"increase\",\"target\":\"new_amount\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, combine_signed_like_terms, '{\"kind\":\"signed_linear_expression\",\"variable_terms\":[{\"operation\":\"atom\",\"coefficient\":\"number\",\"variable\":\"atom\"}],\"constant_terms\":[{\"operation\":\"atom\",\"value\":\"number\"}],\"direction\":\"combine_like_terms\"}', '{\"kind\":\"signed_linear_expression\",\"variable_terms\":[{\"operation\":\"add\",\"coefficient\":7,\"variable\":\"x\"},{\"operation\":\"subtract\",\"coefficient\":2,\"variable\":\"x\"}],\"constant_terms\":[{\"operation\":\"add\",\"value\":8},{\"operation\":\"subtract\",\"value\":3}],\"direction\":\"combine_like_terms\"}', verified(strategy_trace_ok)).
automaton_input_contract(algebraic, combine_unlike_terms, '{\"kind\":\"signed_linear_expression\",\"variable_terms\":[{\"operation\":\"atom\",\"coefficient\":\"number\",\"variable\":\"atom\"}],\"constant_terms\":[{\"operation\":\"atom\",\"value\":\"number\"}],\"direction\":\"combine_like_terms\"}', '{\"kind\":\"signed_linear_expression\",\"variable_terms\":[{\"operation\":\"add\",\"coefficient\":7,\"variable\":\"x\"},{\"operation\":\"subtract\",\"coefficient\":2,\"variable\":\"x\"}],\"constant_terms\":[{\"operation\":\"add\",\"value\":8}],\"direction\":\"combine_like_terms\"}', verified(strategy_trace_ok)).

% A marked contract has a live strategy_trace witness represented in the
% generated transition table. It does not change the public contract shape.
automaton_observed_input_contract(fraction, unit_fraction_partition,
                                  strategy_trace_ok).
