/** <module> Execution-verified JSON inputs for action automata
 *
 * Each row is admitted after the Hermes worker's strategy_trace seam returns
 * ok:true for its concrete JSON example.  The registry signature remains the
 * broad type declaration; these facts record runnable JSON at the boundary.
 */
:- module(automaton_input_contracts, [automaton_input_contract/5]).

automaton_input_contract(addition, base_ones_chunking, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, column_addition_with_carrying, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_all_instead_of_known_fact, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_all_when_count_on_available, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, count_on_from_larger, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, known_fact_retrieval, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_base_transfer, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_ten_drop_leftover, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, make_ten_split_leftover, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, round_then_adjust, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(addition, round_without_adjusting, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_add_unaligned_numerals, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_addition_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_comparison_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_fraction_place_value_comparison, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_multiplication_rule, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_numeral_comparison_without_scale_alignment, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_point_rule_misapplication, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_scale_loss_comparison, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_subtract_unaligned_numerals, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(decimal, decimal_subtraction_by_aligned_units, '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"},\"right\":{\"numeral\":\"integer\",\"scale\":\"positive_integer\"}}', '{\"kind\":\"decimal_pair\",\"left\":{\"numeral\":25,\"scale\":10},\"right\":{\"numeral\":3,\"scale\":10}}', verified(strategy_trace_ok)).
automaton_input_contract(division, fair_share_equal_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, long_division, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, measure_groups_of_size, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, missing_factor_repeated_addition, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, name_group_count_as_share_size, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, name_reached_total_as_quotient, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(division, partial_quotient_chunking, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, share_into_divisor_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(division, stop_after_first_partial_quotient, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, add_numerator_denominator_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_part_of_part, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, area_model_unequal_partition_piece_count, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, benchmark_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, common_unit_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, gap_thinking_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, improper_fraction_chain_loss, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, measurement_division, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, number_line_count_marks_not_intervals, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, number_line_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, reversible_measurement_division, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, set_model_fraction_comparison, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, set_model_subset_size_focus, '{\"kind\":\"fraction_pair\",\"left\":{\"n\":\"integer\",\"d\":\"positive_integer\"},\"right\":{\"n\":\"integer\",\"d\":\"positive_integer\"}}', '{\"kind\":\"fraction_pair\",\"left\":{\"n\":3,\"d\":4},\"right\":{\"n\":2,\"d\":3}}', verified(strategy_trace_ok)).
automaton_input_contract(fraction, unit_fraction_iteration, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, area_as_perimeter_count, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(geometry, rectangle_area_unit_iteration, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(integer, signed_addition_with_sign_relation, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, add_numbers_as_common_multiple, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, common_factor_intersection, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, common_multiple_sequence, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, commute_factors_preserve_product, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, coordinate_groups_items, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, distribute_group_size_split, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, factors_of_first_number_only, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, multiplication_fact_retrieval, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, regroup_to_base_preserving_total, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":12,\"b\":3}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, repeat_equal_groups, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(multiplication, repeat_group_size_by_itself, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, additive_extension_of_ratio, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(ratio, scale_ratio_unit, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, add_instead_of_subtract_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, answer_as_endpoint_count_up, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, compare_by_matching_difference, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, count_up_missing_addend, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, decompose_base_for_ones, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, smaller_from_larger_in_column, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
automaton_input_contract(subtraction, take_away_base_ones, '{\"a\":\"integer\",\"b\":\"integer\"}', '{\"a\":47,\"b\":28}', verified(strategy_trace_ok)).
