:- module(fact_writer, [
    write_prolog_facts/1
]).

:- use_module(library(lists)).

%!  write_prolog_facts(+Path:atom) is det.
%
%   Emit a reconsultable Prolog file capturing the current analyzer state:
%   strategy_patterns/2, unclassified/2, uncovered_module/1, elaborates/7,
%   pattern_evidence/3.
write_prolog_facts(Path) :-
    automaton_analyzer:all_strategy_patterns(SPs),
    automaton_analyzer:all_unclassified(UCs),
    automaton_analyzer:all_uncovered(Uncov),
    automaton_analyzer:all_elaborations(Elabs),
    automaton_analyzer:all_pattern_evidence(PEs),
    setup_call_cleanup(
        open(Path, write, S),
        emit_all(S, SPs, UCs, Uncov, Elabs, PEs),
        close(S)
    ).

emit_all(S, SPs, UCs, Uncov, Elabs, PEs) :-
    format(S, "% docs/analysis/elaborations.pl~n", []),
    format(S, "% Generated by strategies/meta/automaton_analyzer.pl~n", []),
    get_time(T), format_time(string(Stamp), "%FT%T%z", T),
    format(S, "% Generated at: ~w~n~n", [Stamp]),
    format(S, ":- module(elaborations_output, []).~n~n", []),

    format(S, "%% --- strategy_patterns/2 ---~n", []),
    forall(member(sp(Name, Patterns), SPs),
           write_term_line(S, strategy_patterns(Name, Patterns))),
    nl(S),

    format(S, "%% --- unclassified/2 ---~n", []),
    ( UCs = [] ->
        format(S, "% (none)~n", [])
    ;
        forall(member(uc(N, R), UCs),
               write_term_line(S, unclassified(N, R)))
    ),
    nl(S),

    format(S, "%% --- uncovered_module/1 ---~n", []),
    ( Uncov = [] ->
        format(S, "% (none)~n", [])
    ;
        forall(member(P, Uncov),
               write_term_line(S, uncovered_module(P)))
    ),
    nl(S),

    format(S, "%% --- elaborates/7 ---~n", []),
    format(S, "%%   elaborates(Base, Elaborated, SharedPatterns, Type, ConfidenceMax, ConfidenceJaccard, DirectionAsymmetry).~n", []),
    forall(member(el(B, E, Sh, Ty, CM, CJ, A), Elabs),
           write_term_line(S, elaborates(B, E, Sh, Ty, CM, CJ, A))),
    nl(S),

    format(S, "%% --- pattern_evidence/3 ---~n", []),
    format(S, "%%   pattern_evidence(Strategy, Pattern, ev(ClauseHead, Witness)).~n", []),
    forall(member(pe(Name, Pattern, Ev), PEs),
           write_term_line(S, pattern_evidence(Name, Pattern, Ev))).

write_term_line(S, T) :-
    write_term(S, T, [quoted(true), nl(false), numbervars(true)]),
    format(S, ".~n", []).
