/** <module> cw_axiom_pack -- crosswalk family data. */
:-module(cw_axiom_pack,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(sequent(sequent_engine),[]).
cw_family(cw_axiom_pack).
edge(sequent_engine,enabled_axiom_pack/1,[core],[],call_match_ground).
cw_rule((axiom_pack_unified(A,B):-axiom_pack_witness(A,B,_8862))).
cw_rule((axiom_pack_witness(A,enabled_predicate,B):-witness_dict:witness_dict(axiom_pack_enabled_state,closed_world_finite_current_sequent_engine_axiom_packs,_8970{derivation:owner_predicate_state_read,pack:A,projection:exported_enabled_pack_reader,source:enabled_predicate,source_witness:_{kind:axiom_pack_reader_row,module:sequent_engine,pack:A,predicate:enabled_axiom_pack/1}},B),catch(sequent_engine:enabled_axiom_pack(A),_,fail))).
cw_rule((axiom_pack_witness(A,enabled_store,B):-witness_dict:witness_dict(axiom_pack_enabled_state,closed_world_finite_current_sequent_engine_axiom_packs,_9186{derivation:owner_predicate_state_read,pack:A,projection:dynamic_enabled_pack_store,source:enabled_store,source_witness:_{kind:axiom_pack_store_row,module:sequent_engine,pack:A,predicate:axiom_pack_enabled/1}},B),catch(sequent_engine:axiom_pack_enabled(A),_,fail))).
cw_rule((axiom_pack_control(A,B,C,D):-axiom_pack_control_witness(A,B,C,D,_9386))).
cw_rule((axiom_pack_control_witness(A,B,C,D,E):-witness_dict:witness_dict(axiom_pack_control_surface,closed_world_finite_sequent_engine_axiom_pack_controls,_9526{arity:D,derivation:current_predicate_control_surface_check,functor:C,module:B,projection:side_effect_boundary_registry,side_effect_policy:I,source:control_registry,source_witness:_{boundary:H,kind:axiom_pack_control_predicate,module:B,predicate:C/D,variant:A},variant:A},E),axiom_pack_control_spec(A,B,C,D,I,H),current_predicate(B:C/D))).
cw_rule(axiom_pack_control_spec(enable,sequent_engine,enable_axiom_pack,1,mutates_enabled_pack_store,asserts_known_pack_enabled)).
cw_rule(axiom_pack_control_spec(disable,sequent_engine,disable_axiom_pack,1,mutates_enabled_pack_store,retracts_known_pack_enabled)).
cw_rule(axiom_pack_control_spec(scoped,sequent_engine,with_axiom_packs,2,executes_goal_under_temporary_pack_set,setup_call_cleanup_restores_prior_pack_state)).
cw_rule(canonical_concept('sequent_engine:enabled_axiom_pack/1',axiom_pack_unified)).
cw_rule(canonical_concept('sequent_engine:axiom_pack_enabled/1',axiom_pack_unified)).
cw_rule(canonical_concept('sequent_engine:enable_axiom_pack/1',axiom_pack_control)).
cw_rule(canonical_concept('sequent_engine:disable_axiom_pack/1',axiom_pack_control)).
cw_rule(canonical_concept('sequent_engine:with_axiom_packs/2',axiom_pack_control)).
cw_rule(vocabulary_source(axiom_pack_unified,['sequent_engine:enabled_axiom_pack/1','sequent_engine:axiom_pack_enabled/1'])).
cw_rule(vocabulary_source(axiom_pack_control,['sequent_engine:enable_axiom_pack/1','sequent_engine:disable_axiom_pack/1','sequent_engine:with_axiom_packs/2'])).
