/** <module> cw_action_cluster -- crosswalk family data. */
:-module(cw_action_cluster,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(strategies('math/sar_add_action_pairs'),[]).
:-use_module(strategies('math/fraction_action_pairs'),[]).
:-use_module(strategies('math/action_automata_registry'),[]).
cw_family(cw_action_cluster).
edge(sar_add_action_pairs,action_cluster/2,[derived_fact_adjustment],[2],call_bind_out).
cw_rule((action_cluster_unified(addition,A,B,addition_pairs):-action_cluster_witness(addition,A,B,addition_pairs,_6340))).
cw_rule((action_cluster_unified(fraction,A,B,fraction_pairs):-action_cluster_witness(fraction,A,B,fraction_pairs,_6432))).
cw_rule((action_cluster_unified(A,B,C,registry):-action_cluster_witness(A,B,C,registry,_6524))).
cw_rule((action_cluster_witness(A,B,C,D,E):-witness_dict:witness_dict(action_cluster_crosswalk,closed_world_finite_loaded_action_cluster_sources,_6622{action_kind:B,cluster:C,derivation:H,legacy_functor:G,operation:A,source:D,source_witness:I},E),source_action_cluster_witness(D,A,B,C,G,H,I))).
cw_rule((source_action_cluster_witness(addition_pairs,addition,A,B,'sar_add_action_pairs:action_cluster/2',direct_addition_action_cluster_row,_6840{action_kind:A,cluster:B,implicit_operation:addition,kind:direct_action_cluster_row,module:sar_add_action_pairs,predicate:action_cluster/2}):-catch(sar_add_action_pairs:action_cluster(A,B),_,fail))).
cw_rule((source_action_cluster_witness(fraction_pairs,fraction,A,B,'fraction_action_pairs:fraction_action_cluster/2',direct_fraction_action_cluster_row,_7004{action_kind:A,cluster:B,implicit_operation:fraction,kind:direct_action_cluster_row,module:fraction_action_pairs,predicate:fraction_action_cluster/2}):-catch(fraction_action_pairs:fraction_action_cluster(A,B),_,fail))).
cw_rule((source_action_cluster_witness(registry,A,B,C,'action_automata_registry:action_automaton_cluster/3',registry_operation_dispatch,_7168{action_kind:B,cluster:C,dispatched_legacy_functor:G,dispatched_module:E,dispatched_predicate:F/2,kind:registry_action_cluster_dispatch,operation:A,registry_predicate:'action_automata_registry:action_automaton_cluster/3'}):-catch(action_automata_registry:action_automaton_cluster(A,B,C),_,fail),registry_cluster_dispatch(A,E,F,G),dispatched_cluster_row(E,F,B,C))).
cw_rule(registry_cluster_dispatch(addition,sar_add_action_pairs,action_cluster,'sar_add_action_pairs:action_cluster/2')).
cw_rule(registry_cluster_dispatch(subtraction,sar_sub_action_pairs,subtractive_action_cluster,'sar_sub_action_pairs:subtractive_action_cluster/2')).
cw_rule(registry_cluster_dispatch(multiplication,smr_mult_action_pairs,multiplicative_action_cluster,'smr_mult_action_pairs:multiplicative_action_cluster/2')).
cw_rule(registry_cluster_dispatch(division,smr_div_action_pairs,division_action_cluster,'smr_div_action_pairs:division_action_cluster/2')).
cw_rule(registry_cluster_dispatch(fraction,fraction_action_pairs,fraction_action_cluster,'fraction_action_pairs:fraction_action_cluster/2')).
cw_rule(registry_cluster_dispatch(decimal,decimal_action_pairs,decimal_action_cluster,'decimal_action_pairs:decimal_action_cluster/2')).
cw_rule(registry_cluster_dispatch(integer,integer_action_pairs,integer_action_cluster,'integer_action_pairs:integer_action_cluster/2')).
cw_rule(registry_cluster_dispatch(ratio,ratio_action_pairs,ratio_action_cluster,'ratio_action_pairs:ratio_action_cluster/2')).
cw_rule(registry_cluster_dispatch(diagnostic,diagnostic_validation_action_pairs,diagnostic_action_cluster,'diagnostic_validation_action_pairs:diagnostic_action_cluster/2')).
cw_rule(registry_cluster_dispatch(calculus,calculus_limits_action_pairs,calculus_action_cluster,'calculus_limits_action_pairs:calculus_action_cluster/2')).
cw_rule(registry_cluster_dispatch(algebraic,algebraic_action_pairs,algebraic_action_cluster,'algebraic_action_pairs:algebraic_action_cluster/2')).
cw_rule(registry_cluster_dispatch(probability,probability_action_pairs,probability_action_cluster,'probability_action_pairs:probability_action_cluster/2')).
cw_rule((dispatched_cluster_row(A,B,C,D):-E=..[B,C,D],catch(call(A:E),_8064,fail))).
cw_rule(canonical_concept('sar_add_action_pairs:action_cluster/2',action_cluster_unified)).
cw_rule(canonical_concept('fraction_action_pairs:fraction_action_cluster/2',action_cluster_unified)).
cw_rule(canonical_concept('action_automata_registry:action_automaton_cluster/3',action_cluster_unified)).
cw_rule(vocabulary_source(action_cluster_unified,['sar_add_action_pairs:action_cluster/2','fraction_action_pairs:fraction_action_cluster/2','action_automata_registry:action_automaton_cluster/3'])).
