/** <module> cw_arithmetic_property_claim -- mechanical crosswalk family data. */
:- module(cw_arithmetic_property_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_arithmetic_property_claim).
cw_rule(ap(associativity_single_operation, c_associativity_single_operation, ['grounding_metaphors:grounds_inference/3(arithmetic_is_object_collection,associativity_of_addition,associative_erf_for_collections)'])).
cw_rule(ap(commutativity_operation_specific, c_commutativity_operation_specific, ['grounding_metaphors:grounds_inference/3(arithmetic_is_object_collection,commutativity_of_addition,pooling_order_invariance)', 'action_automata_registry:action_automaton_cluster/3(multiplication,commute_factors_preserve_product,multiplicative_factor_relations)'])).
cw_rule(ap(distributivity_over_sum, c_distributivity_expansion_structure, ['action_automata_registry:action_automaton_cluster/3(multiplication,distribute_group_size_split,multiplicative_composite_units)'])).
cw_rule(ap(inverse_operation_coordination, c_inverse_relation_structure, ['action_automata_registry:action_automaton_cluster/3(division,inverse_fact_decomposition,division_grouping_structures)'])).
cw_rule(ap(number_fact_compression, c_number_fact_compression_fluency, ['action_automata_registry:action_automaton_cluster/3(addition,known_fact_retrieval,additive_fact_fluency)', 'action_automata_registry:action_automaton_cluster/3(addition,derived_fact_adjustment,additive_fact_fluency)'])).
cw_rule((claim_literature_atom(A, B):-ap(A, B, _))).
cw_rule((legacy_list(A, B):-ap(A, C, D), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', C, ')'], E), append([[E], D], B))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((arithmetic_property_unified(A, B, C):-arithmetic_property_witness(A, B, C, _))).
cw_rule((arithmetic_property_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(arithmetic_property_crosswalk, closed_world_finite_verified_arithmetic_property_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), ap(A, B, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((arithmetic_property_witness(A, edge(B), B, C):-witness_dict:witness_dict(arithmetic_property_crosswalk, closed_world_finite_verified_arithmetic_property_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge(B), legacy_functor:B, projection:verified_legacy_edge, source:B, source_witness:D}, C), ap(A, _, E), member(B, E), arithmetic_property_edge_source_witness(B, D))).
cw_rule((arithmetic_property_edge_source_witness('grounding_metaphors:grounds_inference/3(arithmetic_is_object_collection,associativity_of_addition,associative_erf_for_collections)', _{grounding_path:associative_erf_for_collections, grounding_witness:A, kind:grounding_metaphor_inference_edge, metaphor:arithmetic_is_object_collection, module:grounding_metaphors, predicate:grounds_inference_witness/4, target_inference:associativity_of_addition}):-catch(grounding_metaphors:grounds_inference_witness(arithmetic_is_object_collection, associativity_of_addition, associative_erf_for_collections, A), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('grounding_metaphors:grounds_inference/3(arithmetic_is_object_collection,commutativity_of_addition,pooling_order_invariance)', _{grounding_path:pooling_order_invariance, grounding_witness:A, kind:grounding_metaphor_inference_edge, metaphor:arithmetic_is_object_collection, module:grounding_metaphors, predicate:grounds_inference_witness/4, target_inference:commutativity_of_addition}):-catch(grounding_metaphors:grounds_inference_witness(arithmetic_is_object_collection, commutativity_of_addition, pooling_order_invariance, A), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('action_automata_registry:action_automaton_cluster/3(multiplication,commute_factors_preserve_product,multiplicative_factor_relations)', _{action_kind:commute_factors_preserve_product, cluster:multiplicative_factor_relations, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:multiplication, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(multiplication, commute_factors_preserve_product, multiplicative_factor_relations), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('action_automata_registry:action_automaton_cluster/3(multiplication,distribute_group_size_split,multiplicative_composite_units)', _{action_kind:distribute_group_size_split, cluster:multiplicative_composite_units, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:multiplication, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(multiplication, distribute_group_size_split, multiplicative_composite_units), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('action_automata_registry:action_automaton_cluster/3(division,inverse_fact_decomposition,division_grouping_structures)', _{action_kind:inverse_fact_decomposition, cluster:division_grouping_structures, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:division, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(division, inverse_fact_decomposition, division_grouping_structures), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('action_automata_registry:action_automaton_cluster/3(addition,known_fact_retrieval,additive_fact_fluency)', _{action_kind:known_fact_retrieval, cluster:additive_fact_fluency, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:addition, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(addition, known_fact_retrieval, additive_fact_fluency), _, fail))).
cw_rule((arithmetic_property_edge_source_witness('action_automata_registry:action_automaton_cluster/3(addition,derived_fact_adjustment,additive_fact_fluency)', _{action_kind:derived_fact_adjustment, cluster:additive_fact_fluency, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:addition, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(addition, derived_fact_adjustment, additive_fact_fluency), _, fail))).
