/** <module> cw_algebra_claim -- mechanical crosswalk family data. */
:- module(cw_algebra_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_algebra_claim).
cw_rule(ac(value_substitution_into_expression, c_substitution_semantics, [edge('action_automata_registry:action_automaton_vocabulary/3(algebraic,programming_expression_evaluation)', "Algebraic program-evaluation vocabulary carrying variable_substitution and variable_assignment."), edge('action_automata_registry:action_automaton_cluster/3(calculus,direct_substitution)', "Calculus limit-by-continuity cluster whose vocabulary carries substitution and function_value."), edge('action_automata_registry:action_automaton_cluster/3(calculus,factor_cancel_substitute)', "Calculus removable-discontinuity cluster that cancels then substitutes — substitution after factoring.")])).
cw_rule(ac(variable_as_indeterminate_quantity, c_variable_as_generalized_quantity, [edge('action_automata_registry:action_automaton_vocabulary/3(algebraic,programming_expression_evaluation)', "Algebraic program-evaluation vocabulary carrying algebraic_expression and variable_assignment — variables as assignable indeterminates."), edge('action_automata_registry:action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)', "Algebraic linear-pattern vocabulary carrying contextual_generalization and explicit_rule — the term standing for a generalized quantity in a relation.")])).
cw_rule(ac(function_evaluation_at_argument, c_function_notation_evaluation, [edge('action_automata_registry:action_automaton_vocabulary/3(algebraic,programming_expression_evaluation)', "Algebraic program-evaluation vocabulary carrying evaluate_as_program, procedural_evaluation, and integer_value — computing the value at an assignment."), edge('action_automata_registry:action_automaton_vocabulary/3(calculus,direct_substitution)', "Calculus direct-substitution vocabulary carrying evaluation_at_a_point and function_value.")])).
cw_rule(ac(function_as_univalent_correspondence, c_function_as_arbitrary_correspondence, [edge('grounding_metaphors:metaphor_breaks_at/3(functions_are_sets_of_ordered_pairs,conceptual_distinction_between_rule_and_extension)', "Break point: the ordered-pairs reading collapses two conceptually distinct rules that share an extension, marking where rule and extension come apart."), edge('grounding_metaphors:metaphor_breaks_at/3(functions_are_curves,monster_functions_lacking_tangents_or_continuity)', "Break point: pathological functions (continuous nowhere-differentiable, space-filling) cannot be grounded as smooth curves, forcing the arbitrary-correspondence reading.")])).
cw_rule(ac(explicit_rule_generalization, c_structural_generalization, [edge('action_automata_registry:action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)', "Algebraic linear-pattern vocabulary carrying explicit_rule, contextual_generalization, and far_term_prediction — a structural rule that holds across all cases."), edge('misconception_registry:incompatibility_with/2(guess_and_check_rule,strategy(algebraic,linear_pattern_contextual_rule))', "Registered deformation incompatibility: guess-and-check against one instance loses the explicit structural rule.")])).
cw_rule(ac(relational_strategy_over_brute_count, c_relational_strategy_choice, [edge('action_automata_registry:action_automaton_vocabulary/3(addition,derived_fact_adjustment)', "Additive derived-fact vocabulary carrying anchor_fact, relation_between_problems, and adjustment — exploiting a known fact's relation to the target."), edge('action_automata_registry:action_automaton_cluster/3(subtraction,sliding_constant_difference)', "Subtraction constant-difference shortcut: shift both terms to preserve the difference rather than counting unit-by-unit."), edge('action_automata_registry:action_automaton_cluster/3(addition,unbalanced_make_base_compensation)', "Addition compensation/conservation shortcut: adjust to a base and compensate rather than counting unit-by-unit.")])).
cw_rule(ac(irrational_extension_of_number_system, c_real_extension_solvability, [edge('grounding_metaphors:metaphor_breaks_at/3(arithmetic_is_object_collection,irrational_numbers)', "Break point: irrationals have no source-domain referent as a collection, marking where the rationals are extended to the reals."), edge('grounding_metaphors:metaphor_breaks_at/3(arithmetic_is_object_construction,irrational_numbers)', "Break point: irrationals are not constructible by finite assembly of unit parts, marking where finite construction fails.")])).
cw_rule((claim_literature_atom(A, B):-ac(A, B, _))).
cw_rule((legacy_list(A, [B|C]):-ac(A, D, E), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', D, ')'], B), findall(F, member(edge(F, _), E), C))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((algebra_claim_unified(A, B, C):-algebra_claim_witness(A, B, C, _))).
cw_rule((algebra_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(algebra_claim_crosswalk, closed_world_finite_verified_algebra_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), ac(A, B, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((algebra_claim_witness(A, edge_surface(B), C, D):-witness_dict:witness_dict(algebra_claim_crosswalk, closed_world_finite_verified_algebra_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge_surface(B), legacy_functor:C, projection:verified_legacy_edge_surface, source:C, source_witness:E}, D), ac(A, _, F), member(edge(C, B), F), algebra_edge_source_witness(C, E))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_vocabulary/3(algebraic,programming_expression_evaluation)', _{action_kind:programming_expression_evaluation, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:algebraic, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(algebraic, programming_expression_evaluation, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_vocabulary/3(algebraic,linear_pattern_contextual_rule)', _{action_kind:linear_pattern_contextual_rule, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:algebraic, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(algebraic, linear_pattern_contextual_rule, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_vocabulary/3(calculus,direct_substitution)', _{action_kind:direct_substitution, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(calculus, direct_substitution, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_vocabulary/3(addition,derived_fact_adjustment)', _{action_kind:derived_fact_adjustment, kind:action_automaton_vocabulary_edge, module:action_automata_registry, operation:addition, predicate:action_automaton_vocabulary/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_vocabulary(addition, derived_fact_adjustment, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_cluster/3(calculus,direct_substitution)', _{action_kind:direct_substitution, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(calculus, direct_substitution, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_cluster/3(calculus,factor_cancel_substitute)', _{action_kind:factor_cancel_substitute, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:calculus, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(calculus, factor_cancel_substitute, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_cluster/3(subtraction,sliding_constant_difference)', _{action_kind:sliding_constant_difference, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:subtraction, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(subtraction, sliding_constant_difference, A), _, fail))).
cw_rule((algebra_edge_source_witness('action_automata_registry:action_automaton_cluster/3(addition,unbalanced_make_base_compensation)', _{action_kind:unbalanced_make_base_compensation, cluster:A, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:addition, predicate:action_automaton_cluster/3}):-catch(action_automata_registry:action_automaton_cluster(addition, unbalanced_make_base_compensation, A), _, fail))).
cw_rule((algebra_edge_source_witness('grounding_metaphors:metaphor_breaks_at/3(functions_are_sets_of_ordered_pairs,conceptual_distinction_between_rule_and_extension)', _{kind:grounding_metaphor_break_edge, metaphor:functions_are_sets_of_ordered_pairs, module:grounding_metaphors, predicate:metaphor_breaks_at/3, reason:A, target_inference:conceptual_distinction_between_rule_and_extension}):-catch(grounding_metaphors:metaphor_breaks_at(functions_are_sets_of_ordered_pairs, conceptual_distinction_between_rule_and_extension, A), _, fail))).
cw_rule((algebra_edge_source_witness('grounding_metaphors:metaphor_breaks_at/3(functions_are_curves,monster_functions_lacking_tangents_or_continuity)', _{kind:grounding_metaphor_break_edge, metaphor:functions_are_curves, module:grounding_metaphors, predicate:metaphor_breaks_at/3, reason:A, target_inference:monster_functions_lacking_tangents_or_continuity}):-catch(grounding_metaphors:metaphor_breaks_at(functions_are_curves, monster_functions_lacking_tangents_or_continuity, A), _, fail))).
cw_rule((algebra_edge_source_witness('grounding_metaphors:metaphor_breaks_at/3(arithmetic_is_object_collection,irrational_numbers)', _{kind:grounding_metaphor_break_edge, metaphor:arithmetic_is_object_collection, module:grounding_metaphors, predicate:metaphor_breaks_at/3, reason:A, target_inference:irrational_numbers}):-catch(grounding_metaphors:metaphor_breaks_at(arithmetic_is_object_collection, irrational_numbers, A), _, fail))).
cw_rule((algebra_edge_source_witness('grounding_metaphors:metaphor_breaks_at/3(arithmetic_is_object_construction,irrational_numbers)', _{kind:grounding_metaphor_break_edge, metaphor:arithmetic_is_object_construction, module:grounding_metaphors, predicate:metaphor_breaks_at/3, reason:A, target_inference:irrational_numbers}):-catch(grounding_metaphors:metaphor_breaks_at(arithmetic_is_object_construction, irrational_numbers, A), _, fail))).
cw_rule((algebra_edge_source_witness('misconception_registry:incompatibility_with/2(guess_and_check_rule,strategy(algebraic,linear_pattern_contextual_rule))', _{conflict:strategy(algebraic, linear_pattern_contextual_rule), kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:guess_and_check_rule, predicate:incompatibility_with_witness/3, registry_witness:A}):-catch(misconception_registry:incompatibility_with_witness(guess_and_check_rule, strategy(algebraic, linear_pattern_contextual_rule), A), _, fail))).
