/** <module> cw_deontic_incoherence -- crosswalk family data. */
:-module(cw_deontic_incoherence,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(learner(deontic_scorekeeper),[]).
:-use_module(library(lists),[member/2]).
cw_family(cw_deontic_incoherence).
edge(deontic_scorekeeper,deontic_incoherent/2,[learner],[2],call_bind_out).
cw_rule((deontic_incoherence_unified(A,B,deontic):-deontic_incoherence_witness(A,B,deontic,_10848))).
cw_rule((deontic_incoherence_unified(A,B,scorecard):-deontic_incoherence_witness(A,B,scorecard,_10936))).
cw_rule((deontic_incoherence_witness(A,B,C,D):-witness_dict:witness_dict(deontic_incoherence,closed_world_finite_scorekeeper_state,_11020{agent:A,derivation:G,legacy_functor:F,reason:B,reason_family:H,source:C,support:I},D),deontic_incoherence_source(C,F),source_deontic_incoherence_witness(C,A,B,G,I),reason_family(B,H))).
cw_rule(deontic_incoherence_source(deontic,'deontic_scorekeeper:deontic_incoherent/2')).
cw_rule(deontic_incoherence_source(scorecard,'deontic_scorekeeper:scorecard/2')).
cw_rule((source_deontic_incoherence_witness(deontic,A,B,direct_relation_query,_11344{commitments:D,entitlements:E}):-catch(deontic_scorekeeper:deontic_incoherent(A,B),_,fail),scorekeeper_state(A,D,E))).
cw_rule((source_deontic_incoherence_witness(scorecard,A,B,scorecard_incoherence_unfold,_11520{incoherence_count:E,scorecard:D}):-catch(scorecard_incoherence(A,B,D),_,fail),get_dict(incoherences,D,G),length(G,E))).
cw_rule(reason_family(commitment_without_entitlement(_11716),commitment_without_entitlement)).
cw_rule(reason_family(entitlement_to_incompatible(_11766,_),entitlement_to_incompatible)).
cw_rule(reason_family(committed_to_negation_of_consequence(_11842,_),committed_to_negation_of_consequence)).
cw_rule((reason_family(A,other):-nonvar(A),\+A=commitment_without_entitlement(_11928),\+A=entitlement_to_incompatible(_,_),\+A=committed_to_negation_of_consequence(_,_))).
cw_rule((scorekeeper_state(A,B,C):-findall(D,deontic_scorekeeper:commitment(A,D),E),sort(E,B),findall(F,deontic_scorekeeper:entitlement(A,F),G),sort(G,C))).
cw_rule((scorecard_incoherence(A,B):-scorecard_incoherence(A,B,_12364))).
cw_rule((scorecard_incoherence(A,B,C):-distinct(A,deontic_scorekeeper:commitment(A,_12448)),deontic_scorekeeper:scorecard(A,C),get_dict(incoherences,C,E),member(B,E))).
cw_rule(canonical_concept('deontic_scorekeeper:deontic_incoherent/2',deontic_incoherence_unified)).
cw_rule(canonical_concept('deontic_scorekeeper:scorecard/2',deontic_incoherence_unified)).
cw_rule(vocabulary_source(deontic_incoherence_unified,['deontic_scorekeeper:deontic_incoherent/2','deontic_scorekeeper:scorecard/2'])).
