/** <module> cw_decimal_claim -- mechanical crosswalk family data. */
:- module(cw_decimal_claim,
          [ cw_family/1,
            cw_rule/1
          ]).

cw_family(cw_decimal_claim).
cw_rule(dc(decimal_place_value_alignment_in_column_arithmetic, c_decimal_place_value_alignment, [edge('misconception_registry:incompatibility_with/2(ragged_decimal_addition)', "Registered misconception: adding decimals right-aligned (ragged) rather than aligning on the point violates place-value alignment in column arithmetic."), edge('misconception_registry:incompatibility_with/2(no_borrow_across_point)', "Registered misconception: refusing to borrow across the decimal point violates place-value alignment in column subtraction."), edge('misconception_registry:incompatibility_with/2(sum_dp_ignoring_trailing_zeros)', "Registered misconception: summing decimal places while ignoring trailing zeros violates place-value alignment in column arithmetic.")])).
cw_rule(dc(decimal_magnitude_ordered_by_place_value, c_decimal_place_value_ordering, [edge('misconception_registry:incompatibility_with/2(longer_is_larger_ordering)', "Registered misconception: ordering decimals by digit count (longer is larger) violates place-value ordering of magnitude."), edge('misconception_registry:incompatibility_with/2(natural_number_ordering)', "Registered misconception: ordering the decimal tail as a whole number violates place-value ordering of magnitude.")])).
cw_rule(dc(decimal_point_as_place_value_locator, c_decimal_positional_notation, [edge('action_automata_registry:action_automaton_cluster/3(decimal,positional_decimal_reading)', "Decimal action automaton that reads the point as locating place-value units (positional reading)."), edge('action_automata_registry:action_automaton_cluster/3(decimal,decimal_whole_number_reading)', "Decimal action automaton that coordinates the whole-number and fractional sides across the point as one positional notation."), edge('misconception_registry:incompatibility_with/2(decimal_point_as_separator)', "Registered misconception: treating the point as separating two independent whole numbers violates the point-as-place-value-locator commitment."), edge('misconception_registry:incompatibility_with/2(decimal_part_as_integer)', "Registered misconception: reading the decimal part as an integer violates the point-as-place-value-locator commitment.")])).
cw_rule(dc(decimal_trailing_zero_value_invariance, c_decimal_trailing_zero_invariance, [edge('misconception_registry:incompatibility_with/2(trailing_zeros_increase_value)', "Registered misconception: treating trailing zeros as increasing value violates trailing-zero value invariance."), edge('misconception_registry:incompatibility_with/2(sum_dp_ignoring_trailing_zeros)', "Registered misconception: summing decimal places while ignoring trailing zeros violates trailing-zero value invariance.")])).
cw_rule(dc(positive_decimal_greater_than_zero, c_positive_decimal_exceeds_zero, [edge('misconception_registry:incompatibility_with/2(zero_larger_than_decimal)', "Registered misconception: judging zero larger than a positive decimal violates 'a positive decimal is greater than zero'."), edge('misconception_registry:incompatibility_with/2(decimals_are_negative)', "Registered misconception: treating decimals as negative violates 'a positive decimal is greater than zero'.")])).
cw_rule((claim_literature_atom(A, B):-dc(A, B, _))).
cw_rule((legacy_list(A, [B|C]):-dc(A, D, E), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', D, ')'], B), findall(F, member(edge(F, _), E), C))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((decimal_claim_unified(A, B, C):-decimal_claim_witness(A, B, C, _))).
cw_rule((decimal_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(decimal_claim_crosswalk, closed_world_finite_verified_decimal_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), dc(A, B, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((decimal_claim_witness(A, edge_surface(B), C, D):-witness_dict:witness_dict(decimal_claim_crosswalk, closed_world_finite_verified_decimal_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge_surface(B), legacy_functor:C, projection:verified_legacy_edge_surface, source:C, source_witness:E}, D), dc(A, _, F), member(edge(C, B), F), decimal_edge_source_witness(C, E))).
cw_rule((decimal_edge_source_witness('action_automata_registry:action_automaton_cluster/3(decimal,positional_decimal_reading)', A):-decimal_action_cluster_witness(positional_decimal_reading, A))).
cw_rule((decimal_edge_source_witness('action_automata_registry:action_automaton_cluster/3(decimal,decimal_whole_number_reading)', A):-decimal_action_cluster_witness(decimal_whole_number_reading, A))).
cw_rule((decimal_edge_source_witness(A, B):-decimal_registry_functor(A, C), decimal_registry_incompatibility_witness(C, B))).
cw_rule((decimal_action_cluster_witness(A, _{action_kind:A, cluster:C, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:decimal, predicate:action_automaton_cluster/3, vocabulary:B}):-catch(action_automata_registry:action_automaton_cluster(decimal, A, C), _, fail), catch(action_automata_registry:action_automaton_vocabulary(decimal, A, B), _, fail))).
cw_rule((decimal_registry_incompatibility_witness(A, _{conflict:B, incompatibility_witness:C, kind:misconception_registry_incompatibility_edge, module:misconception_registry, move:A, predicate:incompatibility_with/2}):-catch(once(decimal_registry_conflict(A, B, C)), _, fail))).
cw_rule((decimal_registry_conflict(A, B, C):-misconception_registry:incompatibility_with_witness(A, B, C))).
cw_rule((decimal_registry_conflict(A, B, C):-test_harness:arith_misconception(D, _, A, E, _, F), E\==skip, B=result_of(A, D, F), misconception_registry:incompatibility_with_witness(A, B, C))).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(ragged_decimal_addition)', ragged_decimal_addition)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(no_borrow_across_point)', no_borrow_across_point)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(sum_dp_ignoring_trailing_zeros)', sum_dp_ignoring_trailing_zeros)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(longer_is_larger_ordering)', longer_is_larger_ordering)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(natural_number_ordering)', natural_number_ordering)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(decimal_point_as_separator)', decimal_point_as_separator)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(decimal_part_as_integer)', decimal_part_as_integer)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(trailing_zeros_increase_value)', trailing_zeros_increase_value)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(zero_larger_than_decimal)', zero_larger_than_decimal)).
cw_rule(decimal_registry_functor('misconception_registry:incompatibility_with/2(decimals_are_negative)', decimals_are_negative)).
