/** <module> cw_fsm_engine -- crosswalk family data. */
:-module(cw_fsm_engine,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(strategies(fsm_engine),[]).
:-use_module(dialectic(dialectical_engine),[]).
cw_family(cw_fsm_engine).
edge(fsm_engine,run_fsm/4,[sample_fsm,start],[3,4],registry_projection).
cw_rule((fsm_engine_unified(fsm_engine:run_fsm/4,strategy_generic):-fsm_engine_witness(fsm_engine:run_fsm/4,strategy_generic,_18300))).
cw_rule((fsm_engine_unified(fsm_engine:run_strategy/4,strategy_high_level):-fsm_engine_witness(fsm_engine:run_strategy/4,strategy_high_level,_18384))).
cw_rule((fsm_engine_unified(dialectical_engine:run_fsm/4,dialectical_generic):-fsm_engine_witness(dialectical_engine:run_fsm/4,dialectical_generic,_18468))).
cw_rule((fsm_engine_witness(A,B,C):-witness_dict:witness_dict(fsm_engine_registry_entry,closed_world_finite_loaded_fsm_executor_registry,_18526{descriptor:A,execution_policy:registry_only_no_fsm_execution,legacy_functor:E,side_effect_boundary:owning_executor_may_incur_cost_or_run_search,source:B,source_witness:F},C),fsm_engine_variant(B,A,E,G,H,I),predicate_presence_witness(G,H,I,F))).
cw_rule(fsm_engine_variant(strategy_generic,fsm_engine:run_fsm/4,'fsm_engine:run_fsm/4',fsm_engine,run_fsm,4)).
cw_rule(fsm_engine_variant(strategy_high_level,fsm_engine:run_strategy/4,'fsm_engine:run_strategy/4',fsm_engine,run_strategy,4)).
cw_rule(fsm_engine_variant(dialectical_generic,dialectical_engine:run_fsm/4,'dialectical_engine:run_fsm/4',dialectical_engine,run_fsm,4)).
cw_rule((predicate_presence_witness(A,B,C,_18958{arity:C,descriptor:A:B/C,kind:loaded_predicate_presence,module:A,name:B,properties:E}):-variant_exists(A,B,C),predicate_properties(A,B,C,E))).
cw_rule((predicate_properties(A,B,C,D):-functor(E,B,C),findall(F,predicate_registry_property(A,E,F),D))).
cw_rule((predicate_registry_property(A,B,defined):-predicate_property(A:B,defined))).
cw_rule((predicate_registry_property(A,B,exported):-predicate_property(A:B,exported))).
cw_rule((predicate_registry_property(A,B,interpreted):-predicate_property(A:B,interpreted))).
cw_rule((predicate_registry_property(A,B,static):-predicate_property(A:B,static))).
cw_rule((variant_exists(A,B,C):-catch((current_predicate(A:B/C),functor(D,B,C),predicate_property(A:D,defined)),_19690,fail))).
cw_rule(canonical_concept('fsm_engine:run_fsm/4',fsm_engine)).
cw_rule(canonical_concept('fsm_engine:run_strategy/4',fsm_engine)).
cw_rule(canonical_concept('dialectical_engine:run_fsm/4',fsm_engine)).
cw_rule(vocabulary_source(fsm_engine,['fsm_engine:run_fsm/4','fsm_engine:run_strategy/4','dialectical_engine:run_fsm/4'])).
