/** <module> cw_grounded_arith -- crosswalk family data. */
:-module(cw_grounded_arith,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(formalization(grounded_arithmetic),[]).
:-use_module(formalization(grounded_utils),[]).
:-use_module(formalization(robinson_q),[]).
cw_family(cw_grounded_arith).
edge(grounded_arithmetic,add_grounded/3,[recollection([]),recollection([tally])],[3],call_with_snapshot).
cw_rule((with_cost_snapshot(A):-with_cost_snapshot_witness(A,_23798))).
cw_rule((with_cost_snapshot_witness(A,_23860{after_goal:D,after_restore:E,before:C,kind:grounded_arithmetic_cost_snapshot,policy:restore_direct_cost_accumulator_after_read}):-(catch(grounded_arithmetic:direct_cost_accumulated(C),_,fail)->true;C=none),(catch(once(A),_,fail)->H=succeeded;H=failed),(catch(grounded_arithmetic:direct_cost_accumulated(D),_,fail)->true;D=unavailable),(C==none->true;catch(restore_cost(C),_,true)),(catch(grounded_arithmetic:direct_cost_accumulated(E),_,fail)->true;E=unavailable),H==succeeded)).
cw_rule((restore_cost(A):-retractall(grounded_arithmetic:direct_cost_accumulator(_24330)),assertz(grounded_arithmetic:direct_cost_accumulator(A)))).
cw_rule((grounded_arith_unified(A,B,C,D):-grounded_arith_witness(A,B,C,D,_24440))).
cw_rule((grounded_arith_witness(add,[A,B],C,grounded_arithmetic,D):-with_cost_snapshot_witness(grounded_arithmetic:add_grounded(A,B,C),E),grounded_operation_witness(add,[A,B],C,grounded_arithmetic,add_grounded/3,recollection_history_concatenation,E,D))).
cw_rule((grounded_arith_witness(subtract,[A,B],C,grounded_arithmetic,D):-with_cost_snapshot_witness(grounded_arithmetic:subtract_grounded(A,B,C),E),grounded_operation_witness(subtract,[A,B],C,grounded_arithmetic,subtract_grounded/3,recollection_history_removal,E,D))).
cw_rule((grounded_arith_witness(successor,[A],B,grounded_arithmetic,C):-with_cost_snapshot_witness(grounded_arithmetic:successor(A,B),D),grounded_operation_witness(successor,[A],B,grounded_arithmetic,successor/2,add_one_tally_to_history,D,C))).
cw_rule((grounded_arith_witness(base_decompose,[A,B],bases_remainder(C,D),grounded_utils,E):-with_cost_snapshot_witness(grounded_utils:base_decompose_grounded(A,B,C,D),F),grounded_operation_witness(base_decompose,[A,B],bases_remainder(C,D),grounded_utils,base_decompose_grounded/4,repeated_base_group_subtraction,F,E))).
cw_rule((grounded_arith_witness(is_recollection,[A],history(B),robinson_q,C):-witness_dict:witness_dict(grounded_arith_crosswalk,closed_world_finite_verified_grounded_arithmetic_operations,_25428{cost_witness:_{after_goal:not_applicable,after_restore:not_applicable,before:not_applicable,kind:grounded_arithmetic_cost_snapshot,policy:source_predicate_is_pure},derivation:owner_predicate_operation_check,inputs:[A],op:is_recollection,output:history(B),projection:constructive_number_trace,source:robinson_q,source_witness:_{evidence:B,inputs:[A],kind:grounded_arithmetic_source_row,module:robinson_q,output:history(B),predicate:is_recollection/2}},C),catch(robinson_q:is_recollection(A,B),_,fail))).
cw_rule((grounded_operation_witness(A,B,C,D,E,F,G,H):-witness_dict:witness_dict(grounded_arith_crosswalk,closed_world_finite_verified_grounded_arithmetic_operations,_25710{cost_witness:G,derivation:owner_predicate_operation_check,inputs:B,op:A,output:C,projection:F,source:D,source_witness:_{input_lengths:K,inputs:B,kind:grounded_arithmetic_source_row,module:D,output:C,output_length:L,predicate:E}},H),maplist(recollection_length,B,K),recollection_length(C,L))).
cw_rule((recollection_length(recollection(A),B):-!,length(A,B))).
cw_rule((recollection_length(bases_remainder(A,B),bases_remainder(C,D)):-!,recollection_length(A,C),recollection_length(B,D))).
cw_rule(recollection_length(A,not_recollection(A))).
cw_rule(canonical_concept('grounded_arithmetic:add_grounded/3',grounded_arith_unified)).
cw_rule(canonical_concept('grounded_arithmetic:subtract_grounded/3',grounded_arith_unified)).
cw_rule(canonical_concept('grounded_arithmetic:successor/2',grounded_arith_unified)).
cw_rule(canonical_concept('grounded_utils:base_decompose_grounded/4',grounded_arith_unified)).
cw_rule(canonical_concept('robinson_q:is_recollection/2',grounded_arith_unified)).
cw_rule(vocabulary_source(grounded_arith_unified,['grounded_arithmetic:add_grounded/3','grounded_arithmetic:subtract_grounded/3','grounded_arithmetic:successor/2','grounded_utils:base_decompose_grounded/4','robinson_q:is_recollection/2'])).
