/** <module> cw_grounding_metaphor -- crosswalk family data. */
:-module(cw_grounding_metaphor,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(formalization(grounding_metaphors),[]).
:-use_module(formalization(grounding_metaphors_extended),[]).
:-use_module(pml(mua_relations),[]).
cw_family(cw_grounding_metaphor).
edge(grounding_metaphors,grounding_metaphor_definition/4,[arithmetic_is_object_collection],[2,3,4],registry_projection).
cw_rule((:-catch(user:ensure_loaded('geometry/schema.pl'),_27174,true))).
cw_rule((grounding_metaphor_unified(A,domains(B,C),definition):-grounding_metaphor_witness(A,domains(B,C),definition,_27250))).
cw_rule((grounding_metaphor_unified(A,domains(B,C),extension):-grounding_metaphor_witness(A,domains(B,C),extension,_27362))).
cw_rule((grounding_metaphor_unified(A,practice(B),mua_practice):-grounding_metaphor_witness(A,practice(B),mua_practice,_27470))).
cw_rule((grounding_metaphor_unified(A,concept(B),geometry):-grounding_metaphor_witness(A,concept(B),geometry,_27566))).
cw_rule((grounding_metaphor_witness(A,B,C,D):-witness_dict:witness_dict(grounding_metaphor_crosswalk,closed_world_finite_loaded_grounding_metaphor_sources,_27650{anchor:B,derivation:G,legacy_functor:F,metaphor:A,projection:I,source:C,source_witness:H},D),grounding_metaphor_source(C,F),source_grounding_metaphor_witness(C,A,B,I,G,H))).
cw_rule(grounding_metaphor_source(definition,'grounding_metaphors:grounding_metaphor_definition/4')).
cw_rule(grounding_metaphor_source(extension,'grounding_metaphors_extended:ln_metaphor/4')).
cw_rule(grounding_metaphor_source(mua_practice,'mua_relations:grounding_metaphor/2')).
cw_rule(grounding_metaphor_source(geometry,'geometry:metaphor_source/4')).
cw_rule((source_grounding_metaphor_witness(definition,A,domains(B,C),domains_projection,definition_table_lookup,D):-catch(grounding_metaphors:grounding_metaphor_definition(A,B,C,_28082),_,fail),(catch(grounding_metaphors:grounding_metaphor_definition_witness(A,D),_,fail)->true;source_definition_witness(A,B,C,D)))).
cw_rule((source_grounding_metaphor_witness(extension,A,domains(B,C),domains_projection,extension_table_lookup,_28296{citations:F,description:E,kind:ln_metaphor_definition,metaphor_id:A,metaphor_kind:G,source_domain:B,target_domain:C}):-catch(grounding_metaphors_extended:ln_metaphor(A,B,C,E),_,fail),findall(I,catch(grounding_metaphors_extended:ln_metaphor_citation(A,I),_,fail),F),(catch(grounding_metaphors_extended:ln_metaphor_kind(A,G),_,fail)->true;G=unknown))).
cw_rule((source_grounding_metaphor_witness(mua_practice,A,practice(B),practice_anchor_projection,mua_practice_assignment_lookup,C):-catch(mua_relations:grounding_metaphor(B,A),_28678,fail),mua_practice_source_witness(B,A,C))).
cw_rule((source_grounding_metaphor_witness(geometry,A,concept(B),concept_anchor_projection,geometry_metaphor_source_lookup,_28784{citation:E,concept:B,geometry_witness:F,kind:geometry_metaphor_source,mapping:D,metaphor:A}):-catch(user:metaphor_source(B,A,D,E),_,fail),geometry_metaphor_source_witness(B,A,F))).
cw_rule(source_definition_witness(A,B,C,_28994{kind:grounding_metaphor_definition,metaphor_id:A,source:grounding_metaphors_definition_lookup,source_domain:B,target_domain:C})).
cw_rule((mua_practice_source_witness(A,B,_29104{bridge_witness:E,kind:mua_grounding_metaphor_assignment,mua_short_label:B,practice:A,translated_metaphor_id:D}):-catch(grounding_metaphors:grounding_metaphor_for_practice_witness(A,D,E),_,fail),!)).
cw_rule(mua_practice_source_witness(A,B,_29282{bridge_witness:none,kind:mua_grounding_metaphor_assignment,mua_short_label:B,practice:A,translated_metaphor_id:none})).
cw_rule((geometry_metaphor_source_witness(A,B,C):-catch(user:lakoff_nunez_metaphor_witness(A,B,C),_29402,fail),!)).
cw_rule((geometry_metaphor_source_witness(A,B,C):-catch(user:measuring_stick_metaphor_witness(A,B,C),_29520,fail),!)).
cw_rule(geometry_metaphor_source_witness(_29614,_,none)).
cw_rule(canonical_concept('grounding_metaphors:grounding_metaphor_definition/4',grounding_metaphor)).
cw_rule(canonical_concept('grounding_metaphors_extended:ln_metaphor/4',grounding_metaphor)).
cw_rule(canonical_concept('mua_relations:grounding_metaphor/2',grounding_metaphor)).
cw_rule(canonical_concept('geometry:metaphor_source/4',grounding_metaphor)).
cw_rule(vocabulary_source(grounding_metaphor,['grounding_metaphors:grounding_metaphor_definition/4','grounding_metaphors_extended:ln_metaphor/4','mua_relations:grounding_metaphor/2','geometry:metaphor_source/4'])).
