/** <module> cw_misconception_hook -- crosswalk family data. */
:-module(cw_misconception_hook,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(strategies('math/action_automata_registry'),[]).
:-use_module(strategies('math/fraction_action_pairs'),[]).
:-use_module(misconceptions(misconception_registry),[]).
cw_family(cw_misconception_hook).
edge(action_automata_registry,action_automaton_hook/4,[addition,count_all],[3,4],registry_projection).
cw_rule((misconception_hook_unified(A,B,C,D,action_registry):-misconception_hook_witness(A,B,C,D,action_registry,_2388))).
cw_rule((misconception_hook_unified(fraction,A,B,C,fraction_action):-misconception_hook_witness(fraction,A,B,C,fraction_action,_2508))).
cw_rule((misconception_hook_unified(A,misconception(B),C,D,literature_registry):-misconception_hook_witness(A,misconception(B),C,D,literature_registry,_2624))).
cw_rule((misconception_hook_witness(A,B,C,D,E,F):-witness_dict:witness_dict(misconception_hook_crosswalk,closed_world_finite_loaded_misconception_hook_sources,_2736{derivation:I,family:C,hook:D,legacy_functor:H,operation:A,outcome:B,projection:K,source:E,source_witness:J},F),source_misconception_hook_witness(E,A,B,C,D,H,K,I,J))).
cw_rule((source_misconception_hook_witness(action_registry,A,B,C,D,'action_automata_registry:action_automaton_hook/4',action_outcome_hook_extraction,registry_operation_dispatch,_2984{dispatched_legacy_functor:F,family:C,hook_fields:H,kind:action_automata_hook_dispatch,operation:A,outcome_kind:G,registry_predicate:'action_automata_registry:action_automaton_hook/4'}):-catch(action_automata_registry:action_automaton_hook(A,B,C,D),_,fail),action_hook_dispatch(A,F),outcome_kind(B,G),hook_fields(D,H))).
cw_rule((source_misconception_hook_witness(fraction_action,fraction,A,B,C,'fraction_action_pairs:fraction_action_misconception_hook/3',action_outcome_hook_extraction,direct_fraction_hook_extraction,_3256{family:B,hook_fields:F,kind:direct_fraction_hook_extraction,module:fraction_action_pairs,outcome_kind:E,predicate:fraction_action_misconception_hook/3}):-catch(fraction_action_pairs:fraction_action_misconception_hook(A,B,C),_,fail),outcome_kind(A,E),hook_fields(C,F))).
cw_rule((source_misconception_hook_witness(literature_registry,A,misconception(B),A,registry_hook(C,D,E),'misconception_registry:misconception_registry_entry/5',registry_entry_projected_to_hook,bounded_literature_registry_projection,_3498{citation:E,commitment:C,entitlement:D,kind:literature_registry_misconception_hook,module:misconception_registry,name:B,operation:A,predicate:misconception_registry_entry/5}):-catch(once(misconception_registry:misconception_registry_entry(B,A,E,C,D)),_,fail))).
cw_rule(outcome_kind(action_outcome(A,_3716),A)).
cw_rule((outcome_kind(A,unknown):-nonvar(A),A\=action_outcome(_3788,_))).
cw_rule((hook_fields(action_misconception_hook(A),A):-!)).
cw_rule(hook_fields(A,A)).
cw_rule(action_hook_dispatch(addition,'sar_add_action_pairs:action_misconception_hook/3')).
cw_rule(action_hook_dispatch(subtraction,'sar_sub_action_pairs:subtractive_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(multiplication,'smr_mult_action_pairs:multiplicative_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(division,'smr_div_action_pairs:division_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(fraction,'fraction_action_pairs:fraction_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(decimal,'decimal_action_pairs:decimal_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(integer,'integer_action_pairs:integer_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(ratio,'ratio_action_pairs:ratio_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(diagnostic,'diagnostic_validation_action_pairs:diagnostic_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(calculus,'calculus_limits_action_pairs:calculus_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(algebraic,'algebraic_action_pairs:algebraic_action_misconception_hook/3')).
cw_rule(action_hook_dispatch(probability,'probability_action_pairs:probability_action_misconception_hook/3')).
cw_rule(canonical_concept('action_automata_registry:action_automaton_hook/4',misconception_hook)).
cw_rule(canonical_concept('fraction_action_pairs:fraction_action_misconception_hook/3',misconception_hook)).
cw_rule(canonical_concept('misconception_registry:misconception_registry_entry/5',misconception_hook)).
cw_rule(vocabulary_source(misconception_hook,['action_automata_registry:action_automaton_hook/4','fraction_action_pairs:fraction_action_misconception_hook/3','misconception_registry:misconception_registry_entry/5'])).
