/** <module> cw_material_inference -- crosswalk family data. */
:-module(cw_material_inference,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(arche_trace(defeasible_inference),[]).
:-use_module(learner(deontic_scorekeeper),[]).
:-use_module(arche_trace(embodied_prover),[]).
:-use_module(pml(semantic_axioms),[]).
cw_family(cw_material_inference).
edge(defeasible_inference,material_inference/3,[arithmetic_is_object_collection],[2,3],call_bind_out).
edge(semantic_axioms,semantic_material_witness/3,[[s(u)]],[2,3],call_once_bind_out).
edge(user,angle_material_claim_witness/2,[polygon_sum_over_triangle_sum],[2],call_once_bind_out).
edge(user,area_perimeter_material_claim_witness/2,[area_complete_unit_cover],[2],call_once_bind_out).
edge(user,attribute_material_claim_witness/2,[equal_sides_not_angle_equality],[2],call_once_bind_out).
edge(user,classification_material_claim_witness/2,[square_to_rectangle],[2],call_once_bind_out).
edge(user,coordinate_geometry_material_claim_witness/2,[slope_ratio_over_height_only],[2],call_once_bind_out).
edge(user,cross_link_material_inference_witness/5,[tilted_square_as_diamond],[2,3,4,5],call_bind_out).
edge(user,developmental_arc_material_witness/2,[polygon_angle_sum_via_triangulation],[2],call_once_bind_out).
edge(user,material_inference_profile_witness/3,[square_classification_arc],[2,3],call_once_bind_out).
edge(user,pythagorean_material_claim_witness/2,[pythagorean_side_equation],[2],call_once_bind_out).
edge(user,quad_inference_witness/4,[square,rectangle],[3,4],call_once_bind_out).
edge(user,shape_recognition_material_claim_witness/2,[property_classification_over_visual],[2],call_once_bind_out).
edge(user,similarity_material_claim_witness/2,[similarity_definition],[2],call_once_bind_out).
edge(user,synthesizer_anchor_material_witness/2,[category_container_inclusion_license],[2],call_once_bind_out).
edge(user,transformation_material_claim_witness/2,[point_image_rotation_center_diagnostic],[2],call_once_bind_out).
edge(user,validated_strength_lift_witness/3,[square_to_rectangle],[2,3],call_once_bind_out).
edge(user,van_hiele_level_material_claim_witness/2,[level_0_square_rectangle_example],[2],call_once_bind_out).
edge(user,volume_surface_area_material_claim_witness/2,[euler_convex_polyhedron_formula],[2],call_once_bind_out).
cw_rule((:-catch(user:ensure_loaded('geometry/schema.pl'),_,true))).
cw_rule((material_inference_unified(A,B,C,defeasible):-material_inference_witness(A,B,C,defeasible,_30540))).
cw_rule((material_inference_unified(A,[B],C,deontic):-material_inference_witness(A,[B],C,deontic,_30660))).
cw_rule((material_inference_unified(A,[B],C,mua):-material_inference_witness(A,[B],C,mua,_30780))).
cw_rule((material_inference_unified(pml_rhythm,[A],B,pml_rhythm):-material_inference_witness(pml_rhythm,[A],B,pml_rhythm,_30900))).
cw_rule((material_inference_witness(A,B,C,D,E):-witness_dict:witness_dict(material_inference,closed_world_finite_loaded_material_sources,_30986{conclusion:C,derivation:H,id:A,legacy_functor:G,premise_projection:J,premises:B,source:D,source_witness:I},E),material_inference_source(D,G),source_material_inference_witness(D,A,B,C,J,H,I))).
cw_rule(material_inference_source(defeasible,'defeasible_inference:material_inference/3')).
cw_rule(material_inference_source(deontic,'deontic_scorekeeper:material_inference/3')).
cw_rule(material_inference_source(mua,'deontic_scorekeeper:mua_derived_material_inference/3')).
cw_rule(material_inference_source(pml_rhythm,'embodied_prover:pml_rhythm_axiom/2')).
cw_rule((source_material_inference_witness(defeasible,A,B,C,list_verbatim,defeasible_material_catalog_lookup,none):-catch(defeasible_inference:material_inference(A,B,C),_31442,fail))).
cw_rule((source_material_inference_witness(deontic,A,[B],C,single_premise_wrapped_as_list,finite_scorekeeper_rule_evaluation,none):-catch(deontic_scorekeeper:material_inference(A,B,C),_31570,fail))).
cw_rule((source_material_inference_witness(mua,A,[B],C,single_premise_wrapped_as_list,pp_sufficient_elaboration_witness,D):-catch(deontic_scorekeeper:mua_derived_material_inference_witness(A,B,C,D),_31700,fail))).
cw_rule((source_material_inference_witness(pml_rhythm,pml_rhythm,[A],B,antecedent_wrapped_as_singleton_list,loaded_multifile_pml_rhythm_axiom,none):-catch(embodied_prover:pml_rhythm_axiom(A,B),_31838,fail))).
cw_rule(canonical_concept('defeasible_inference:material_inference/3',material_inference)).
cw_rule(canonical_concept('deontic_scorekeeper:material_inference/3',material_inference)).
cw_rule(canonical_concept('deontic_scorekeeper:mua_derived_material_inference/3',material_inference)).
cw_rule(canonical_concept('embodied_prover:pml_rhythm_axiom/2',material_inference)).
cw_rule(vocabulary_source(material_inference,['defeasible_inference:material_inference/3','deontic_scorekeeper:material_inference/3','deontic_scorekeeper:mua_derived_material_inference/3','embodied_prover:pml_rhythm_axiom/2'])).
