/** <module> cw_metaphor_break -- crosswalk family data. */
:-module(cw_metaphor_break,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(formalization(grounding_metaphors),[]).
:-use_module(pml(mua_relations),[]).
:-use_module(arche_trace(defeasible_inference),[]).
cw_family(cw_metaphor_break).
edge(grounding_metaphors,metaphor_breaks_at/3,[arithmetic_is_object_collection,irrational_numbers],[3],call_bind_out).
cw_rule((metaphor_break_unified(A,B,C,grounding_catalogue):-metaphor_break_witness(A,B,C,grounding_catalogue,_450))).
cw_rule((metaphor_break_unified(A,B,none,mua):-metaphor_break_witness(A,B,none,mua,_554))).
cw_rule((metaphor_break_unified(A,compiled,B,compiled):-metaphor_break_witness(A,compiled,B,compiled,_646))).
cw_rule((metaphor_break_witness(A,B,C,D,E):-witness_dict:witness_dict(metaphor_break_crosswalk,closed_world_finite_loaded_metaphor_break_sources,_732{derivation:H,detail:C,inference:B,legacy_functor:G,metaphor:A,projection:J,source:D,source_witness:I},E),metaphor_break_source(D,G),source_metaphor_break_witness(D,A,B,C,J,H,I))).
cw_rule(metaphor_break_source(grounding_catalogue,'grounding_metaphors:metaphor_breaks_at/3')).
cw_rule(metaphor_break_source(mua,'mua_relations:metaphor_breaks_at/2')).
cw_rule(metaphor_break_source(compiled,'defeasible_inference:compiled_break/2')).
cw_rule((source_metaphor_break_witness(grounding_catalogue,A,B,C,reason_preserved,catalogue_break_witness,D):-catch(grounding_metaphors:metaphor_break_witness(A,B,C,D),_1144,fail))).
cw_rule((source_metaphor_break_witness(mua,A,B,none,terse_pair_detail_absent,mua_break_pair_lookup,none):-catch(mua_relations:metaphor_breaks_at(A,B),_1274,fail))).
cw_rule((source_metaphor_break_witness(compiled,A,compiled,B,break_id_and_condition_set,compiled_incoherent_condition_lookup,_1350{break_id:A,condition_count:D,condition_set:B,kind:compiled_break_condition_set}):-catch(defeasible_inference:compiled_break(A,B),_,fail),length(B,D))).
cw_rule(canonical_concept('grounding_metaphors:metaphor_breaks_at/3',metaphor_break_unified)).
cw_rule(canonical_concept('grounding_metaphors:ln_metaphor_breaks_at/3',metaphor_break_unified)).
cw_rule(canonical_concept('mua_relations:metaphor_breaks_at/2',metaphor_break_unified)).
cw_rule(canonical_concept('defeasible_inference:compiled_break/2',metaphor_break_unified)).
cw_rule(vocabulary_source(metaphor_break_unified,['grounding_metaphors:metaphor_breaks_at/3','grounding_metaphors:ln_metaphor_breaks_at/3','mua_relations:metaphor_breaks_at/2','defeasible_inference:compiled_break/2'])).
