/** <module> cw_practice_vocabulary -- crosswalk family data. */
:-module(cw_practice_vocabulary,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(strategies(math/sar_add_action_pairs),[]).
:-use_module(strategies(math/fraction_action_pairs),[]).
:-use_module(pml(mua_relations),[]).
cw_family(cw_practice_vocabulary).
edge(sar_add_action_pairs,action_vocabulary/2,[count_on],[2],registry_projection).
cw_rule((practice_vocabulary_unified(A,B,additive_action):-practice_vocabulary_witness(A,B,additive_action,_14072))).
cw_rule((practice_vocabulary_unified(A,B,fraction_action):-practice_vocabulary_witness(A,B,fraction_action,_14160))).
cw_rule((practice_vocabulary_unified(A,B,mua_kind_terms):-practice_vocabulary_witness(A,B,mua_kind_terms,_14248))).
cw_rule((practice_vocabulary_unified(A,[B],mua_vocabulary_description):-practice_vocabulary_witness(A,[B],mua_vocabulary_description,_14352))).
cw_rule((practice_vocabulary_witness(A,B,C,D):-witness_dict:witness_dict(practice_vocabulary_crosswalk,closed_world_finite_loaded_practice_vocabulary_sources,_14436{derivation:G,key:A,legacy_functor:F,source:C,source_witness:H,vocabulary:B,vocabulary_shape:I},D),source_practice_vocabulary_witness(C,A,B,F,I,G,H))).
cw_rule((source_practice_vocabulary_witness(additive_action,A,B,'sar_add_action_pairs:action_vocabulary/2',term_list,direct_additive_action_vocabulary_row,_14654{action_kind:A,kind:direct_action_vocabulary_row,module:sar_add_action_pairs,predicate:action_vocabulary/2,term_count:D,terms:B}):-catch(sar_add_action_pairs:action_vocabulary(A,B),_,fail),length(B,D))).
cw_rule((source_practice_vocabulary_witness(fraction_action,A,B,'fraction_action_pairs:fraction_action_vocabulary/2',term_list,direct_fraction_action_vocabulary_row,_14842{action_kind:A,kind:direct_action_vocabulary_row,module:fraction_action_pairs,predicate:fraction_action_vocabulary/2,term_count:D,terms:B}):-catch(fraction_action_pairs:fraction_action_vocabulary(A,B),_,fail),length(B,D))).
cw_rule((source_practice_vocabulary_witness(mua_kind_terms,A,B,'mua_relations:kind_vocabulary_terms/2',sorted_term_union,mua_registry_and_curated_vocabulary_union,_15030{action_kind:A,kind:mua_kind_vocabulary_union,module:mua_relations,predicate:kind_vocabulary_terms/2,term_count:D,terms:B,union_rule:registry_terms_plus_pv_sufficient_terms}):-catch(once(mua_relations:kind_vocabulary_terms(A,B)),_,fail),B\==[],length(B,D))).
cw_rule((source_practice_vocabulary_witness(mua_vocabulary_description,A,[B],'mua_relations:vocabulary/2',singleton_description_list,vocabulary_description_projected_to_singleton_list,_15246{description:B,kind:mua_vocabulary_description,module:mua_relations,predicate:vocabulary/2,projection:description_as_singleton_list,vocabulary_id:A}):-catch(mua_relations:vocabulary(A,B),_,fail))).
cw_rule(canonical_concept('sar_add_action_pairs:action_vocabulary/2',practice_vocabulary_unified)).
cw_rule(canonical_concept('fraction_action_pairs:fraction_action_vocabulary/2',practice_vocabulary_unified)).
cw_rule(canonical_concept('mua_relations:kind_vocabulary_terms/2',practice_vocabulary_unified)).
cw_rule(canonical_concept('mua_relations:vocabulary/2',practice_vocabulary_unified)).
cw_rule(vocabulary_source(practice_vocabulary_unified,['sar_add_action_pairs:action_vocabulary/2','fraction_action_pairs:fraction_action_vocabulary/2','mua_relations:kind_vocabulary_terms/2','mua_relations:vocabulary/2'])).
