/** <module> cw_stress_map -- crosswalk family data. */
:-module(cw_stress_map,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(arche_trace(critique),[]).
:-use_module(learner(reflective_monitor),[]).
:-use_module(library(lists),[member/2]).
cw_family(cw_stress_map).
edge(critique,get_stress_map/1,[],[1],call_aggregate).
cw_rule((stress_map_unified(A,B,critique):-stress_map_witness(A,B,critique,_21404))).
cw_rule((stress_map_unified(A,B,reflective_monitor):-stress_map_witness(A,B,reflective_monitor,_21492))).
cw_rule((stress_map_witness(A,B,C,D):-witness_dict:witness_dict(stress_map_entry,closed_world_finite_loaded_stress_map_snapshot,_21576{count:B,derivation:map_snapshot_membership,legacy_functor:F,signature:A,source:C,source_witness:G},D),stress_map_source(C,F),source_stress_map_witness(C,A,B,G))).
cw_rule(stress_map_source(critique,'critique:get_stress_map/1')).
cw_rule(stress_map_source(reflective_monitor,'reflective_monitor:get_stress_map/1')).
cw_rule((source_stress_map_witness(critique,A,B,_21864{entry:stress(A,B),kind:stress_map_snapshot_membership,layer:arche_trace_critique,map_reader:'critique:get_stress_map/1',map_size:D,map_snapshot:E}):-catch(once(critique:get_stress_map(E)),_,fail),member(stress(A,B),E),length(E,D))).
cw_rule((source_stress_map_witness(reflective_monitor,A,B,_22078{entry:stress(A,B),kind:stress_map_snapshot_membership,layer:learner_reflective_monitor,map_reader:'reflective_monitor:get_stress_map/1',map_size:D,map_snapshot:E}):-catch(once(reflective_monitor:get_stress_map(E)),_,fail),member(stress(A,B),E),length(E,D))).
cw_rule(canonical_concept('critique:get_stress_map/1',stress_map_unified)).
cw_rule(canonical_concept('reflective_monitor:get_stress_map/1',stress_map_unified)).
cw_rule(canonical_concept('critique:commitment_stress/2',stress_map_unified)).
cw_rule(canonical_concept('critique:reflect/2',stress_map_unified)).
cw_rule(canonical_concept('critique:reset_stress_map/0',stress_map_unified)).
cw_rule(canonical_concept('reflective_monitor:reflect/2',stress_map_unified)).
cw_rule(canonical_concept('reflective_monitor:reset_stress_map/0',stress_map_unified)).
cw_rule(canonical_concept('reflective_monitor:parse_trace/3',stress_map_unified)).
cw_rule(vocabulary_source(stress_map_unified,['critique:get_stress_map/1','reflective_monitor:get_stress_map/1','critique:commitment_stress/2','critique:reflect/2','critique:reset_stress_map/0','reflective_monitor:reflect/2','reflective_monitor:reset_stress_map/0','reflective_monitor:parse_trace/3'])).
