/** <module> cw_sequent_proof -- crosswalk family data. */
:-module(cw_sequent_proof,[cw_family/1,cw_rule/1,edge/5]).
:-use_module(arche_trace(sequent_engine),[]).
:-use_module(arche_trace(embodied_prover),[]).
:-use_module(learner(deontic_scorekeeper),[]).
cw_family(cw_sequent_proof).
edge(sequent_engine,proves/1,[sequent([],identity,[])],[],call_once_bind_out).
cw_rule((sequent_proof_unified(A,sequent):-sequent_proof_witness(A,sequent,_18346))).
cw_rule((sequent_proof_unified(A,sequent_safe):-sequent_proof_witness(A,sequent_safe,_18418))).
cw_rule((sequent_proof_unified(A,sequent_impl):-sequent_proof_witness(A,sequent_impl,_18490))).
cw_rule((sequent_proof_unified(A,embodied):-sequent_proof_witness(A,embodied,_18562))).
cw_rule((sequent_proof_unified(A,deontic_bridge):-sequent_proof_witness(A,deontic_bridge,_18634))).
cw_rule((sequent_proof_witness(A,B,C):-witness_dict:witness_dict(sequent_proof_crosswalk,closed_world_finite_loaded_sequent_sources,_18704{derivation:F,legacy_functor:E,parameters:H,sequent:A,source:B,source_witness:G},C),sequent_proof_source(B,E),source_sequent_proof_witness(B,A,H,F,G))).
cw_rule(sequent_proof_source(sequent,'sequent_engine:proves/1')).
cw_rule(sequent_proof_source(sequent_safe,'sequent_engine:safe_proves/2')).
cw_rule(sequent_proof_source(sequent_impl,'sequent_engine:proves_impl/2')).
cw_rule(sequent_proof_source(embodied,'embodied_prover:proves/4')).
cw_rule(sequent_proof_source(deontic_bridge,'deontic_scorekeeper:proves_via_arche_trace/1')).
cw_rule((source_sequent_proof_witness(sequent,A,_19138{mode:default_loaded_axiom_packs},sequent_engine_proves_call,C):-catch(once(sequent_engine:proves(A)),_,fail),sequent_engine_source_witness(A,C))).
cw_rule((source_sequent_proof_witness(sequent_safe,A,_19286{packs:current_enabled_axiom_packs,time_limit_seconds:2},bounded_safe_proves_call,C):-catch(once(sequent_engine:safe_proves(A,[time_limit(2)])),_,fail),sequent_engine_source_witness(A,E),C=_{bound:time_limit_seconds(2),engine_witness:E,kind:bounded_sequent_engine_proof})).
cw_rule((source_sequent_proof_witness(sequent_impl,A,_19520{history:[]},internal_driver_call,C):-catch(once(sequent_engine:proves_impl(A,[])),_,fail),sequent_engine_source_witness(A,E),C=_{engine_witness:E,history:[],kind:sequent_engine_internal_driver})).
cw_rule((source_sequent_proof_witness(embodied,A,_19734{initial_context:neutral,resources_in:1000},embodied_prover_witness_call,C):-catch(once(embodied_prover:proves_witness(A,1000,_,_,C)),_,fail))).
cw_rule((source_sequent_proof_witness(deontic_bridge,A,_19930{bridge:catch_guarded_arche_trace},deontic_scorekeeper_bridge_call,_{bridge:proves_via_arche_trace,engine_witness:D,kind:deontic_arche_trace_bridge}):-catch(once(deontic_scorekeeper:proves_via_arche_trace(A)),_,fail),sequent_engine_source_witness(A,D))).
cw_rule((sequent_engine_source_witness((A=>B),_20124{conclusions:B,kind:sequent_engine_identity,premises:A,rule:identity,shared_formula:D}):-member(D,A),member(D,B),!)).
cw_rule((sequent_engine_source_witness((A=>B),_20266{conclusions:B,incoherence_witness:D,kind:sequent_engine_explosion,premises:A,rule:explosion}):-catch(sequent_engine:incoherent_witness(A,D),_,fail),!)).
cw_rule(sequent_engine_source_witness(A,_20428{kind:sequent_engine_semidet_proof,rule:loaded_axiom_or_structural_reduction,sequent:A})).
cw_rule(canonical_concept('sequent_engine:proves/1',sequent_proof)).
cw_rule(canonical_concept('sequent_engine:safe_proves/2',sequent_proof)).
cw_rule(canonical_concept('sequent_engine:proves_impl/2',sequent_proof)).
cw_rule(canonical_concept('embodied_prover:proves/4',sequent_proof)).
cw_rule(canonical_concept('deontic_scorekeeper:proves_via_arche_trace/1',sequent_proof)).
cw_rule(vocabulary_source(sequent_proof,['sequent_engine:proves/1','sequent_engine:safe_proves/2','sequent_engine:proves_impl/2','embodied_prover:proves/4','deontic_scorekeeper:proves_via_arche_trace/1'])).
