/** <module> cw_whole_number_addsub_claim -- mechanical crosswalk family data. */
:- module(cw_whole_number_addsub_claim,
          [ cw_family/1,
            cw_rule/1,
            edge/5
          ]).

:- use_module(standards('indiana/standard_k_ca_1_3'), []).
:- use_module(standards('indiana/standard_1_ca_1'), []).
:- use_module(standards('indiana/standard_1_ca_3'), []).
:- use_module(standards('indiana/standard_2_ca_2'), []).

cw_family(cw_whole_number_addsub_claim).
edge(standard_k_ca_1_3,find_complement_to_ten_witness/3,[recollection([tally,tally,tally,tally,tally,tally])],[2,3],call_once_bind_out).
edge(standard_1_ca_1,add_making_ten_witness/4,[recollection([tally,tally,tally,tally,tally,tally,tally,tally]),recollection([tally,tally,tally,tally,tally])],[3,4],call_once_bind_out).
edge(standard_1_ca_3,add_by_place_value_witness/4,[recollection([tally,tally,tally,tally,tally,tally,tally,tally,tally,tally]),recollection([tally])],[3,4],call_once_bind_out).
edge(standard_2_ca_2,add_three_digit_witness/4,[recollection([tally,tally,tally,tally,tally,tally,tally,tally,tally,tally]),recollection([tally])],[3,4],call_once_bind_out).
cw_rule(wn(addition_closure_totality, c_addition_total_operation, "Addition is defined for every pair of numbers and generates totals beyond any memorized set.", ['grounded_arithmetic:add_grounded/3', 'grounding_metaphors:grounds_inference/3'])).
cw_rule(wn(subtraction_fixed_removal, c_subtraction_removes_fixed_quantity, "Subtraction removes a fixed quantity from a starting amount (take-away).", ['action_automata_registry:action_automaton_cluster/3(subtraction,take_away_base_ones)', 'grounded_arithmetic:subtract_grounded/3'])).
cw_rule(wn(subtraction_directed_difference, c_subtraction_order_difference_relation, "Subtraction expresses a directed difference (comparison) and is order-sensitive: the larger cannot be removed from the smaller in the collection metaphor.", ['action_automata_registry:action_automaton_cluster/3(subtraction,compare_by_matching_difference)', 'grounding_metaphors:metaphor_breaks_at/3'])).
cw_rule(wn(self_subtraction_identity_zero, c_self_subtraction_yields_zero, "Any quantity minus itself is zero.", ['grounded_arithmetic:subtract_grounded/3'])).
cw_rule((claim_literature_atom(A, B):-wn(A, B, _, _))).
cw_rule((legacy_list(A, B):-wn(A, C, _, D), atomic_list_concat(['literature_vocabulary:canonical_commitment/2(', C, ')'], E), append([[E], D], B))).
cw_rule((vocabulary_source(A, B):-legacy_list(A, B))).
cw_rule((canonical_concept(A, B):-legacy_list(B, C), member(A, C))).
cw_rule((whole_number_addsub_claim_unified(A, B, C):-whole_number_addsub_claim_witness(A, B, C, _))).
cw_rule((whole_number_addsub_claim_witness(A, commitment(B, C), literature_commitment, D):-witness_dict:witness_dict(whole_number_addsub_claim_crosswalk, closed_world_finite_verified_whole_number_addsub_claim_edges, _{canonical:A, derivation:literature_canonical_commitment_lookup, detail:commitment(B, C), literature_atom:B, projection:literature_commitment_gloss, source:literature_commitment, source_witness:_{atom:B, gloss:C, kind:literature_commitment_row, module:literature_vocabulary, predicate:canonical_commitment/2}}, D), wn(A, B, _, _), catch(literature_vocabulary:canonical_commitment(B, E), _, fail), (string(E)->C=E;format(string(C), "~w", [E])))).
cw_rule((whole_number_addsub_claim_witness(A, edge(B), B, C):-witness_dict:witness_dict(whole_number_addsub_claim_crosswalk, closed_world_finite_verified_whole_number_addsub_claim_edges, _{canonical:A, derivation:owner_predicate_edge_check, detail:edge(B), legacy_functor:B, projection:verified_legacy_edge, source:B, source_witness:D}, C), wn(A, _, _, E), member(B, E), whole_number_addsub_edge_source_witness(A, B, D))).
cw_rule((whole_number_addsub_edge_source_witness(addition_closure_totality, 'grounded_arithmetic:add_grounded/3', _{evidence_policy:finite_sample_of_total_predicate, kind:grounded_addition_edge, module:grounded_arithmetic, predicate:add_grounded/3, samples:[A, B]}):-grounded_add_sample(2, 3, 5, A), grounded_add_sample(5, 2, 7, B))).
cw_rule((whole_number_addsub_edge_source_witness(addition_closure_totality, 'grounding_metaphors:grounds_inference/3', _{grounding_witnesses:[A, B], kind:grounding_metaphor_inference_edge, metaphor:arithmetic_is_object_collection, module:grounding_metaphors, predicate:grounds_inference/3, target_inferences:[commutativity_of_addition, associativity_of_addition]}):-catch(grounding_metaphors:grounds_inference_witness(arithmetic_is_object_collection, commutativity_of_addition, _, A), _, fail), catch(grounding_metaphors:grounds_inference_witness(arithmetic_is_object_collection, associativity_of_addition, _, B), _, fail))).
cw_rule((whole_number_addsub_edge_source_witness(subtraction_fixed_removal, 'action_automata_registry:action_automaton_cluster/3(subtraction,take_away_base_ones)', _{action_kind:take_away_base_ones, cluster:B, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:subtraction, predicate:action_automaton_cluster/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_cluster(subtraction, take_away_base_ones, B), _, fail), catch(action_automata_registry:action_automaton_vocabulary(subtraction, take_away_base_ones, A), _, fail))).
cw_rule((whole_number_addsub_edge_source_witness(subtraction_fixed_removal, 'grounded_arithmetic:subtract_grounded/3', _{evidence_policy:finite_sample_of_partial_predicate, interpretation:fixed_removal, kind:grounded_subtraction_edge, module:grounded_arithmetic, predicate:subtract_grounded/3, samples:[A]}):-grounded_subtract_sample(5, 2, 3, A))).
cw_rule((whole_number_addsub_edge_source_witness(subtraction_directed_difference, 'action_automata_registry:action_automaton_cluster/3(subtraction,compare_by_matching_difference)', _{action_kind:compare_by_matching_difference, cluster:B, kind:action_automaton_cluster_edge, module:action_automata_registry, operation:subtraction, predicate:action_automaton_cluster/3, vocabulary:A}):-catch(action_automata_registry:action_automaton_cluster(subtraction, compare_by_matching_difference, B), _, fail), catch(action_automata_registry:action_automaton_vocabulary(subtraction, compare_by_matching_difference, A), _, fail))).
cw_rule((whole_number_addsub_edge_source_witness(subtraction_directed_difference, 'grounding_metaphors:metaphor_breaks_at/3', _{break_witness:B, kind:grounding_metaphor_break_edge, metaphor:arithmetic_is_object_collection, module:grounding_metaphors, predicate:metaphor_breaks_at/3, reason:A, target_inference:subtraction_of_larger_from_smaller}):-catch(grounding_metaphors:metaphor_break_witness(arithmetic_is_object_collection, subtraction_of_larger_from_smaller, A, B), _, fail))).
cw_rule((whole_number_addsub_edge_source_witness(self_subtraction_identity_zero, 'grounded_arithmetic:subtract_grounded/3', _{evidence_policy:finite_samples_of_identity_case, interpretation:self_subtraction_identity_zero, kind:grounded_subtraction_edge, module:grounded_arithmetic, predicate:subtract_grounded/3, samples:[A, B]}):-grounded_subtract_sample(3, 3, 0, A), grounded_subtract_sample(4, 4, 0, B))).
cw_rule((grounded_add_sample(A, B, C, _{left:E, left_integer:A, right:F, right_integer:B, sum:D, sum_integer:C}):-catch(grounded_arithmetic:integer_to_recollection(A, E), _, fail), catch(grounded_arithmetic:integer_to_recollection(B, F), _, fail), catch(grounded_arithmetic:add_grounded(E, F, D), _, fail), catch(grounded_arithmetic:recollection_to_integer(D, C), _, fail))).
cw_rule((grounded_subtract_sample(A, B, C, _{difference:F, difference_integer:C, minuend:D, minuend_integer:A, subtrahend:E, subtrahend_integer:B}):-catch(grounded_arithmetic:integer_to_recollection(A, D), _, fail), catch(grounded_arithmetic:integer_to_recollection(B, E), _, fail), catch(grounded_arithmetic:subtract_grounded(D, E, F), _, fail), catch(grounded_arithmetic:recollection_to_integer(F, C), _, fail))).
