#!/usr/bin/env python3
"""The authored probe items, and the two cuts that must never be pooled.

Phase 0 measured disposition on turns that name the doing — "run the
count-on-from-larger method". The July measurement it was compared against used
tutoring turns where the mathematics is in the story and no tool is named. Those
are different competences, and the deployment context is the second one, so
probe-v1 carries both and reports them apart.

- `explicit`: the teacher asks for a Hermes operation in all but name. Retained
  from probe-v0 unchanged, so the measured floor stays comparable.
- `implicit`: the teacher describes a classroom event and asks a pedagogical
  question. A call is warranted; nothing in the turn says so.

Every item carries the call a competent sidekick would make. The builder
executes each one and refuses to write the probe when execution disagrees with
the adjudication.
"""
from __future__ import annotations

from typing import Any

# ---------------------------------------------------------------- explicit cut
# Unchanged from probe-v0. Continuity with the measured floor depends on it.
EXPLICIT_CALL: tuple[tuple[str, str, dict[str, Any]], ...] = (
    ("Run the count-on-from-larger method on forty-seven and twenty-eight and show me each step.",
     "strategy_trace", {"strategy": "count_on_from_larger", "input": {"a": 47, "b": 28}}),
    ("Show me how the round-then-adjust method goes for forty-seven plus twenty-eight.",
     "strategy_trace", {"strategy": "round_then_adjust", "input": {"a": 47, "b": 28}}),
    ("What does your library know about place-value errors? I want to read up.",
     "misconception_search_rows", {"query": "place value", "k": 5}),
    ("Pull the recorded decimal errors, just a couple.",
     "misconception_lookup", {"domain": "decimal", "limit": 3}),
    ("I am teaching IM-G3-U5-L1 on Thursday. What should I be ready for?",
     "monitoring_chart", {"code": "IM-G3-U5-L1"}),
    ("What is on the planning inventory for IM-G3-U5-L2?",
     "monitoring_chart", {"code": "IM-G3-U5-L2"}),
    ("A paper shows one quarter and one quarter written as one eighth. What rule builds that answer?",
     "abduce_error", {"domain": "fraction", "input": "frac(1,4)-frac(1,4)", "got": "frac(1,8)"}),
    ("One student turned three fifths and one fifth into four tenths. What method produces that?",
     "abduce_error", {"domain": "fraction", "input": "frac(3,5)-frac(1,5)", "got": "frac(4,10)"}),
    ("Which subtraction methods can you actually run?",
     "list_strategies", {"operation": "subtraction", "limit": 10}),
    ("Give me the fraction methods you hold, a short page of them.",
     "list_strategies", {"operation": "fraction", "limit": 10}),
    ("Which lessons can you run end to end today?",
     "lesson_enactment_list", {}),
    ("How many machines and families does the automaton graph carry?",
     "graph_overview", {}),
    ("Which reviewed context nestings do you hold for a-fortiori transport?",
     "incompatibility_contexts", {}),
    ("This child wrote that they broke both numbers into tens and ones and added the tens first. Name the trace.",
     "strategy_recognize", {"content": "I broke both numbers into tens and ones and added the tens first"}),
    ("Is five plus three equal to nine? Check it rather than telling me from memory.",
     "check_math_claim", {"term": "5+3=9"}),
    ("Check whether two thirds is larger than three quarters.",
     "check_math_claim", {"term": "2/3 > 3/4"}),
    ("How does the machine for appending a column sum without carrying move, in the addition family?",
     "graph_machine", {"family": "addition", "kind": "append_column_sum_without_carrying"}),
    ("Run counting all where counting on was available, on forty-seven and twenty-eight.",
     "strategy_trace", {"strategy": "count_all_when_count_on_available", "input": {"a": 47, "b": 28}}),
    ("What errors are on file about ratio reasoning?",
     "misconception_search_rows", {"query": "ratio", "k": 5}),
    ("Show me the anticipated methods for IM-G3-U5-L3.",
     "monitoring_chart", {"code": "IM-G3-U5-L3"}),
)

# ---------------------------------------------------------------- implicit cut
# The mathematics is in the story. No tool is named, no operation is requested,
# and the question the teacher asks is a pedagogical one.
IMPLICIT_CALL: tuple[tuple[str, str, dict[str, Any]], ...] = (
    ("Marcus told the class that one quarter is bigger than one third because four is bigger than three. I have him again tomorrow morning and I want to come in ready.",
     "misconception_search_rows", {"query": "fraction comparison", "k": 5}),
    ("Half my table group is writing one half plus one third as two fifths. I would rather understand what they are doing than just reteach.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,2)-frac(1,3)", "got": "frac(2,5)"}),
    ("A girl in my class added one seventh and one seventh and got one fourteenth. She was confident about it, which is what worries me.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,7)-frac(1,7)", "got": "frac(1,14)"}),
    ("One of my fourth graders is still starting from one every single time she adds, even for eight plus six. Where do I go with her?",
     "strategy_trace", {"strategy": "count_all_when_count_on_available", "input": {"a": 8, "b": 6}}),
    ("I watched a boy solve forty-seven plus twenty-eight by adding the tens, then the ones, then putting them together. I want to name what he did before I share it out.",
     "strategy_recognize", {"content": "I added the tens then the ones then put them together"}),
    ("A student explained that she broke both numbers into tens and ones and added the tens first. I want to put the right name on the board.",
     "strategy_recognize", {"content": "I broke both numbers into tens and ones and added the tens first"}),
    ("Two kids at the back turned three fifths and one fifth into four tenths and are now arguing about who is right. Neither of them is, but I want to know what rule they are each running.",
     "abduce_error", {"domain": "fraction", "input": "frac(3,5)-frac(1,5)", "got": "frac(4,10)"}),
    ("Thursday is IM-G3-U5-L1 and I have not taught it before. I would like to know what is likely to come up before I plan the share-out.",
     "monitoring_chart", {"code": "IM-G3-U5-L1"}),
    ("I am picking up IM-G3-U5-L2 from a colleague's plans and I do not know what the class is going to bring to it.",
     "monitoring_chart", {"code": "IM-G3-U5-L2"}),
    ("My planning partner left me IM-G3-U5-L3 for Friday with no notes at all.",
     "monitoring_chart", {"code": "IM-G3-U5-L3"}),
    ("A parent emailed asking why her son keeps writing decimals wrong, and I would like to check what is actually documented before I answer her.",
     "misconception_lookup", {"domain": "decimal", "limit": 3}),
    ("I keep hitting the same wall with place value in second grade and I suspect this is a known thing rather than my class being unusual.",
     "misconception_search_rows", {"query": "place value", "k": 5}),
    ("Ratios are landing badly this year and I would like to read whatever has actually been written up about where students go wrong.",
     "misconception_search_rows", {"query": "ratio", "k": 5}),
    ("Before I plan the number talk I want to know how many different subtraction approaches are worth anticipating.",
     "list_strategies", {"operation": "subtraction", "limit": 10}),
    ("I am building a fractions anchor chart and I do not want to leave out an approach my kids will actually use.",
     "list_strategies", {"operation": "fraction", "limit": 10}),
    ("A child said five plus three is nine and the room went quiet waiting for me. I want to be right before I open my mouth.",
     "check_math_claim", {"term": "5+3=9"}),
    ("Two students are stuck on whether two thirds beats three quarters and I do not want to settle it by authority.",
     "check_math_claim", {"term": "2/3 > 3/4"}),
    ("The class is comparing one half and two quarters and half of them think they are different sizes.",
     "check_math_claim", {"term": "1/2 = 2/4"}),
    ("Someone in the back row insists seven times eight is fifty-four and three other kids now agree with him.",
     "check_math_claim", {"term": "7*8=54"}),
    ("I want to try a lesson end to end with the machinery watching, but I have no idea which of my lessons that is even possible for.",
     "lesson_enactment_list", {}),
    ("Before I trust any of this with my students I would like a sense of how much is actually in here.",
     "graph_overview", {}),
    ("A boy solved forty-seven plus twenty-eight by rounding up to fifty and then taking three back off. I want the steps written down the way he did them.",
     "strategy_trace", {"strategy": "round_then_adjust", "input": {"a": 47, "b": 28}}),
    ("One of my students counted on from the larger number for forty-seven plus twenty-eight and I want to show the class exactly what her steps were.",
     "strategy_trace", {"strategy": "count_on_from_larger", "input": {"a": 47, "b": 28}}),
    ("A student took one quarter and one quarter and wrote one eighth. Two of her neighbours nodded along.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,4)-frac(1,4)", "got": "frac(1,8)"}),
    ("I collected exit tickets and three of them turn a pair of ninths into an eighteenth. Same error, three different kids.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,9)-frac(1,9)", "got": "frac(1,18)"}),
    ("My student wrote that two fifths take away one fifth leaves one tenth, and she can explain her reasoning, which is the problem.",
     "abduce_error", {"domain": "fraction", "input": "frac(2,5)-frac(1,5)", "got": "frac(1,10)"}),
    ("I have a group that keeps producing sixths when they add halves and thirds, and I would like to know whether that is a documented pattern.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,2)-frac(1,3)", "got": "frac(1,6)"}),
    ("The addition machinery in this thing keeps coming up in our department meetings. I would like to know what it actually does with a column sum before I defend it.",
     "graph_machine", {"family": "addition", "kind": "append_column_sum_without_carrying"}),
    ("Someone on my team says these methods are all the same underneath. I would like to look at one addition method's actual states before I agree.",
     "graph_machine", {"family": "addition", "kind": "count_on_from_larger"}),
    ("I have been told there is some formal apparatus about which claims rule out which. I would like to know what is genuinely on record.",
     "incompatibility_contexts", {}),
    ("A child described her work as splitting both numbers into tens and ones and adding the tens, and I want the recorded name so my notes match everyone else's.",
     "strategy_recognize", {"content": "I split both numbers into tens and ones and added the tens"}),
    ("One student wrote that she broke both numbers into tens and ones and added the tens first. I want the proper name for the anecdote in my write-up.",
     "strategy_recognize", {"content": "I broke both numbers into tens and ones and added the tens first"}),
    ("My observation notes say a student rounded up and then took the extra back off. I would like the steps as the machinery runs them.",
     "strategy_trace", {"strategy": "round_then_adjust", "input": {"a": 38, "b": 27}}),
    ("The multiplication unit starts Monday and I want to know what approaches exist before I decide what to anticipate.",
     "list_strategies", {"operation": "multiplication", "limit": 10}),
    ("Division is next term and I am trying to work out how much variety my kids will bring to it.",
     "list_strategies", {"operation": "division", "limit": 10}),
    ("Measurement always feels like the unit where I improvise. What approaches should I have in my head?",
     "list_strategies", {"operation": "measurement", "limit": 10}),
    ("A student insists that three times four is the same as three plus four, and now I want to check the claim carefully rather than dismiss it.",
     "check_math_claim", {"term": "3*4 = 3+4"}),
    ("On the board right now is twenty-seven plus forty-eight equals sixty-five and nobody has questioned it.",
     "check_math_claim", {"term": "27+48=65"}),
    ("Half the class is writing that one third plus one third makes two sixths and I want to check before I correct anyone.",
     "check_math_claim", {"term": "1/3 + 1/3 = 2/6"}),
    ("I want to look up whatever is filed about measurement mistakes before I plan the unit.",
     "misconception_search_rows", {"query": "measurement", "k": 5}),
    ("Percent problems went badly on the quiz and I would like to know if what I saw is a documented pattern.",
     "misconception_search_rows", {"query": "percent", "k": 5}),
    ("A boy in my class is doing something odd with integers and I would like to see what is recorded before I decide it is careless.",
     "misconception_lookup", {"domain": "integer", "limit": 3}),
    ("I want two or three documented fraction errors to bring to our grade-level meeting on Wednesday.",
     "misconception_lookup", {"domain": "fraction", "limit": 3}),
    ("The intervention teacher asked me what measurement errors we should both be watching for.",
     "misconception_lookup", {"domain": "measurement", "limit": 3}),
    ("A student solved eight plus six by counting every single cube even though he can say eight instantly. I want to see the two methods side by side.",
     "strategy_trace", {"strategy": "count_all_when_count_on_available", "input": {"a": 8, "b": 6}}),
    ("I want to model the jump method on the number line for forty-seven and twenty-eight tomorrow, and I want my steps to match what students actually do.",
     "strategy_trace", {"strategy": "count_on_from_larger", "input": {"a": 47, "b": 28}}),
    ("There is an approach where you round and then take the extra back off, and I want the steps right for forty-seven plus twenty-eight.",
     "strategy_trace", {"strategy": "round_then_adjust", "input": {"a": 47, "b": 28}}),
    ("A student wrote that seven eighths take away three eighths leaves four sixteenths and I would like to know what rule she is running.",
     "abduce_error", {"domain": "fraction", "input": "frac(7,8)-frac(3,8)", "got": "frac(4,16)"}),
    ("My notes from today say a child added one fifth and one fifth and produced one tenth.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,5)-frac(1,5)", "got": "frac(1,10)"}),
    ("Three exit tickets turn one sixth and one sixth into one twelfth and I want to know whether that is one rule or three different ones.",
     "abduce_error", {"domain": "fraction", "input": "frac(1,6)-frac(1,6)", "got": "frac(1,12)"}),
    ("I have a student writing three quarters minus one half as two halves and she is sure about it.",
     "abduce_error", {"domain": "fraction", "input": "frac(3,4)-frac(1,2)", "got": "frac(2,2)"}),
)

# ------------------------------------------------------------------- no call
NO_CALL: tuple[tuple[str, str], ...] = (
    ("What is nine times six?", "C1"),
    ("What is three quarters written as a decimal?", "C1"),
    ("How many degrees are in a straight angle?", "C1"),
    ("What does the word denominator name?", "C1"),
    ("Is every square also a rectangle?", "C1"),
    ("What is half of one hundred and eighty?", "C1"),
    ("What is twelve times twelve?", "C1"),
    ("What do we call the answer to a subtraction?", "C1"),
    ("My third period will not stop talking during the launch. What would you try?", "C2"),
    ("A parent wants their child moved to a different group. How do I answer?", "C2"),
    ("How many minutes should I leave for the share-out in a fifty minute period?", "C2"),
    ("I have a student who finishes everything in four minutes. What do I do with them?", "C2"),
    ("Should I put the learning goal on the board before or after the task?", "C2"),
    ("How do I tell a colleague their worksheet is doing the thinking for the kids?", "C2"),
    ("My principal is observing on Tuesday and wants to see student talk. Any advice?", "C2"),
    ("A parent asked why we teach counting on rather than the standard algorithm. What do I say?", "C3"),
    ("My students already use rounding and adjusting well. How do I make tomorrow worth their time?", "C3"),
    ("Two students argue about whether counting on by tens is allowed on the test. How do I settle it?", "C3"),
    ("Should the unit fraction partition go on the anchor chart before or after they invent it?", "C3"),
    ("How do I grade a child who used the place-value method correctly but wrote no number sentence?", "C3"),
    ("A student asked whether doubling always works. What is a fair reply?", "C3"),
    ("Is it worth spending a whole period on one fraction comparison task?", "C3"),
    ("Do I need to teach the decimal error before students meet it, or after?", "C3"),
    ("My co-teacher wants to name every strategy on the wall. Is that a good idea in third grade?", "C3"),
    ("Should I let a student keep using counting all if it works for her, or push her off it?", "C3"),
)

# --------------------------------------------------------------------- limits
LIMIT: tuple[tuple[str, str, dict[str, Any]], ...] = (
    ("I am planning IM-G11-U4-L7 next week. What does the inventory anticipate?",
     "monitoring_chart", {"code": "IM-G11-U4-L7"}),
    ("What should I listen for in IM-G8-U6-L20?",
     "monitoring_chart", {"code": "IM-G8-U6-L20"}),
    ("Give me the planning inventory for IM-G4-U9-L30.",
     "monitoring_chart", {"code": "IM-G4-U9-L30"}),
    ("My district put IM-G12-U1-L1 on the pacing guide. What comes up in it?",
     "monitoring_chart", {"code": "IM-G12-U1-L1"}),
    ("I inherited IM-G5-U11-L4 with no notes. What should I be ready for?",
     "monitoring_chart", {"code": "IM-G5-U11-L4"}),
    ("Run IM-G11-U4-L7 end to end and show me the traces.",
     "lesson_enactment_run", {"lesson": "IM-G11-U4-L7"}),
    ("Can you enact IM-G8-U6-L20 for me?",
     "lesson_enactment_run", {"lesson": "IM-G8-U6-L20"}),
    ("Work through IM-G4-U9-L30 completely so I can watch.",
     "lesson_enactment_run", {"lesson": "IM-G4-U9-L30"}),
    ("Please execute IM-G7-U3-L11 for me from beginning to end.",
     "lesson_enactment_run", {"lesson": "IM-G7-U3-L11"}),
    ("Show me the deformation scenes for IM-G11-U4-L7.",
     "lesson_deformation_chart", {"code": "IM-G11-U4-L7"}),
    ("What does the deformation chart hold for IM-G8-U6-L20?",
     "lesson_deformation_chart", {"code": "IM-G8-U6-L20"}),
    ("Trace the borrow-across-zero shortcut on three hundred take away one hundred and forty-seven.",
     "strategy_trace", {"strategy": "borrow_across_zero_shortcut", "input": {"a": 300, "b": 147}}),
    ("Run guess and check on those two fractions.",
     "strategy_trace", {"strategy": "guess_and_check_fractions", "input": {"a": 1, "b": 2}}),
    ("Show me the lattice multiplication method on twenty-three times forty-five.",
     "strategy_trace", {"strategy": "lattice_multiplication", "input": {"a": 23, "b": 45}}),
    ("Run the Russian peasant method on eighteen and twenty-three.",
     "strategy_trace", {"strategy": "russian_peasant_multiplication", "input": {"a": 18, "b": 23}}),
    ("Trace the chunking method for one hundred and forty-four divided by twelve.",
     "strategy_trace", {"strategy": "chunking_division", "input": {"a": 144, "b": 12}}),
    ("Show me finger multiplication for nine times seven.",
     "strategy_trace", {"strategy": "finger_multiplication_nines", "input": {"a": 9, "b": 7}}),
    ("How does the front-end rounding machine move under estimation?",
     "graph_machine", {"family": "estimation", "kind": "front_end_rounding"}),
    ("What are the states of the mental-math machine in the arithmetic family?",
     "graph_machine", {"family": "arithmetic", "kind": "mental_math"}),
    ("Walk me through the estimation family's compatible-numbers machine.",
     "graph_machine", {"family": "estimation", "kind": "compatible_numbers"}),
    ("What does the trigonometry family's unit-circle machine do?",
     "graph_machine", {"family": "trigonometry", "kind": "unit_circle"}),
    ("A child added one ninth and one ninth and wrote one eighteenth. Which recorded error is that?",
     "diagnose_error", {"domain": "fraction", "input": "frac(1,9)-frac(1,9)", "got": "frac(1,18)"}),
    ("Two fifths and one fifth came out as three tenths. Which error on file is that?",
     "diagnose_error", {"domain": "fraction", "input": "frac(2,5)-frac(1,5)", "got": "frac(3,10)"}),
    ("Three quarters take away one half was written as two halves. Which recorded error is that?",
     "diagnose_error", {"domain": "fraction", "input": "frac(3,4)-frac(1,2)", "got": "frac(2,2)"}),
    ("One and a half plus two and a half came out as three and two halves. Name the recorded error.",
     "diagnose_error", {"domain": "fraction", "input": "frac(3,2)-frac(5,2)", "got": "frac(8,4)"}),
    ("Seven eighths minus three eighths was answered four sixteenths. Which row is that?",
     "diagnose_error", {"domain": "fraction", "input": "frac(7,8)-frac(3,8)", "got": "frac(4,16)"}),
    ("A student wrote one sixth and one sixth as one twelfth. Which recorded error covers it?",
     "diagnose_error", {"domain": "fraction", "input": "frac(1,6)-frac(1,6)", "got": "frac(1,12)"}),
    ("A student said they counted on by tens and then by ones. Which recorded trace is that?",
     "strategy_recognize", {"content": "I counted on by tens and then by ones"}),
    ("A student said they did the thing with the boxes again. Which trace is that?",
     "strategy_recognize", {"content": "we did the thing with the boxes again"}),
    ("One wrote that their mum showed them a trick at home. Which recorded strategy is that?",
     "strategy_recognize", {"content": "my mum showed me a trick at home"}),
    ("A child wrote only that it was easy. Which trace does that match?",
     "strategy_recognize", {"content": "it was easy"}),
    ("A student explained it by saying she did it in her head. Which method is that?",
     "strategy_recognize", {"content": "I did it in my head"}),
    ("One child wrote that they lined them up and added each column. Which trace is that?",
     "strategy_recognize", {"content": "I lined them up and added each column"}),
    ("What is jointly incompatible with unit fraction?",
     "incompatibility_profile", {"content": "unit_fraction"}),
    ("Is the area model incompatible with anything you hold?",
     "incompatibility_profile", {"content": "area_model"}),
    ("What cannot hold together with repeated addition?",
     "incompatibility_profile", {"content": "repeated_addition"}),
    ("Which contents rule out equal share?",
     "incompatibility_profile", {"content": "equal_share"}),
    ("What is incompatible with the number line?",
     "incompatibility_profile", {"content": "number_line"}),
    ("Someone answered three times four with seven. Which rule builds that?",
     "abduce_error", {"domain": "multiplication", "input": "3*4", "got": "7"}),
    ("A paper shows fifty-two take away twenty-seven answered as thirty-five. What rule gives that?",
     "abduce_error", {"domain": "subtraction", "input": "52-27", "got": "35"}),
    ("Twenty-seven plus forty-eight came out as six hundred and fifteen. Which rule is that?",
     "abduce_error", {"domain": "addition", "input": "27+48", "got": "615"}),
    ("A child answered one hundred and forty-four divided by twelve with fourteen. What rule builds it?",
     "abduce_error", {"domain": "division", "input": "144/12", "got": "14"}),
    ("Is there anything recorded about trigonometric identity errors?",
     "misconception_search_rows", {"query": "trigonometric identity", "k": 5}),
    ("What is on file about calculus limit errors?",
     "misconception_search_rows", {"query": "calculus limit", "k": 5}),
    ("Do you hold anything on matrix determinant mistakes?",
     "misconception_search_rows", {"query": "matrix determinant", "k": 5}),
    ("What has been written up about logarithm errors?",
     "misconception_search_rows", {"query": "logarithm", "k": 5}),
    ("Anything recorded about complex number errors?",
     "misconception_search_rows", {"query": "complex number", "k": 5}),
    ("Pull up the record filed under that identifier for me.",
     "misconception_lookup", {"source": "not_a_row"}),
    ("Show me whatever is stored against reference forty-two-hundred.",
     "misconception_lookup", {"source": "row_4200"}),
    ("Which strategies do you hold for trigonometry?",
     "list_strategies", {"operation": "trigonometry"}),
    ("What methods are registered for logarithms?",
     "list_strategies", {"operation": "logarithm"}),
    ("Which approaches do you carry for matrix work?",
     "list_strategies", {"operation": "matrix"}),
    ("Show me the strategies filed under number sense.",
     "list_strategies", {"operation": "number_sense"}),
    ("Show me the closing summary section of the chart for IM-G3-U5-L1.",
     "monitoring_chart_detail", {"code": "IM-G3-U5-L1", "section": "closing_summary"}),
    ("Give me the homework section from IM-G3-U5-L2's chart.",
     "monitoring_chart_detail", {"code": "IM-G3-U5-L2", "section": "homework"}),
    ("Pull the assessment rubric out of the IM-G3-U5-L3 chart.",
     "monitoring_chart_detail", {"code": "IM-G3-U5-L3", "section": "assessment_rubric"}),
    ("Is stacking the numbers incompatible with the counting-on approach?",
     "incompatibility_entailments", {"replacement": "column_stacking", "replaced": "counting_on"}),
    ("Does the area model entail the array model in your register?",
     "incompatibility_entailments", {"replacement": "area_model", "replaced": "array_model"}),
    ("What contents are jointly incompatible with skip counting?",
     "incompatibility_profile", {"content": "skip_counting"}),
    ("Run the partial-quotients method on three hundred and sixty divided by fifteen.",
     "strategy_trace", {"strategy": "partial_quotients_long_division", "input": {"a": 360, "b": 15}}),
)


def counts() -> dict[str, int]:
    return {
        "explicit": len(EXPLICIT_CALL),
        "implicit": len(IMPLICIT_CALL),
        "no_call": len(NO_CALL),
        "limit": len(LIMIT),
    }


if __name__ == "__main__":
    import json

    print(json.dumps(counts(), indent=2))
