"""Reviewed class-C authoring pools for the sidekick wave-2 build.

Definitions state ordinary mathematical usage. They are authored replies, not
teacher-model claims and not appeals to authority. Out-of-scope subjects name
classroom, relational, or logistical situations for which no core operation is
applicable. Probe-v1 diagnostic surfaces are deliberately absent.
"""
from __future__ import annotations

import re
from typing import Iterable


DEFINITION_PAIRS = (
    ("addend", "An addend is a quantity being combined in an addition."),
    ("sum", "A sum is the result of an addition."),
    ("factor", "A factor is a quantity multiplied by another quantity."),
    ("product", "A product is the result of a multiplication."),
    ("dividend", "A dividend is the quantity being divided."),
    ("divisor", "A divisor is the quantity used to divide the dividend."),
    ("quotient", "A quotient is the result of a division."),
    ("remainder", "A remainder is the amount left after making all possible equal groups."),
    ("unit fraction", "A unit fraction names one equal part of a whole."),
    ("equivalent fractions", "Equivalent fractions name the same amount with different-sized parts."),
    ("mixed number", "A mixed number combines a whole number and a fraction less than one."),
    ("improper fraction", "An improper fraction names at least one whole with a single fraction notation."),
    ("common factor", "A common factor divides each of two or more whole numbers evenly."),
    ("multiple", "A multiple is a result found by multiplying a number by a whole number."),
    ("common multiple", "A common multiple is a multiple shared by two or more numbers."),
    ("prime factorization", "A prime factorization writes a whole number as a product of prime factors."),
    ("composite number", "A composite number is a whole number greater than one with more than two factors."),
    ("even number", "An even number can be separated into groups of two with none left over."),
    ("odd number", "An odd number leaves one when separated into groups of two."),
    ("place value", "Place value is the value a digit has because of its position in a numeral."),
    ("digit", "A digit is one symbol used to write numerals in a number system."),
    ("decimal point", "A decimal point separates whole-number places from fractional places in decimal notation."),
    ("tenth", "A tenth is one of ten equal parts of a whole."),
    ("hundredth", "A hundredth is one of one hundred equal parts of a whole."),
    ("expanded form", "Expanded form writes a number as the sum of its place-value parts."),
    ("standard form", "Standard form writes a number with digits in their usual place-value positions."),
    ("equation", "An equation states that two expressions have the same value."),
    ("expression", "An expression combines numbers, variables, or operations without stating an equality."),
    ("variable", "A variable is a symbol that can stand for a quantity."),
    ("coefficient", "A coefficient is a number multiplying a variable in a term."),
    ("constant", "A constant is a value that does not vary in the expression being used."),
    ("inequality", "An inequality compares values that need not be equal."),
    ("ratio", "A ratio compares two quantities multiplicatively."),
    ("rate", "A rate is a ratio comparing quantities measured in different units."),
    ("unit rate", "A unit rate compares a quantity with one unit of another quantity."),
    ("proportion", "A proportion states that two ratios are equivalent."),
    ("percent", "A percent is a rate measured per one hundred."),
    ("mean", "The mean is found by sharing a total equally across the number of values."),
    ("median", "The median is the middle value when data are ordered."),
    ("mode", "The mode is a value that occurs most often in a data set."),
    ("range", "The range is the distance from the least value to the greatest value in a data set."),
    ("data set", "A data set is a collection of values gathered for a question."),
    ("frequency", "Frequency is the number of times a value or category occurs."),
    ("bar graph", "A bar graph uses bar lengths to compare amounts across categories."),
    ("line plot", "A line plot records how often values occur along a number line."),
    ("histogram", "A histogram groups numerical data into intervals and shows each interval's frequency."),
    ("coordinate plane", "A coordinate plane locates points with two perpendicular number lines."),
    ("origin", "The origin is the point where the coordinate axes meet."),
    ("x-axis", "The x-axis is the horizontal number line in a coordinate plane."),
    ("y-axis", "The y-axis is the vertical number line in a coordinate plane."),
    ("ordered pair", "An ordered pair gives a point's horizontal coordinate followed by its vertical coordinate."),
    ("angle", "An angle is formed by two rays with a common endpoint."),
    ("vertex", "A vertex is a point where sides, rays, or edges meet."),
    ("parallel lines", "Parallel lines in a plane remain the same distance apart and do not meet."),
    ("perpendicular lines", "Perpendicular lines meet to form right angles."),
    ("polygon", "A polygon is a closed plane figure made from straight line segments."),
    ("triangle", "A triangle is a polygon with three sides."),
    ("quadrilateral", "A quadrilateral is a polygon with four sides."),
    ("rhombus", "A rhombus is a quadrilateral with four sides of equal length."),
    ("trapezoid", "A trapezoid is a quadrilateral with at least one pair of parallel sides."),
    ("circle", "A circle is the set of points in a plane at one fixed distance from a center."),
    ("radius", "A radius is a segment from a circle's center to the circle."),
    ("diameter", "A diameter is a segment through a circle's center with endpoints on the circle."),
    ("circumference", "Circumference is the distance around a circle."),
    ("area", "Area measures how much two-dimensional region a figure covers."),
)


BASE_OUT_OF_SCOPE_SCOPES = (
    "a group that will not settle after the launch",
    "a parent who wants nightly worksheets",
    "a colleague whose worksheets do the thinking",
    "an observation by the principal next week",
    "running out of time before the share-out",
    "a student who cried during the quiz",
    "seating a group of four",
    "a co-teacher who talks over you",
    "asking for more planning time",
    "a family asking for extra practice",
    "a student who will not work with a partner",
)


NEW_OUT_OF_SCOPE_SCOPES = (
    "welcoming a new student who arrives midway through the week",
    "helping a student rejoin the group after an argument",
    "choosing a calm way to begin class after an assembly",
    "writing a note home about repeated lateness",
    "planning a private check-in with a withdrawn student",
    "sharing speaking time with an instructional assistant",
    "deciding where backpacks should go during class",
    "responding when two students both want the same seat",
    "setting a routine for borrowing pencils",
    "helping a substitute follow the classroom routines",
    "preparing students for a fire drill during class",
    "making the transition back from lunch less noisy",
    "finding a fair way to rotate classroom jobs",
    "responding to a family email sent late at night",
    "asking an administrator for coverage during a meeting",
    "planning what to say after a student uses hurtful language",
    "helping a nervous student enter a group conversation",
    "deciding when to contact home about missing work",
    "making space for a student who needs movement breaks",
    "organizing shared supplies so arguments are less likely",
    "handling a student who refuses to put away a phone",
    "writing a concise absence note for families",
    "choosing a routine for collecting papers",
    "supporting a student who is embarrassed to ask for help",
    "planning a conversation with a colleague about noise",
    "responding when a caregiver challenges a classroom rule",
    "making partner changes without singling anyone out",
    "deciding how to acknowledge a student's difficult morning",
    "preparing a class for a visitor who will take notes",
    "setting boundaries for messages outside work hours",
    "helping students clean up without losing the last minutes of class",
    "finding a neutral way to interrupt side conversations",
    "planning a brief welcome for a returning student",
    "responding when a student says the room feels unsafe",
    "making a quiet space available without using it as punishment",
    "asking a colleague to return borrowed materials",
    "deciding how to distribute limited art supplies",
    "helping a student repair trust after breaking a promise",
    "writing a reminder about an upcoming field trip form",
    "planning dismissal when buses are delayed",
    "supporting a student who misses a former teacher",
    "responding to repeated requests to leave the room",
    "setting a routine for students who arrive before the bell",
    "making the classroom library easier to maintain",
    "addressing a pattern of students talking during announcements",
    "deciding how to introduce a new classroom volunteer",
    "planning a respectful way to correct a name pronunciation",
    "responding when a student does not want their work displayed",
    "making a conference schedule that includes working caregivers",
    "asking for help with an overloaded duty schedule",
    "helping a student calm down after losing a game",
    "planning a class celebration without food",
    "choosing language for a reminder about personal space",
    "responding when a student repeatedly forgets materials",
    "making space for a student who needs a quieter arrival",
    "planning how to hand off a concern to the counselor",
    "setting expectations for using flexible seating",
    "helping a student apologize without forcing a performance",
    "deciding whether to postpone a difficult family call",
    "organizing a line so the same students are not always last",
    "responding when a student laughs at another student's mistake",
    "writing a request for classroom furniture repair",
    "planning what to do when the room is unusually hot",
    "supporting a student who is worried about changing schools",
    "asking a team to shorten an agenda that is too full",
    "making a plan for distributing donated coats privately",
    "responding to a student who wants to eat alone",
    "choosing a signal for getting the class's attention",
    "helping two colleagues resolve a scheduling conflict",
    "planning a gentle reminder about strong perfume",
    "setting a routine for charging school devices",
    "responding when a student will not speak during a conference",
    "making room for a student who uses a mobility device",
    "writing an update after a canceled school event",
    "planning how to welcome families who need an interpreter",
    "deciding what to delegate before taking a personal day",
    "helping a student whose friend moved away",
    "responding to a family asking for a different teacher",
    "setting a boundary when a meeting runs past its end time",
    "planning a routine for wet coats on rainy days",
    "making a seating change after a conflict",
    "asking students for feedback without putting anyone on the spot",
    "responding when a student says an adult did not listen",
    "organizing a calm return after an emergency drill",
    "planning a conversation about repeated hallway noise",
    "helping a student prepare to speak with the principal",
    "deciding how to recognize a birthday without requiring attention",
    "writing a message about a lost personal item",
    "setting a routine for visitors entering the room",
    "responding when a student wants to change groups immediately",
    "making time for lunch during a meeting-heavy day",
    "asking a colleague to stop copying the whole staff on minor issues",
    "planning a supportive response to a student returning from suspension",
    "helping a family understand a change in pickup procedures",
    "deciding how to close a tense staff conversation",
    "setting a routine for students to request a private conversation",
    "responding to a student who is worried about a sibling",
    "making classroom announcements shorter and easier to follow",
    "planning how to share an unpopular schedule change",
    "asking for clarification when two administrators give conflicting directions",
)


CORE_SURFACE = re.compile(
    r"\b(?:strategy trace|strategy recognition|misconception lookup|monitoring chart|"
    r"lesson enactment|deontic|incompatibility|automaton|graph machine|math claim)\b",
    re.IGNORECASE,
)


def scope_faults(scopes: Iterable[str]) -> list[str]:
    """Return authored C2 subjects that accidentally name a core operation."""
    return [scope for scope in scopes if CORE_SURFACE.search(scope)]


assert len(DEFINITION_PAIRS) == 65
assert len(NEW_OUT_OF_SCOPE_SCOPES) == 100
assert not scope_faults(BASE_OUT_OF_SCOPE_SCOPES + NEW_OUT_OF_SCOPE_SCOPES)
