#!/usr/bin/env python3
"""Build default deformation-chart facts from covered and attested lessons.

K-5 eligibility remains the coverage-table strategy rule.  Grade 6 Unit 4
adds only vision-attested fraction-division lessons whose stated work uses
tape diagrams; algorithm-only and specialized-chart lessons are left out so
the fixed partition scenes never substitute different lesson content.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
COVERAGE = REPO_ROOT / "curriculum/im/coverage/im_coverage.json"
DEFAULT_OUTPUT = REPO_ROOT / "curriculum/im/generated/default_fill_lessons.pl"
PARTITION_KINDS = {"unit_fraction_partition", "unit_fraction_iteration"}


def prolog_json(goal: str, *loads: str) -> object:
    command = ["swipl", "-q", "-l", "paths.pl"]
    for source in loads:
        command.extend(["-l", source])
    command.extend(["-g", goal])
    result = subprocess.run(command, cwd=REPO_ROOT, text=True, stdout=subprocess.PIPE,
                            stderr=subprocess.PIPE, check=False)
    if result.returncode:
        raise RuntimeError(f"Prolog query failed: {result.stderr.strip()}")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Prolog query did not produce JSON") from exc


def g6_candidates() -> list[dict[str, object]]:
    goal = r'''use_module(library(http/json)),findall(_{code:CodeText,purpose:Purpose,goals:Goals,standards:Standards},(vision_lesson_digest:vision_lesson(Code,6,4,_Lesson,_Title),atom_string(Code,CodeText),findall(StandardText,(vision_lesson_digest:vision_lesson_standard(Code,_Band,Standard),atom_string(Standard,StandardText)),Standards0),sort(Standards0,Standards),findall(Goal,vision_lesson_digest:vision_lesson_goal(Code,_Audience,Goal),Goals),(vision_lesson_digest:vision_lesson_purpose(Code,Purpose)->true;Purpose="")),Rows0),sort(Rows0,Rows),json_write_dict(current_output,Rows),nl,halt'''
    return prolog_json(goal, "curriculum/im/generated/vision_lesson_digest.pl")  # type: ignore[return-value]


def specialized_division_charts() -> set[str]:
    goal = r'''use_module(library(http/json)),findall(CodeText,(lesson_deformation_chart:lesson_division_deformation_chart(Code,_),atom_string(Code,CodeText)),Codes0),sort(Codes0,Codes),json_write_dict(current_output,Codes),nl,halt'''
    return set(prolog_json(goal, "curriculum/im/lesson_deformation_chart.pl"))  # type: ignore[arg-type]


def chart_rows(codes: list[str]) -> list[dict[str, object]]:
    code_terms = ",".join(repr(code) for code in codes)
    goal = f'''use_module(library(http/json)),Codes=[{code_terms}],findall(_{{code:CodeText,title:Title,standards:Standards}},(member(CodeText,Codes),atom_string(Code,CodeText),once(lesson_monitoring:encoded_lesson(Code,_Concept,Title,_Grade,_Unit,_Lesson)),findall(StandardText,(lesson_monitoring:lesson_standard(Code,_Framework,Standard,_Statement),atom_string(Standard,StandardText)),Standards0),sort(Standards0,Standards)),Rows),json_write_dict(current_output,Rows),nl,halt'''
    return prolog_json(goal, "curriculum/im/lesson_monitoring.pl")  # type: ignore[return-value]


def prolog_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def prolog_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generated_source(rows: list[dict[str, object]]) -> str:
    lines = [
        "/** <module> Generated: default deformation-chart lessons with titles and standards",
        " *",
        " * Generated by scripts/curriculum/build_default_fill_lessons.py from the",
        " * coverage table and eligible Grade 6 Unit 4 vision attestations. Do not",
        " * hand-edit; regenerate after either source changes.",
        " */",
        ":- module(default_fill_lessons, [default_fill_lesson/1, default_fill_lesson/3]).",
        ":- discontiguous default_fill_lesson/1.",
        ":- discontiguous default_fill_lesson/3.",
        "",
    ]
    for row in rows:
        code = str(row["code"])
        title = str(row["title"])
        standards = [prolog_string(str(item)) for item in row["standards"]]
        lines.append(f"default_fill_lesson({prolog_atom(code)}).")
        lines.append(
            f"default_fill_lesson({prolog_atom(code)}, {prolog_string(title)}, [{','.join(standards)}])."
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="print eligibility plan without writing")
    args = parser.parse_args()

    coverage = json.loads(COVERAGE.read_text(encoding="utf-8"))
    covered = {
        str(row["lesson"])
        for row in coverage["published_lessons"]
        if PARTITION_KINDS.intersection(row.get("strategy_atoms", []))
    }
    specialized = specialized_division_charts()
    candidates = [row for row in g6_candidates() if "6.NS.A.1" in row["standards"]]
    eligible_g6: set[str] = set()
    skipped_g6: list[dict[str, str]] = []
    for row in candidates:
        code = str(row["code"])
        attested_text = " ".join([str(row["purpose"]), *(str(goal) for goal in row["goals"])]).lower()
        if code in specialized:
            skipped_g6.append({"code": code, "reason": "specialized_division_chart"})
        elif "tape diagram" not in attested_text:
            skipped_g6.append({"code": code, "reason": "no_attested_tape_diagram_scene"})
        elif "algorithm" in attested_text:
            skipped_g6.append({"code": code, "reason": "algorithmic_work_not_partition_scene"})
        else:
            eligible_g6.add(code)

    codes = sorted(covered | eligible_g6)
    summary = {
        "mode": "dry-run" if args.dry_run else "build",
        "output": str(args.output),
        "coverage_table_eligible": len(covered),
        "g6_fraction_division_examined": len(candidates),
        "g6_fraction_division_eligible": sorted(eligible_g6),
        "g6_fraction_division_skipped": skipped_g6,
        "total_eligible": len(codes),
    }
    if args.dry_run:
        print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    rows = chart_rows(codes)
    found = {str(row["code"]) for row in rows}
    missing = sorted(set(codes) - found)
    if missing:
        raise RuntimeError(f"no lesson-monitoring rows for: {', '.join(missing)}")
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated_source(rows), encoding="utf-8")
    print(json.dumps({**summary, "written": len(rows)}, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
