#!/usr/bin/env python3
"""Compile vision-attested standards with locally available CCSS statements.

The generated facts intentionally take the explicit-lesson-standard path in
``lesson_monitoring``.  That path supersedes the unit fallback, so a request
does not rescan vision digests or standards tables.  Digest codes without a
loaded CCSS statement are reported and omitted rather than guessed.
"""
from __future__ import annotations

import argparse
import json
import subprocess
from collections import Counter
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO_ROOT / "curriculum/im/generated/lesson_standard_anchors.pl"


def prolog_rows() -> list[list[str]]:
    """Return distinct digest lesson/code/statement rows from loaded tables."""
    goal = r'''use_module(library(http/json)),findall([LessonText,StandardText,Statement],(vision_lesson_digest:vision_lesson_standard(Lesson,_Band,Standard),atom_string(Lesson,LessonText),atom_string(Standard,StandardText),lesson_monitoring:loaded_standard_anchor(_Concept,ccss,StandardText,Statement)),Rows0),sort(Rows0,Rows),json_write_dict(current_output,Rows),nl,halt'''
    result = subprocess.run(
        ["swipl", "-q", "-l", "paths.pl", "-l", "curriculum/im/lesson_monitoring.pl",
         "-l", "curriculum/im/generated/vision_lesson_digest.pl", "-g", goal],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(f"standards query failed: {result.stderr.strip()}")
    try:
        return json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("standards query did not produce JSON") from exc


def digest_pairs() -> list[list[str]]:
    """Return all distinct digest lesson/code pairs for omission accounting."""
    goal = r'''use_module(library(http/json)),findall([LessonText,StandardText],(vision_lesson_digest:vision_lesson_standard(Lesson,_Band,Standard),atom_string(Lesson,LessonText),atom_string(Standard,StandardText)),Rows0),sort(Rows0,Rows),json_write_dict(current_output,Rows),nl,halt'''
    result = subprocess.run(
        ["swipl", "-q", "-l", "paths.pl", "-l", "curriculum/im/generated/vision_lesson_digest.pl", "-g", goal],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(f"digest query failed: {result.stderr.strip()}")
    return json.loads(result.stdout)


def prolog_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def prolog_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generated_source(rows: list[list[str]]) -> str:
    lines = [
        "/* Generated by scripts/curriculum/build_lesson_standard_anchors.py; do not edit. */",
        ":- multifile lesson_monitoring:explicit_lesson_standard/4.",
        "",
    ]
    for lesson, standard, statement in rows:
        lines.append(
            "lesson_monitoring:explicit_lesson_standard("
            f"{prolog_atom(lesson)}, ccss, {prolog_atom(standard)}, {prolog_string(statement)})."
        )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="print counts without writing")
    args = parser.parse_args()

    rows = prolog_rows()
    all_pairs = digest_pairs()
    available = {(lesson, standard) for lesson, standard, _statement in rows}
    missing = sorted((lesson, standard) for lesson, standard in all_pairs if (lesson, standard) not in available)
    summary = {
        "mode": "dry-run" if args.dry_run else "build",
        "output": str(args.output),
        "facts": len(rows),
        "lessons_anchored": len({lesson for lesson, _standard, _statement in rows}),
        "skipped_pairs_without_statement": len(missing),
        "skipped_by_standard": dict(sorted(Counter(standard for _lesson, standard in missing).items())),
    }
    if args.dry_run:
        print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(generated_source(rows), encoding="utf-8")
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
