#!/usr/bin/env python3
"""Build lesson-scoped misconception resonance facts from the embedding index.

The input query for each lesson is derived only from the encoded lesson title
and its registered strategy vocabulary.  The script deliberately does not
read transcripts: transcripts can motivate which lessons to inspect, but do
not define the teacher-guide lesson query.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(REPO_ROOT))
DEFAULT_OUTPUT = REPO_ROOT / "curriculum/im/generated/lesson_resonance.pl"


def lesson_rows(codes: list[str]) -> list[dict[str, object]]:
    """Read title and registered strategies through the lesson-monitoring API."""
    import subprocess

    code_terms = ",".join(repr(code) for code in codes)
    goal = f'''use_module(library(http/json)),Codes=[{code_terms}],findall(_{{code:CodeText,title:Title,strategies:Strategies}},(member(CodeText,Codes),atom_string(Code,CodeText),once(lesson_monitoring:encoded_lesson(Code,_,Title,_,_,_)),findall(KindText,(lesson_monitoring:lesson_strategy(Code,_,Kind,_),atom_string(Kind,KindText)),Kinds0),sort(Kinds0,Strategies)),Rows0),sort(Rows0,Rows),json_write_dict(current_output,Rows),nl,halt'''
    result = subprocess.run(
        ["swipl", "-q", "-l", "paths.pl", "-l", "curriculum/im/lesson_monitoring.pl", "-g", goal],
        cwd=REPO_ROOT,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )
    if result.returncode:
        raise RuntimeError(f"lesson query failed: {result.stderr.strip()}")
    try:
        rows = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("lesson query did not produce JSON") from exc
    if len(rows) != len(codes):
        found = {str(row.get("code")) for row in rows if isinstance(row, dict)}
        missing = sorted(set(codes) - found)
        raise RuntimeError(f"no encoded lesson facts for: {', '.join(missing)}")
    return rows


def lesson_query(row: dict[str, object]) -> str:
    title = str(row["title"]).strip()
    strategies = [str(value).replace("_", " ") for value in row["strategies"]]
    vocabulary = ", ".join(strategies) if strategies else "no registered strategy vocabulary"
    return f"Lesson: {title}\nRegistered strategy vocabulary: {vocabulary}"


def prolog_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "\\'") + "'"


def prolog_string(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def generated_source(rows: list[tuple[str, list[dict[str, object]]]]) -> str:
    lines = [
        "/* Generated by scripts/curriculum/build_lesson_resonance.py; do not edit. */",
        ":- multifile lesson_monitoring:lesson_resonant_misconception/6.",
        "",
    ]
    for code, matches in rows:
        for rank, match in enumerate(matches, start=1):
            lines.append(
                "lesson_monitoring:lesson_resonant_misconception("
                f"{prolog_atom(code)}, {rank}, {prolog_atom(str(match['name']))}, "
                f"{prolog_atom(str(match['domain']))}, {prolog_string(str(match['citation']))}, "
                f"{float(match['score']):.8f})."
            )
    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("codes", nargs="*", help="encoded IM lesson codes")
    parser.add_argument("--mapped-lessons", action="store_true",
                        help="build the plan for every scope_sequence_mapped lesson")
    parser.add_argument("--k", type=int, default=6, help="resonance rows per lesson (default: 6)")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="print lesson-derived queries without embedding or writing")
    args = parser.parse_args()
    if args.k < 1:
        parser.error("--k must be positive")
    if args.codes and args.mapped_lessons:
        parser.error("codes and --mapped-lessons are mutually exclusive")
    if not args.codes and not args.mapped_lessons:
        parser.error("provide lesson codes or --mapped-lessons")
    codes = args.codes
    if args.mapped_lessons:
        import subprocess

        result = subprocess.run(
            ["swipl", "-q", "-l", "paths.pl", "-l", "curriculum/im/lesson_monitoring.pl",
             "-g", "findall(CodeText,(lesson_monitoring:scope_sequence_mapped_lesson(Code),atom_string(Code,CodeText)),Codes0),sort(Codes0,Codes),use_module(library(http/json)),json_write_dict(current_output,Codes),nl,halt"],
            cwd=REPO_ROOT,
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
        if result.returncode:
            raise RuntimeError(f"mapped-lesson query failed: {result.stderr.strip()}")
        try:
            codes = json.loads(result.stdout)
        except json.JSONDecodeError as exc:
            raise RuntimeError("mapped-lesson query did not produce JSON") from exc
    rows = lesson_rows(codes)
    plan = [{"code": row["code"], "query": lesson_query(row)} for row in rows]
    if args.dry_run:
        print(json.dumps({"mode": "dry-run", "output": str(args.output), "k": args.k, "queries": plan}, indent=2))
        return 0

    from hermes.app import llm
    from hermes.app.routes.misconception_search import cosine_matches, load_index
    from scripts.research.misconception_embedding import embed

    index = load_index(REPO_ROOT)
    if index is None:
        raise RuntimeError("misconception embedding index is absent or invalid; run scripts/research/misconception_embedding.py build")
    client = llm.make_client(REPO_ROOT)
    vectors = embed([str(item["query"]) for item in plan], model=index.model, client=client)
    matches = [cosine_matches(index, vector, limit=args.k) for vector in vectors]
    source = generated_source([(str(item["code"]), result) for item, result in zip(plan, matches)])
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(source, encoding="utf-8")
    print(json.dumps({"output": str(args.output), "lessons": len(plan), "rows": sum(len(result) for result in matches)}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
