#!/usr/bin/env python3
"""Bake lesson misconception incompatibility witnesses under the full worker load."""
from __future__ import annotations

import argparse
import json
import os
import subprocess
import tempfile
import time
from collections import Counter
from datetime import date
from pathlib import Path


REPO = Path(__file__).resolve().parents[2]
DEFAULT_OUTPUT = REPO / "curriculum/im/generated/lesson_misconception_witness_store.pl"
ITER7_CAPS = ("ITER7_TERM_CAP", "ITER7_NEIGHBOR_CAP", "ITER7_MAX_EXTRA")
STRATA = ("explicit_attachment", "cluster_fallback", "geometry_fallback")


def prolog_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def worker_env() -> dict[str, str]:
    env = os.environ.copy()
    for name in ITER7_CAPS:
        env.pop(name, None)
    return env


def run_worker_goal(goal: str) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [
            "swipl",
            "-q",
            "-l",
            "hermes_worker.pl",
            "-g",
            f"load_runtime,{goal}",
            "-t",
            "halt",
        ],
        cwd=REPO,
        env=worker_env(),
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def discover_codes() -> list[dict[str, str]]:
    goal = r"""
use_module(library(http/json)),
findall(Code-Stratum,
        ( lesson_monitoring:encoded_lesson(Code,_,_,_,_,_),
          ( lesson_monitoring:lesson_has_specific_attachments(Code)
          -> Stratum = explicit_attachment
          ; lesson_monitoring:geometry_concept_fallback_allowed(Code),
            once((lesson_monitoring:monitoring_chart_cluster(Code,geometry,ClusterId,_),
                  lesson_monitoring:geometry_cluster_concept(ClusterId,_)))
          -> Stratum = geometry_fallback
          ; Stratum = cluster_fallback
          )
        ),
        Pairs0),
sort(Pairs0,Pairs),
findall(_{code:CodeText,stratum:StratumText},
        ( member(Code-Stratum,Pairs),
          atom_string(Code,CodeText),atom_string(Stratum,StratumText)
        ),Rows),
json_write_dict(user_output,Rows,[width(0)]),nl
""".replace("\n", " ")
    proc = run_worker_goal(goal)
    if proc.returncode:
        detail = proc.stderr.strip() or proc.stdout.strip()
        raise RuntimeError(
            f"worker code discovery failed with status {proc.returncode}: {detail}"
        )
    for line in reversed(proc.stdout.splitlines()):
        if line.startswith("["):
            rows = json.loads(line)
            if isinstance(rows, list):
                return rows
    raise RuntimeError("worker code discovery did not return a JSON array")


def evenly_spaced(values: list[str], count: int) -> list[str]:
    if count <= 0:
        return []
    if count >= len(values):
        return list(values)
    if count == 1:
        return [values[len(values) // 2]]
    indices = [round(i * (len(values) - 1) / (count - 1)) for i in range(count)]
    return [values[index] for index in indices]


def stratified_sample(rows: list[dict[str, str]], size: int) -> list[str]:
    if size < len(STRATA):
        raise ValueError(f"sample size must be at least {len(STRATA)}")
    buckets = {
        stratum: sorted(row["code"] for row in rows if row["stratum"] == stratum)
        for stratum in STRATA
    }
    empty = [name for name, values in buckets.items() if not values]
    if empty:
        raise RuntimeError("empty witness-store strata: " + ", ".join(empty))
    base, remainder = divmod(size, len(STRATA))
    selected: list[str] = []
    for index, stratum in enumerate(STRATA):
        selected.extend(evenly_spaced(buckets[stratum], base + (index < remainder)))
    return sorted(selected)


def generated_header(*, mode: str, code_count: int) -> str:
    scope = "full encoded-lesson closure" if mode == "full" else f"{mode} verification build"
    lines = [
            "/* Generated by scripts/curriculum/build_lesson_misconception_witness_store.py; do not edit.",
            f" * Bake date: {date.today().isoformat()}.",
            " * Runtime: hermes_worker.pl load_runtime (the served worker vocabulary).",
            " * Stability pin: ITER7_TERM_CAP, ITER7_NEIGHBOR_CAP, and ITER7_MAX_EXTRA were unset.",
            f" * Scope: {scope}; {code_count} lesson codes.",
            " */",
            ":- multifile lesson_monitoring:lesson_misconception_witness_fact/4.",
            ":- multifile lesson_monitoring:lesson_misconception_witness_store_baked/0.",
    ]
    if mode == "full":
        lines.append("lesson_monitoring:lesson_misconception_witness_store_baked.")
    else:
        lines.append("% Verification samples do not activate the worker's store-first path.")
    lines.append("")
    return "\n".join(lines)


def bake(codes: list[str]) -> str:
    code_terms = ",".join(prolog_atom(code) for code in codes)
    goal = f"""
Codes=[{code_terms}],
forall(member(Code,Codes),
       ( lesson_monitoring:encoded_lesson(Code,_,_,_,_,_)
       -> true
       ; throw(error(existence_error(encoded_lesson,Code),_))
       )),
forall((member(Code,Codes),
        lesson_monitoring:lesson_misconception(Code,Operation,Name,Info),
        member(incompatibility_witness(Witness),Info)),
       write_term(user_output,
                  lesson_monitoring:lesson_misconception_witness_fact(
                      Code,Operation,Name,Witness),
                  [quoted(true),fullstop(true),nl(true),numbervars(true)]))
""".replace("\n", " ")
    proc = run_worker_goal(goal)
    if proc.returncode:
        raise RuntimeError(f"worker witness bake failed: {proc.stderr.strip()}")
    return proc.stdout


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    modes = parser.add_mutually_exclusive_group()
    modes.add_argument("--full", action="store_true", help="bake every encoded lesson (default)")
    modes.add_argument("--codes", nargs="+", metavar="CODE", help="bake only named codes")
    modes.add_argument("--sample-size", type=int, metavar="N", help="bake a deterministic three-stratum sample")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--dry-run", action="store_true", help="select and report codes without deriving witnesses")
    args = parser.parse_args()

    discovered = discover_codes()
    known = {row["code"]: row["stratum"] for row in discovered}
    if args.codes:
        mode = "codes"
        codes = sorted(dict.fromkeys(args.codes))
        missing = sorted(set(codes) - set(known))
        if missing:
            parser.error("unknown encoded lesson codes: " + ", ".join(missing))
    elif args.sample_size is not None:
        mode = f"sample-{args.sample_size}"
        try:
            codes = stratified_sample(discovered, args.sample_size)
        except (ValueError, RuntimeError) as exc:
            parser.error(str(exc))
    else:
        mode = "full"
        codes = sorted(known)

    output = args.output.resolve()
    strata = Counter(known[code] for code in codes)
    summary: dict[str, object] = {
        "mode": mode,
        "output": str(output),
        "codes": len(codes),
        "strata": dict(sorted(strata.items())),
        "iter7_caps": "unset",
        "store_first_activated": mode == "full",
    }
    if args.dry_run:
        summary["selected_codes"] = codes
        print(json.dumps(summary, indent=2, sort_keys=True))
        return 0

    started = time.monotonic()
    facts = bake(codes)
    content = generated_header(mode=mode, code_count=len(codes)) + facts
    output.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        "w", encoding="utf-8", dir=output.parent, prefix=output.name + ".", delete=False
    ) as stream:
        stream.write(content)
        temporary = Path(stream.name)
    temporary.replace(output)
    summary["facts"] = facts.count("lesson_monitoring:lesson_misconception_witness_fact(")
    summary["seconds"] = round(time.monotonic() - started, 3)
    print(json.dumps(summary, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
