#!/usr/bin/env python3
"""Non-destructive vision ingestion (Option B, both lanes).

Lane 1 — new-operation demand facts (promotion ruled by Tio, 2026-07-13; memo
in docs/proposals/2026-07-12-vision-unblock-and-slick-sprint.md, WS1): for
each lesson whose vision read shows Tier-1 whole-number arithmetic in an
operation the lesson does not map, emit one vision_lesson_strategy/4 fact
per registry-valid (op, kind) the events attest, into generated
lessons/im/grade_6_vision.pl / grade_7_vision.pl. The predicate is distinct
from explicit_lesson_strategy/4 on purpose: vision facts license execution
and compiler coverage (learner/activity_contract.pl builds vision_attested
obligations from them; the compiler counts them toward task_covered) but
never enter the monitoring-chart join, so a lesson's cluster-derived chart
— including cited cluster misconceptions — is untouched. No lesson is
converted, no existing mapping displaced, no misconception added.

Lane 2 — reviewed task instances (kind-blind, the landed step-2 semantics):
every Tier-1 event with a verbatim excerpt whose operation the lesson demands
(including via lane 1) becomes an e343_pdf reviewed_task_instance in
action_mapping_rules.json.

Source is the Opus-verified G6-7 harvest only; the Haiku-only G6-8 broad read
feeds the teacher digest (build_digest.py), never executable facts.

Dry-run by default; --apply writes the fact modules and merges the instances.
Re-runs are idempotent: facts regenerate identically (the base demand map
excludes the generated *_vision.pl files), instances dedupe by id.
"""
import os, json, re, argparse, subprocess, collections

REPO = os.path.dirname(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
TASK_OP_DOMAIN = {"add":"addition","subtract":"subtraction","multiply":"multiplication","divide":"division"}

def is_int(x): return bool(re.fullmatch(r'-?\d+', str(x).strip()))

def tier1_task(task_str):
    m = re.match(r'\s*([a-z_*/]+)\s*\(\s*(.+?)\s*\)\s*$', str(task_str))
    if not m: return None, None
    fn = m.group(1); args = [a.strip() for a in m.group(2).split(',')]
    fn = {"*":"multiply","/":"divide"}.get(fn, fn)
    if fn not in TASK_OP_DOMAIN or len(args) != 2 or not all(is_int(a) for a in args): return None, None
    a, b = int(args[0]), int(args[1])
    ok = ((fn=='add' and a>=0 and b>=0) or (fn=='subtract' and a>=b>=0)
          or (fn=='multiply' and a>0 and b>0) or (fn=='divide' and a>=0 and b>0))
    if not ok or abs(a) > 100000 or abs(b) > 100000: return None, None
    return f"{fn}({a}, {b})", TASK_OP_DOMAIN[fn]

def base_op_domains():
    """Per-lesson demanded op-domains BEFORE the vision facts: git-HEAD compiled
    mappings + hand-authored explicit facts. The generated *_vision.pl files are
    excluded so lane 1 regenerates identically on re-runs."""
    ops = collections.defaultdict(set)
    def scan(txt, pat):
        for m in re.finditer(pat, txt):
            ops[m.group(1)].add(m.group(2))
    head = subprocess.run(["git","show","HEAD:lessons/im/generated/compiled_action_mappings.pl"],
                          cwd=REPO, capture_output=True, text=True).stdout
    scan(head, r"compiled_lesson_strategy\('([^']+)',\s*([a-z_]+),")
    import glob
    for f in glob.glob(f"{REPO}/lessons/im/grade_*.pl") + [f"{REPO}/lessons/im/lesson_monitoring.pl"]:
        if f.endswith("_vision.pl"): continue
        scan(open(f).read(), r"explicit_lesson_strategy\('([^']+)',\s*([a-z_]+),")
    return ops

def slug(code): return code.lower().replace('-','_')

def lesson_sort_key(L): return (L["grade"], L["unit"], L["lesson"])

def fact_module_text(grade, facts_by_lesson, evidence):
    """facts_by_lesson: code -> sorted [(dom, kind)]; evidence: (code,dom,kind) ->
    (count, sample_task, pages, excerpt, unit_pdf)."""
    lines = [
        f"% lessons/im/grade_{grade}_vision.pl - Vision-attested strategy demands for grade {grade}",
        "% (generated by scripts/curriculum/ingest_vision.py; regenerate, do not hand-edit).",
        "%",
        f"% Each fact records an operation the grade-{grade} guide has students work inside",
        "% a lesson whose mapping did not yet carry it: whole-number arithmetic recovered",
        "% by the 2026-07-12 vision read of the rendered unit PDFs, with page-cited",
        "% excerpts in scripts/curriculum/vision_harvest/im_g6g7_vision_harvest.json.",
        "% Promotion ruling: Tio, 2026-07-13 (docs/proposals/",
        "% 2026-07-12-vision-unblock-and-slick-sprint.md, WS1).",
        "%",
        "% vision_lesson_strategy/4 is deliberately NOT explicit_lesson_strategy/4:",
        "% these facts license task execution (vision_attested obligations in",
        "% learner/activity_contract.pl) and compiler coverage, but stay out of the",
        "% monitoring-chart join, so cluster-derived charts and their cited",
        "% misconceptions are untouched. No lesson is converted, no existing mapping",
        "% displaced, no misconception added.",
        "",
        ":- multifile vision_lesson_strategy/4.",
        ":- discontiguous vision_lesson_strategy/4.",
        "",
    ]
    for code in sorted(facts_by_lesson):
        for dom, kind in facts_by_lesson[code]:
            n, task, pages, excerpt, pdf = evidence[(code, dom, kind)]
            ex = excerpt.replace("\n", " ")[:110]
            lines.append(f"% {code} {dom}/{kind}: {n} event(s), e.g. {task} "
                         f"({pdf} p.{pages}): \"{ex}\"")
            lines.append(f"vision_lesson_strategy('{code}', {dom}, {kind}, Info) :-")
            lines.append(f"    strategy_info({dom}, {kind}, Info).")
        lines.append("")
    return "\n".join(lines)

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--apply", action="store_true")
    a = ap.parse_args()
    lessons = json.load(open(os.path.join(os.path.dirname(__file__), "vision_harvest/im_g6g7_vision_harvest.json")))
    vocab = json.load(open(os.path.join(os.path.dirname(__file__), "vision_harvest/registry_vocab.json")))
    lessons.sort(key=lesson_sort_key)
    base = base_op_domains()

    # Lane 1: new-operation facts from registry-valid Tier-1 events.
    facts = collections.defaultdict(set)          # code -> {(dom, kind)}
    evidence = {}                                 # (code, dom, kind) -> (n, task, pages, excerpt, pdf)
    counts = collections.Counter()
    for L in lessons:
        code = L["code"]; g, u = L["grade"], L["unit"]
        unit_pdf = L.get("unit_pdf") or f"Grade{g}-{u}-Unit-teacher-guide-.pdf"
        for t in L.get("task_events", []):
            tf, dom = tier1_task(t.get("task",""))
            excerpt = (t.get("excerpt","") or "").strip()
            if not tf or not excerpt: continue
            if dom in base.get(code, set()): continue
            kind = t.get("kind") or "NONE"
            if kind == "NONE" or kind not in vocab.get(dom, []): continue
            key = (code, dom, kind)
            if key in evidence:
                n, task, pages, ex, pdf = evidence[key]
                evidence[key] = (n + 1, task, pages, ex, pdf)
            else:
                evidence[key] = (1, tf, str(t.get("pages","")), excerpt, unit_pdf)
            facts[code].add((dom, kind))
    facts_by_lesson = {c: sorted(v) for c, v in facts.items()}
    effective = collections.defaultdict(set, {c: set(v) for c, v in base.items()})
    for c, pairs in facts_by_lesson.items():
        effective[c].update(dom for dom, _ in pairs)

    # Lane 2: reviewed instances, kind-blind, over the effective demand map.
    reviewed = []; seen = set()
    inst_lessons = set(); left_out = 0
    for L in lessons:
        code = L["code"]; g, u = L["grade"], L["unit"]
        unit_pdf = L.get("unit_pdf") or f"Grade{g}-{u}-Unit-teacher-guide-.pdf"
        for i, t in enumerate(L.get("task_events", [])):
            tf, dom = tier1_task(t.get("task",""))
            excerpt = (t.get("excerpt","") or "").strip()[:200]
            if not tf or not excerpt: continue
            if dom not in effective.get(code, set()):
                left_out += 1
                continue
            tid = f"{slug(code)}_{tf.split('(')[0]}_{i}"
            if tid in seen: tid += "_x"
            seen.add(tid)
            reviewed.append({"id": tid, "code": code, "task": tf,
                             "position": (t.get("position","activity") or "activity")[:40],
                             "excerpt": excerpt,
                             "source": {"e343_pdf": {"file": unit_pdf, "pages": str(t.get("pages",""))}},
                             "deformations": []})
            inst_lessons.add(code)
    n_facts = sum(len(v) for v in facts_by_lesson.values())
    by_grade = collections.Counter(int(c.split('-')[1][1]) for c in facts_by_lesson)

    print("=== OPTION-B INGEST (%s) ===" % ("APPLY" if a.apply else "DRY-RUN"))
    print(f"lane 1: {n_facts} new-op facts across {len(facts_by_lesson)} lessons "
          f"(grade split: {dict(by_grade)})")
    print(f"lane 2: {len(reviewed)} Tier-1 reviewed_task_instances across {len(inst_lessons)} lessons")
    print(f"left in the digest (op still not demanded, or no registry-valid kind attested): {left_out}")
    if not a.apply:
        for r in reviewed[:5]: print("  ", r["code"], r["task"], r["source"]["e343_pdf"])
        return

    for grade in (6, 7):
        gf = {c: v for c, v in facts_by_lesson.items() if f"-G{grade}-" in c}
        path = f"{REPO}/lessons/im/grade_{grade}_vision.pl"
        open(path, "w").write(fact_module_text(grade, gf, evidence))
        print(f"WROTE {sum(len(v) for v in gf.values())} facts -> {path}")

    rules_path = f"{REPO}/scripts/curriculum/action_mapping_rules.json"
    rules = json.load(open(rules_path))
    existing = {r["id"] for r in rules.get("reviewed_task_instances", [])}
    added = [r for r in reviewed if r["id"] not in existing]
    rules.setdefault("reviewed_task_instances", []).extend(added)
    json.dump(rules, open(rules_path, "w"), indent=1)
    print(f"WROTE +{len(added)} reviewed_task_instances into action_mapping_rules.json")

if __name__ == "__main__": main()
