#!/usr/bin/env python3
"""Generate the automaton-binding registry from the shared research corpus."""
from __future__ import annotations

import argparse
import difflib
import sqlite3
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DATABASE = ROOT / "data" / "research" / "research_shared.db"
OUTPUT = ROOT / "knowledge" / "misconceptions" / "research_corpus_automaton_bindings.pl"


def atom(value: object | None) -> str:
    text = "" if value is None else str(value)
    return "'" + text.replace("\\", "\\\\").replace("'", "''") + "'"


def rows() -> list[sqlite3.Row]:
    if not DATABASE.is_file():
        raise RuntimeError(f"research corpus database is absent: {DATABASE.relative_to(ROOT)}")
    connection = sqlite3.connect(DATABASE)
    connection.row_factory = sqlite3.Row
    try:
        return connection.execute(
            """
            SELECT b.id AS binding_id, b.row_type, b.row_id, b.automaton_ref,
                   b.operation, b.kind, b.role, b.source, b.confidence,
                   b.score, b.evidence, b.notes,
                   COALESCE(error_article.bibtex_key, strategy_article.bibtex_key, '') AS bibtex_key
              FROM automaton_instance_bindings AS b
              LEFT JOIN error_instances AS error_row
                ON b.row_type = 'misconception' AND error_row.id = b.row_id
              LEFT JOIN articles AS error_article ON error_article.id = error_row.article_id
              LEFT JOIN strategy_instances AS strategy_row
                ON b.row_type = 'strategy' AND strategy_row.id = b.row_id
              LEFT JOIN articles AS strategy_article ON strategy_article.id = strategy_row.article_id
             ORDER BY b.id
            """
        ).fetchall()
    finally:
        connection.close()


def render() -> str:
    bindings = rows()
    lines = [
        "/** <module> Generated research-corpus automaton bindings",
        " *",
        " * This finite registry is generated from data/research/research_shared.db",
        " * automaton_instance_bindings. BibTeX keys are recovered through the",
        " * appropriate error_instances or strategy_instances article join.",
        " *",
        " * Generated by scripts/extract_research_corpus_automaton_bindings.py.",
        " * Regenerate: python3 scripts/extract_research_corpus_automaton_bindings.py",
        " */",
        "",
        ":- module(research_corpus_automaton_bindings,",
        "          [ research_corpus_automaton_binding_row/1,",
        "            research_corpus_automaton_binding_count/1",
        "          ]).",
        "",
        f"research_corpus_automaton_binding_count({len(bindings)}).",
        "",
    ]
    for binding in bindings:
        values = (
            binding["binding_id"], binding["row_type"], binding["row_id"],
            binding["bibtex_key"], binding["operation"], binding["kind"],
            binding["automaton_ref"], binding["role"], binding["source"],
            binding["confidence"], binding["score"], binding["evidence"], binding["notes"],
        )
        rendered = [str(values[0]), atom(values[1]), str(values[2])]
        rendered.extend(atom(value) for value in values[3:])
        lines.append("research_corpus_automaton_binding_row(row(" + ", ".join(rendered) + ")).")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true", help="fail if the generated registry is stale")
    args = parser.parse_args()
    expected = render()
    actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.is_file() else ""
    if args.check:
        if actual == expected:
            print(f"research corpus automaton binding registry is current: {OUTPUT.relative_to(ROOT)}")
            return 0
        with tempfile.NamedTemporaryFile("w", encoding="utf-8", suffix=".pl", delete=False) as temp:
            temp.write(expected)
            temp_path = Path(temp.name)
        print("research corpus automaton binding registry is stale; run python3 scripts/extract_research_corpus_automaton_bindings.py")
        for line in list(difflib.unified_diff(actual.splitlines(), expected.splitlines(), fromfile=str(OUTPUT), tofile=str(temp_path), lineterm=""))[:12]:
            print(line)
        temp_path.unlink(missing_ok=True)
        return 1
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"wrote {OUTPUT.relative_to(ROOT)}: {len(bindings := rows())} bindings")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
