% Generated by scripts/extract_capability_registry.py.
% Regenerate: python3 scripts/extract_capability_registry.py
:- module(capability_registry,
          [ capability/5,
            capability_route/3,
            capability_page/2
          ]).

capability('accommodation_witness', 'cw_accommodation', 'unclassified', ['source', 'target'], unrouted).
capability('ace_of_bases_render', 'base_ten_scene', 'render', [], routed_paged).
capability('action_cluster_witness', 'cw_action_cluster', 'unclassified', ['cluster', 'kind', 'operation', 'source'], unrouted).
capability('algebra_claim_witness', 'cw_algebra_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('area_compare', 'area_model_scene', 'render', ['da', 'db', 'na', 'nb'], routed_paged).
capability('area_render', 'area_model_scene', 'render', [], routed_paged).
capability('arithmetic_property_witness', 'cw_arithmetic_property_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('axiom_hierarchy_witness', 'hermes_worker', 'arche_trace', ['kind'], unrouted).
capability('axiom_pack_witness', 'cw_axiom_pack', 'arche_trace', ['pack', 'source'], unrouted).
capability('axiom_toggle', 'hermes_worker', 'arche_trace', ['action'], routed_paged).
capability('balance_compare', 'balance_scale_scene', 'render', ['a', 'b', 'c'], routed_paged).
capability('balance_render', 'balance_scale_scene', 'render', ['a', 'b', 'c'], routed_paged).
capability('balance_solve_witness', 'balance_scale_scene', 'render', ['a', 'b', 'c'], unrouted).
capability('base_ten_compare', 'base_ten_scene', 'render', ['a', 'b', 'base'], routed_paged).
capability('base_ten_render', 'base_ten_scene', 'render', [], routed_paged).
capability('batch_event_score', 'hermes_worker', 'unclassified', ['events'], routed_paged).
capability('benny_demo', 'misconceptions_benny_demo', 'unclassified', [], routed_paged).
capability('brandom_backstop', 'sequent_brandom_bridge', 'arche_trace', [], routed_paged).
capability('brandomian_check', 'sequent_brandom_bridge', 'arche_trace', ['commitments'], routed_paged).
capability('calculus_claim_witness', 'cw_calculus_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('canonical_check', 'hermes_worker', 'crosswalk', ['terms'], routed_paged).
capability('canonical_contract', 'canonical_all', 'crosswalk', [], routed_paged).
capability('capability_atlas', 'hermes_worker', 'infrastructure', [], routed_paged).
capability('carving_operation_summary', 'carving_query', 'carving', ['operation'], routed_paged).
capability('carving_strategy_proof', 'carving_query', 'carving', ['operation', 'x', 'y', 'z'], routed_paged).
capability('commitment_match', 'commitment_matcher', 'unclassified', ['content'], unrouted).
capability('compute', 'hermes_worker', 'learner', [], routed_paged).
capability('corpus_grammar_summary', 'corpus_attested_grammar', 'unclassified', [], unrouted).
capability('counting_claim_witness', 'cw_counting_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('critique_bad_infinite', 'critique', 'unclassified', ['proof'], unrouted).
capability('decimal_claim_witness', 'cw_decimal_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('defeasible_classify', 'defeasible_inference', 'unclassified', ['defeater_set', 'inference_id'], unrouted).
capability('deontic_consequences', 'deontic_scorekeeper', 'arche_trace', ['agent', 'commitments'], routed_paged).
capability('deontic_crisis', 'deontic_scorekeeper', 'arche_trace', ['agent', 'commitments', 'entitlements'], routed_paged).
capability('deontic_requires_entitlement', 'deontic_scorekeeper', 'arche_trace', ['proposition'], routed_paged).
capability('deontic_scorecard', 'deontic_scorekeeper', 'arche_trace', ['agent', 'commitments', 'entitlements'], routed_paged).
capability('deontic_up_level', 'deontic_scorekeeper', 'arche_trace', ['agent', 'commitments'], routed_paged).
capability('diagnose_error', 'hermes_worker', 'misconceptions', ['domain', 'got', 'input'], routed_paged).
capability('discourse_features', 'discourse_features', 'unclassified', ['utterances'], unrouted).
capability('discourse_pragmatics', 'discourse_pragmatics', 'unclassified', ['utterances'], unrouted).
capability('domain_context_witness', 'cw_domain_context', 'unclassified', ['context', 'domain', 'source'], unrouted).
capability('elaborations', 'automaton_analyzer', 'unclassified', [], unrouted).
capability('embodied_proof_witness', 'embodied_prover', 'unclassified', ['resources', 'sequent'], unrouted).
capability('eml_transition_witness', 'sequent_engine', 'unclassified', ['from', 'to'], unrouted).
capability('event_score', 'hermes_event_scoring', 'unclassified', ['event'], routed_paged).
capability('executable_practice_witness', 'cw_executable_practice', 'unclassified', ['source', 'variant'], unrouted).
capability('expressive_power', 'hermes_worker', 'unclassified', ['lesson'], routed_paged).
capability('field_connectivity_audit', 'field_context', 'monitoring', [], routed_paged).
capability('field_context', 'field_context', 'monitoring', ['lesson_code'], routed_paged).
capability('fraction_cgi_addition', 'fraction_cgi_dispatch', 'render', ['d', 'kind', 'na', 'nb'], routed_paged).
capability('fraction_claim_witness', 'cw_fraction_claim', 'render', ['canonical', 'source'], unrouted).
capability('fraction_compare', 'fraction_bars_scene', 'render', ['a', 'b', 'kind'], routed_paged).
capability('fraction_extra_claim_witness', 'cw_fraction_extra_claim', 'render', ['canonical', 'source'], unrouted).
capability('fraction_render', 'hermes_worker', 'render', ['kind'], routed_paged).
capability('fsm_engine_witness', 'cw_fsm_engine', 'unclassified', ['descriptor', 'source'], unrouted).
capability('geometry', 'hermes_worker', 'geometry_witness', ['args', 'predicate'], routed_paged).
capability('geometry_angle_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_area_perimeter_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_attribute_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_ccss_standard_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept'], unrouted).
capability('geometry_classification_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_coordinate_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_cross_link_witness', 'hermes_worker', 'geometry_witness', ['relation', 'source', 'status', 'target'], unrouted).
capability('geometry_developmental_arc_witness', 'hermes_worker', 'geometry_witness', ['arc_id'], unrouted).
capability('geometry_entailment_witness', 'sequent_engine', 'geometry_witness', ['entailed', 'entailer'], unrouted).
capability('geometry_im_grade5_standard_anchor_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept', 'framework'], unrouted).
capability('geometry_im_grade6_lesson_standard_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept'], unrouted).
capability('geometry_im_grade7_lesson_standard_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept'], unrouted).
capability('geometry_im_grade8_lesson_standard_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept'], unrouted).
capability('geometry_indiana_standard_witness', 'hermes_worker', 'geometry_witness', ['code', 'concept'], unrouted).
capability('geometry_lakoff_nunez_metaphor_witness', 'hermes_worker', 'geometry_witness', ['concept', 'metaphor'], unrouted).
capability('geometry_material_profile_witness', 'hermes_worker', 'geometry_witness', ['concept'], unrouted).
capability('geometry_measurement_misconception_witness', 'hermes_worker', 'geometry_witness', ['id_value'], unrouted).
capability('geometry_measuring_stick_metaphor_witness', 'hermes_worker', 'geometry_witness', ['concept', 'metaphor'], unrouted).
capability('geometry_n103_bootstrap_witness', 'hermes_worker', 'geometry_witness', ['bootstrap_id'], unrouted).
capability('geometry_pck_classification_witness', 'hermes_worker', 'geometry_witness', ['concept'], unrouted).
capability('geometry_pythagorean_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_quadrilateral_entailment_witness', 'hermes_worker', 'geometry_witness', ['entailed', 'entailer'], unrouted).
capability('geometry_shape_recognition_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_similarity_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_strength_lift_coverage_witness', 'hermes_worker', 'geometry_witness', [], unrouted).
capability('geometry_synthesizer_anchor_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_synthesizer_triangulation_witness', 'hermes_worker', 'geometry_witness', ['concept'], unrouted).
capability('geometry_transformation_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_van_de_walle_bootstrap_witness', 'hermes_worker', 'geometry_witness', ['bootstrap_id'], unrouted).
capability('geometry_van_hiele_level_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_van_hiele_marker_witness', 'hermes_worker', 'geometry_witness', ['concept', 'level'], unrouted).
capability('geometry_van_hiele_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('geometry_volume_surface_area_material_witness', 'hermes_worker', 'geometry_witness', ['claim_id'], unrouted).
capability('gesture_alignment', 'gesture_alignment', 'unclassified', ['observations', 'utterances'], unrouted).
capability('get_base', 'cgi_base', 'infrastructure', [], unrouted).
capability('godel_primes_witness', 'cw_godel_primes', 'unclassified', ['query', 'source'], unrouted).
capability('ground', 'hermes_encyclopedia', 'unclassified', ['query'], routed_paged).
capability('grounded_arith_witness', 'cw_grounded_arith', 'unclassified', ['inputs', 'operation', 'output', 'source'], unrouted).
capability('grounding_for', 'hermes_encyclopedia', 'unclassified', ['operation'], routed_paged).
capability('grounding_inference_witness', 'grounding_metaphors', 'unclassified', ['inference', 'metaphor'], unrouted).
capability('grounding_metaphor_witness', 'cw_grounding_metaphor', 'unclassified', ['anchor', 'metaphor', 'source'], unrouted).
capability('grounding_metaphors', 'hermes_encyclopedia', 'unclassified', [], routed_paged).
capability('health', 'capability_registry', 'infrastructure', [], unrouted).
capability('hybridization_render', 'hybridization_scene', 'render', [], routed_paged).
capability('hyperedges', 'hermes_worker', 'arche_trace', ['kind'], routed_paged).
capability('image_schema', 'grounding_to_primitive', 'unclassified', [], unrouted).
capability('incoherent_witness', 'sequent_engine', 'unclassified', ['context'], unrouted).
capability('incompatibility_discovery_witness', 'incompatibility_discovery', 'arche_trace', ['context', 'set'], unrouted).
capability('incompatibility_entailment_witness', 'incompatibility_sets', 'arche_trace', ['replaced', 'replacement'], unrouted).
capability('integer_signed_claim_witness', 'cw_integer_signed_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('intersubjective_material_witness', 'intersubjective_praxis', 'unclassified', ['from', 'to'], unrouted).
capability('knowledge', 'hermes_worker', 'learner', [], routed_paged).
capability('learner_reset', 'more_machine_learner', 'learner', [], routed_paged).
capability('lesson_deformation_chart', 'lesson_deformation_chart', 'unclassified', ['code'], routed_paged).
capability('lesson_misconception_incompatibility_witness', 'hermes_worker', 'unclassified', ['lesson_code', 'name', 'operation'], unrouted).
capability('list_misconceptions', 'hermes_encyclopedia', 'misconceptions', ['domain'], routed_paged).
capability('list_standards', 'hermes_encyclopedia', 'unclassified', ['framework'], routed_paged).
capability('list_strategies', 'hermes_encyclopedia', 'unclassified', [], routed_paged).
capability('lit_search', 'hermes_encyclopedia', 'unclassified', ['query'], routed_paged).
capability('magnitude_equivalence_claim_witness', 'cw_magnitude_equivalence_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('material_inference_witness', 'cw_material_inference', 'unclassified', ['conclusion', 'inference_id', 'premises', 'source'], unrouted).
capability('media_alignment', 'media_alignment', 'unclassified', ['segments', 'source'], routed_paged).
capability('metaphor_break_witness', 'cw_metaphor_break', 'unclassified', ['detail', 'inference', 'metaphor', 'source'], unrouted).
capability('misconception_hook_witness', 'cw_misconception_hook', 'misconceptions', ['family', 'operation', 'outcome', 'source'], unrouted).
capability('misconception_incompatibility_witness', 'misconception_registry', 'misconceptions', ['conflict', 'move'], unrouted).
capability('misconception_jumps_witness', 'visualization', 'misconceptions', ['a', 'b', 'deformation', 'operation'], unrouted).
capability('modal_context_witness', 'cw_modal_context', 'unclassified', ['context', 'source', 'term'], unrouted).
capability('monitoring_chart_export', 'hermes_worker', 'monitoring', ['lesson_code'], routed_paged).
capability('mua_coherence_witness', 'cw_mua_coherence', 'unclassified', ['input', 'source', 'subject'], unrouted).
capability('mua_kind_coherence_witness', 'mua_relations', 'unclassified', ['kind', 'row_text'], unrouted).
capability('mult_div_family_witness', 'standard_3_ca_3_4', 'unclassified', ['a', 'b'], unrouted).
capability('multiplication_division_claim_witness', 'cw_multiplication_division_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('multiply_array_witness', 'standard_3_ca_3_4', 'unclassified', ['cols', 'rows'], unrouted).
capability('normative_crisis_witness', 'cw_normative_crisis', 'unclassified', ['context', 'goal', 'source'], unrouted).
capability('notation_monitoring_chart', 'lesson_notation_chart', 'render', ['code'], routed_paged).
capability('notation_render', 'hermes_worker', 'render', ['kind'], routed_paged).
capability('number_line_compare', 'number_line_scene', 'render', ['a', 'b', 'operation'], routed_paged).
capability('number_line_render', 'number_line_scene', 'render', [], routed_paged).
capability('number_theory_self_defeat_witness', 'sequent_engine', 'unclassified', ['list'], unrouted).
capability('orr_entry_witness', 'cw_orr_entry', 'unclassified', ['source', 'variant'], unrouted).
capability('pair_candidate_witness', 'hermes_pair_scoring', 'unclassified', ['event_a', 'event_b'], unrouted).
capability('pair_graph', 'hermes_pair_scoring', 'unclassified', ['events'], routed_paged).
capability('pair_score', 'hermes_pair_scoring', 'unclassified', ['events'], routed_paged).
capability('place_value_chart_render', 'place_value_chart_scene', 'render', [], routed_paged).
capability('place_value_number_claim_witness', 'cw_place_value_number_claim', 'render', ['canonical', 'source'], unrouted).
capability('pml_score', 'hermes_encyclopedia', 'pml', ['clauses'], routed_paged).
capability('practice_vocabulary_witness', 'cw_practice_vocabulary', 'unclassified', ['key', 'source'], unrouted).
capability('primitive_for_practice', 'grounding_to_primitive', 'unclassified', [], unrouted).
capability('productive_deformation_witness', 'cw_productive_deformation', 'unclassified', ['deformation', 'family', 'operation', 'productive', 'source'], unrouted).
capability('query_misconception', 'hermes_worker', 'misconceptions', ['description', 'domain', 'source'], routed_paged).
capability('ranked_figures', 'hermes_worker', 'monitoring', ['lesson_code'], routed_paged).
capability('ratio_proportion_claim_witness', 'cw_ratio_proportion_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('render_coverage', 'misconception_render_coverage', 'monitoring', [], routed_paged).
capability('reorganize', 'fraction_band_ladder', 'learner', [], routed_paged).
capability('representation_candidates', 'hermes_worker', 'crosswalk', ['misconception', 'strategy'], routed_paged).
capability('representation_check', 'hermes_worker', 'crosswalk', ['mode', 'representation'], routed_paged).
capability('representation_spec_check', 'hermes_worker', 'crosswalk', ['representation'], routed_paged).
capability('representation_spine_witness', 'representation_spine', 'crosswalk', ['concept'], unrouted).
capability('robinson_axiom_witness', 'sequent_engine', 'unclassified', ['axiom', 'claim'], unrouted).
capability('semantic_material_witness', 'semantic_axioms', 'unclassified', ['from', 'to'], unrouted).
capability('sequent_proof_witness', 'cw_sequent_proof', 'arche_trace', ['sequent', 'source'], routed_paged).
capability('set_base', 'cgi_base', 'infrastructure', ['base'], unrouted).
capability('set_grouping_compare', 'set_grouping_scene', 'render', ['a', 'b'], routed_paged).
capability('set_grouping_render', 'set_grouping_scene', 'render', [], routed_paged).
capability('standard_1_ca_1_making_ten_witness', 'standard_1_ca_1', 'standards', ['a', 'b'], unrouted).
capability('standard_1_ca_3_add_by_place_value_witness', 'standard_1_ca_3', 'standards', ['a', 'b'], unrouted).
capability('standard_1_ns_1_count_by_fives_witness', 'standard_1_ns_1', 'standards', ['from', 'to'], unrouted).
capability('standard_1_ns_2_place_value_witness', 'standard_1_ns_2', 'standards', ['number'], unrouted).
capability('standard_2_ca_2_add_three_digit_witness', 'standard_2_ca_2', 'standards', ['a', 'b'], unrouted).
capability('standard_2_ns_1_count_by_twos_witness', 'standard_2_ns_1', 'standards', ['from', 'to'], unrouted).
capability('standard_2_ns_2_4_place_value_witness', 'standard_2_ns_2_4', 'standards', ['number'], unrouted).
capability('standard_2_ns_3_parity_witness', 'standard_2_ns_3', 'standards', ['number', 'result'], unrouted).
capability('standard_2_ns_5_place_value_comparison_witness', 'standard_2_ns_5', 'standards', ['left', 'right'], unrouted).
capability('standard_3_ca_3_4_fact_family_witness', 'standard_3_ca_3_4', 'standards', ['a', 'b'], unrouted).
capability('standard_3_ca_5_mult_skip_count_witness', 'standard_3_ca_5', 'standards', ['factor', 'times'], unrouted).
capability('standard_3_ns_2_unit_fraction_witness', 'standard_3_ns_2', 'standards', ['denominator'], unrouted).
capability('standard_3_ns_5_fraction_comparison_witness', 'standard_3_ns_5', 'standards', ['left', 'result', 'right'], unrouted).
capability('standard_k_ca_1_3_complement_witness', 'standard_k_ca_1_3', 'standards', ['given'], unrouted).
capability('standard_k_ns_1_count_by_ones_witness', 'standard_k_ns_1', 'standards', ['from', 'to'], unrouted).
capability('standard_k_ns_2_represent_count_witness', 'standard_k_ns_2', 'standards', ['object_count'], unrouted).
capability('standard_k_ns_3_order_independence_witness', 'standard_k_ns_3', 'standards', ['objects'], unrouted).
capability('standard_k_ns_4_verify_subitizing_witness', 'standard_k_ns_4', 'standards', ['pattern'], unrouted).
capability('standard_k_ns_5_6_compare_groups_witness', 'standard_k_ns_5_6', 'standards', ['group_a', 'group_b'], unrouted).
capability('standard_k_ns_7_place_value_witness', 'standard_k_ns_7', 'standards', ['number'], unrouted).
capability('strategy_trace', 'hermes_encyclopedia', 'unclassified', ['input', 'strategy'], routed_paged).
capability('target_expressive_power_witness', 'hermes_worker', 'unclassified', ['target'], unrouted).
capability('teacher_layer', 'teacher_layer', 'render', [], routed_paged).
capability('trace_adjudication', 'trace_adjudication', 'unclassified', ['ledger', 'utterances'], unrouted).
capability('unit_coordination_svg', 'unit_coordination_viz', 'unclassified', ['base', 'denominator', 'numerator', 'value_up'], unrouted).
capability('unit_coordination_witness', 'cw_unit_coordination', 'unclassified', ['detail', 'key', 'source'], unrouted).
capability('unit_echo_render', 'unit_echo_scene', 'unclassified', ['base', 'iterations'], routed_paged).
capability('validate_reader_axioms', 'hermes_encyclopedia', 'pml', ['clauses', 'lesson_code'], unrouted).
capability('viability_witness', 'cw_viability', 'unclassified', ['cost', 'resources', 'source'], unrouted).
capability('visualize_coordination', 'unit_coordination_viz', 'learner', [], routed_paged).
capability('whole_number_addsub_claim_witness', 'cw_whole_number_addsub_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('whole_number_claim_witness', 'cw_whole_number_claim', 'unclassified', ['canonical', 'source'], unrouted).
capability('arche-trace/differance_juncture.pl', 'differance_juncture', 'arche_trace', [], orphan_module).
capability('arche-trace/registry_incompatibility_adapter.pl', 'registry_incompatibility_adapter', 'arche_trace', [], orphan_module).
capability('crosswalk/merge_evidence.pl', 'merge_evidence', 'crosswalk', [], orphan_module).
capability('formalization/axioms_geometry.pl', 'axioms_geometry', 'synthesis', [], orphan_module).
capability('formalization/axioms_number_theory.pl', 'axioms_number_theory', 'synthesis', [], orphan_module).
capability('formalization/axioms_robinson.pl', 'axioms_robinson', 'synthesis', [], orphan_module).
capability('formalization/synthesis/run_add.pl', 'run_add', 'synthesis', [], orphan_module).
capability('formalization/synthesis/run_lazy.pl', 'run_lazy', 'synthesis', [], orphan_module).
capability('formalization/synthesis/run_synth.pl', 'run_synth', 'synthesis', [], orphan_module).
capability('formalization/synthesis/synth.pl', 'synth', 'synthesis', [], orphan_module).
capability('formalization/synthesis/synth_lazy.pl', 'synth_lazy', 'synthesis', [], orphan_module).
capability('geometry/geometry_bridge.pl', 'geometry_bridge', 'geometry_witness', [], orphan_module).
capability('learner/activity_contract.pl', 'activity_contract', 'learner', [], orphan_module).
capability('learner/arithmetic_machine.pl', 'arithmetic_machine', 'learner', [], orphan_module).
capability('learner/atlas/basis_transitions.pl', 'basis_transitions', 'learner', [], orphan_module).
capability('learner/atlas/task_quotient.pl', 'task_quotient', 'learner', [], orphan_module).
capability('learner/axioms_domains.pl', 'axioms_domains', 'learner', [], orphan_module).
capability('learner/crisis_processor.pl', 'crisis_processor', 'learner', [], orphan_module).
capability('learner/curriculum_processor.pl', 'curriculum_processor', 'learner', [], orphan_module).
capability('learner/fraction_band_ladder.pl', 'fraction_band_ladder', 'learner', [], orphan_module).
capability('learner/interactive_ui.pl', 'interactive_ui', 'learner', [], orphan_module).
capability('learner/knowledge_manager.pl', 'knowledge_manager', 'learner', [], orphan_module).
capability('learner/learned_knowledge_v2.pl', 'learned_knowledge_v2', 'learner', [], orphan_module).
capability('learner/main.pl', 'main', 'learner', [], orphan_module).
capability('learner/primordial_start.pl', 'primordial_start', 'learner', [], orphan_module).
capability('learner/reorg_demo_server.pl', 'reorg_demo_server', 'learner', [], orphan_module).
capability('learner/reorg_domains/fraction.pl', 'reorg_fraction', 'learner', [], orphan_module).
capability('learner/reorg_domains/fraction_algebra.pl', 'reorg_fraction_algebra', 'learner', [], orphan_module).
capability('learner/reorg_domains/fraction_improper.pl', 'reorg_fraction_improper', 'learner', [], orphan_module).
capability('learner/reorg_domains/fraction_of_fraction.pl', 'reorg_fraction_of_fraction', 'learner', [], orphan_module).
capability('learner/reorg_domains/fraction_splitting.pl', 'reorg_fraction_splitting', 'learner', [], orphan_module).
capability('learner/server.pl', 'server', 'learner', [], orphan_module).
capability('learner/server_visualization.pl', 'server_visualization', 'learner', [], orphan_module).
capability('learner/task_transition.pl', 'task_transition', 'learner', [], orphan_module).
capability('lessons/im/generated/compiled_task_instances.pl', 'compiled_task_instances', 'workflow', [], orphan_module).
capability('lessons/im/generated/vision_lesson_digest.pl', 'vision_lesson_digest', 'workflow', [], orphan_module).
capability('lessons/im/im_glossary.pl', 'im_glossary', 'workflow', [], orphan_module).
capability('lessons/im_harness.pl', 'im_harness', 'workflow', [], orphan_module).
capability('misconceptions/literature_canonical_mappings.pl', 'literature_canonical_mappings', 'misconceptions', [], orphan_module).
capability('misconceptions/pml_wire.pl', 'pml_wire', 'misconceptions', [], orphan_module).
capability('more-zeeman/prolog/zeeman_bifurcation.pl', 'zeeman_bifurcation', 'zeeman', [], orphan_module).
capability('more-zeeman/prolog/zeeman_machine.pl', 'zeeman_machine', 'zeeman', [], orphan_module).
capability('more-zeeman/prolog/zeeman_pml_bridge.pl', 'zeeman_pml_bridge', 'zeeman', [], orphan_module).
capability('more-zeeman/prolog/zeeman_tape.pl', 'zeeman_tape', 'zeeman', [], orphan_module).
capability('pml/audit_connectors.pl', 'audit_connectors', 'pml', [], orphan_module).
capability('pml/axioms_eml.pl', 'axioms_eml', 'pml', [], orphan_module).
capability('pml/mua_conjectures.pl', 'mua_conjectures', 'pml', [], orphan_module).
capability('pml/mua_health.pl', 'mua_health', 'pml', [], orphan_module).
capability('pml/talkmoves_adapter.pl', 'talkmoves_adapter', 'pml', [], orphan_module).
capability('strategies/math/unit_coordination_viz.pl', 'unit_coordination_viz', 'synthesis', [], orphan_module).
capability('strategies/math_benchmark.pl', 'math_benchmark', 'synthesis', [], orphan_module).
capability('strategies/render/rigid_motion_scene.pl', 'rigid_motion_scene', 'synthesis', [], orphan_module).
capability('tools/axiom_toggle.pl', 'axiom_toggle', 'infrastructure', [], orphan_module).

capability_route('ace_of_bases_render', 'POST', '/api/monitoring_visuals').
capability_route('ace_of_bases_render', 'POST', '/api/render').
capability_route('area_compare', 'POST', '/api/monitoring_visuals').
capability_route('area_compare', 'POST', '/api/render').
capability_route('area_render', 'POST', '/api/chat').
capability_route('area_render', 'POST', '/api/monitoring_visuals').
capability_route('area_render', 'POST', '/api/render').
capability_route('axiom_toggle', 'POST', '/api/axiom_toggle').
capability_route('balance_compare', 'POST', '/api/monitoring_visuals').
capability_route('balance_compare', 'POST', '/api/render').
capability_route('balance_render', 'POST', '/api/chat').
capability_route('balance_render', 'POST', '/api/monitoring_visuals').
capability_route('balance_render', 'POST', '/api/render').
capability_route('base_ten_compare', 'POST', '/api/monitoring_visuals').
capability_route('base_ten_compare', 'POST', '/api/render').
capability_route('base_ten_render', 'POST', '/api/chat').
capability_route('base_ten_render', 'POST', '/api/monitoring_visuals').
capability_route('base_ten_render', 'POST', '/api/render').
capability_route('batch_event_score', 'POST', '/api/event_score').
capability_route('benny_demo', 'POST', '/api/benny_demo').
capability_route('brandom_backstop', 'POST', '/api/brandom_backstop').
capability_route('brandomian_check', 'POST', '/api/brandomian_check').
capability_route('canonical_check', 'POST', '/api/canonical_check').
capability_route('canonical_contract', 'POST', '/api/canonical_contract').
capability_route('capability_atlas', 'GET', '/api/capabilities').
capability_route('carving_operation_summary', 'POST', '/api/carving_operation_summary').
capability_route('carving_strategy_proof', 'POST', '/api/carving_strategy_proof').
capability_route('compute', 'POST', '/api/compute').
capability_route('deontic_consequences', 'POST', '/api/deontic_consequences').
capability_route('deontic_crisis', 'POST', '/api/crisis').
capability_route('deontic_requires_entitlement', 'POST', '/api/deontic_requires_entitlement').
capability_route('deontic_scorecard', 'POST', '/api/deontic_scorecard').
capability_route('deontic_up_level', 'POST', '/api/deontic_up_level').
capability_route('diagnose_error', 'POST', '/api/diagnose_error').
capability_route('event_score', 'POST', '/api/event_score').
capability_route('expressive_power', 'POST', '/api/expressive_power').
capability_route('field_connectivity_audit', 'POST', '/api/field_connectivity_audit').
capability_route('field_context', 'POST', '/api/field_context').
capability_route('fraction_cgi_addition', 'POST', '/api/fraction_cgi_addition').
capability_route('fraction_compare', 'GET', '/api/fraction/compare').
capability_route('fraction_compare', 'GET', '/api/fraction/render').
capability_route('fraction_compare', 'POST', '/api/chat').
capability_route('fraction_compare', 'POST', '/api/render').
capability_route('fraction_render', 'GET', '/api/fraction/compare').
capability_route('fraction_render', 'GET', '/api/fraction/render').
capability_route('fraction_render', 'POST', '/api/monitoring_visuals').
capability_route('fraction_render', 'POST', '/api/render').
capability_route('geometry', 'POST', '/api/geometry').
capability_route('ground', 'POST', '/api/chat').
capability_route('grounding_for', 'POST', '/api/grounding').
capability_route('grounding_metaphors', 'POST', '/api/grounding').
capability_route('hybridization_render', 'POST', '/api/monitoring_visuals').
capability_route('hybridization_render', 'POST', '/api/render').
capability_route('hyperedges', 'POST', '/api/hyperedges').
capability_route('knowledge', 'GET', '/api/knowledge').
capability_route('learner_reset', 'POST', '/api/learner/reset').
capability_route('lesson_deformation_chart', 'POST', '/api/lesson_deformation_chart').
capability_route('list_misconceptions', 'POST', '/api/misconceptions').
capability_route('list_standards', 'POST', '/api/standards').
capability_route('list_strategies', 'POST', '/api/strategies').
capability_route('lit_search', 'POST', '/api/literature').
capability_route('media_alignment', 'POST', '/api/media_transcribe').
capability_route('monitoring_chart_export', 'POST', '/api/monitoring_chart_export').
capability_route('monitoring_chart_export', 'POST', '/api/monitoring_visuals').
capability_route('notation_monitoring_chart', 'POST', '/api/notation_monitoring_chart').
capability_route('notation_render', 'POST', '/api/notation_render').
capability_route('number_line_compare', 'POST', '/api/render').
capability_route('number_line_render', 'POST', '/api/monitoring_visuals').
capability_route('number_line_render', 'POST', '/api/render').
capability_route('pair_graph', 'POST', '/api/pair_graph').
capability_route('pair_score', 'POST', '/api/pair_graph').
capability_route('place_value_chart_render', 'POST', '/api/monitoring_visuals').
capability_route('place_value_chart_render', 'POST', '/api/render').
capability_route('pml_score', 'POST', '/api/pml_score').
capability_route('query_misconception', 'POST', '/api/query_misconception').
capability_route('ranked_figures', 'POST', '/api/ranked_figures').
capability_route('render_coverage', 'POST', '/api/render_coverage').
capability_route('reorganize', 'GET', '/api/reorganize').
capability_route('representation_candidates', 'POST', '/api/monitoring_visuals').
capability_route('representation_check', 'POST', '/api/monitoring_visuals').
capability_route('representation_spec_check', 'POST', '/api/monitoring_visuals').
capability_route('sequent_proof_witness', 'POST', '/api/sequent_proof').
capability_route('set_grouping_compare', 'POST', '/api/render').
capability_route('set_grouping_render', 'POST', '/api/chat').
capability_route('set_grouping_render', 'POST', '/api/monitoring_visuals').
capability_route('set_grouping_render', 'POST', '/api/render').
capability_route('strategy_trace', 'POST', '/api/render').
capability_route('strategy_trace', 'POST', '/api/strategy_trace').
capability_route('teacher_layer', 'POST', '/api/render').
capability_route('unit_echo_render', 'POST', '/api/monitoring_visuals').
capability_route('unit_echo_render', 'POST', '/api/render').
capability_route('visualize_coordination', 'GET', '/api/visualize/coordination').

capability_page('ace_of_bases_render', '/hermes/app/web/console.html').
capability_page('ace_of_bases_render', '/hermes/app/web/discussions.html').
capability_page('ace_of_bases_render', '/more-zeeman/area-model/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/balance-scale/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/base-ten/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('ace_of_bases_render', '/more-zeeman/fraction-bars/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/hybridization/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/monitoring_chart.html').
capability_page('ace_of_bases_render', '/more-zeeman/notation/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/number-line/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/place-value-chart/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/set-grouping/index.html').
capability_page('ace_of_bases_render', '/more-zeeman/unit-echo/index.html').
capability_page('area_compare', '/hermes/app/web/console.html').
capability_page('area_compare', '/hermes/app/web/discussions.html').
capability_page('area_compare', '/more-zeeman/area-model/index.html').
capability_page('area_compare', '/more-zeeman/balance-scale/index.html').
capability_page('area_compare', '/more-zeeman/base-ten/index.html').
capability_page('area_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('area_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('area_compare', '/more-zeeman/hybridization/index.html').
capability_page('area_compare', '/more-zeeman/monitoring_chart.html').
capability_page('area_compare', '/more-zeeman/notation/index.html').
capability_page('area_compare', '/more-zeeman/number-line/index.html').
capability_page('area_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('area_compare', '/more-zeeman/set-grouping/index.html').
capability_page('area_compare', '/more-zeeman/unit-echo/index.html').
capability_page('area_render', '/hermes/app/web/console.html').
capability_page('area_render', '/hermes/app/web/discussions.html').
capability_page('area_render', '/more-zeeman/area-model/index.html').
capability_page('area_render', '/more-zeeman/balance-scale/index.html').
capability_page('area_render', '/more-zeeman/base-ten/index.html').
capability_page('area_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('area_render', '/more-zeeman/fraction-bars/index.html').
capability_page('area_render', '/more-zeeman/hybridization/index.html').
capability_page('area_render', '/more-zeeman/monitoring_chart.html').
capability_page('area_render', '/more-zeeman/notation/index.html').
capability_page('area_render', '/more-zeeman/number-line/index.html').
capability_page('area_render', '/more-zeeman/place-value-chart/index.html').
capability_page('area_render', '/more-zeeman/set-grouping/index.html').
capability_page('area_render', '/more-zeeman/unit-echo/index.html').
capability_page('axiom_toggle', '/hermes/app/web/breaks.html').
capability_page('balance_compare', '/hermes/app/web/console.html').
capability_page('balance_compare', '/hermes/app/web/discussions.html').
capability_page('balance_compare', '/more-zeeman/area-model/index.html').
capability_page('balance_compare', '/more-zeeman/balance-scale/index.html').
capability_page('balance_compare', '/more-zeeman/base-ten/index.html').
capability_page('balance_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('balance_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('balance_compare', '/more-zeeman/hybridization/index.html').
capability_page('balance_compare', '/more-zeeman/monitoring_chart.html').
capability_page('balance_compare', '/more-zeeman/notation/index.html').
capability_page('balance_compare', '/more-zeeman/number-line/index.html').
capability_page('balance_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('balance_compare', '/more-zeeman/set-grouping/index.html').
capability_page('balance_compare', '/more-zeeman/unit-echo/index.html').
capability_page('balance_render', '/hermes/app/web/console.html').
capability_page('balance_render', '/hermes/app/web/discussions.html').
capability_page('balance_render', '/more-zeeman/area-model/index.html').
capability_page('balance_render', '/more-zeeman/balance-scale/index.html').
capability_page('balance_render', '/more-zeeman/base-ten/index.html').
capability_page('balance_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('balance_render', '/more-zeeman/fraction-bars/index.html').
capability_page('balance_render', '/more-zeeman/hybridization/index.html').
capability_page('balance_render', '/more-zeeman/monitoring_chart.html').
capability_page('balance_render', '/more-zeeman/notation/index.html').
capability_page('balance_render', '/more-zeeman/number-line/index.html').
capability_page('balance_render', '/more-zeeman/place-value-chart/index.html').
capability_page('balance_render', '/more-zeeman/set-grouping/index.html').
capability_page('balance_render', '/more-zeeman/unit-echo/index.html').
capability_page('base_ten_compare', '/hermes/app/web/console.html').
capability_page('base_ten_compare', '/hermes/app/web/discussions.html').
capability_page('base_ten_compare', '/more-zeeman/area-model/index.html').
capability_page('base_ten_compare', '/more-zeeman/balance-scale/index.html').
capability_page('base_ten_compare', '/more-zeeman/base-ten/index.html').
capability_page('base_ten_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('base_ten_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('base_ten_compare', '/more-zeeman/hybridization/index.html').
capability_page('base_ten_compare', '/more-zeeman/monitoring_chart.html').
capability_page('base_ten_compare', '/more-zeeman/notation/index.html').
capability_page('base_ten_compare', '/more-zeeman/number-line/index.html').
capability_page('base_ten_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('base_ten_compare', '/more-zeeman/set-grouping/index.html').
capability_page('base_ten_compare', '/more-zeeman/unit-echo/index.html').
capability_page('base_ten_render', '/hermes/app/web/console.html').
capability_page('base_ten_render', '/hermes/app/web/discussions.html').
capability_page('base_ten_render', '/more-zeeman/area-model/index.html').
capability_page('base_ten_render', '/more-zeeman/balance-scale/index.html').
capability_page('base_ten_render', '/more-zeeman/base-ten/index.html').
capability_page('base_ten_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('base_ten_render', '/more-zeeman/fraction-bars/index.html').
capability_page('base_ten_render', '/more-zeeman/hybridization/index.html').
capability_page('base_ten_render', '/more-zeeman/monitoring_chart.html').
capability_page('base_ten_render', '/more-zeeman/notation/index.html').
capability_page('base_ten_render', '/more-zeeman/number-line/index.html').
capability_page('base_ten_render', '/more-zeeman/place-value-chart/index.html').
capability_page('base_ten_render', '/more-zeeman/set-grouping/index.html').
capability_page('base_ten_render', '/more-zeeman/unit-echo/index.html').
capability_page('batch_event_score', '/hermes/app/web/discussions.html').
capability_page('benny_demo', '/hermes/app/web/console.html').
capability_page('brandom_backstop', '/hermes/app/web/breaks.html').
capability_page('brandomian_check', '/hermes/app/web/breaks.html').
capability_page('canonical_check', '/hermes/app/web/console.html').
capability_page('canonical_contract', '/hermes/app/web/console.html').
capability_page('capability_atlas', '/more-zeeman/atlas.html').
capability_page('carving_operation_summary', '/more-zeeman/strategies.html').
capability_page('carving_strategy_proof', '/more-zeeman/strategies.html').
capability_page('compute', '/more-zeeman/bridge.html').
capability_page('deontic_consequences', '/hermes/app/web/console.html').
capability_page('deontic_crisis', '/hermes/app/web/breaks.html').
capability_page('deontic_requires_entitlement', '/hermes/app/web/breaks.html').
capability_page('deontic_scorecard', '/hermes/app/web/breaks.html').
capability_page('deontic_scorecard', '/hermes/app/web/console.html').
capability_page('deontic_up_level', '/hermes/app/web/console.html').
capability_page('diagnose_error', '/hermes/app/web/console.html').
capability_page('event_score', '/hermes/app/web/discussions.html').
capability_page('expressive_power', '/more-zeeman/expressive-power-comparison.html').
capability_page('field_connectivity_audit', '/hermes/app/web/console.html').
capability_page('field_context', '/hermes/app/web/console.html').
capability_page('fraction_cgi_addition', '/more-zeeman/notation/index.html').
capability_page('fraction_compare', '/hermes/app/web/console.html').
capability_page('fraction_compare', '/hermes/app/web/discussions.html').
capability_page('fraction_compare', '/more-zeeman/area-model/index.html').
capability_page('fraction_compare', '/more-zeeman/balance-scale/index.html').
capability_page('fraction_compare', '/more-zeeman/base-ten/index.html').
capability_page('fraction_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('fraction_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('fraction_compare', '/more-zeeman/hybridization/index.html').
capability_page('fraction_compare', '/more-zeeman/monitoring_chart.html').
capability_page('fraction_compare', '/more-zeeman/notation/index.html').
capability_page('fraction_compare', '/more-zeeman/number-line/index.html').
capability_page('fraction_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('fraction_compare', '/more-zeeman/set-grouping/index.html').
capability_page('fraction_compare', '/more-zeeman/unit-echo/index.html').
capability_page('fraction_render', '/hermes/app/web/console.html').
capability_page('fraction_render', '/hermes/app/web/discussions.html').
capability_page('fraction_render', '/more-zeeman/area-model/index.html').
capability_page('fraction_render', '/more-zeeman/balance-scale/index.html').
capability_page('fraction_render', '/more-zeeman/base-ten/index.html').
capability_page('fraction_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('fraction_render', '/more-zeeman/fraction-bars/index.html').
capability_page('fraction_render', '/more-zeeman/hybridization/index.html').
capability_page('fraction_render', '/more-zeeman/monitoring_chart.html').
capability_page('fraction_render', '/more-zeeman/notation/index.html').
capability_page('fraction_render', '/more-zeeman/number-line/index.html').
capability_page('fraction_render', '/more-zeeman/place-value-chart/index.html').
capability_page('fraction_render', '/more-zeeman/set-grouping/index.html').
capability_page('fraction_render', '/more-zeeman/unit-echo/index.html').
capability_page('geometry', '/hermes/app/web/console.html').
capability_page('ground', '/hermes/app/web/console.html').
capability_page('grounding_for', '/hermes/app/web/breaks.html').
capability_page('grounding_for', '/hermes/app/web/console.html').
capability_page('grounding_metaphors', '/hermes/app/web/breaks.html').
capability_page('grounding_metaphors', '/hermes/app/web/console.html').
capability_page('hybridization_render', '/hermes/app/web/console.html').
capability_page('hybridization_render', '/hermes/app/web/discussions.html').
capability_page('hybridization_render', '/more-zeeman/area-model/index.html').
capability_page('hybridization_render', '/more-zeeman/balance-scale/index.html').
capability_page('hybridization_render', '/more-zeeman/base-ten/index.html').
capability_page('hybridization_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('hybridization_render', '/more-zeeman/fraction-bars/index.html').
capability_page('hybridization_render', '/more-zeeman/hybridization/index.html').
capability_page('hybridization_render', '/more-zeeman/monitoring_chart.html').
capability_page('hybridization_render', '/more-zeeman/notation/index.html').
capability_page('hybridization_render', '/more-zeeman/number-line/index.html').
capability_page('hybridization_render', '/more-zeeman/place-value-chart/index.html').
capability_page('hybridization_render', '/more-zeeman/set-grouping/index.html').
capability_page('hybridization_render', '/more-zeeman/unit-echo/index.html').
capability_page('hyperedges', '/hermes/app/web/breaks.html').
capability_page('knowledge', '/more-zeeman/bridge.html').
capability_page('learner_reset', '/more-zeeman/bridge.html').
capability_page('lesson_deformation_chart', '/more-zeeman/monitoring_chart.html').
capability_page('list_misconceptions', '/hermes/app/web/console.html').
capability_page('list_standards', '/hermes/app/web/console.html').
capability_page('list_strategies', '/hermes/app/web/console.html').
capability_page('list_strategies', '/hermes/app/web/strategies.html').
capability_page('list_strategies', '/more-zeeman/strategies/index.html').
capability_page('lit_search', '/hermes/app/web/no.html').
capability_page('media_alignment', '/hermes/app/web/discussions.html').
capability_page('monitoring_chart_export', '/hermes/app/web/console.html').
capability_page('monitoring_chart_export', '/more-zeeman/monitoring_chart.html').
capability_page('monitoring_chart_export', '/more-zeeman/scoreboard.html').
capability_page('notation_monitoring_chart', '/more-zeeman/notation/index.html').
capability_page('notation_render', '/more-zeeman/notation/index.html').
capability_page('number_line_compare', '/hermes/app/web/console.html').
capability_page('number_line_compare', '/hermes/app/web/discussions.html').
capability_page('number_line_compare', '/more-zeeman/area-model/index.html').
capability_page('number_line_compare', '/more-zeeman/balance-scale/index.html').
capability_page('number_line_compare', '/more-zeeman/base-ten/index.html').
capability_page('number_line_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('number_line_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('number_line_compare', '/more-zeeman/hybridization/index.html').
capability_page('number_line_compare', '/more-zeeman/monitoring_chart.html').
capability_page('number_line_compare', '/more-zeeman/notation/index.html').
capability_page('number_line_compare', '/more-zeeman/number-line/index.html').
capability_page('number_line_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('number_line_compare', '/more-zeeman/set-grouping/index.html').
capability_page('number_line_compare', '/more-zeeman/unit-echo/index.html').
capability_page('number_line_render', '/hermes/app/web/console.html').
capability_page('number_line_render', '/hermes/app/web/discussions.html').
capability_page('number_line_render', '/more-zeeman/area-model/index.html').
capability_page('number_line_render', '/more-zeeman/balance-scale/index.html').
capability_page('number_line_render', '/more-zeeman/base-ten/index.html').
capability_page('number_line_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('number_line_render', '/more-zeeman/fraction-bars/index.html').
capability_page('number_line_render', '/more-zeeman/hybridization/index.html').
capability_page('number_line_render', '/more-zeeman/monitoring_chart.html').
capability_page('number_line_render', '/more-zeeman/notation/index.html').
capability_page('number_line_render', '/more-zeeman/number-line/index.html').
capability_page('number_line_render', '/more-zeeman/place-value-chart/index.html').
capability_page('number_line_render', '/more-zeeman/set-grouping/index.html').
capability_page('number_line_render', '/more-zeeman/unit-echo/index.html').
capability_page('pair_graph', '/hermes/app/web/discussions.html').
capability_page('pair_score', '/hermes/app/web/discussions.html').
capability_page('place_value_chart_render', '/hermes/app/web/console.html').
capability_page('place_value_chart_render', '/hermes/app/web/discussions.html').
capability_page('place_value_chart_render', '/more-zeeman/area-model/index.html').
capability_page('place_value_chart_render', '/more-zeeman/balance-scale/index.html').
capability_page('place_value_chart_render', '/more-zeeman/base-ten/index.html').
capability_page('place_value_chart_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('place_value_chart_render', '/more-zeeman/fraction-bars/index.html').
capability_page('place_value_chart_render', '/more-zeeman/hybridization/index.html').
capability_page('place_value_chart_render', '/more-zeeman/monitoring_chart.html').
capability_page('place_value_chart_render', '/more-zeeman/notation/index.html').
capability_page('place_value_chart_render', '/more-zeeman/number-line/index.html').
capability_page('place_value_chart_render', '/more-zeeman/place-value-chart/index.html').
capability_page('place_value_chart_render', '/more-zeeman/set-grouping/index.html').
capability_page('place_value_chart_render', '/more-zeeman/unit-echo/index.html').
capability_page('pml_score', '/hermes/app/web/console.html').
capability_page('query_misconception', '/hermes/app/web/console.html').
capability_page('ranked_figures', '/more-zeeman/scoreboard.html').
capability_page('render_coverage', '/hermes/app/web/console.html').
capability_page('reorganize', '/more-zeeman/bridge.html').
capability_page('representation_candidates', '/hermes/app/web/console.html').
capability_page('representation_check', '/hermes/app/web/console.html').
capability_page('representation_spec_check', '/hermes/app/web/console.html').
capability_page('sequent_proof_witness', '/hermes/app/web/breaks.html').
capability_page('set_grouping_compare', '/hermes/app/web/console.html').
capability_page('set_grouping_compare', '/hermes/app/web/discussions.html').
capability_page('set_grouping_compare', '/more-zeeman/area-model/index.html').
capability_page('set_grouping_compare', '/more-zeeman/balance-scale/index.html').
capability_page('set_grouping_compare', '/more-zeeman/base-ten/index.html').
capability_page('set_grouping_compare', '/more-zeeman/fraction-bars/calculator.html').
capability_page('set_grouping_compare', '/more-zeeman/fraction-bars/index.html').
capability_page('set_grouping_compare', '/more-zeeman/hybridization/index.html').
capability_page('set_grouping_compare', '/more-zeeman/monitoring_chart.html').
capability_page('set_grouping_compare', '/more-zeeman/notation/index.html').
capability_page('set_grouping_compare', '/more-zeeman/number-line/index.html').
capability_page('set_grouping_compare', '/more-zeeman/place-value-chart/index.html').
capability_page('set_grouping_compare', '/more-zeeman/set-grouping/index.html').
capability_page('set_grouping_compare', '/more-zeeman/unit-echo/index.html').
capability_page('set_grouping_render', '/hermes/app/web/console.html').
capability_page('set_grouping_render', '/hermes/app/web/discussions.html').
capability_page('set_grouping_render', '/more-zeeman/area-model/index.html').
capability_page('set_grouping_render', '/more-zeeman/balance-scale/index.html').
capability_page('set_grouping_render', '/more-zeeman/base-ten/index.html').
capability_page('set_grouping_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('set_grouping_render', '/more-zeeman/fraction-bars/index.html').
capability_page('set_grouping_render', '/more-zeeman/hybridization/index.html').
capability_page('set_grouping_render', '/more-zeeman/monitoring_chart.html').
capability_page('set_grouping_render', '/more-zeeman/notation/index.html').
capability_page('set_grouping_render', '/more-zeeman/number-line/index.html').
capability_page('set_grouping_render', '/more-zeeman/place-value-chart/index.html').
capability_page('set_grouping_render', '/more-zeeman/set-grouping/index.html').
capability_page('set_grouping_render', '/more-zeeman/unit-echo/index.html').
capability_page('strategy_trace', '/hermes/app/web/console.html').
capability_page('strategy_trace', '/hermes/app/web/discussions.html').
capability_page('strategy_trace', '/hermes/app/web/strategies.html').
capability_page('strategy_trace', '/more-zeeman/area-model/index.html').
capability_page('strategy_trace', '/more-zeeman/balance-scale/index.html').
capability_page('strategy_trace', '/more-zeeman/base-ten/index.html').
capability_page('strategy_trace', '/more-zeeman/fraction-bars/calculator.html').
capability_page('strategy_trace', '/more-zeeman/fraction-bars/index.html').
capability_page('strategy_trace', '/more-zeeman/hybridization/index.html').
capability_page('strategy_trace', '/more-zeeman/monitoring_chart.html').
capability_page('strategy_trace', '/more-zeeman/notation/index.html').
capability_page('strategy_trace', '/more-zeeman/number-line/index.html').
capability_page('strategy_trace', '/more-zeeman/place-value-chart/index.html').
capability_page('strategy_trace', '/more-zeeman/set-grouping/index.html').
capability_page('strategy_trace', '/more-zeeman/unit-echo/index.html').
capability_page('teacher_layer', '/hermes/app/web/console.html').
capability_page('teacher_layer', '/hermes/app/web/discussions.html').
capability_page('teacher_layer', '/more-zeeman/area-model/index.html').
capability_page('teacher_layer', '/more-zeeman/balance-scale/index.html').
capability_page('teacher_layer', '/more-zeeman/base-ten/index.html').
capability_page('teacher_layer', '/more-zeeman/fraction-bars/calculator.html').
capability_page('teacher_layer', '/more-zeeman/fraction-bars/index.html').
capability_page('teacher_layer', '/more-zeeman/hybridization/index.html').
capability_page('teacher_layer', '/more-zeeman/monitoring_chart.html').
capability_page('teacher_layer', '/more-zeeman/notation/index.html').
capability_page('teacher_layer', '/more-zeeman/number-line/index.html').
capability_page('teacher_layer', '/more-zeeman/place-value-chart/index.html').
capability_page('teacher_layer', '/more-zeeman/set-grouping/index.html').
capability_page('teacher_layer', '/more-zeeman/unit-echo/index.html').
capability_page('unit_echo_render', '/hermes/app/web/console.html').
capability_page('unit_echo_render', '/hermes/app/web/discussions.html').
capability_page('unit_echo_render', '/more-zeeman/area-model/index.html').
capability_page('unit_echo_render', '/more-zeeman/balance-scale/index.html').
capability_page('unit_echo_render', '/more-zeeman/base-ten/index.html').
capability_page('unit_echo_render', '/more-zeeman/fraction-bars/calculator.html').
capability_page('unit_echo_render', '/more-zeeman/fraction-bars/index.html').
capability_page('unit_echo_render', '/more-zeeman/hybridization/index.html').
capability_page('unit_echo_render', '/more-zeeman/monitoring_chart.html').
capability_page('unit_echo_render', '/more-zeeman/notation/index.html').
capability_page('unit_echo_render', '/more-zeeman/number-line/index.html').
capability_page('unit_echo_render', '/more-zeeman/place-value-chart/index.html').
capability_page('unit_echo_render', '/more-zeeman/set-grouping/index.html').
capability_page('unit_echo_render', '/more-zeeman/unit-echo/index.html').
capability_page('visualize_coordination', '/more-zeeman/coordination.html').
