/** <module> Reflective Monitor for Disequilibrium Detection
 *
 * This module implements the "Reflect" stage of the ORR cycle. Its primary
 * role is to analyze the execution trace produced by the meta-interpreter
 * (`meta_interpreter.pl`) and detect signs of "disequilibrium."
 *
 * Disequilibrium can manifest in two main ways:
 * 1.  **Goal Failure**: The system was unable to find a proof for the goal.
 * 2.  **Logical Incoherence**: The proof that was found relies on a set of
 *     commitments (clauses) that are logically inconsistent with each other,
 *     as determined by `sequent_engine.pl`.
 *
 * This module also maintains a "conceptual stress map," which tracks how
 * often certain predicates are involved in failures. This map can be used by
 * the reorganization engine to guide its search for a solution.
 *
 * The stress map is stored as dynamic facts of the form:
 * `stress(PredicateSignature, Count)`.
 *
 * 
 * 
 */
:- module(reflective_monitor, [
    reflect/2,
    reflect_success/3,
    successful_episode/5,
    successful_spatial_episode/4,
    recognized_plan/3,
    get_stress_map/1,
    reset_stress_map/0,
    reset_success_reflection/0
]).

:- use_module(arche_trace(sequent_engine)).
:- use_module(peano_utils, [peano_to_int/2]).
:- use_module(spatial_recollection, [reflect_spatial_evidence/2]).

:- dynamic stress/2.
:- dynamic successful_episode/5.
:- dynamic recognized_plan/3.
:- dynamic successful_spatial_episode/4.

%!      reflect(+Trace:list, -DisequilibriumTrigger:term) is semidet.
%
%       Analyzes an execution trace from the meta-interpreter to detect
%       disequilibrium. It succeeds if a trigger for disequilibrium is found,
%       binding `DisequilibriumTrigger` to a term describing the issue. It
%       fails if the trace represents a state of equilibrium (i.e., the goal
%       succeeded and its premises are coherent).
%
%       The process involves:
%       1. Parsing the trace to separate successful commitments from failures.
%       2. Updating a conceptual stress map based on any failures.
%       3. Checking for disequilibrium triggers, prioritizing goal failure over
%          incoherence.
%
%       @param Trace The execution trace generated by `solve/4`.
%       @param DisequilibriumTrigger A term describing the reason for
%       disequilibrium, e.g., `goal_failure([...])` or `incoherence([...])`.
reflect(Trace, Trigger) :-
    % 1. Parse the trace to extract commitments and failures.
    parse_trace(Trace, Commitments, Failures),

    % 2. Update the conceptual stress map based on failures.
    update_stress_map(Failures),

    % 3. Check for disequilibrium triggers.
    (
        % Trigger 1: Goal Failure
        Failures \= [],
        Trigger = goal_failure(Failures), !
    ;
        % Trigger 2: Logical Incoherence
        incoherent(Commitments),
        Trigger = incoherence(Commitments), !
    ).


%!  reflect_success(+Goal, +Trace, -Reflection) is det.
%
%   Successful computation is evidence, not automatically a general rule.
%   Record the episode and recognize a plan only after the same normalized
%   action shape succeeds on at least two distinct inputs.
reflect_success(Goal, Trace, Reflection) :-
    (   successful_goal(Goal, Operation, Inputs, Result)
    ->  successful_trace_shape(Trace, Source, Shape),
        successful_spatial_reflection(Trace, SpatialReflection),
        (   success_evidence_admissible(Operation, SpatialReflection)
        ->  record_success_episode(Operation, Inputs, Result, Source, Shape),
            record_spatial_episode(Operation, Inputs, Result, SpatialReflection),
            recognition_evidence(Operation, Shape, Cases),
            length(Cases, EvidenceCount),
            (   EvidenceCount >= 2
            ->  Plan = recognized_plan(Operation, Shape),
                replace_recognized_plan(Operation, Shape, Cases),
                Status = recognized
            ;   Plan = candidate_plan(Operation, Shape),
                Status = observed
            )
        ;   EvidenceCount = 0,
            Plan = withheld_plan(Operation, Shape),
            Status = representation_deformation
        ),
        Reflection = _{ status: Status,
                        operation: Operation,
                        inputs: Inputs,
                        result: Result,
                        source: Source,
                        spatial_reflection: SpatialReflection,
                        plan: Plan,
                        evidence_count: EvidenceCount }
    ;   Reflection = _{ status: not_applicable,
                        goal: Goal,
                        reason: unsupported_success_shape }
    ).

successful_spatial_reflection(Trace, SpatialReflection) :-
    sub_term(SubTrace, Trace),
    is_dict(SubTrace, synthesized_path),
    get_dict(representation_evidence, SubTrace, [RepresentationEvidence|_]),
    !,
    reflect_spatial_evidence(RepresentationEvidence, SpatialReflection).
successful_spatial_reflection(Trace, SpatialReflection) :-
    sub_term(SubTrace, Trace),
    is_dict(SubTrace, synthesized_path),
    get_dict(spatial_evidence, SubTrace, SpatialEvidence),
    !,
    reflect_spatial_evidence(SpatialEvidence, SpatialReflection).
successful_spatial_reflection(_Trace, none).

success_evidence_admissible(fraction, SpatialReflection) :- !,
    is_dict(SpatialReflection, spatial_reflection),
    SpatialReflection.status == licensed.
success_evidence_admissible(_Operation, _SpatialReflection).

record_spatial_episode(_Operation, _Inputs, _Result, none) :- !.
record_spatial_episode(Operation, Inputs, Result, SpatialReflection) :-
    (   successful_spatial_episode(Operation, Inputs, Result, SpatialReflection)
    ->  true
    ;   assertz(successful_spatial_episode(Operation, Inputs, Result,
                                           SpatialReflection))
    ).

record_success_episode(Operation, Inputs, Result, Source, Shape) :-
    (   successful_episode(Operation, Inputs, Result, Source, Shape)
    ->  true
    ;   assertz(successful_episode(Operation, Inputs, Result, Source, Shape))
    ).

recognition_evidence(Operation, Shape, Cases) :-
    findall(case(Inputs, Result, Source),
            successful_episode(Operation, Inputs, Result, Source, Shape),
            Cases0),
    sort(Cases0, Cases).

replace_recognized_plan(Operation, Shape, Cases) :-
    retractall(recognized_plan(Operation, Shape, _)),
    assertz(recognized_plan(Operation, Shape, evidence(Cases))).

successful_goal(object_level:add(A0, B0, R0), add, [A, B], R) :- !,
    numeric_term(A0, A), numeric_term(B0, B), numeric_term(R0, R).
successful_goal(add(A0, B0, R0), add, [A, B], R) :-
    numeric_term(A0, A), numeric_term(B0, B), numeric_term(R0, R).
successful_goal(object_level:Goal, Operation, Inputs, Result) :- !,
    successful_goal(Goal, Operation, Inputs, Result).
successful_goal(Goal, Operation, [A, B], R) :-
    Goal =.. [Operation, A0, B0, R0],
    memberchk(Operation, [subtract, multiply, divide]),
    numeric_term(A0, A), numeric_term(B0, B), numeric_term(R0, R).
successful_goal(fraction(N0, D0, Quantity), fraction, [N, D], fraction(N, D)) :-
    numeric_term(N0, N),
    numeric_term(D0, D),
    Quantity = quantity(raw_value(fraction(N, D)), _, _, _, _, _).

numeric_term(N, N) :- integer(N), N >= 0, !.
numeric_term(Peano, N) :- peano_to_int(Peano, N).

successful_trace_shape(Trace, primitive_reorganization(Domain), Shape) :-
    sub_term(SubTrace, Trace),
    is_dict(SubTrace, synthesized_path),
    get_dict(source, SubTrace, primitive_reorganization),
    get_dict(domain, SubTrace, Domain),
    get_dict(plan_shape, SubTrace, Shape),
    !.
successful_trace_shape(Trace, recursive_unit_actions, Shape) :-
    sub_term(SubTrace, Trace),
    is_dict(SubTrace, synthesized_path),
    get_dict(source, SubTrace, recursive_unit_actions),
    get_dict(plan_shape, SubTrace, Shape),
    !.
successful_trace_shape(Trace, learned_strategy, learned(Name)) :-
    sub_term(learned_strategy(Name, _), Trace),
    !.
successful_trace_shape(_Trace, primordial, counting_on_by_one).


% parse_trace(+Trace, -Commitments, -Failures)
%
% Recursively walks the trace structure generated by the meta-interpreter
% and extracts the list of commitments (clauses used) and failures.
parse_trace(Trace, Commitments, Failures) :-
    parse_trace_recursive(Trace, Commitments_Nested, Failures_Nested),
    flatten(Commitments_Nested, Commitments),
    flatten(Failures_Nested, Failures).

parse_trace_recursive([], [], []).
parse_trace_recursive([Event|Events], [Commitments|Other_Cs], [Failures|Other_Fs]) :-
    parse_event(Event, Commitments, Failures),
    parse_trace_recursive(Events, Other_Cs, Other_Fs).

% How to handle each type of trace event.
parse_event(trace(_, SubTrace), C, F) :- parse_trace_recursive(SubTrace, C, F).
parse_event(clause(Clause), [Clause], []).
parse_event(fail(Goal), [], [fail(Goal)]).
parse_event(call(_), [], []). % Built-in calls are not commitments in this context.


% update_stress_map(+Failures)
%
% For each failed goal, identify the clause signature and increment its stress level.
update_stress_map([]).
update_stress_map([fail(Goal)|Failures]) :-
    functor(Goal, Name, Arity),
    increment_stress(Name/Arity),
    update_stress_map(Failures).

increment_stress(Signature) :-
    (   retract(stress(Signature, Count))
    ->  NewCount is Count + 1
    ;   NewCount = 1
    ),
    assertz(stress(Signature, NewCount)).

% --- Public helpers for managing the stress map ---

%!      get_stress_map(-Map:list) is det.
%
%       Returns the current conceptual stress map as a list of
%       `stress(Signature, Count)` terms.
%
%       @param Map A list containing all current stress facts.
get_stress_map(Map) :-
    findall(stress(Signature, Count), stress(Signature, Count), Map).

%!      reset_stress_map is det.
%
%       Clears the entire conceptual stress map by retracting all `stress/2` facts.
reset_stress_map :-
    retractall(stress(_, _)).

reset_success_reflection :-
    retractall(successful_episode(_, _, _, _, _)),
    retractall(recognized_plan(_, _, _)),
    retractall(successful_spatial_episode(_, _, _, _)).
