#!/usr/bin/env python3
"""Build and check the tracked 2026-08-10 kernel-dependency overlay.

The two admissions are fixed by the kernel admission ceremony.  Collected R3
rows can corroborate their citations in this checkout, but a tracked gate does
not require the gitignored collection on a fresh clone.
"""

from __future__ import annotations

import argparse
import json
import subprocess
import sys
from pathlib import Path
from typing import Any


ROOT = Path(__file__).resolve().parents[3]
PATHS = ROOT / "paths.pl"
STORE = ROOT / "scripts/bigred/loops/kernel_dependency_overlay.pl"
DEFAULT_COLLECTION = (
    ROOT / ".bigred-collected/2026-08-10-loops-wave3-r3/rows"
)
COLLECTION_CITATION = ".bigred-collected/2026-08-10-loops-wave3-r3/rows"
CEREMONY_CITATION = "plans/2026-08-10-kernel-admission-wave-draft.md"
COMPOSITION = (
    "comp(1,recollect_base_cycles,cardinality_in_base(in(base)),"
    "[cardinality(in(count))])"
)
WAVE = "2026-08-10"
MUA_TYPE = "pp_sufficiency_algorithmic_elaboration"


class OverlayError(RuntimeError):
    """The tracked overlay or its optional collected evidence drifted."""


ROWS: list[dict[str, Any]] = [
    {
        "machine": {
            "family": "counting",
            "kind": "recursive_place_value_inscription",
        },
        "composition": COMPOSITION,
        "evidence": {
            "collection": COLLECTION_CITATION,
            "file": "r3_rows_0027.jsonl",
            "line": 3,
            "row_key": "r3:counting/recursive_place_value_inscription",
        },
        "depth": 1,
        "wave": WAVE,
        "route": {
            "kind": "deploys_kernel",
            "mechanism": "run_kernel",
            "source": "knowledge/strategies/math/counting_action_pairs.pl:348",
        },
        "domain": {
            "count": "nonnegative_integer_0_plus",
            "shared_inputs_with_sibling": 86,
            "evidence_inputs": 110,
        },
        "note": "authored machine deploys the admitted kernel",
        "provenance": {"ceremony_draft": CEREMONY_CITATION},
        "mua_type": MUA_TYPE,
    },
    {
        "machine": {"family": "counting", "kind": "inscribe_cardinality"},
        "composition": COMPOSITION,
        "evidence": {
            "collection": COLLECTION_CITATION,
            "file": "r3_rows_0026.jsonl",
            "line": 3,
            "row_key": "r3:counting/inscribe_cardinality",
        },
        "depth": 1,
        "wave": WAVE,
        "route": {
            "kind": "measured_without_deployment",
            "mechanism": "integer_numeral/3",
            "source": "knowledge/strategies/math/counting_action_pairs.pl:52-71",
        },
        "domain": {
            "count": "integer_1_through_10",
            "shared_inputs_with_sibling": 86,
            "evidence_inputs": 110,
        },
        "note": (
            "sufficiency is measured without deployment; direct construction "
            "through integer_numeral/3 is the stronger form"
        ),
        "provenance": {"ceremony_draft": CEREMONY_CITATION},
        "mua_type": MUA_TYPE,
    },
]


def prolog_atom(value: str) -> str:
    return "'" + value.replace("\\", "\\\\").replace("'", "''") + "'"


def render_store(rows: list[dict[str, Any]] = ROWS) -> str:
    """Render the fixed ceremony rows as one dated Prolog wave block."""
    header = """/** <module> Ceremony-admitted kernel dependencies
 *
 * These rows record PP-sufficiency by algorithmic elaboration only.  The
 * byte-identical bridge is the elaboration witness; no LX half is claimed.
 * The two machines earn that typing by different routes, recorded per row.
 * This overlay annotates bounded consumers and does not extend reachability.
 *
 * Generated by scripts/bigred/loops/build_kernel_dependency_overlay.py under
 * the cited 2026-08-10 admission draft.
 */

:- module(kernel_dependency_overlay,
          [ kernel_dependency/9,
            kernel_dependency_dict/1
          ]).

kernel_dependency_dict(_{
        edge_type:kernel_dependency,
        machine:_{family:Family, kind:Kind},
        composition:Composition,
        evidence:_{collection:Collection, file:File, line:Line,
                   row_key:RowKey},
        depth:Depth,
        wave:Wave,
        route:_{kind:RouteKind, mechanism:Mechanism, source:Source},
        domain:_{count:CountDomain,
                 shared_inputs_with_sibling:SharedInputs,
                 evidence_inputs:EvidenceInputs},
        note:Note,
        provenance:_{ceremony_draft:CeremonyDraft},
        mua_type:MuaType
    }) :-
    kernel_dependency(
        machine(Family, Kind),
        composition(CompositionTerm),
        evidence(collection(Collection), file(File), line(Line), row_key(RowKey)),
        depth(Depth),
        wave(Wave),
        route(RouteKind, mechanism(Mechanism), source(Source)),
        domain(count(CountDomain), shared_inputs_with_sibling(SharedInputs),
               evidence_inputs(EvidenceInputs)),
        note(Note),
        provenance(ceremony_draft(CeremonyDraft), mua_type(MuaType))
    ),
    term_string(CompositionTerm, Composition, [quoted(false)]).

% ---------------------------------------------------------------------------
% Admission wave 2026-08-10
% ---------------------------------------------------------------------------
"""
    facts = []
    for row in rows:
        machine = row["machine"]
        evidence = row["evidence"]
        route = row["route"]
        domain = row["domain"]
        fact = f"""kernel_dependency(
    machine({prolog_atom(machine['family'])}, {prolog_atom(machine['kind'])}),
    composition({row['composition']}),
    evidence(
        collection({prolog_atom(evidence['collection'])}),
        file({prolog_atom(evidence['file'])}),
        line({evidence['line']}),
        row_key({prolog_atom(evidence['row_key'])})
    ),
    depth({row['depth']}),
    wave({prolog_atom(row['wave'])}),
    route(
        {prolog_atom(route['kind'])},
        mechanism({prolog_atom(route['mechanism'])}),
        source({prolog_atom(route['source'])})
    ),
    domain(
        count({prolog_atom(domain['count'])}),
        shared_inputs_with_sibling({domain['shared_inputs_with_sibling']}),
        evidence_inputs({domain['evidence_inputs']})
    ),
    note({prolog_atom(row['note'])}),
    provenance(
        ceremony_draft({prolog_atom(row['provenance']['ceremony_draft'])}),
        mua_type({prolog_atom(row['mua_type'])})
    )
)."""
        facts.append(fact)
    return header + "\n\n".join(facts) + "\n"


def read_store() -> list[dict[str, Any]]:
    """Load the generated module and round-trip every field through Prolog."""
    goal = (
        "use_module(library(http/json)),"
        "findall(D,kernel_dependency_overlay:kernel_dependency_dict(D),Rows),"
        "json_write_dict(current_output,_{rows:Rows},[width(0)]),nl"
    )
    completed = subprocess.run(
        [
            "swipl", "-q", "-l", str(PATHS), "-s", str(STORE),
            "-g", goal, "-t", "halt",
        ],
        cwd=ROOT,
        text=True,
        capture_output=True,
        check=False,
    )
    if completed.returncode:
        raise OverlayError(
            "kernel overlay failed to load: "
            f"{completed.stderr.strip()[:1000]}"
        )
    line = next(
        (value for value in completed.stdout.splitlines() if value.startswith("{")),
        "",
    )
    if not line:
        raise OverlayError("SWI-Prolog returned no kernel-overlay JSON")
    return json.loads(line)["rows"]


def expected_round_trip_rows() -> list[dict[str, Any]]:
    return [{"edge_type": "kernel_dependency", **row} for row in ROWS]


def verify_store() -> list[dict[str, Any]]:
    """Verify exact generated text, row count, fields, and MUA round-trip."""
    if not STORE.is_file():
        raise OverlayError(f"tracked store is absent: {STORE}")
    expected_bytes = render_store().encode("utf-8")
    actual_bytes = STORE.read_bytes()
    if actual_bytes != expected_bytes:
        raise OverlayError("tracked kernel overlay differs from fresh rendering")
    rows = read_store()
    expected = expected_round_trip_rows()
    if rows != expected:
        raise OverlayError("Prolog kernel overlay does not round-trip ruled fields")
    if len(rows) != 2:
        raise OverlayError(f"kernel overlay exposes {len(rows)} rows, expected 2")
    mua_types = {row["mua_type"] for row in rows}
    if mua_types != {MUA_TYPE}:
        raise OverlayError(f"unexpected mua_type values: {sorted(mua_types)}")
    return rows


def read_collection_rows(directory: Path) -> dict[str, dict[str, Any]]:
    """Read only the two cited evidence rows from an optional local collection."""
    wanted = {row["evidence"]["row_key"] for row in ROWS}
    found: dict[str, dict[str, Any]] = {}
    for path in sorted(directory.rglob("*.jsonl")):
        with path.open(encoding="utf-8") as handle:
            for line in handle:
                if not line.strip():
                    continue
                row = json.loads(line)
                key = row.get("key")
                if key in wanted:
                    if key in found:
                        raise OverlayError(f"duplicate collected evidence row: {key}")
                    found[key] = row
    missing = wanted - set(found)
    if missing:
        raise OverlayError(f"collected evidence rows absent: {sorted(missing)}")
    return found


def verify_collection(directory: Path) -> None:
    """Corroborate citations without deriving the ceremony's admission ruling."""
    found = read_collection_rows(directory)
    for ruled in ROWS:
        key = ruled["evidence"]["row_key"]
        row = found[key]
        evidence = row.get("evidence") or {}
        inputs = list(evidence.get("screen_inputs") or []) + list(
            evidence.get("verification_inputs") or []
        )
        if row.get("outcome") != "certified_candidate":
            raise OverlayError(f"{key} is not a certified candidate")
        if row.get("candidate_type") != "kernel_dependency":
            raise OverlayError(f"{key} has wrong candidate_type")
        if evidence.get("candidate_compositions") != [COMPOSITION]:
            raise OverlayError(f"{key} has a different composition receipt")
        if evidence.get("depth") != 1 or len(inputs) != 110:
            raise OverlayError(f"{key} does not carry depth 1 over 110 inputs")
        if evidence.get("kind") != "byte_identical_bridge":
            raise OverlayError(f"{key} does not carry byte-identical evidence")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    parser.add_argument(
        "--collection-rows",
        type=Path,
        default=DEFAULT_COLLECTION,
        help="optional gitignored R3 rows; absence is reported and skipped",
    )
    args = parser.parse_args()

    if not args.check:
        STORE.write_text(render_store(), encoding="utf-8")

    rows = verify_store()
    if args.collection_rows.is_dir():
        verify_collection(args.collection_rows)
        evidence_status = "checked 2 cited collected rows"
    else:
        evidence_status = (
            "SKIP collected evidence absent; tracked store fields and Prolog "
            "round-trip checked"
        )
    print(
        "PASS kernel dependency overlay: "
        f"rows={len(rows)} mua_type={MUA_TYPE} {evidence_status}"
    )
    return 0


if __name__ == "__main__":
    try:
        raise SystemExit(main())
    except (OverlayError, OSError, ValueError, json.JSONDecodeError) as error:
        print(f"FAIL kernel dependency overlay: {error}", file=sys.stderr)
        raise SystemExit(1)
