% Generated by build_corpus_window.py. Hand edits will not survive the check.
%
% window_row/7 retains actions whose registers fall outside shell, core,
% and closure. window_row/6 is the projection used by callers that need
% the three named groups.
% window_register_group/2 is the authored register grouping used by
% the shell-core-closure census. outside is retained rather than
% silently included in one of the three phases.

window_register_group(comparison, shell).
window_register_group(constitution, shell).
window_register_group(delegation, outside).
window_register_group(inscription, closure).
window_register_group(iteration, core).
window_register_group(normative, closure).
window_register_group(operation, core).
window_register_group(partition, shell).
window_register_group(search, shell).
window_register_group(transformation, shell).

window_legend_action(accept_without_check, computational, normative, deforming).
window_legend_action(accumulate_total, computational, iteration, neutral).
window_legend_action(acknowledge_commitment, discursive, constitution, neutral).
window_legend_action(align_to_common_unit, computational, transformation, conserving).
window_legend_action(apply_quantity_change, computational, operation, neutral).
window_legend_action(apply_stored_rule, computational, operation, neutral).
window_legend_action(assign_roles, computational, constitution, neutral).
window_legend_action(assume_vindication_task, discursive, normative, conserving).
window_legend_action(attach_units_coordination, computational, inscription, conserving).
window_legend_action(attend_to_utterance, discursive, constitution, neutral).
window_legend_action(attribute_commitment, discursive, constitution, neutral).
window_legend_action(authorize_deferral, discursive, operation, conserving).
window_legend_action(certify_meaning_use_relation, discursive, normative, conserving).
window_legend_action(challenge_entitlement, discursive, comparison, neutral).
window_legend_action(combine_quantities, computational, operation, neutral).
window_legend_action(commute_operands, computational, transformation, conserving).
window_legend_action(compare_additive_gaps, computational, comparison, neutral).
window_legend_action(compare_magnitudes, computational, comparison, neutral).
window_legend_action(compare_residuals, computational, comparison, neutral).
window_legend_action(compose_expression, computational, transformation, neutral).
window_legend_action(compute_product, computational, operation, neutral).
window_legend_action(compute_quotient, computational, operation, neutral).
window_legend_action(conflate_attribution_with_acknowledgement, discursive, constitution, deforming).
window_legend_action(conflate_roles, computational, constitution, deforming).
window_legend_action(count_back_from, computational, iteration, neutral).
window_legend_action(count_on_from, computational, iteration, neutral).
window_legend_action(count_units, computational, iteration, neutral).
window_legend_action(count_up_to_target, computational, iteration, neutral).
window_legend_action(decompose_by_place, computational, partition, neutral).
window_legend_action(decompose_operand, computational, partition, neutral).
window_legend_action(decompose_region, computational, partition, neutral).
window_legend_action(defer_to_asserter, discursive, delegation, neutral).
window_legend_action(deploy_vocabulary_from_practice, discursive, transformation, neutral).
window_legend_action(derive_consequent, discursive, comparison, neutral).
window_legend_action(disembed_part, computational, partition, neutral).
window_legend_action(dispatch_to_kernel, computational, delegation, neutral).
window_legend_action(distribute_over_partition, computational, transformation, conserving).
window_legend_action(double_count, computational, iteration, deforming).
window_legend_action(elaborate_practice_algorithmically, discursive, transformation, neutral).
window_legend_action(emit_result, computational, inscription, neutral).
window_legend_action(enumerate_candidates, computational, search, neutral).
window_legend_action(establish_reference_frame, computational, constitution, neutral).
window_legend_action(evaluate_expression, computational, operation, neutral).
window_legend_action(exchange_base_down, computational, transformation, conserving).
window_legend_action(exhaust_resource, computational, operation, neutral).
window_legend_action(explicate_practice_in_elaborated_vocabulary, discursive, transformation, conserving).
window_legend_action(filter_by_constraint, computational, search, neutral).
window_legend_action(grant_entitlement, discursive, operation, conserving).
window_legend_action(grant_entitlement_without_grounding, discursive, normative, deforming).
window_legend_action(halt_before_completion, computational, iteration, deforming).
window_legend_action(hold_incompatible_commitments, discursive, normative, deforming).
window_legend_action(inherit_entitlement, discursive, delegation, neutral).
window_legend_action(initiate, computational, constitution, neutral).
window_legend_action(inscribe_result, computational, inscription, neutral).
window_legend_action(interrupt_before_completion, discursive, iteration, conserving).
window_legend_action(intersect_candidate_sets, computational, search, neutral).
window_legend_action(isolate_unknown, computational, comparison, neutral).
window_legend_action(iterate_composite_unit, computational, iteration, neutral).
window_legend_action(iterate_unit, computational, iteration, neutral).
window_legend_action(judge_against_benchmark, computational, comparison, neutral).
window_legend_action(let_the_utterance_run_on, discursive, iteration, deforming).
window_legend_action(locate_material_inference, discursive, comparison, neutral).
window_legend_action(locate_position, computational, comparison, neutral).
window_legend_action(match_one_to_one, computational, comparison, neutral).
window_legend_action(measure_out_group_size, computational, operation, neutral).
window_legend_action(measure_quantity, computational, iteration, neutral).
window_legend_action(misname_result, computational, inscription, deforming).
window_legend_action(misread_intermediate_value, computational, constitution, deforming).
window_legend_action(name_result, computational, inscription, neutral).
window_legend_action(name_the_incompatible_token, discursive, comparison, neutral).
window_legend_action(omit_required_step, computational, normative, deforming).
window_legend_action(omit_vindication_task, discursive, normative, deforming).
window_legend_action(order_by_magnitude, computational, comparison, neutral).
window_legend_action(partition_into_equal_parts, computational, partition, neutral).
window_legend_action(re_express_equivalently, computational, transformation, conserving).
window_legend_action(read_operand_attribute, computational, constitution, neutral).
window_legend_action(receive_kernel_outcome, computational, delegation, neutral).
window_legend_action(recompose_total, computational, transformation, conserving).
window_legend_action(record_conservation, computational, normative, conserving).
window_legend_action(record_deontic_incoherence, discursive, normative, deforming).
window_legend_action(record_deontic_score, discursive, normative, conserving).
window_legend_action(record_loss, computational, normative, deforming).
window_legend_action(record_viability, computational, normative, conserving).
window_legend_action(register_givens, computational, constitution, neutral).
window_legend_action(regress_deferral, discursive, delegation, deforming).
window_legend_action(regroup_to_base, computational, transformation, conserving).
window_legend_action(remove_quantity, computational, operation, neutral).
window_legend_action(rename_in_place_of_transforming, computational, transformation, deforming).
window_legend_action(repair_the_commitment, discursive, transformation, conserving).
window_legend_action(replicate_equal_groups, computational, operation, neutral).
window_legend_action(restore_adjustment, computational, transformation, conserving).
window_legend_action(retain_unchanged, computational, transformation, neutral).
window_legend_action(retain_what_must_survive, computational, transformation, conserving).
window_legend_action(retain_where_change_was_due, computational, transformation, deforming).
window_legend_action(retrieve_known_fact, computational, operation, neutral).
window_legend_action(round_to_landmark, computational, transformation, neutral).
window_legend_action(scale_multiplicatively, computational, transformation, neutral).
window_legend_action(select_extremal, computational, search, neutral).
window_legend_action(select_part, computational, partition, neutral).
window_legend_action(select_unit_scale, computational, constitution, neutral).
window_legend_action(set_aside_irrelevant_attribute, computational, normative, conserving).
window_legend_action(share_into_known_groups, computational, operation, neutral).
window_legend_action(specify_practice_in_vocabulary, discursive, transformation, neutral).
window_legend_action(substitute_additive_for_multiplicative, computational, comparison, deforming).
window_legend_action(substitute_appearance_for_measure, computational, comparison, deforming).
window_legend_action(substitute_authority_for_inference, discursive, operation, deforming).
window_legend_action(substitute_count_for_measure, computational, iteration, deforming).
window_legend_action(substitute_formal_schema_for_material_inference, discursive, comparison, deforming).
window_legend_action(substitute_operation, computational, operation, deforming).
window_legend_action(substitute_scalar_for_structured_quantity, computational, transformation, deforming).
window_legend_action(substitute_symbol_reading, computational, constitution, deforming).
window_legend_action(substitute_values, computational, transformation, neutral).
window_legend_action(test_compatibility, discursive, normative, conserving).
window_legend_action(test_criteria, computational, normative, conserving).
window_legend_action(transfer_between_operands, computational, transformation, conserving).
window_legend_action(traverse_boundary, computational, iteration, neutral).
window_legend_action(treat_relevant_as_irrelevant, computational, normative, deforming).
window_legend_action(undertake_commitment, discursive, operation, neutral).
window_legend_action(unitize_referent, computational, constitution, neutral).
window_legend_action(verify_by_substitution, computational, normative, conserving).
window_legend_action(verify_invariant, computational, normative, conserving).
window_legend_action(withdraw_commitment, discursive, operation, neutral).

window_legend_arc(break_first_work_break, 4).
window_legend_arc(break_keep_break, 3).
window_legend_arc(break_recover_break, 19).
window_legend_arc(break_recover_break_work_on, 1).
window_legend_arc(break_then_keep_then_break, 1).
window_legend_arc(break_then_keep_work_on, 1).
window_legend_arc(break_then_test_what_held, 1).
window_legend_arc(break_then_work_on, 10).
window_legend_arc(break_three_times, 1).
window_legend_arc(break_twice_then_keep_work_on, 1).
window_legend_arc(break_twice_then_test_what_held, 3).
window_legend_arc(keep_break_recover_break_keep, 1).
window_legend_arc(keep_first_break_keep_break, 1).
window_legend_arc(keep_first_break_recover_break, 1).
window_legend_arc(keep_first_break_recover_break_again, 1).
window_legend_arc(keep_first_break_work_on, 1).
window_legend_arc(keep_first_then_break, 1).
window_legend_arc(keep_first_then_work_on, 2).
window_legend_arc(keep_first_work_keep, 3).
window_legend_arc(keep_then_break, 5).
window_legend_arc(keep_then_work_on, 31).
window_legend_arc(keep_work_keep, 9).
window_legend_arc(keep_work_keep_work_keep, 1).
window_legend_arc(keep_work_keep_work_on, 2).
window_legend_arc(unrecorded_run, 48).
window_legend_arc(work_then_break, 49).
window_legend_arc(work_then_keep, 35).

window_row(addition, append_column_sum_without_carrying, keep_first_break_recover_break, [align_to_common_unit], [substitute_operation], [omit_required_step, inscribe_result, record_loss], []).
window_row(addition, base_ones_chunking, work_then_keep, [decompose_operand], [combine_quantities, combine_quantities], [record_conservation], []).
window_row(addition, column_addition_with_carrying, keep_work_keep_work_keep, [align_to_common_unit, regroup_to_base], [apply_stored_rule, accumulate_total], [inscribe_result, record_conservation], []).
window_row(addition, count_all_instead_of_known_fact, work_then_break, [register_givens], [exhaust_resource, count_units], [record_loss], []).
window_row(addition, count_all_when_count_on_available, break_first_work_break, [], [substitute_operation, count_units, count_on_from], [record_loss], []).
window_row(addition, count_on_from_larger, unrecorded_run, [assign_roles, assign_roles], [count_on_from], [name_result], []).
window_row(addition, derived_fact_adjustment, work_then_keep, [compare_magnitudes], [retrieve_known_fact, combine_quantities], [record_conservation], []).
window_row(addition, drop_carry_to_next_column, keep_first_break_recover_break_again, [align_to_common_unit], [apply_stored_rule, accumulate_total], [inscribe_result, treat_relevant_as_irrelevant, record_loss], []).
window_row(addition, dropped_ones_chunk, work_then_break, [decompose_operand], [combine_quantities, halt_before_completion], [record_loss], []).
window_row(addition, known_fact_retrieval, unrecorded_run, [register_givens], [retrieve_known_fact], [name_result], []).
window_row(addition, make_base_transfer, work_then_keep, [assign_roles, select_unit_scale, transfer_between_operands], [count_up_to_target], [record_conservation], []).
window_row(addition, make_ten_drop_leftover, keep_then_break, [assign_roles, decompose_operand, regroup_to_base], [halt_before_completion], [record_loss], []).
window_row(addition, make_ten_split_leftover, keep_work_keep, [assign_roles, decompose_operand, regroup_to_base], [combine_quantities], [record_conservation], []).
window_row(addition, rote_derived_fact_rule_misfire, work_then_break, [read_operand_attribute], [retrieve_known_fact, apply_stored_rule], [record_loss], []).
window_row(addition, round_then_adjust, work_then_keep, [assign_roles, select_unit_scale, round_to_landmark, restore_adjustment], [combine_quantities], [], []).
window_row(addition, round_without_adjusting, work_then_break, [assign_roles, select_unit_scale, round_to_landmark], [combine_quantities], [omit_required_step, record_loss], []).
window_row(addition, unbalanced_make_base_compensation, work_then_break, [assign_roles, select_unit_scale, retain_where_change_was_due], [count_up_to_target, combine_quantities], [record_loss], []).
window_row(addition, wrong_carry_amount_to_next_column, keep_first_break_keep_break, [align_to_common_unit, misread_intermediate_value, regroup_to_base], [apply_stored_rule], [inscribe_result, record_loss], []).
window_row(algebraic, balance_preserving_linear_solution, keep_work_keep, [register_givens, re_express_equivalently, isolate_unknown], [], [verify_by_substitution], []).
window_row(algebraic, contextual_linear_equation_construction, unrecorded_run, [assign_roles, assign_roles, compose_expression, compose_expression, compose_expression], [], [inscribe_result], []).
window_row(algebraic, distributive_expression_rewrite, work_then_keep, [read_operand_attribute, read_operand_attribute, distribute_over_partition, distribute_over_partition, recompose_total], [], [], []).
window_row(algebraic, drop_distributed_term, keep_then_break, [read_operand_attribute, distribute_over_partition], [halt_before_completion], [record_loss], []).
window_row(algebraic, equation_truth_by_substitution, work_then_keep, [substitute_values], [evaluate_expression, evaluate_expression], [test_criteria], []).
window_row(algebraic, exponent_as_multiplier, break_first_work_break, [conflate_roles], [compute_product], [omit_required_step], []).
window_row(algebraic, exponent_as_repeated_factor, unrecorded_run, [assign_roles, assign_roles], [iterate_unit], [inscribe_result], []).
window_row(algebraic, exponential_equivalence_by_expansion, keep_first_then_work_on, [re_express_equivalently, re_express_equivalently], [], [test_criteria, name_result], []).
window_row(algebraic, guess_and_check_rule, keep_then_break, [register_givens], [apply_stored_rule], [test_criteria, record_loss], []).
window_row(algebraic, linear_pattern_contextual_rule, work_then_keep, [read_operand_attribute, read_operand_attribute], [count_units, compute_product, combine_quantities], [record_conservation], []).
window_row(algebraic, one_sided_equation_operation, break_three_times, [substitute_symbol_reading, retain_where_change_was_due], [remove_quantity, compute_quotient], [misname_result], []).
window_row(algebraic, operational_equals_left_value, work_then_break, [substitute_values, substitute_symbol_reading], [evaluate_expression], [treat_relevant_as_irrelevant], []).
window_row(algebraic, programming_expression_evaluation, unrecorded_run, [register_givens, register_givens], [evaluate_expression], [name_result], [receive_kernel_outcome]).
window_row(algebraic, symbolic_expression_construction, keep_then_work_on, [assign_roles, assign_roles, compose_expression], [], [verify_invariant, inscribe_result], []).
window_row(calculus, factor_cancel_substitute, keep_then_work_on, [read_operand_attribute, substitute_values, decompose_operand, substitute_values], [evaluate_expression], [test_criteria, name_result], [receive_kernel_outcome]).
window_row(calculus, factor_cancel_without_common_factor, break_recover_break, [read_operand_attribute, substitute_values], [apply_stored_rule], [omit_required_step, misname_result, record_loss], []).
window_row(counting, compare_cardinalities_one_to_one, unrecorded_run, [register_givens, match_one_to_one, read_operand_attribute], [], [name_result], []).
window_row(counting, compare_ones_digits_only, keep_first_break_work_on, [align_to_common_unit, compare_magnitudes], [], [treat_relevant_as_irrelevant, name_result], []).
window_row(counting, inscribe_cardinality, unrecorded_run, [register_givens, select_unit_scale], [], [inscribe_result], []).
window_row(counting, omit_highest_place_regrouping, work_then_break, [register_givens, select_part], [], [omit_required_step, misname_result], []).
window_row(counting, place_value_comparison, keep_first_then_work_on, [align_to_common_unit, align_to_common_unit, locate_position, compare_magnitudes], [], [name_result], []).
window_row(counting, recursive_place_value_inscription, keep_work_keep, [register_givens, select_unit_scale, regroup_to_base, unitize_referent, select_unit_scale, read_operand_attribute, read_operand_attribute], [iterate_composite_unit, iterate_composite_unit, iterate_composite_unit], [record_conservation], []).
window_row(counting, spatial_extent_as_cardinality, break_first_work_break, [compare_magnitudes, substitute_appearance_for_measure], [], [treat_relevant_as_irrelevant], []).
window_row(decimal, change_decimal_place_name_without_regrouping, work_then_break, [read_operand_attribute, rename_in_place_of_transforming, retain_where_change_was_due], [], [omit_required_step], []).
window_row(decimal, decimal_add_unaligned_numerals, break_twice_then_test_what_held, [register_givens], [combine_quantities], [omit_required_step, inscribe_result, record_loss, verify_invariant], []).
window_row(decimal, decimal_addition_by_aligned_units, keep_then_work_on, [read_operand_attribute, select_unit_scale, align_to_common_unit, align_to_common_unit], [combine_quantities], [inscribe_result], []).
window_row(decimal, decimal_comparison_by_aligned_units, keep_then_work_on, [read_operand_attribute, select_unit_scale, align_to_common_unit, align_to_common_unit, compare_magnitudes], [], [], []).
window_row(decimal, decimal_fraction_place_value_comparison, keep_then_work_on, [initiate, read_operand_attribute, re_express_equivalently, align_to_common_unit, compare_magnitudes], [], [emit_result], []).
window_row(decimal, decimal_multiplication_rule, keep_work_keep, [read_operand_attribute, recompose_total], [compute_product, accumulate_total], [set_aside_irrelevant_attribute, inscribe_result], []).
window_row(decimal, decimal_numeral_comparison_without_scale_alignment, break_twice_then_test_what_held, [register_givens, compare_magnitudes], [], [omit_required_step, record_loss, verify_invariant], []).
window_row(decimal, decimal_place_unit_regrouping, work_then_keep, [read_operand_attribute, read_operand_attribute], [iterate_unit], [record_conservation], []).
window_row(decimal, decimal_point_rule_misapplication, break_recover_break, [read_operand_attribute], [compute_product, substitute_operation], [inscribe_result, record_loss], []).
window_row(decimal, decimal_scale_loss_comparison, break_then_work_on, [initiate, compare_magnitudes, compare_magnitudes], [], [accept_without_check, omit_required_step, emit_result], []).
window_row(decimal, decimal_subtract_unaligned_numerals, break_twice_then_test_what_held, [register_givens], [remove_quantity], [omit_required_step, inscribe_result, record_loss, verify_invariant], []).
window_row(decimal, decimal_subtraction_by_aligned_units, keep_then_work_on, [read_operand_attribute, select_unit_scale, align_to_common_unit, align_to_common_unit], [remove_quantity], [inscribe_result], []).
window_row(decimal, decimal_whole_number_reading, work_then_break, [register_givens], [], [treat_relevant_as_irrelevant, treat_relevant_as_irrelevant, misname_result, record_loss], []).
window_row(decimal, ecuadorian_decimal_long_division, unrecorded_run, [read_operand_attribute, select_unit_scale, scale_multiplicatively], [apply_stored_rule, compute_quotient], [name_result], []).
window_row(decimal, positional_decimal_reading, work_then_keep, [read_operand_attribute, decompose_by_place, assign_roles, recompose_total], [], [], []).
window_row(decimal, recalled_result_scaling, unrecorded_run, [read_operand_attribute, scale_multiplicatively], [retrieve_known_fact], [name_result], []).
window_row(discourse, algorithmic_elaboration, work_then_keep, [register_givens, elaborate_practice_algorithmically], [], [certify_meaning_use_relation], []).
window_row(discourse, assertion_without_vindication_task, keep_then_break, [attend_to_utterance], [undertake_commitment, authorize_deferral], [omit_vindication_task, record_deontic_incoherence], []).
window_row(discourse, assertional_commitment, work_then_keep, [attend_to_utterance], [undertake_commitment, authorize_deferral], [assume_vindication_task, record_deontic_score], []).
window_row(discourse, attribution_and_acknowledgement_kept_apart, work_then_keep, [attend_to_utterance, attribute_commitment, acknowledge_commitment], [], [test_compatibility, record_deontic_score], []).
window_row(discourse, attribution_taken_as_acknowledgement, work_then_break, [attend_to_utterance, attribute_commitment, conflate_attribution_with_acknowledgement], [], [record_deontic_incoherence], []).
window_row(discourse, authority_where_inference_required, work_then_break, [attend_to_utterance, acknowledge_commitment], [substitute_authority_for_inference], [grant_entitlement_without_grounding, record_deontic_incoherence], []).
window_row(discourse, commitment_repair, work_then_keep, [acknowledge_commitment, challenge_entitlement, repair_the_commitment], [withdraw_commitment], [record_deontic_score], []).
window_row(discourse, deferral_regress, work_then_break, [attribute_commitment, challenge_entitlement], [], [record_deontic_incoherence], [defer_to_asserter, regress_deferral]).
window_row(discourse, entitlement_by_authority, work_then_keep, [attend_to_utterance, acknowledge_commitment], [grant_entitlement], [assume_vindication_task, record_deontic_score], []).
window_row(discourse, entitlement_by_deferral, work_then_keep, [attribute_commitment, challenge_entitlement], [], [record_deontic_score], [defer_to_asserter, inherit_entitlement]).
window_row(discourse, entitlement_by_formal_schema, break_recover_break, [acknowledge_commitment, substitute_formal_schema_for_material_inference, derive_consequent], [], [grant_entitlement_without_grounding, record_deontic_incoherence], []).
window_row(discourse, entitlement_by_inference, work_then_keep, [acknowledge_commitment, locate_material_inference, derive_consequent], [grant_entitlement], [record_deontic_score], []).
window_row(discourse, incompatibility_recognition, keep_work_keep, [acknowledge_commitment, acknowledge_commitment], [withdraw_commitment], [test_compatibility, record_deontic_score], []).
window_row(discourse, incompatible_commitments_held, work_then_break, [acknowledge_commitment, acknowledge_commitment], [], [hold_incompatible_commitments, record_deontic_incoherence], []).
window_row(discourse, pragmatic_metavocabulary_construction, work_then_keep, [register_givens, specify_practice_in_vocabulary, deploy_vocabulary_from_practice], [], [certify_meaning_use_relation], []).
window_row(discourse, tutorial_interruption_on_incompatible_token, work_then_keep, [attend_to_utterance, name_the_incompatible_token, repair_the_commitment], [interrupt_before_completion], [test_compatibility, record_deontic_score], []).
window_row(discourse, universally_lx_loop, work_then_keep, [register_givens, elaborate_practice_algorithmically, deploy_vocabulary_from_practice, explicate_practice_in_elaborated_vocabulary], [], [certify_meaning_use_relation], []).
window_row(discourse, utterance_run_to_its_loss, work_then_break, [attend_to_utterance, name_the_incompatible_token], [let_the_utterance_run_on], [record_deontic_incoherence], []).
window_row(division, divide_larger_by_smaller, break_then_test_what_held, [register_givens, order_by_magnitude, conflate_roles], [apply_stored_rule], [name_result, verify_invariant], []).
window_row(division, fair_share_equal_groups, keep_then_work_on, [assign_roles], [share_into_known_groups], [verify_invariant, name_result], []).
window_row(division, inverse_fact_decomposition, unrecorded_run, [], [retrieve_known_fact, measure_out_group_size, accumulate_total], [name_result], []).
window_row(division, long_division, unrecorded_run, [register_givens], [apply_stored_rule, apply_stored_rule, apply_stored_rule], [inscribe_result, name_result], []).
window_row(division, measure_groups_of_size, keep_then_work_on, [assign_roles, retain_what_must_survive], [measure_out_group_size, count_units], [name_result], []).
window_row(division, missing_factor_known_product_search, unrecorded_run, [assign_roles, enumerate_candidates, filter_by_constraint], [], [name_result], []).
window_row(division, missing_factor_repeated_addition, work_then_keep, [register_givens], [count_up_to_target], [name_result, record_conservation], []).
window_row(division, name_group_count_as_share_size, work_then_break, [assign_roles, conflate_roles], [], [misname_result, record_loss], []).
window_row(division, name_reached_total_as_quotient, work_then_break, [register_givens], [count_up_to_target], [misname_result, record_loss], []).
window_row(division, partial_quotient_chunking, unrecorded_run, [select_unit_scale, select_unit_scale], [remove_quantity, accumulate_total], [name_result], []).
window_row(division, reject_known_product_match, work_then_break, [assign_roles, enumerate_candidates, filter_by_constraint], [], [treat_relevant_as_irrelevant, record_loss], []).
window_row(division, share_into_divisor_groups, break_recover_break, [assign_roles, conflate_roles], [share_into_known_groups], [misname_result, record_loss], []).
window_row(division, stop_after_first_partial_quotient, work_then_break, [select_unit_scale, select_unit_scale], [remove_quantity, halt_before_completion], [misname_result, record_loss], []).
window_row(division, stop_after_one_known_fact, work_then_break, [], [retrieve_known_fact, measure_out_group_size, halt_before_completion], [misname_result, record_loss], []).
window_row(division, stop_at_nearby_product_in_search, work_then_break, [assign_roles, enumerate_candidates], [halt_before_completion], [misname_result, record_loss], []).
window_row(division, sum_dividend_and_divisor, work_then_break, [register_givens], [substitute_operation], [omit_required_step, misname_result, record_loss], []).
window_row(fraction, add_numerator_denominator_comparison, break_then_work_on, [initiate], [combine_quantities], [omit_required_step], []).
window_row(fraction, add_numerator_denominator_sum, keep_break_recover_break_keep, [initiate, re_express_equivalently], [combine_quantities], [omit_required_step, omit_required_step, verify_invariant, record_viability, emit_result], []).
window_row(fraction, area_model_fraction_comparison, keep_work_keep_work_on, [initiate, unitize_referent, partition_into_equal_parts, disembed_part, align_to_common_unit], [iterate_unit], [verify_invariant, emit_result], []).
window_row(fraction, area_model_part_of_part, unrecorded_run, [unitize_referent, partition_into_equal_parts, select_part, partition_into_equal_parts, select_part], [count_units, count_units], [name_result], []).
window_row(fraction, area_model_unequal_partition_piece_count, break_recover_break_work_on, [initiate], [substitute_count_for_measure, count_units, substitute_count_for_measure], [accept_without_check, accept_without_check, accept_without_check, treat_relevant_as_irrelevant, emit_result], []).
window_row(fraction, benchmark_fraction_comparison, unrecorded_run, [initiate, establish_reference_frame, judge_against_benchmark, judge_against_benchmark, judge_against_benchmark, compare_residuals], [], [emit_result], []).
window_row(fraction, clear_inner_referent, work_then_break, [partition_into_equal_parts, partition_into_equal_parts], [], [name_result, omit_required_step, record_loss], []).
window_row(fraction, co_denominator_count_on_from_larger, keep_first_work_keep, [unitize_referent, select_unit_scale], [], [verify_invariant, attach_units_coordination], [dispatch_to_kernel, receive_kernel_outcome]).
window_row(fraction, co_denominator_make_base_transfer, keep_first_work_keep, [unitize_referent, select_unit_scale], [], [verify_invariant, attach_units_coordination], [dispatch_to_kernel, receive_kernel_outcome]).
window_row(fraction, common_denominator_fraction_addition, keep_then_work_on, [initiate, re_express_equivalently, align_to_common_unit, re_express_equivalently, re_express_equivalently, align_to_common_unit], [combine_quantities], [emit_result], []).
window_row(fraction, common_denominator_fraction_subtraction, keep_then_work_on, [initiate, re_express_equivalently, align_to_common_unit, re_express_equivalently, re_express_equivalently, align_to_common_unit], [remove_quantity], [emit_result], []).
window_row(fraction, common_unit_fraction_comparison, unrecorded_run, [initiate, read_operand_attribute, retain_unchanged, retain_unchanged, read_operand_attribute, compare_magnitudes], [], [emit_result], []).
window_row(fraction, cross_multiplication_rule_from_pattern, unrecorded_run, [read_operand_attribute, assign_roles, assign_roles], [apply_stored_rule, compute_product, compute_product], [name_result], [dispatch_to_kernel]).
window_row(fraction, cross_multiplication_rule_without_ground, work_then_break, [], [retrieve_known_fact, apply_stored_rule, compute_product, compute_product], [name_result, omit_required_step], []).
window_row(fraction, gap_thinking_fraction_comparison, break_twice_then_keep_work_on, [initiate, establish_reference_frame, substitute_additive_for_multiplicative, substitute_additive_for_multiplicative, compare_additive_gaps, compare_residuals], [], [omit_required_step, record_viability, emit_result], []).
window_row(fraction, improper_fraction_chain_loss, break_then_work_on, [unitize_referent, rename_in_place_of_transforming], [iterate_unit], [treat_relevant_as_irrelevant, misname_result], [receive_kernel_outcome]).
window_row(fraction, improper_fraction_iteration, keep_then_work_on, [unitize_referent, disembed_part], [iterate_unit], [verify_invariant, name_result], [receive_kernel_outcome]).
window_row(fraction, iterate_given_overshoot, work_then_break, [unitize_referent], [iterate_unit], [omit_required_step, record_loss], []).
window_row(fraction, iterate_only_no_reverse, break_recover_break, [register_givens], [iterate_unit, exhaust_resource], [omit_required_step, record_loss], []).
window_row(fraction, measurement_division, keep_then_work_on, [register_givens, align_to_common_unit], [measure_out_group_size], [name_result, name_result], []).
window_row(fraction, number_line_count_marks_not_intervals, break_then_keep_work_on, [initiate, unitize_referent, partition_into_equal_parts, locate_position, align_to_common_unit, compare_magnitudes], [substitute_count_for_measure], [emit_result], []).
window_row(fraction, number_line_fraction_comparison, keep_then_work_on, [initiate, unitize_referent, partition_into_equal_parts, locate_position, align_to_common_unit, compare_magnitudes], [iterate_unit], [emit_result], []).
window_row(fraction, recursive_partition, keep_then_work_on, [partition_into_equal_parts, disembed_part, partition_into_equal_parts], [], [name_result, verify_invariant], [receive_kernel_outcome]).
window_row(fraction, reversible_measurement_division, unrecorded_run, [register_givens, select_unit_scale], [measure_quantity, replicate_equal_groups], [name_result], []).
window_row(fraction, set_model_fraction_comparison, keep_work_keep_work_on, [initiate, unitize_referent, partition_into_equal_parts, disembed_part, align_to_common_unit], [count_units], [verify_invariant, emit_result], []).
window_row(fraction, set_model_subset_size_focus, break_then_work_on, [initiate, unitize_referent, conflate_roles, compare_magnitudes], [substitute_count_for_measure, substitute_count_for_measure], [accept_without_check, omit_required_step, emit_result], []).
window_row(fraction, solve_for_unit, keep_then_work_on, [register_givens, assign_roles, partition_into_equal_parts, isolate_unknown], [iterate_unit], [verify_invariant], [receive_kernel_outcome]).
window_row(fraction, splitting, keep_then_work_on, [partition_into_equal_parts, disembed_part, recompose_total], [iterate_unit], [verify_invariant, attach_units_coordination], [receive_kernel_outcome, receive_kernel_outcome]).
window_row(fraction, unit_fraction_iteration, keep_then_work_on, [unitize_referent, disembed_part], [iterate_unit], [verify_invariant], [receive_kernel_outcome]).
window_row(fraction, unit_fraction_partition, keep_then_work_on, [unitize_referent, partition_into_equal_parts, disembed_part], [], [verify_invariant], [receive_kernel_outcome]).
window_row(fraction, whole_number_grab, work_then_break, [unitize_referent, read_operand_attribute], [], [treat_relevant_as_irrelevant, misname_result, record_loss], []).
window_row(geometry, angle_additive_composition, keep_work_keep, [establish_reference_frame], [accumulate_total], [verify_invariant, verify_invariant], []).
window_row(geometry, angle_as_ray_length, keep_first_then_break, [retain_what_must_survive, scale_multiplicatively, substitute_appearance_for_measure], [], [], []).
window_row(geometry, angle_turn_measurement, unrecorded_run, [establish_reference_frame, establish_reference_frame, locate_position], [iterate_unit], [name_result], []).
window_row(geometry, area_as_perimeter_count, break_recover_break, [register_givens, substitute_appearance_for_measure], [traverse_boundary], [treat_relevant_as_irrelevant], []).
window_row(geometry, area_preserving_polygon_decomposition, work_then_keep, [register_givens, decompose_region], [measure_quantity, accumulate_total], [record_conservation], []).
window_row(geometry, area_unit_covering, keep_then_work_on, [unitize_referent], [iterate_unit, count_units], [verify_invariant, name_result], []).
window_row(geometry, area_unit_scale_selection, unrecorded_run, [read_operand_attribute, compare_magnitudes, select_unit_scale], [], [], []).
window_row(geometry, axis_aligned_coordinate_distance, unrecorded_run, [locate_position, locate_position, retain_unchanged], [remove_quantity, apply_stored_rule], [], []).
window_row(geometry, choose_first_area_unit_without_scale, break_first_work_break, [select_unit_scale], [], [treat_relevant_as_irrelevant, omit_required_step], []).
window_row(geometry, compare_solid_volume_by_cube_count, keep_then_work_on, [unitize_referent, compare_magnitudes], [count_units, count_units], [set_aside_irrelevant_attribute], []).
window_row(geometry, compare_solid_volume_by_visible_extent, break_then_work_on, [read_operand_attribute, compare_magnitudes], [], [treat_relevant_as_irrelevant], []).
window_row(geometry, composite_prism_volume_sum, keep_first_work_keep, [], [measure_quantity, accumulate_total], [verify_invariant, record_conservation], []).
window_row(geometry, count_overlapping_area_tiles, break_recover_break, [], [iterate_unit, count_units, double_count], [omit_required_step], []).
window_row(geometry, decomposition_with_gap_or_overlap, break_recover_break, [register_givens], [accumulate_total], [accept_without_check, omit_required_step, record_loss], []).
window_row(geometry, dimensional_measure_unit_coordination, unrecorded_run, [read_operand_attribute, read_operand_attribute, assign_roles], [], [inscribe_result], []).
window_row(geometry, directed_difference_as_coordinate_distance, work_then_break, [locate_position, locate_position], [remove_quantity], [omit_required_step, misname_result], []).
window_row(geometry, divide_volume_by_one_dimension, break_recover_break, [retain_unchanged], [compute_quotient], [treat_relevant_as_irrelevant, misname_result], []).
window_row(geometry, ignore_perimeter_rectangle_constraint, work_then_break, [register_givens, retain_where_change_was_due], [], [treat_relevant_as_irrelevant, misname_result], []).
window_row(geometry, ignore_symmetry_multiplicity, break_then_work_on, [register_givens], [count_units, remove_quantity], [treat_relevant_as_irrelevant], []).
window_row(geometry, linear_unit_for_area_or_volume, break_recover_break, [read_operand_attribute], [], [treat_relevant_as_irrelevant, inscribe_result, record_loss], []).
window_row(geometry, omit_half_in_triangle_area, work_then_break, [], [compute_product], [omit_required_step, omit_required_step, misname_result], []).
window_row(geometry, omit_unlabeled_boundary_side, work_then_break, [register_givens], [halt_before_completion], [omit_required_step, misname_result], []).
window_row(geometry, ordered_pair_coordinate_plot, keep_then_work_on, [establish_reference_frame, retain_what_must_survive, locate_position], [], [], []).
window_row(geometry, orientation_bound_shape_classification, work_then_break, [read_operand_attribute, substitute_appearance_for_measure], [], [misname_result], []).
window_row(geometry, parallelogram_area_base_height, keep_then_work_on, [assign_roles, decompose_region], [compute_product], [test_criteria], []).
window_row(geometry, perimeter_two_sides_only, work_then_break, [], [traverse_boundary, traverse_boundary, halt_before_completion], [misname_result], []).
window_row(geometry, perimeter_uses_area_formula, break_recover_break, [read_operand_attribute, substitute_appearance_for_measure], [compute_product], [misname_result], []).
window_row(geometry, polygon_perimeter_boundary_accumulation, unrecorded_run, [register_givens], [traverse_boundary, accumulate_total], [], []).
window_row(geometry, polyhedron_surface_area_from_net, unrecorded_run, [register_givens, decompose_region], [measure_quantity, accumulate_total], [], []).
window_row(geometry, rectangle_area_perimeter_constraint_search, unrecorded_run, [register_givens, register_givens, enumerate_candidates, filter_by_constraint], [], [name_result], []).
window_row(geometry, rectangle_area_unit_iteration, unrecorded_run, [register_givens], [iterate_unit, iterate_unit, iterate_composite_unit, count_units], [], []).
window_row(geometry, rectangle_factor_pair_search, work_then_keep, [register_givens, enumerate_candidates, filter_by_constraint, commute_operands], [], [verify_invariant], []).
window_row(geometry, rectangle_missing_side_from_area, work_then_keep, [register_givens, retain_unchanged], [compute_quotient], [verify_invariant], []).
window_row(geometry, rectangle_missing_side_from_perimeter, work_then_keep, [register_givens, assign_roles], [compute_quotient, remove_quantity], [verify_invariant], []).
window_row(geometry, rectangle_perimeter_boundary_traversal, unrecorded_run, [register_givens], [traverse_boundary, traverse_boundary, traverse_boundary, traverse_boundary, accumulate_total], [], []).
window_row(geometry, rectangle_perimeter_side_pair_search, work_then_keep, [register_givens, enumerate_candidates, filter_by_constraint], [compute_quotient], [verify_invariant], []).
window_row(geometry, rectangular_prism_missing_dimension_from_volume, work_then_keep, [register_givens], [compute_quotient], [verify_invariant], []).
window_row(geometry, rectangular_prism_volume_layer_iteration, unrecorded_run, [unitize_referent, unitize_referent], [iterate_composite_unit, count_units], [], []).
window_row(geometry, rigid_shape_composition, work_then_keep, [unitize_referent, recompose_total], [], [verify_invariant, verify_invariant], []).
window_row(geometry, shape_classification_by_defining_attributes, work_then_keep, [read_operand_attribute], [], [test_criteria, set_aside_irrelevant_attribute, record_conservation], []).
window_row(geometry, slanted_side_as_parallelogram_height, break_then_work_on, [assign_roles, conflate_roles], [compute_product], [omit_required_step], []).
window_row(geometry, subtract_side_from_area, work_then_break, [register_givens], [remove_quantity], [omit_required_step, misname_result], []).
window_row(geometry, sum_overlapping_prism_volumes, work_then_break, [], [measure_quantity, double_count], [omit_required_step, misname_result], []).
window_row(geometry, symmetry_constrained_side_reconstruction, unrecorded_run, [register_givens, assign_roles, isolate_unknown], [accumulate_total, share_into_known_groups], [], []).
window_row(geometry, triangle_area_half_base_height, keep_then_work_on, [assign_roles, assign_roles, recompose_total, select_part], [compute_product], [], []).
window_row(geometry, visible_faces_only_surface_area, work_then_break, [register_givens, enumerate_candidates], [], [omit_required_step, misname_result], []).
window_row(integer, drop_sign_use_magnitude_sum, break_recover_break, [read_operand_attribute, read_operand_attribute], [combine_quantities], [treat_relevant_as_irrelevant, misname_result, record_loss], []).
window_row(integer, inequality_as_boundary_point, work_then_break, [read_operand_attribute], [], [treat_relevant_as_irrelevant, omit_required_step, misname_result], []).
window_row(integer, inequality_solution_set_representation, keep_then_work_on, [read_operand_attribute, read_operand_attribute], [], [test_criteria, inscribe_result], []).
window_row(integer, order_by_magnitude_ignore_sign, break_recover_break, [establish_reference_frame, substitute_scalar_for_structured_quantity, order_by_magnitude], [], [record_loss], []).
window_row(integer, signed_addition_with_sign_relation, work_then_keep, [read_operand_attribute, read_operand_attribute, read_operand_attribute, assign_roles], [combine_quantities], [record_conservation], []).
window_row(integer, signed_number_location_and_order, keep_then_work_on, [establish_reference_frame, locate_position, order_by_magnitude], [], [verify_invariant], []).
window_row(measurement, change_unit_label_without_scaling, work_then_break, [read_operand_attribute, retain_where_change_was_due, rename_in_place_of_transforming], [], [omit_required_step], []).
window_row(measurement, count_marks_not_intervals, work_then_break, [register_givens], [substitute_count_for_measure], [record_loss], []).
window_row(measurement, drop_unit_from_measured_quantity_change, work_then_break, [register_givens], [apply_quantity_change], [treat_relevant_as_irrelevant, misname_result], []).
window_row(measurement, linear_unit_iteration, unrecorded_run, [read_operand_attribute, unitize_referent, partition_into_equal_parts], [iterate_unit], [name_result], []).
window_row(measurement, liquid_volume_count_marks_not_intervals, work_then_break, [register_givens], [substitute_count_for_measure], [record_loss], []).
window_row(measurement, liquid_volume_scale_reading, unrecorded_run, [read_operand_attribute, unitize_referent, partition_into_equal_parts, locate_position], [], [name_result], []).
window_row(measurement, unit_conversion_by_iteration, unrecorded_run, [register_givens], [iterate_composite_unit, compute_product], [name_result], []).
window_row(measurement, unit_preserving_measured_quantity_change, keep_then_work_on, [select_unit_scale, retain_what_must_survive], [apply_quantity_change], [name_result], []).
window_row(multiplication, add_counts_without_composite_unit, break_recover_break, [register_givens], [substitute_count_for_measure, count_units, substitute_operation], [record_loss], []).
window_row(multiplication, add_instead_of_multiply, work_then_break, [register_givens, conflate_roles], [substitute_operation], [record_loss], []).
window_row(multiplication, add_numbers_as_common_multiple, break_recover_break, [register_givens], [substitute_operation, combine_quantities], [omit_required_step], []).
window_row(multiplication, common_factor_intersection, unrecorded_run, [enumerate_candidates, enumerate_candidates, intersect_candidate_sets, select_extremal], [], [], []).
window_row(multiplication, common_multiple_sequence, unrecorded_run, [enumerate_candidates, select_extremal, select_unit_scale], [iterate_composite_unit], [], []).
window_row(multiplication, commute_factors_preserve_product, keep_work_keep, [register_givens, commute_operands], [compute_product, compute_product], [record_conservation], []).
window_row(multiplication, context_free_fact_family_guess, work_then_break, [register_givens], [retrieve_known_fact, substitute_operation], [misname_result, record_loss], []).
window_row(multiplication, coordinate_groups_items, unrecorded_run, [assign_roles], [replicate_equal_groups, iterate_composite_unit], [name_result], []).
window_row(multiplication, distribute_group_size_split, work_then_keep, [decompose_operand, recompose_total], [compute_product, compute_product], [record_conservation], []).
window_row(multiplication, drop_regrouping_remainder, keep_then_break, [regroup_to_base], [replicate_equal_groups, halt_before_completion], [misname_result, record_loss], []).
window_row(multiplication, drop_second_partial_product, work_then_break, [decompose_operand], [compute_product], [omit_required_step, record_loss], []).
window_row(multiplication, factors_of_first_number_only, work_then_break, [enumerate_candidates], [], [omit_required_step, omit_required_step, misname_result], []).
window_row(multiplication, known_product_adjustment, work_then_keep, [read_operand_attribute], [retrieve_known_fact, compute_product, combine_quantities], [record_conservation], []).
window_row(multiplication, known_product_without_adjustment, work_then_break, [read_operand_attribute], [retrieve_known_fact], [omit_required_step, misname_result, record_loss], []).
window_row(multiplication, multiplication_fact_retrieval, work_then_keep, [register_givens, assign_roles], [retrieve_known_fact], [record_conservation], []).
window_row(multiplication, regroup_to_base_preserving_total, keep_then_work_on, [regroup_to_base, retain_what_must_survive], [replicate_equal_groups], [name_result], []).
window_row(multiplication, repeat_equal_groups, unrecorded_run, [assign_roles, assign_roles], [replicate_equal_groups], [name_result], []).
window_row(multiplication, repeat_group_size_by_itself, break_recover_break, [assign_roles, conflate_roles], [replicate_equal_groups], [record_loss], []).
window_row(multiplication, rigid_factor_order_roles, work_then_break, [register_givens, retain_where_change_was_due], [], [treat_relevant_as_irrelevant, omit_required_step, record_loss], []).
window_row(multiplication, sequential_recompute_commuted_products, break_recover_break, [register_givens, compare_magnitudes], [compute_product, compute_product], [omit_required_step, record_loss], []).
window_row(probability, equiprobable_endpoint_counting, break_then_work_on, [register_givens, read_operand_attribute, compare_magnitudes], [count_units, substitute_count_for_measure], [], []).
window_row(probability, terminal_tree_endpoint_probability_sum, unrecorded_run, [register_givens, read_operand_attribute], [accumulate_total], [name_result], []).
window_row(ratio, additive_extension_of_ratio, work_then_break, [register_givens, compose_expression], [remove_quantity, combine_quantities], [record_loss], []).
window_row(ratio, construct_referent_ratio_diagram, unrecorded_run, [assign_roles, assign_roles, assign_roles, compose_expression], [], [inscribe_result], []).
window_row(ratio, reverse_ratio_referent_order, break_recover_break, [register_givens, conflate_roles], [], [inscribe_result, record_loss], []).
window_row(ratio, scale_ratio_unit, work_then_keep, [register_givens, read_operand_attribute, scale_multiplicatively, scale_multiplicatively, compose_expression], [], [record_conservation], []).
window_row(statistics, box_plot_from_five_number_summary, keep_then_work_on, [register_givens, order_by_magnitude, compose_expression, align_to_common_unit], [], [inscribe_result], []).
window_row(statistics, categorical_frequency_bar_representation, unrecorded_run, [assign_roles, establish_reference_frame], [count_units], [inscribe_result], []).
window_row(statistics, distribution_summary_selection, unrecorded_run, [register_givens, read_operand_attribute], [], [], []).
window_row(statistics, dot_plot_frequency_representation, keep_then_work_on, [establish_reference_frame], [], [verify_invariant, inscribe_result], []).
window_row(statistics, five_number_summary_and_iqr, unrecorded_run, [register_givens, order_by_magnitude, partition_into_equal_parts, locate_position], [remove_quantity], [], []).
window_row(statistics, histogram_equal_interval_representation, unrecorded_run, [register_givens, select_unit_scale, partition_into_equal_parts], [count_units], [inscribe_result], []).
window_row(statistics, mean_absolute_deviation, unrecorded_run, [register_givens, locate_position], [measure_quantity, apply_stored_rule, compute_quotient], [], []).
window_row(statistics, mean_as_balance_point, work_then_keep, [register_givens, locate_position], [measure_quantity], [verify_invariant], []).
window_row(statistics, mean_as_fair_share, unrecorded_run, [register_givens], [accumulate_total, count_units, share_into_known_groups], [], []).
window_row(statistics, mean_deviation_without_absolute_value, break_then_work_on, [locate_position], [measure_quantity, compute_quotient], [omit_required_step], []).
window_row(statistics, median_as_ordered_middle, unrecorded_run, [register_givens, order_by_magnitude], [], [], []).
window_row(statistics, mode_as_maximal_frequency, unrecorded_run, [register_givens], [count_units], [name_result], []).
window_row(statistics, question_without_variability, break_then_work_on, [read_operand_attribute, substitute_scalar_for_structured_quantity], [], [name_result], []).
window_row(statistics, statistical_question_variability_classification, keep_then_work_on, [register_givens, read_operand_attribute], [], [test_criteria, name_result], []).
window_row(subtraction, add_instead_of_subtract_column, break_keep_break, [decompose_by_place, recompose_total], [substitute_operation, substitute_operation], [record_loss], []).
window_row(subtraction, answer_as_endpoint_count_up, work_then_break, [assign_roles, assign_roles], [count_up_to_target, count_up_to_target], [misname_result, record_loss], []).
window_row(subtraction, borrow_across_zero_cascade, keep_then_work_on, [decompose_by_place, read_operand_attribute, exchange_base_down, exchange_base_down, exchange_base_down], [remove_quantity], [], []).
window_row(subtraction, borrow_across_zero_no_cascade, break_keep_break, [decompose_by_place, read_operand_attribute, read_operand_attribute, misread_intermediate_value, recompose_total], [], [omit_required_step, omit_required_step, record_loss], []).
window_row(subtraction, borrow_without_reducing_bases, break_then_keep_then_break, [decompose_by_place, recompose_total], [remove_quantity, remove_quantity], [omit_required_step, record_loss], []).
window_row(subtraction, compare_by_matching_difference, unrecorded_run, [assign_roles, match_one_to_one], [remove_quantity, count_units], [name_result], []).
window_row(subtraction, compare_returns_larger_count, work_then_break, [assign_roles, match_one_to_one], [], [treat_relevant_as_irrelevant, misname_result, record_loss], []).
window_row(subtraction, count_up_missing_addend, unrecorded_run, [assign_roles, assign_roles], [count_up_to_target, count_up_to_target], [name_result], []).
window_row(subtraction, decompose_base_for_ones, keep_work_keep, [decompose_by_place, exchange_base_down, recompose_total], [remove_quantity, remove_quantity], [], []).
window_row(subtraction, drop_ones_after_base_takeaway, work_then_break, [decompose_operand], [count_back_from, halt_before_completion], [record_loss], []).
window_row(subtraction, slide_subtrahend_only, break_recover_break, [select_unit_scale], [count_up_to_target, remove_quantity], [omit_required_step, record_loss], []).
window_row(subtraction, sliding_constant_difference, keep_work_keep, [select_unit_scale, transfer_between_operands], [count_up_to_target, remove_quantity], [record_conservation], []).
window_row(subtraction, smaller_from_larger_in_column, break_keep_break, [decompose_by_place, recompose_total], [substitute_operation, substitute_operation], [omit_required_step, record_loss], []).
window_row(subtraction, take_away_base_ones, work_then_keep, [decompose_operand], [count_back_from, count_back_from], [record_conservation], []).

window_row(Family, Signature, Arc, Shell, Core, Closure) :-
    window_row(Family, Signature, Arc, Shell, Core, Closure, _Other).
