/** <module> Generated coverage and absence registry
 *
 * This bounded relation records receipt status for three live source sets:
 * Lakoff--Nunez metaphor families, IM lessons with compiled productive
 * tasks, and the lesson-evidence pipeline inputs.  It does not claim a
 * complete curriculum inventory.
 *
 * Statuses preserve distinctions found in the current tree:
 *   - present: a named source fact or parsed source record supports the receipt.
 *   - coverage_gap: the relevant machinery loads, but no receipt joins this subject.
 *   - broken_pipeline: a required upstream input is absent from this checkout.
 *   - path_drift: the reader names an old path while the source is present elsewhere.
 *   - not_applicable: the receipt belongs only to an optional build mode.
 *   - unknown: the available source record cannot establish the receipt.
 *
 * Generated by scripts/extract_coverage_absence_registry.py.
 * Regenerate: python3 scripts/extract_coverage_absence_registry.py
 */

:- module(coverage_absence_registry,
          [ coverage_receipt/4,
            receipt_denominator/2,
            receipt_status_count/3,
            metaphor_without_renderer/2,
            lesson_without_structured_negative/2
          ]).

coverage_receipt(metaphor(bmi_circle_polygon), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(bmi_projective), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(bmi_via_set_blend), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(categories_are_containers), renderer, coverage_gap(no_primitive_renderer_join), [source_fact(grounding_to_primitive, primitive_renders_metaphor), source_table(representation_asset_manifest, representation_concepts)]).
coverage_receipt(metaphor(container_schema), renderer, present, [source_fact(grounding_to_primitive, primitive_renders_metaphor, 'P2', container_schema, secondary), source_table(representation_asset_manifest, representation_concepts), source_fact(representation_grammar, representation_render_status, fraction_bars, fraction_render)]).
coverage_receipt(metaphor(fictive_motion), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(motion_along_a_path), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(rotation_plane_blend), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(source_path_goal), renderer, present, [source_fact(grounding_to_primitive, primitive_renders_metaphor, 'P1', source_path_goal, primary), source_table(representation_asset_manifest, representation_concepts), source_fact(representation_grammar, representation_render_status, number_line, number_line_render)]).
coverage_receipt(metaphor(space_set_blend), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(spaces_are_sets_of_points), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(metaphor(unit_circle_blend), renderer, coverage_gap(no_primitive_mapping), [source_fact(geometry_schema, lakoff_nunez_metaphor_family)]).
coverage_receipt(lesson('IM-G1-U2-L1'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U2-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U2-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U2-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U2-L18'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U2-L19'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U2-L2'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U2-L20'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U2-L3'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U2-L6'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U3-L11'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U3-L12'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U3-L17'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U3-L2'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U3-L22'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U3-L26'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U3-L6'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G1-U4-L14'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G1-U6-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U6-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U8-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G1-U8-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G2-U1-L16'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade2/unit1/lesson16.md', 'curriculum/im_teacher_guides/grade2/unit1/lesson16.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G2-U2-L1'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G2-U2-L11'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G2-U2-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G2-U2-L14'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade2/unit2/lesson14.md', 'curriculum/im_teacher_guides/grade2/unit2/lesson14.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G2-U2-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G2-U3-L10'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G2-U3-L11'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G2-U5-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U1-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U1-L12'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G3-U1-L13'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G3-U1-L14'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G3-U1-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U1-L18'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade3/unit1/lesson18.md', 'curriculum/im_teacher_guides/grade3/unit1/lesson18.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G3-U1-L19'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U1-L9'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade3/unit1/lesson9.md', 'curriculum/im_teacher_guides/grade3/unit1/lesson9.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G3-U2-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U2-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U3-L2'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G3-U3-L9'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G3-U4-L1'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade3/unit4/lesson1.md', 'curriculum/im_teacher_guides/grade3/unit4/lesson1.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G3-U4-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U4-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U4-L6'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade3/unit4/lesson6.md', 'curriculum/im_teacher_guides/grade3/unit4/lesson6.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G3-U4-L7'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U6-L8'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G3-U7-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U7-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G3-U7-L9'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade3/unit7/lesson9.md', 'curriculum/im_teacher_guides/grade3/unit7/lesson9.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G4-U1-L2'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G4-U3-L1'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G4-U3-L8'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G4-U5-L16'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G4-U5-L3'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G4-U5-L7'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade4/unit5/lesson7.md', 'curriculum/im_teacher_guides/grade4/unit5/lesson7.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G4-U6-L14'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G4-U6-L5'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G5-U1-L11'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G5-U2-L1'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/grade5/unit2/lesson1.md', 'curriculum/im_teacher_guides/grade5/unit2/lesson1.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-G5-U4-L19'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G5-U4-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G5-U5-L11'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-G5-U5-L4'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G5-U5-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G5-U8-L7'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G6-U2-L11'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L16'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L17'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L2'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L7'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U2-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L17'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L2'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U3-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L1'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L17'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L2'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L7'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U4-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L1'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L10'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G6-U5-L11'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G6-U5-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L7'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U5-L8'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G6-U5-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L1'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L13'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L16'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G6-U7-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L7'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U2-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L1'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L4'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L5'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L6'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U4-L9'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L1'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L12'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L14'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L15'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L16'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-G7-U5-L2'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L3'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L4'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L5'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L6'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L7'), structured_negative, present, [source_fact(lesson_monitoring, explicit_lesson_misconception)]).
coverage_receipt(lesson('IM-G7-U5-L8'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-GK-U5-L7'), structured_negative, present, [source_fact(compiled_task_instances, compiled_lesson_task_instance)]).
coverage_receipt(lesson('IM-GK-U7-L10'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(lesson('IM-GK-U8-L18'), structured_negative, path_drift('geometry/corpus/im_teacher_guides/kindergarten/unit8/lesson18.md', 'curriculum/im_teacher_guides/kindergarten/unit8/lesson18.md'), [source_fact(lesson_negative_receipts, reviewed_source_fragment)]).
coverage_receipt(lesson('IM-GK-U8-L3'), structured_negative, coverage_gap(no_structured_negative_receipt), [machinery(lesson_monitoring), machinery(compiled_task_instances), machinery(lesson_negative_receipts)]).
coverage_receipt(pipeline(build_lesson_evidence), input(spine), broken_pipeline('data/learningcommons/derived/im_k8_spine.json'), [reader_path, absent_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(standard_action_catalog), broken_pipeline('data/learningcommons/derived/im_ccss_action_catalog.json'), [reader_path, absent_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(productive_deformation_catalog), broken_pipeline('data/learningcommons/derived/im_productive_deformation_catalog.json'), [reader_path, absent_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(negative_receipts), present, [parsed_receipt_records(10)]).
coverage_receipt(pipeline(build_lesson_evidence), input(compiled_action_mappings), path_drift('lessons/im/generated/compiled_action_mappings.pl', 'curriculum/im/generated/compiled_action_mappings.pl'), [reader_path, relocated_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(compiled_task_instances), path_drift('lessons/im/generated/compiled_task_instances.pl', 'curriculum/im/generated/compiled_task_instances.pl'), [reader_path, relocated_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(atlas_landscape), broken_pipeline('scripts/bigred/iteration15/work/atlas/atlas_landscape.jsonl'), [reader_path, absent_source_file]).
coverage_receipt(pipeline(build_lesson_evidence), input(refresh_catalog_nodes), not_applicable(refresh_catalog_only), [reader_path('data/learningcommons/nodes.jsonl')]).

receipt_denominator(metaphor_renderer, 12).
receipt_denominator(productive_lesson_structured_negative, 151).
receipt_denominator(lesson_evidence_pipeline, 8).

receipt_status_count(metaphor_renderer, present, 2).
receipt_status_count(metaphor_renderer, coverage_gap, 10).
receipt_status_count(metaphor_renderer, broken_pipeline, 0).
receipt_status_count(metaphor_renderer, path_drift, 0).
receipt_status_count(metaphor_renderer, not_applicable, 0).
receipt_status_count(metaphor_renderer, unknown, 0).
receipt_status_count(productive_lesson_structured_negative, present, 39).
receipt_status_count(productive_lesson_structured_negative, coverage_gap, 102).
receipt_status_count(productive_lesson_structured_negative, broken_pipeline, 0).
receipt_status_count(productive_lesson_structured_negative, path_drift, 10).
receipt_status_count(productive_lesson_structured_negative, not_applicable, 0).
receipt_status_count(productive_lesson_structured_negative, unknown, 0).
receipt_status_count(lesson_evidence_pipeline, present, 1).
receipt_status_count(lesson_evidence_pipeline, coverage_gap, 0).
receipt_status_count(lesson_evidence_pipeline, broken_pipeline, 4).
receipt_status_count(lesson_evidence_pipeline, path_drift, 2).
receipt_status_count(lesson_evidence_pipeline, not_applicable, 1).
receipt_status_count(lesson_evidence_pipeline, unknown, 0).

metaphor_without_renderer(Family, Status) :-
    coverage_receipt(metaphor(Family), renderer, Status, _),
    Status = coverage_gap(_).

lesson_without_structured_negative(Lesson, Status) :-
    coverage_receipt(lesson(Lesson), structured_negative, Status, _),
    ( Status = coverage_gap(_) ; Status = broken_pipeline(_) ;
      Status = path_drift(_, _) ; Status = unknown(_) ).
