/** <module> Generated data-consumption manifest
 *
 * The manifest partitions the current data tree into artifact rows. A row is
 * one file except data/asktm and data/research_assets, each one directory
 * corpus whose member files are supplied together and not independently
 * addressed by repository code. Every regular file in data/ belongs to exactly
 * one row. JSON, JSONL, CSV, DB, SQLite, and BibTeX files in scripts/,
 * knowledge/, and curriculum/ are also individual rows. Prolog source facts,
 * Markdown, and application assets are outside this bounded denominator.
 *
 * Reader and writer joins come from static Python, Prolog, and shell path
 * references. Python resolves literals, Path joins rooted at a repository
 * constant, simple named path constants, and glob bases. Prolog and shell
 * contribute literal path arguments. A missing reader path remains a row in
 * data_missing_reader_path/4; it is not repaired or discarded. Dynamic paths,
 * reflection, indirect database access, and nonconstant path assembly are
 * outside this instrument, so an unconsumed row means no reader it can see,
 * not proof that no runtime consumer exists.
 *
 * Statuses are derived from the current scan: live_reader; reader_and_writer;
 * writer_without_reader; unconsumed_file; and unconsumed_corpus. The latter
 * two are analysis markers only, never deletion recommendations.
 *
 * duplicate_content/2 uses an exact file byte hash or a deterministic corpus
 * tree hash. It cannot find table subsets, normalized-text matches, or equal
 * members hidden inside one directory corpus.
 *
 * Generated by scripts/extract_data_consumption_manifest.py.
 * Regenerate: python3 scripts/extract_data_consumption_manifest.py
 */

:- module(data_consumption_manifest,
          [ data_artifact/9,
            data_artifact_denominator/2,
            data_root_denominator/4,
            data_status_count/2,
            data_missing_reader_path/4,
            duplicate_content/2,
            data_consumption_control/5,
            unconsumed_data_artifact/3
          ]).

data_artifact('curriculum/im/coverage/im_coverage.json', file, 1, 828282, '5514471aad950672c6efecf00b403e989180a5971bd33ad8b8fa0b7adf85105d', reader_and_writer, static_reader_and_writer, [reader('scripts/checks/lesson_topics_cache.py', 50, read_text), reader('scripts/curriculum/build_default_fill_lessons.py', 91, read_text), reader('scripts/curriculum/build_lesson_evidence.py', 586, glob), reader('scripts/curriculum/compile_receipt_routes.py', 142, glob), reader('scripts/extract_coverage_absence_registry.py', 246, read_text), reader('scripts/research/build_default_fill_lessons.py', 11, open), reader('scripts/research/build_field_context_cache.py', 134, read_text), reader('scripts/research/build_im_coverage.py', 102, glob), reader('scripts/research/build_lesson_topics_cache.py', 44, read_text), reader('scripts/research/misconception_embedding.py', 280, read_text), reader('scripts/research/propose_middle_school_pairings.py', 148, read_text)], [writer('scripts/curriculum/ingest_vision.py', 192, open), writer('scripts/research/build_im_coverage.py', 413, write_text)]).
data_artifact('curriculum/im/coverage/lesson_evidence_ratchet.json', file, 1, 1987, '41ca66870d2025a04c1f566c6cdd4bbd68957cb57b4233b0883916fc7270eb0b', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 586, glob), reader('scripts/curriculum/compile_receipt_routes.py', 142, glob), reader('scripts/extract_coverage_absence_registry.py', 246, read_text), reader('scripts/research/build_im_coverage.py', 54, read_text), reader('scripts/research/build_im_coverage.py', 102, glob)], [writer('scripts/curriculum/ingest_vision.py', 192, open)]).
data_artifact('curriculum/im/docling_figures_interpreted.json', file, 1, 1269904, '3fb9ff749f50efbaa949f74c2e0c68bb2bc0b494a161e8d5d45f2001d9f01cba', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 586, glob), reader('scripts/curriculum/compile_receipt_routes.py', 142, glob), reader('scripts/extract_coverage_absence_registry.py', 246, read_text), reader('scripts/research/build_im_coverage.py', 102, glob)], [writer('scripts/curriculum/ingest_vision.py', 192, open)]).
data_artifact('curriculum/im/generated/field_context_cache.json', file, 1, 17240426, '53ba92cfce0c418614d11105c5c991f3463a72ae6842b0dad65724d1145f40ef', reader_and_writer, static_reader_and_writer, [reader('hermes/app/field_context_cache.py', 12, read_text), reader('hermes/review_queue.pl', 172, text_reader_call), reader('scripts/checks/field_context_cache.py', 59, read_text), reader('scripts/checks/relevance_negation.py', 217, read_text), reader('scripts/checks/review_surface.py', 50, read_text), reader('scripts/curriculum/build_lesson_evidence.py', 586, glob), reader('scripts/curriculum/compile_receipt_routes.py', 142, glob), reader('scripts/extract_coverage_absence_registry.py', 246, read_text), reader('scripts/research/build_field_context_cache.py', 522, read_text), reader('scripts/research/build_im_coverage.py', 102, glob), reader('scripts/research/build_relevance_negation.py', 329, read_text), reader('scripts/research/misconception_embedding.py', 281, read_text), reader('scripts/research/propose_middle_school_pairings.py', 173, read_text)], [writer('scripts/curriculum/ingest_vision.py', 192, open)]).
data_artifact('curriculum/im/generated/recovered_task_spans.json', file, 1, 477811, '784aaea835920422846f2cb1925db0e4465e0fde4361370a54da7d8fc96e1c67', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 586, glob), reader('scripts/curriculum/compile_receipt_routes.py', 142, glob), reader('scripts/extract_coverage_absence_registry.py', 246, read_text), reader('scripts/research/build_im_coverage.py', 102, glob)], [writer('scripts/curriculum/ingest_vision.py', 192, open)]).
data_artifact('data/asktm', directory_corpus, 6543, 685669439, 'a1a1ae279e70292ae47df69c4b913c10737afc63f563d2daff7dbabc5133e3c6', unconsumed_corpus, no_static_reader_or_writer, [], []).
data_artifact('data/learningcommons/derived/im_ccss_action_catalog.json', file, 1, 156240, '10d40fff1b20ea6265144336e30c2d64b5711330f9765615b8b834f886c322ab', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 745, read_text), reader('scripts/curriculum/build_lesson_evidence.py', 751, read_text)], [writer('scripts/curriculum/build_lesson_evidence.py', 749, write_text)]).
data_artifact('data/learningcommons/derived/im_k8_spine.json', file, 1, 543320, '5d5cb6c3181c377710eeb3195c37502dcc0ba8c219b013996d47bd7d45797209', live_reader, static_reader, [reader('scripts/curriculum/build_lesson_evidence.py', 740, read_text), reader('scripts/extract_im_lesson_identity.py', 109, read_text), reader('scripts/extract_vision_lesson_digest_audit.py', 155, read_text), reader('scripts/research/verify_vision_excerpts.py', 600, read_text)], []).
data_artifact('data/learningcommons/derived/im_lesson_evidence.json', file, 1, 2019940, '3f05e62f90151a5716e2e6df1a00b5d74ffca59993fb4e69197d96926cb43cf1', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 770, read_text), reader('scripts/curriculum/pusu_pass.py', 340, read_text), reader('scripts/extract_task_span_absence_registry.py', 390, lesson_readiness), reader('scripts/research/generate_negative_receipts.py', 258, read_text), reader('scripts/research/generate_negative_receipts.py', 360, read_text), reader('scripts/research/generate_negative_receipts.py', 1266, read_text)], [writer('scripts/curriculum/build_lesson_evidence.py', 774, write_text)]).
data_artifact('data/learningcommons/derived/im_productive_deformation_catalog.json', file, 1, 24867, '5e5f052e5b867875c305e0e37f896a31ce91ca22339277e3205a56e9a063f77e', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/build_lesson_evidence.py', 756, read_text), reader('scripts/curriculum/build_lesson_evidence.py', 766, read_text)], [writer('scripts/curriculum/build_lesson_evidence.py', 764, write_text)]).
data_artifact('data/learningcommons/derived/pusu_pass.json', file, 1, 2681701, '31ec62c4f222c1b5c187fe12ef39906587fe79faa5612ce94613f0cda3907390', writer_without_reader, static_writer_no_reader, [], [writer('scripts/curriculum/pusu_pass.py', 431, write_text), writer('scripts/curriculum/pusu_pass.py', 453, write_text)]).
data_artifact('data/learningcommons/derived/pusu_pass.pl', file, 1, 27553, '7ba215cde1d080f42919e5938e8fec0a2d2b5471792f631ad7416cc0a411f97a', writer_without_reader, static_writer_no_reader, [], [writer('scripts/curriculum/pusu_pass.py', 432, write_text), writer('scripts/curriculum/pusu_pass.py', 454, write_text)]).
data_artifact('data/research/corpus_binding_diagnostics.json', file, 1, 100050, '921493df457632963f262b6f116695079f49918a35db51520eb66a5b6a7697ad', live_reader, static_reader, [reader('hermes/review_queue.pl', 189, text_reader_call), reader('scripts/checks/review_surface.py', 119, read_text)], []).
data_artifact('data/research/corpus_binding_proposals.json', file, 1, 310881, '76e1128bf875b1fd171e6990c45181c4f3575c48243db228d3d17895e8437bc2', live_reader, static_reader, [reader('hermes/review_queue.pl', 187, text_reader_call), reader('scripts/checks/review_surface.py', 45, read_text)], []).
data_artifact('data/research/grade78_pairing_proposals.jsonl', file, 1, 225287, '34ba0b2db861521dbd3248eb8364a43dcd6004336fd8ce7433650b2a2343000b', live_reader, static_reader, [reader('hermes/review_queue.pl', 171, text_reader_call), reader('scripts/checks/review_surface.py', 44, read_jsonl)], []).
data_artifact('data/research/incompatibility_triples.json', file, 1, 344280, '589fa93536490637373ffd0d67cebfe2547e1205d6010717938f9e4ebc2f3855', live_reader, static_reader, [reader('scripts/extract_error_rule_incompatibility.py', 104, read_text)], []).
data_artifact('data/research/lesson_embedding_payloads.json', file, 1, 12418216, '63a95b409085caaa697124eddf8cd900aa43a1ca3363e10f9f9a766fd6e42696', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/lesson_embeddings.json', file, 1, 6378040, 'df7163e75d2d373ee136466ed22e26d1b22325d1a3eef5032e8ec6d6067c77a9', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/lesson_embeddings.npz', file, 1, 11473865, '427c68db16dab2310d83aea34fdd7d4386f1e28d88ef7fbb9a47020b49d575a0', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/literature/README.md', file, 1, 1098, 'f563390b7c05b2fe519b8e3dc59f115bf93460b63a319fdf86e8fd2eda0b9784', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/literature/corpus_failures.jsonl', file, 1, 2597, 'adc90f9b7b6b035940b511c0151b4ab9ca6ea7851978b8b5e0fdfca9448fe05f', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/literature/corpus_index.jsonl', file, 1, 1228501, '3a308d81009e8d2ef02ee3438c7a230aace68476bf152d177b8bd9b87fa2c693', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/literature/corpus_manifest.json', file, 1, 498, '12bf8e758f3ac7fed920f858c72c276f2e9a72593cb62e8801cdf137c35a66a4', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/misconception_embeddings.json', file, 1, 563734, 'b0681ccf1980144f16f2d32b25beb1345343d119330797918d409410b97e3e2f', live_reader, static_reader, [reader('hermes/app/routes/misconception_search.py', 78, read_text)], []).
data_artifact('data/research/misconception_embeddings.npz', file, 1, 18037540, '0ee870b49d4eb25dd70abd45959127a939eebfaa2abaf949bed618015e0469f6', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/recognition_benchmark.json', file, 1, 436699, 'b4a84b561e101cab1185749a9b562c6fb00528f9680e1d91fe597c25b9838725', live_reader, static_reader, [reader('scripts/checks/recognition_benchmark.py', 84, read_bytes), reader('scripts/checks/recognition_benchmark.py', 91, read_text)], []).
data_artifact('data/research/references.bib', file, 1, 659759, '581f34ac125c2638c1cf5d3faef926e0b9deb563c9e57446adb29dd8b16565dd', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/registry_op_embedding_payloads.json', file, 1, 223912, 'bea7b3a131d5c502868ba377aa60bcf663c2e8683b001498a9df3b8a2883fe0a', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/registry_op_embeddings.json', file, 1, 129373, 'a051416255c9f52922c46fccbf9bfd5f3747c062cdecda8f092ee321de83ed3a', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/registry_op_embeddings.npz', file, 1, 1718833, '9c5ecaf8971bc99fedf36790b0151dcd1571d6ab65a9a82ffacf021281121ddc', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/research_shared.db', file, 1, 13881344, 'bc3609b8fba19d84264bfb87e776458867fac2f9f38323e1509a1e3c030f8f00', reader_and_writer, static_reader_and_writer, [reader('hermes/app/routes/logic.py', 177, sqlite_connect), reader('hermes/app/routes/logic.py', 270, sqlite_connect), reader('scripts/checks/attested_phrases.py', 111, sqlite_connect), reader('scripts/checks/recognition_benchmark.py', 141, sqlite_connect), reader('scripts/checks/review_surface.py', 77, sqlite_connect), reader('scripts/extract_research_corpus_automaton_bindings.py', 25, sqlite_connect), reader('scripts/extract_research_corpus_misconceptions.py', 83, sqlite_connect), reader('scripts/research/ask_the_window.py', 93, sqlite_connect), reader('scripts/research/build_attested_phrases.py', 188, sqlite_connect), reader('scripts/research/code_incompatibility_triples.py', 279, sqlite_connect), reader('scripts/research/export_mua_for_mud.py', 233, sqlite_connect), reader('scripts/research/map_corpus_to_automata.py', 204, sqlite_connect)], [writer('scripts/research/apply_incompatibility_triples.py', 79, sqlite_connect)]).
data_artifact('data/research/self_description_census.json', file, 1, 65705, '48563d9f9ccbedbe6696ae12a0f059c450cec363fa1c3ee477861e36e841ece9', reader_and_writer, static_reader_and_writer, [reader('scripts/checks/self_description_census.py', 54, read_bytes)], [writer('scripts/research/build_self_description_census.py', 951, write_text)]).
data_artifact('data/research/strategy_embedding_payloads.json', file, 1, 202985, '8585b8de9dc7792bdc2edec63fd37465c38c418afe7315347b95319185f35fbf', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/strategy_embeddings.json', file, 1, 103986, 'cf85ec98773800fd00937892998d6d3b050e0e286f09dab95989f0975b91beeb', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/strategy_embeddings.npz', file, 1, 1507895, '4af9d6e6b08f5aa3d26aa68360b6c4864f4e9a88d08cc755152818ff50c7af48', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/talkmoves_recognizer_sweep.json', file, 1, 6607, '981075f5a4fbe3b360580201b91e16dd49baf031b6ec6e9e8e28353b3b6b619f', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/vision_excerpt_verification.json', file, 1, 3251269, '0baba32a88d8fa71ee1f3bde237c8fbda5b01cf96e3595087805d49beaa5a081', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research/window_vs_shards.json', file, 1, 23271, '1f7d2864b9eb03ea61210eadb0a1c74a7ad7cdde3c9c20ddf2f519c4a2cabf0b', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('data/research_assets', directory_corpus, 1610, 190039134, 'cafa888de592ace6df4e9cedb3e4b17652703b5f86ff4ed9a2803d7add7eeeaf', reader_and_writer, static_reader_and_writer, [reader('hermes/app/scripts/export_real_transplants.py', 94, read_text), reader('hermes/representation/extract_figures_docling.py', 118, open), reader('scripts/checks/pedagogical_questions_check.py', 18, glob)], [writer('hermes/representation/extract_figures_docling.py', 210, open)]).
data_artifact('scripts/bigred/iteration15/work/atlas/atlas_landscape.jsonl', file, 1, 6958191, '064d4dc2c5c5d7966c3955fcea40c1be3b8097a540fe9f70a42bf74e3093c441', live_reader, static_reader, [reader('scripts/curriculum/build_lesson_evidence.py', 571, read_text)], []).
data_artifact('scripts/bigred/iteration15/work/atlas/atlas_summary.json', file, 1, 5723, 'dd2f27719e2abe1c435be7d7c28771d6da58c20691c3321aa3b141d48d47e0ba', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_complete_expression.json', file, 1, 987, 'adcc686b08f96259cc2c802eb3bcf176018abdb8841bed5a158f373885bf1192', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_cross_pair.json', file, 1, 1005, 'e56b50b6a41d51c8c5616ab1a5b371d5f1bd0021d5babc6c7b9f174ad4fc6f0c', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_declared_absent.json', file, 1, 985, '000d6751de5d82f27b9ded70e3712e504f86ba4206d27cf372d6e5b8a51fbd47', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_e343_pdf.json', file, 1, 979, 'c5f530623ba54846028bc4f356d576fda47b8f1601b8782815d426e725c742f9', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_hyphen_range.json', file, 1, 317, 'a45abf14364f2bc0d56baae0d369d39c8420e0abe06855ebfe206affab8a6b0f', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_manufactured_dot_image.json', file, 1, 989, 'bbb5676aa9dbf1054deeeac7e5918c66044eba3f9cfdcfefdc588d9d438bae3e', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_markerless_cross_pair.json', file, 1, 1115, 'db4b1f3a285fbc6769b71162b629711682c6d2c9591f2641f9f7b52837a588c2', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_markerless_single_expression.json', file, 1, 983, '23b1bca4fbf7cbf42999fc44eb0fa31b6eff80b6e719d61e46ee84e7028dd70d', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_missing_witness.json', file, 1, 849, 'f4da370ede7495922472952fbd95adaa9f9000683d1029941f0836a60f917773', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_off_span_citation.json', file, 1, 1002, 'df32b58708609db5dd904f47d10ba6cb8f9ea70914afccee7d3cab3290f30af1', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_recovered_span_complete.json', file, 1, 1058, 'f21ef33b0c165611d1211605dd328c71ef19184c600f46df19203d7a9bddb296', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_recovered_span_truncated.json', file, 1, 1017, '1c2d98ea3ee4466fc869dd63327b0ec97c8454bdcbb7eac22eff79cc604bcc7b', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_truncated_expression.json', file, 1, 996, '4e0f29b8f057ba9c2d6076006e59acec23b377ac995afe2fe8dc89d9fd983077', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/lesson_task_readings_wrapped_span.json', file, 1, 525, 'bf036bb21642e67d81d951aad51997ff81012ef394b0326bd0df60f81b958937', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob)], []).
data_artifact('scripts/checks/fixtures/negative_receipt_candidate_contract_whole_domain.json', file, 1, 504, '8267e86340140fcdc6e8be19e0519fc238b879a65a72793228308a7f793e3924', live_reader, static_reader, [reader('scripts/checks/lesson_task_readings.py', 13, glob), reader('scripts/research/generate_negative_receipts.py', 409, read_text)], []).
data_artifact('scripts/curriculum/action_mapping_rules.json', file, 1, 290141, '4bdc85133a8b9c6a3534145590560d3b15248dbd564bbcad0d61bd0b8dde39e4', reader_and_writer, static_reader_and_writer, [reader('scripts/curriculum/ingest_vision.py', 196, open), reader('scripts/research/verify_vision_excerpts.py', 751, read_text)], [writer('scripts/curriculum/ingest_vision.py', 200, open)]).
data_artifact('scripts/curriculum/basis_set.json', file, 1, 6321, '565dcf8bd832096502516bd9c282dadf84bdbcfa7b412d87ee436e147b13e281', live_reader, static_reader, [reader('scripts/curriculum/mini_atlas.pl', 5, text_reader_call)], []).
data_artifact('scripts/curriculum/guide_math_glyphs.json', file, 1, 5848, '70e1600049e7d3ce5818287e3284f66e8fb163062080e4633adccc8c99b5432b', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('scripts/curriculum/lesson_negative_receipts.json', file, 1, 131945, 'af0f37e9da24f3083e19c200e15a50675efe25f658acc8742edfdbc2131e968a', live_reader, static_reader, [reader('scripts/curriculum/build_lesson_evidence.py', 348, read_text), reader('scripts/extract_coverage_absence_registry.py', 298, read_text), reader('scripts/extract_vision_lesson_digest_audit.py', 156, read_text), reader('scripts/research/generate_negative_receipts.py', 984, read_text), reader('scripts/research/generate_negative_receipts.py', 1267, read_text)], []).
data_artifact('scripts/curriculum/lesson_task_readings.json', file, 1, 66191, 'c8a1186e6b615ace37d7d5739c51bf833e38ddd947029538a8024ed7f4702285', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('scripts/curriculum/vision_harvest/im_g6_8_vision_harvest.json', file, 1, 1891193, '8b543302896d141345e927dee6a4d73289c169723fbbf4ea95313b1547dff196', live_reader, static_reader, [reader('scripts/extract_vision_lesson_digest_audit.py', 154, read_text), reader('scripts/research/check_vision_harvest_excerpts.py', 292, read_text), reader('scripts/research/verify_vision_excerpts.py', 563, read_text)], []).
data_artifact('scripts/curriculum/vision_harvest/im_g6g7_vision_harvest.json', file, 1, 1104416, 'c9cc53ed1750d3dd8d406be4b09349fe1eb7fd1f2a48b99ea2b195a4845a4d18', live_reader, static_reader, [reader('scripts/research/check_vision_harvest_excerpts.py', 293, read_text), reader('scripts/research/verify_vision_excerpts.py', 562, read_text)], []).
data_artifact('scripts/curriculum/vision_harvest/registry_vocab.json', file, 1, 4556, 'e92149bbf57c78c9f38e9ce83e7e79ddfde4cf464815faab90d9855c4fa3e715', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('scripts/research/brandomian_lexicons.json', file, 1, 510, 'a75cde2981082c8e214e3851bed3683d0f165bd8bd740f842ade4a4e24da13c9', live_reader, static_reader, [reader('scripts/checks/vocabulary_licenses.py', 463, read_text)], []).
data_artifact('scripts/research/churn_out/pilot_summary.json', file, 1, 1032364, '1c545cbbcf26248ab9a60a2392b512bee19197e90dc33182e2155dcd70bf85da', unconsumed_file, no_static_reader_or_writer, [], []).
data_artifact('scripts/research/mobius_band_lexicons.json', file, 1, 1655, 'a78d7498123eec35241b8e56cee9e4ffcbeec41aff3385537fc8532bb0fbc830', live_reader, static_reader, [reader('scripts/checks/vocabulary_licenses.py', 462, read_text), reader('scripts/research/mobius_adversarial_loop.py', 372, read_text)], []).

data_artifact_denominator(data_tree_regular_file, 8185).
data_artifact_denominator(manifest_artifact, 67).
data_root_denominator(curriculum, 5, 5, 19818410).
data_root_denominator(data, 34, 8185, 954458419).
data_root_denominator(scripts, 28, 28, 11512365).

data_status_count(live_reader, 29).
data_status_count(reader_and_writer, 12).
data_status_count(writer_without_reader, 2).
data_status_count(unconsumed_file, 23).
data_status_count(unconsumed_corpus, 1).

data_missing_reader_path('data/external/talkmoves', 'scripts/research/talkmoves_lesson_run.py', 864, read_text).
data_missing_reader_path('data/external/talkmoves/keys/talkmoves_answer_key.jsonl', 'scripts/research/talkmoves_lesson_run.py', 657, open).
data_missing_reader_path('data/external/talkmoves/manifests/talkmoves_blind_manifest.json', 'scripts/research/other_curriculum_intake.py', 242, read_text).
data_missing_reader_path('data/external/talkmoves/manifests/talkmoves_blind_manifest.json', 'scripts/research/talkmoves_lesson_run.py', 852, read_text).
data_missing_reader_path('data/external/talkmoves/manifests/talkmoves_blind_manifest.json', 'scripts/research/talkmoves_rerun.py', 44, read_text).
data_missing_reader_path('data/learningcommons/nodes.jsonl', 'scripts/curriculum/build_lesson_evidence.py', 198, read_text).
data_missing_reader_path('data/research/review_decisions.jsonl', 'scripts/checks/review_surface.py', 263, read_text).


data_consumption_control(learningcommons_coverage_registry, 'data/learningcommons/derived/im_lesson_evidence.json', 'scripts/extract_coverage_absence_registry.py', not_found, declared_reader_not_in_checkout).
data_consumption_control(learningcommons_coverage_builder_claim, 'data/learningcommons/derived/im_lesson_evidence.json', 'scripts/research/build_im_coverage.py', not_found, declared_reader_not_in_checkout).
data_consumption_control(learningcommons_lesson_evidence_builder, 'data/learningcommons/derived/im_lesson_evidence.json', 'scripts/curriculum/build_lesson_evidence.py', resolved, expected_reader).
data_consumption_control(research_db_recognition_benchmark, 'data/research/research_shared.db', 'scripts/checks/recognition_benchmark.py', resolved, expected_reader).
data_consumption_control(atlas_landscape_lesson_evidence, 'scripts/bigred/iteration15/work/atlas/atlas_landscape.jsonl', 'scripts/curriculum/build_lesson_evidence.py', resolved, expected_reader).

unconsumed_data_artifact(Path, Kind, Reason) :-
    data_artifact(Path, Kind, _, _, _, Status, Reason, [], []),
    memberchk(Status, [unconsumed_file, unconsumed_corpus]).
