#!/usr/bin/env python3
"""Regression check for the grammar layer over the action alphabet.

``knowledge/strategies/action_grammar.pl`` is generated by
``scripts/research/build_action_grammar.py`` from three sources: the canonical
alphabet, the strategy transition tables, and the discursive genre in
``knowledge/discourse/commitment_automata.pl``.  This check holds it to what it
claims.

  Regeneration.  The builder rerun into a temporary directory is byte-identical
  to the committed file.  A hand edit to the derived rows cannot pass.

  Strict load.  Both new modules load clean under SWI with warnings fatal.

  Coverage.  Every machine in both genres has exactly one machine_grammar row;
  every arc a row names is declared; every declared arc and phrase is carried by
  at least one machine, so neither table holds a dead name.

  The discursive genre is well formed.  Every machine's declared actions match
  its edges, every state is reachable from the start, an accepting state is
  reachable, no state-action pair has two targets, and every action has a
  canonical_action/3 row of the right genre.

  The stance projection is faithful.  Each row's stances list is the machine's
  own word rewritten through action_register/4, and its arc is that list with
  runs collapsed.  This is recomputed here from the tables rather than trusted.

  The phrase factorization is faithful.  Concatenating each row's phrases, with
  named phrases expanded back to their sequences, reproduces the machine's
  action word exactly.

  The gap census is complete.  ``machine_conservation_gap/4`` names exactly the
  machines whose every step is neutral -- no more, so it cannot overstate the
  gap, and no fewer, so a machine cannot slip out of the work list by being
  omitted.

  The stances are audited against a source that did not author them.  The
  productive/deformation pairing lives in
  ``knowledge/strategies/math/*_action_pairs.pl``.  Over every pairing whose two
  sides both have an extracted automaton, the check requires that the productive
  side carry no deforming step and the deformation side carry one.  That is the
  one thing an independent source can say about a stance assignment, and it says
  it about 65 pairs without anyone reading the stance table.

  Answerability is extraction, not authorship.  Every ``machine_answerability``
  row names an ``invariant/1`` that an action-pair source declares verbatim, and
  every ``incompatible_pair`` divergence step is recomputed from the two words.

  The interruption model carries no verdicts.  It was replaced: the derived
  stop / watch / continue verdicts would have fired on 59 of 189 machines, and the
  practice they modelled is infrequent.  Two authored conditions stand in their
  place, every ``contradiction_loop`` instance is re-tested for a cycle reachable
  from the start, every cycle in the corpus has an instance, and the check fails
  if a ``verdict(_)`` reappears anywhere -- because a verdict forecloses the
  reading the owner reports being surprised by.  Every diverged pair has its
  reading held open, and the token census is re-derived from the corpus.

  The unmodelled edges are counted, not hidden.  The discursive genre's
  provenance splits into edges a predicate here carries and edges only the
  literature carries; the second count is reported every run.
"""
from __future__ import annotations

import collections
import itertools
import py_compile
import re
import shutil
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATHS_PL = ROOT / "paths.pl"
BUILDER = ROOT / "scripts/research/build_action_grammar.py"
GRAMMAR = ROOT / "knowledge/strategies/action_grammar.pl"
MAP_PATH = ROOT / "knowledge/strategies/action_vocabulary_map.pl"
STRATEGY_TABLES = ROOT / "knowledge/strategies/transition_tables"
DISCOURSE = ROOT / "knowledge/discourse/commitment_automata.pl"

VERDICTS = ("stop", "watch", "continue")
STANCES = ("conserving", "deforming", "neutral")

TUPLE_RE = re.compile(
    r"(?m)^automaton_tuple\((\w+),\s*(\w+),\s*states\(\[([^\]]*)\]\),\s*"
    r"actions\(\[([^\]]*)\]\),\s*start\((\w+)\),\s*accepting\(\[([^\]]*)\]\)\)")
TRANS_RE = re.compile(
    r"(?m)^automaton_transition\((\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*(\w+),\s*"
    r"provenance\((.*?)\)\)\.")
MAPS_RE = re.compile(r"(?m)^action_maps\((\w+), (\w+), (\w+), (\w+),")
AXES_RE = re.compile(
    r"(?m)^action_register\((\w+), genre\((\w+)\), register\((\w+)\), stance\((\w+)\)\)")
CANON_RE = re.compile(r"(?m)^canonical_action\((\w+), gloss\(")
PHRASE_RE = re.compile(r"(?m)^action_phrase\((\w+), sequence\(\[([^\]]*)\]\)")
ARC_RE = re.compile(r"(?m)^normative_arc\((\w+), stances\(\[([^\]]*)\]\)")
GRAMMAR_RE = re.compile(
    r"(?m)^machine_grammar\((\w+), (\w+), (\w+), arc\((\w+)\),\s*"
    r"phrases\(\[([^\]]*)\]\),\s*stances\(\[([^\]]*)\]\)\)")
PAIR_RE = re.compile(
    r"(?m)^incompatible_pair\((\w+), (\w+), (\w+), deforms\((\w+)\),\s*"
    r"divergence\((\d+), (\w+), (\w+)\),\s*class\((\w+)\)\)")
ANSWER_RE = re.compile(
    r"(?m)^machine_answerability\((\w+), (\w+), (\w+),\s*\n?\s*"
    r"invariant\((\w+)\), source\('([^']+)'\)\)")
GAP_REASON_RE = re.compile(
    r'(?m)^machine_conservation_gap\(\w+, (\w+), (\w+),\s*\n?\s*reason\("(.*?)"\)\)\.',
    re.S)
GAP_RE = re.compile(
    r"(?m)^machine_conservation_gap\((\w+), (\w+), (\w+),\s*reason\(")
TRIGGER_RE = re.compile(r"(?m)^interruption_trigger\((\w+), condition\(")
INSTANCE_RE = re.compile(
    r"(?m)^trigger_instance\((\w+), (\w+), (\w+),\s*\n?\s*trigger\((\w+)\)")
HELD_RE = re.compile(
    r"(?m)^reading_held_open\((\w+), (\w+), (\w+), divergence\((\d+)\)")
CENSUS_RE = re.compile(
    r"(?m)^token_loss_rate\((\w+), (\w+), machines\((\d+)\), ending_deforming\((\d+)\)\)")


def items(text: str) -> list[str]:
    return [part.strip() for part in text.split(",") if part.strip()]


def read_alphabet() -> tuple[dict, set]:
    text = MAP_PATH.read_text(encoding="utf-8")
    axes = {name: (genre, register, stance)
            for name, genre, register, stance in AXES_RE.findall(text)}
    canonical = set(CANON_RE.findall(text))
    projection = {(f, s, l): c for f, s, l, c in MAPS_RE.findall(text)}
    return {"axes": axes, "projection": projection, "canonical": canonical}, canonical


def read_machines(projection: dict):
    """Return machines with their canonical words, plus the discursive edge census."""
    sources = [(p, "computational") for p in sorted(STRATEGY_TABLES.glob("*.pl"))]
    sources.append((DISCOURSE, "discursive"))
    declared, edges, genre, starts, accepting = {}, collections.defaultdict(set), {}, {}, {}
    provenance = collections.Counter()
    for path, kind in sources:
        text = path.read_text(encoding="utf-8")
        for family, signature, states, actions, start, accepts in (
                m.groups() for m in TUPLE_RE.finditer(text)):
            key = (family, signature)
            declared[key] = (items(states), items(actions))
            starts[key], accepting[key] = start, set(items(accepts))
            genre[key] = kind
        for family, signature, source, action, target, prov in (
                m.groups() for m in TRANS_RE.finditer(text)):
            key = (family, signature)
            edges[key].add((source, action, target))
            if kind == "discursive":
                provenance["grounded" if "grounded(" in prov else "unmodelled"] += 1
    words = {}
    for key in sorted(edges):
        routes = collections.defaultdict(list)
        for source, action, target in sorted(edges[key]):
            canonical = projection.get((key[0], key[1], action), action)
            if canonical not in [a for a, _ in routes[source]]:
                routes[source].append((canonical, target))
        sequence, state, seen = [], starts[key], {starts[key]}
        while True:
            outgoing = routes.get(state, [])
            if len(outgoing) != 1:
                break
            action, target = outgoing[0]
            sequence.append(action)
            if target in seen:
                break
            seen.add(target)
            state = target
        words[key] = tuple(sequence)
    return declared, edges, genre, starts, accepting, words, provenance


def check_discursive(declared, edges, starts, accepting, axes, canonical) -> list[str]:
    errors = []
    for key, rows in sorted(edges.items()):
        if key[0] != "discourse":
            continue
        states, actions = declared[key]
        where = f"{key[0]}/{key[1]}"
        if set(a for _, a, _ in rows) != set(actions):
            errors.append(f"{where}: declared actions and edge actions differ")
        touched = {s for s, _, _ in rows} | {t for _, _, t in rows}
        if touched != set(states):
            errors.append(f"{where}: declared states and edge states differ")
        destinations = collections.defaultdict(set)
        for source, action, target in rows:
            destinations[(source, action)].add(target)
        for pair, targets in destinations.items():
            if len(targets) > 1:
                errors.append(f"{where}: {pair} has two targets {sorted(targets)}")
        routes = collections.defaultdict(list)
        for source, action, target in rows:
            routes[source].append(target)
        reached, stack = {starts[key]}, [starts[key]]
        while stack:
            for target in routes.get(stack.pop(), []):
                if target not in reached:
                    reached.add(target)
                    stack.append(target)
        if set(states) - reached:
            errors.append(f"{where}: unreachable states {sorted(set(states) - reached)}")
        if not accepting[key] & reached:
            errors.append(f"{where}: no accepting state is reachable")
        for _, action, _ in rows:
            if action not in canonical:
                errors.append(f"{where}: {action} has no canonical_action/3 row")
            elif action in axes and axes[action][0] not in ("discursive", "computational"):
                errors.append(f"{where}: {action} carries genre {axes[action][0]}")
    return errors


def check_grammar(alphabet, genre, words, edges, starts) -> tuple[list[str], dict]:
    text = GRAMMAR.read_text(encoding="utf-8")
    axes = alphabet["axes"]
    phrases = {name: tuple(items(body)) for name, body in PHRASE_RE.findall(text)}
    arcs = {name: tuple(items(body)) for name, body in ARC_RE.findall(text)}
    rows = [(g, f, s, arc, items(ph), items(st))
            for g, f, s, arc, ph, st in GRAMMAR_RE.findall(text)]
    errors: list[str] = []

    seen = collections.Counter((f, s) for _, f, s, _, _, _ in rows)
    for key, count in seen.items():
        if count > 1:
            errors.append(f"{key[0]}/{key[1]}: {count} machine_grammar rows")
    for key in sorted(set(words) - set(seen)):
        errors.append(f"{key[0]}/{key[1]}: no machine_grammar row")
    for key in sorted(set(seen) - set(words)):
        errors.append(f"{key[0]}/{key[1]}: machine_grammar row for no machine")

    arc_use, phrase_use = collections.Counter(), collections.Counter()
    for g, family, signature, arc, phrase_list, stance_list in rows:
        key = (family, signature)
        where = f"{family}/{signature}"
        if key in genre and genre[key] != g:
            errors.append(f"{where}: row says genre {g}, tables say {genre[key]}")
        if arc not in arcs:
            errors.append(f"{where}: arc {arc} is not declared")
            continue
        arc_use[arc] += 1
        word = words.get(key, ())
        expected_stances = [axes[a][2] for a in word if a in axes]
        if len(expected_stances) != len(word):
            errors.append(f"{where}: an action has no action_register/4 row")
            continue
        if stance_list != expected_stances:
            errors.append(f"{where}: stances row does not match the machine's word")
        collapsed = [k for k, _ in itertools.groupby(stance_list)]
        if tuple(collapsed) != arcs[arc]:
            errors.append(f"{where}: arc {arc} is not this row's collapsed stance word")
        rebuilt: list[str] = []
        for part in phrase_list:
            if part in phrases:
                rebuilt.extend(phrases[part])
                phrase_use[part] += 1
            else:
                rebuilt.append(part)
        if tuple(rebuilt) != word:
            errors.append(f"{where}: the phrases row does not rebuild the machine's word")
        for stance in stance_list:
            if stance not in STANCES:
                errors.append(f"{where}: {stance} is not a stance")

    for name in sorted(set(arcs) - set(arc_use)):
        errors.append(f"arc {name} is declared but carried by no machine")
    for name in sorted(set(phrases) - set(phrase_use)):
        errors.append(f"phrase {name} is declared but carried by no machine")

    # the conservation-gap census: exactly the machines whose every step is
    # neutral, no more and no fewer
    declared_gaps = {(f, s) for _, f, s in GAP_RE.findall(text)}
    actual_gaps = {key for key, word in words.items()
                   if word and all(axes[a][2] == "neutral" for a in word if a in axes)}
    for key in sorted(actual_gaps - declared_gaps):
        errors.append(
            f"{key[0]}/{key[1]} has no conserving or deforming step and no "
            "machine_conservation_gap/4 row; the gap census has to be complete "
            "or it is not a work list")
    for key in sorted(declared_gaps - actual_gaps):
        errors.append(
            f"{key[0]}/{key[1]} carries a machine_conservation_gap/4 row and "
            "does have a conserving or deforming step")

    # The cross-source stance audit.
    #
    # The productive/deformation pairing was authored in
    # knowledge/strategies/math/*_action_pairs.pl and this alphabet's 121 stance
    # assignments were authored here. The two are independent, and the pairing
    # can test one thing about the stances: a productive strategy should carry no
    # deforming step and a deformation should carry one. Nobody has to review the
    # stance table by hand for that to be checked.
    stance_of_machine = {}
    for _, family, signature, _, _, stance_list in rows:
        stance_of_machine[(family, signature)] = stance_list
    pairs = PAIR_RE.findall(text)
    if not pairs:
        errors.append("no incompatible_pair/6 rows; the stance audit cannot run")
    for family, productive, deformation, _, step, left, right, klass in pairs:
        for signature, side in ((productive, "productive"), (deformation, "deformation")):
            if (family, signature) not in stance_of_machine:
                errors.append(f"{family}/{signature} is paired and has no grammar row")
        pstances = stance_of_machine.get((family, productive), [])
        dstances = stance_of_machine.get((family, deformation), [])
        if "deforming" in pstances:
            errors.append(
                f"{family}/{productive} is the PRODUCTIVE side of a pairing "
                f"authored in the action-pair sources and carries a deforming "
                f"step ({pstances}); either a stance assignment here is wrong or "
                "the pairing is")
        if dstances and "deforming" not in dstances:
            errors.append(
                f"{family}/{deformation} is the DEFORMATION side of a pairing "
                f"authored in the action-pair sources and carries no deforming "
                f"step ({dstances}); either a stance assignment here is wrong or "
                "the pairing is")
        if klass not in ("substantive_break", "substantive_keep",
                         "register_divergence", "same_register_neutral"):
            errors.append(f"{family}/{productive}: divergence class {klass} is unknown")
        word_left = words.get((family, productive), ())
        word_right = words.get((family, deformation), ())
        index = int(step) - 1
        if not (0 <= index < min(len(word_left), len(word_right))):
            errors.append(f"{family}/{productive}: divergence step {step} is out of range")
        elif (word_left[index], word_right[index]) != (left, right):
            errors.append(
                f"{family}/{productive}: divergence names {left}/{right} and the "
                f"words have {word_left[index]}/{word_right[index]} at step {step}")
        elif any(word_left[i] != word_right[i] for i in range(index)):
            errors.append(
                f"{family}/{productive}: the two words already differ before "
                f"step {step}, so that is not where they part")

    # every answerability row has to be in the action-pair sources, verbatim
    pair_text = "".join(
        path.read_text(encoding="utf-8")
        for path in sorted((ROOT / "knowledge/strategies/math").glob("*action_pairs*.pl")))
    for _, _, signature, invariant, source in ANSWER_RE.findall(text):
        if f"invariant({invariant})" not in pair_text:
            errors.append(
                f"machine_answerability names invariant({invariant}) for "
                f"{signature}, which no action-pair source declares")

    # the gap reasons have to classify correctly against the sources
    declared_invariants = {
        signature for _, _, signature, _, _ in ANSWER_RE.findall(text)}
    for family, signature, reason in GAP_REASON_RE.findall(text):
        has_invariant = signature in declared_invariants
        if has_invariant and "EXTRACTION gap" not in reason:
            errors.append(
                f"{family}/{signature} declares an invariant and its gap reason "
                "does not call it an extraction gap")
        if not has_invariant and "AUTHORING gap" not in reason:
            errors.append(
                f"{family}/{signature} declares no invariant and its gap reason "
                "does not call it an authoring gap")

    ends_deforming = {
        key: bool(word) and axes[word[-1]][2] == "deforming"
        for key, word in words.items() if all(a in axes for a in word)
    }
    holders = collections.defaultdict(list)
    for key, word in words.items():
        for action in set(word):
            holders[action].append(key)

    # The interruption model carries no verdicts, and the check enforces that.
    # A verdict about which reading is running would foreclose the one the owner
    # says he is sometimes surprised by, so its absence is a property to hold.
    triggers = {name for name in TRIGGER_RE.findall(text)}
    if "verdict(" in text:
        errors.append(
            "the grammar still emits a verdict(_); the interruption model was "
            "replaced by interruption_trigger/4 precisely because a verdict "
            "forecloses a reading that the owner reports sometimes lands well")
    if triggers != {"contradiction_loop", "unmoored_utterance"}:
        errors.append(
            f"interruption_trigger names {sorted(triggers)}; the two conditions "
            "the owner stated are contradiction_loop and unmoored_utterance")

    instances = INSTANCE_RE.findall(text)
    for _, family, signature, trigger in instances:
        if trigger not in triggers:
            errors.append(f"{family}/{signature}: trigger {trigger} is not declared")
        if trigger != "contradiction_loop":
            continue
        key = (family, signature)
        adjacency = collections.defaultdict(set)
        for source, _, target in edges.get(key, ()):
            adjacency[source].add(target)
        stack, cyclic = [(starts[key], (starts[key],))], False
        while stack and not cyclic:
            state, path = stack.pop()
            for target in sorted(adjacency.get(state, ())):
                if target in path:
                    cyclic = True
                    break
                stack.append((target, path + (target,)))
        if not cyclic:
            errors.append(
                f"{family}/{signature} carries a contradiction_loop instance and "
                "has no cycle reachable from its start")
    looping = {
        (f, s) for f, s in
        [(m[1], m[2]) for m in instances if m[3] == "contradiction_loop"]}
    for key in sorted(words):
        adjacency = collections.defaultdict(set)
        for source, _, target in edges.get(key, ()):
            adjacency[source].add(target)
        stack, cyclic = [(starts[key], (starts[key],))], False
        while stack and not cyclic:
            state, path = stack.pop()
            for target in sorted(adjacency.get(state, ())):
                if target in path:
                    cyclic = True
                    break
                stack.append((target, path + (target,)))
        if cyclic and key not in looping:
            errors.append(
                f"{key[0]}/{key[1]} has a cycle reachable from its start and no "
                "contradiction_loop instance")

    # every incompatible pair has to have its reading held open, and vice versa
    held = {(f, p, d): int(step) for f, p, d, step in HELD_RE.findall(text)}
    paired_keys = {(f, p, d): int(step) for f, p, d, _, step, _, _, _ in pairs}
    for key in sorted(set(paired_keys) - set(held)):
        errors.append(
            f"{key[0]}/{key[1]} against {key[2]} is an incompatible pair with no "
            "reading_held_open row; holding both readings open is the default and "
            "has no exceptions")
    for key in sorted(set(held) - set(paired_keys)):
        errors.append(f"reading_held_open names {key}, which is not a pair")
    for key, step in sorted(held.items()):
        if paired_keys.get(key) != step:
            errors.append(
                f"{key[0]}/{key[1]}: reading_held_open says step {step} and the "
                f"pair says {paired_keys.get(key)}")

    # the census has to match the corpus it summarizes
    for genre, action, total, losing in CENSUS_RE.findall(text):
        carriers = holders.get(action, [])
        if len(carriers) != int(total):
            errors.append(
                f"token_loss_rate({action}) says {total} machines and the corpus "
                f"has {len(carriers)}")
        actual = sum(1 for c in carriers if ends_deforming.get(c))
        if actual != int(losing):
            errors.append(
                f"token_loss_rate({action}) says {losing} end deforming and the "
                f"corpus has {actual}")
        if len(carriers) < 4:
            errors.append(
                f"token_loss_rate({action}) reports on {len(carriers)} machines, "
                "below the floor the builder sets")

    summary = {
        "gaps": len(declared_gaps),
        "pairs": len(pairs),
        "answerability": len(ANSWER_RE.findall(text)),
        "divergence_classes": dict(sorted(
            collections.Counter(k for *_, k in pairs).items())),
        "phrases": len(phrases),
        "arcs": len(arcs),
        "rows": len(rows),
        "triggers": len(triggers),
        "instances": len(instances),
        "held": len(held),
        "census": len(CENSUS_RE.findall(text)),
        "arc_use": arc_use,
        "phrase_use": phrase_use,
        "words": words,
        "axes": axes,
        "genre": genre,
    }
    return errors, summary


def run_strict_load(alias: str) -> None:
    goal = f"user:use_module(strategies({alias}), []), halt."
    result = subprocess.run(
        ["swipl", "-q", "--on-warning=status", "--on-error=status",
         "-l", str(PATHS_PL), "-g", goal],
        cwd=ROOT, capture_output=True, text=True, timeout=180)
    if result.returncode != 0:
        raise RuntimeError(f"strict SWI load of strategies({alias}) failed "
                           f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}")


def run_consult(path: Path) -> None:
    result = subprocess.run(
        ["swipl", "-q", "--on-warning=status", "--on-error=status",
         "-g", f"consult('{path.relative_to(ROOT)}'), halt."],
        cwd=ROOT, capture_output=True, text=True, timeout=180)
    if result.returncode != 0:
        raise RuntimeError(f"strict SWI consult of {path.name} failed "
                           f"(exit {result.returncode}):\n{result.stdout}\n{result.stderr}")


def check_regeneration(workdir: Path) -> list[str]:
    target = workdir / "action_grammar.pl"
    result = subprocess.run(
        [sys.executable, str(BUILDER), "--output", str(target)],
        cwd=ROOT, capture_output=True, text=True, timeout=600)
    if result.returncode != 0:
        return [f"builder failed (exit {result.returncode}): {result.stderr.strip()}"]
    if target.read_bytes() != GRAMMAR.read_bytes():
        return ["the builder rerun is not byte-identical to the committed "
                f"{GRAMMAR.relative_to(ROOT)}; run "
                f"python3 {BUILDER.relative_to(ROOT)}"]
    second = workdir / "action_grammar_second.pl"
    subprocess.run([sys.executable, str(BUILDER), "--output", str(second)],
                   cwd=ROOT, capture_output=True, text=True, timeout=600)
    if second.read_bytes() != target.read_bytes():
        return ["two builder runs disagree"]
    return []


def main() -> int:
    for path in (BUILDER, GRAMMAR, MAP_PATH, DISCOURSE):
        if not path.exists():
            print(f"FAIL: {path} does not exist", file=sys.stderr)
            return 1
    errors: list[str] = []
    try:
        alphabet, canonical = read_alphabet()
        declared, edges, genre, starts, accepting, words, provenance = read_machines(
            alphabet["projection"])
    except (ValueError, OSError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1

    errors += check_discursive(declared, edges, starts, accepting, alphabet["axes"], canonical)
    grammar_errors, summary = check_grammar(alphabet, genre, words, edges, starts)
    errors += grammar_errors

    for path in (BUILDER, Path(__file__)):
        try:
            py_compile.compile(str(path), doraise=True)
        except py_compile.PyCompileError as exc:
            errors.append(f"{path.name} does not compile: {exc}")

    workdir = Path(tempfile.mkdtemp(prefix="action-grammar-"))
    try:
        run_consult(DISCOURSE)
        run_strict_load("action_grammar")
        run_strict_load("action_vocabulary_map")
        errors += check_regeneration(workdir)
    except (RuntimeError, OSError) as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        shutil.rmtree(workdir, ignore_errors=True)
        return 1
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    if errors:
        print(f"FAIL: {len(errors)} problem(s):", file=sys.stderr)
        for error in errors:
            print(f"  - {error}", file=sys.stderr)
        return 1

    axes = summary["axes"]
    computational = [k for k, g in genre.items() if g == "computational"]
    discursive = [k for k, g in genre.items() if g == "discursive"]
    cross = collections.defaultdict(set)
    for g, family, signature, arc, _, _ in GRAMMAR_RE.findall(
            GRAMMAR.read_text(encoding="utf-8")):
        cross[arc].add(g)
    cross_arcs = sorted(a for a, gs in cross.items() if len(gs) > 1)

    print("PASS strict SWI load of the discursive genre and both new modules")
    print(f"PASS regeneration: {BUILDER.name} rerun is byte-identical, twice")
    print(f"PASS coverage: {summary['rows']} machine_grammar rows for "
          f"{len(words)} machines ({len(computational)} computational, "
          f"{len(discursive)} discursive); no arc or phrase unused")
    print("PASS the discursive genre is deterministic, reachable, and terminating")
    print("PASS every stances row is its machine's word through action_register/4, "
          "and every arc is that row collapsed")
    print("PASS every phrases row rebuilds its machine's action word exactly")
    print(f"PASS the conservation-gap census is exactly the machines with no "
          f"conserving or deforming step ({summary['gaps']}), each reason "
          "classified against the action-pair sources")
    print(f"PASS cross-source stance audit: over {summary['pairs']} pairings "
          "authored in the action-pair sources, no productive strategy carries a "
          "deforming step and every deformation carries one")
    print(f"PASS answerability: {summary['answerability']} invariant rows, each "
          "declared in an action-pair source; every divergence step recomputed "
          "from the two words")
    print(f"PASS interruption model: {summary['triggers']} authored triggers, "
          f"{summary['instances']} instance(s) in this corpus, no verdicts anywhere")
    print(f"PASS both readings of every one of {summary['held']} diverged pairs "
          "are held open, and each census row matches the corpus")
    print()
    print("Compression up the layers:")
    print(f"  machines, both genres            : {len(words)}")
    print(f"  distinct canonical action words  : {len(set(words.values()))}")
    print(f"  distinct stance words            : "
          f"{len({tuple(axes[a][2] for a in w) for w in words.values()})}")
    print(f"  normative arcs                   : {summary['arcs']}")
    print(f"  arcs spelled by both genres      : {len(cross_arcs)}  {cross_arcs}")
    print()
    print("Phrase layer (the within-genre idioms):")
    print(f"  phrases named                    : {summary['phrases']}")
    print(f"  phrase instances across machines : {sum(summary['phrase_use'].values())}")
    print("  most carried:")
    for name, count in summary["phrase_use"].most_common(6):
        print(f"      {count:3d}  {name}")
    print()
    print("Answerability and incompatibility, read from the action-pair sources:")
    print(f"  invariant rows                   : {summary['answerability']}")
    print(f"  incompatible pairs               : {summary['pairs']}")
    print(f"  divergence classes               : {summary['divergence_classes']}")
    print()
    print("Discursive genre provenance:")
    print(f"  edges a predicate here carries   : {provenance['grounded']}")
    print(f"  edges only the literature carries: {provenance['unmodelled']}")
    print()
    print("Normative arcs by machine count:")
    for arc, count in summary["arc_use"].most_common():
        tag = " both genres" if arc in cross_arcs else ""
        print(f"  {count:4d}  {arc}{tag}")
    print()
    print("PASS action_grammar check")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
