#!/usr/bin/env python3
"""Keep the action-mapping reader's two guide genres explicit and fail-closed."""
from __future__ import annotations

import pathlib
import sys
import tempfile


ROOT = pathlib.Path(__file__).resolve().parents[2]
CURRICULUM = ROOT / "scripts" / "curriculum"
sys.path.insert(0, str(CURRICULUM))

import compile_action_mappings as compiler  # noqa: E402


HAND_GUIDE = """# Hand-templated fixture
## Learning Goals (teacher-facing)
- Add within 10.
## Lesson Purpose
Students add two quantities.
Student Task Statement
2 + 3
Student Response
5
"""

DOCLING_GUIDE = """Unit 1, Lesson 1

## Docling fixture

## Goals

- Add two quantities.

## Learning Targets

- I can add.

## Lesson Narrative

Students add quantities represented in a task.
Students compare quantities before choosing an operation.

## Activity Narrative

The task asks students to add.

## Student Task Statement

![Image](document_artifacts/image.png)

This sentence was generated by a vision model and is not curriculum text.

- Find the value of 2 + 3.

5 min
3
Grade 6 Unit 1
Unit 1
Lesson 1
Math, CC BY Open Up Resources.
- Instructional Routines
- Notice and Wonder

## Student Response

5
"""

PICTURE_DESCRIPTIONS = """![Picture 1](document_artifacts/image.png)

This sentence was generated by a vision model and is not curriculum text.

Provenance: `granite-vision-fixture`
"""

UNKNOWN_HEADINGS_GUIDE = """Unit 1, Lesson 2

## Unknown fixture

## Learning Outcomes

- Add two quantities.

## Overview

Students add quantities.
"""


def write(path: pathlib.Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")


def main() -> int:
    with tempfile.TemporaryDirectory(prefix=".task210-", dir=ROOT) as directory:
        fixture_root = pathlib.Path(directory)
        hand_path = (
            fixture_root
            / compiler.GUIDE_ROOT.relative_to(ROOT)
            / "grade5/unit1/lesson1.md"
        )
        docling_dir = (
            fixture_root
            / compiler.MIDDLE_GUIDE_ROOT.relative_to(ROOT)
            / "Grade6/Grade6-1-1-Lesson-teacher-guide-"
        )
        write(hand_path, HAND_GUIDE)
        write(docling_dir / "document.md", DOCLING_GUIDE)
        write(docling_dir / "picture_descriptions.md", PICTURE_DESCRIPTIONS)

        docs = compiler.read_teacher_guides(fixture_root)
        corpora = {doc.code: doc.source_corpus for doc in docs}
        expected = {
            "IM-G5-U1-L1": compiler.HAND_TEMPLATED_GUIDE_CORPUS,
            "IM-G6-U1-L1": compiler.DOCLING_GUIDE_CORPUS,
        }
        if corpora != expected:
            raise SystemExit(f"guide provenance was not retained: {corpora!r}")

        spans = compiler.extract_student_task_spans(docs)
        span_corpora = {span.code: span.source_corpus for span in spans}
        if span_corpora != expected:
            raise SystemExit(f"span provenance was not retained: {span_corpora!r}")
        docling = next(span for span in spans if span.code == "IM-G6-U1-L1")
        if "Find the value of 2 + 3." not in docling.text:
            raise SystemExit("Docling curriculum task text was not segmented")
        if docling.lines != ((28, "Find the value of 2 + 3."),):
            raise SystemExit(f"Docling furniture entered the task span: {docling.lines!r}")
        if "generated by a vision model" in docling.text:
            raise SystemExit("model-authored picture description entered a task span")
        doc = next(doc for doc in docs if doc.code == "IM-G6-U1-L1")
        if "generated by a vision model" in doc.concise_text:
            raise SystemExit("model-authored picture description entered lesson context")
        line, excerpt = compiler._first_match(doc, [r"compare quantities"])
        source_line = doc.path.read_text(encoding="utf-8").splitlines()[line - 1]
        if excerpt not in source_line:
            raise SystemExit("joined narrative match did not retain its physical line")
        if compiler._first_match(doc, [r"task\. Students"]) is not None:
            raise SystemExit("cross-line narrative match was not withheld")
        mapping = compiler.Mapping(
            doc.code,
            "addition",
            "known_fact_retrieval",
            "whole_number",
            "fixture_line_citation",
            str(doc.path.relative_to(ROOT)),
            line,
            excerpt,
        )
        if compiler.validate_mapping_citations(ROOT, [mapping]) != 1:
            raise SystemExit("line citation validator did not check the fixture mapping")
        bad_mapping = compiler.Mapping(
            doc.code,
            "addition",
            "known_fact_retrieval",
            "whole_number",
            "fixture_bad_line_citation",
            str(doc.path.relative_to(ROOT)),
            1,
            excerpt,
        )
        try:
            compiler.validate_mapping_citations(ROOT, [bad_mapping])
        except SystemExit as error:
            if str(doc.path.relative_to(ROOT)) not in str(error):
                raise
        else:
            raise SystemExit("wrong-line mapping citation was accepted")
        out_of_range_mapping = compiler.Mapping(
            doc.code,
            "addition",
            "known_fact_retrieval",
            "whole_number",
            "fixture_out_of_range_citation",
            str(doc.path.relative_to(ROOT)),
            999,
            excerpt,
        )
        try:
            compiler.validate_mapping_citations(ROOT, [out_of_range_mapping])
        except SystemExit as error:
            if str(doc.path.relative_to(ROOT)) not in str(error):
                raise
        else:
            raise SystemExit("out-of-range mapping citation was accepted")

        unknown_dir = (
            fixture_root
            / compiler.MIDDLE_GUIDE_ROOT.relative_to(ROOT)
            / "Grade6/Grade6-1-2-Lesson-teacher-guide-"
        )
        write(unknown_dir / "document.md", UNKNOWN_HEADINGS_GUIDE)
        write(unknown_dir / "picture_descriptions.md", "")
        try:
            compiler.read_teacher_guides(fixture_root)
        except SystemExit as error:
            if "unrecognized or incomplete headings" not in str(error):
                raise
        else:
            raise SystemExit("unrecognized Docling headings returned an empty success")

    print(
        "action mapping Docling reader passed: corpus provenance retained; "
        "caption and furniture excluded; line citations checked; "
        "unknown headings refused"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
