#!/usr/bin/env python3
"""Regression check for the corpus-sourced recognition phrases.

``knowledge/strategies/attested_phrases.pl`` is generated by
``scripts/research/build_attested_phrases.py`` from
``data/research/research_shared.db``.  Every row is a phrase the literature uses
for a strategy, cited to a bibtex key, attached to one action of that strategy by
named shared content words.

What this check holds:

  Regeneration.  The builder rerun is byte-identical to the committed file, twice.
  A hand edit cannot pass, and neither can a corpus change that nobody rebuilt for.

  Every citation is real.  Each ``source`` key appears in the corpus database, so
  a row cannot cite a paper the corpus does not have.

  Every attachment shows its work.  Each row's ``shared`` words are recomputed
  from the phrase and the action's own label, and the row fails if they are not
  actually shared.  The citation warrants the signature; the shared words are the
  whole of what warrants the step.

  Register is never claimed to be student voice.  Every phrase row is
  ``register(analyst)``.  The corpus supplies what researchers call a step, and
  the check fails if a row claims otherwise, because the student-voice material is
  the quoted utterances and those are deliberately not surfaces.

  The widening is counted.  ``action_spans/3`` knows the action and not the
  signature, so a phrase cited for one signature reaches the same-named action
  wherever it occurs.  This check reports how many rows that touches instead of
  leaving it implied.

  Nothing regressed.  Unrelated text still abstains, a generated description still
  round-trips, and the analyst wording that returned nothing before now returns
  something.
"""
from __future__ import annotations

import collections
import re
import sqlite3
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATHS_PL = ROOT / "paths.pl"
BUILDER = ROOT / "scripts/research/build_attested_phrases.py"
ATTESTED = ROOT / "knowledge/strategies/attested_phrases.pl"
DB = ROOT / "data/research/research_shared.db"
TABLES = ROOT / "knowledge/strategies/transition_tables"
RECOGNIZER = ROOT / "hermes/strategy_recognizer.pl"

PHRASE_RE = re.compile(
    r"(?m)^attested_phrase\((\w+), (\w+), (\w+),\s*\n\s*\[([^\]]*)\],\s*\n"
    r"\s*source\('((?:[^'\\]|\\.)*)'\),\s*\n"
    r"\s*attachment\(register\((\w+)\), shared\(\[([^\]]*)\]\)\)\)\.")
UTTERANCE_RE = re.compile(
    r"(?m)^attested_utterance\((\w+), (\w+),\s*\n\s*\"((?:[^\"\\]|\\.)*)\",\s*\n"
    r"\s*source\('((?:[^'\\]|\\.)*)'\)\)\.")
TRANS_RE = re.compile(
    r"(?m)^automaton_transition\((\w+), (\w+), (\w+), (\w+), (\w+),")

STOPWORDS = frozenset(
    "the a an of to in as by and or for with on at from into is it that this "
    "their its one two be was were all".split())


def content_words(text: str) -> set[str]:
    return {w for w in re.findall(r"[a-z]+", text.lower())
            if w not in STOPWORDS and len(w) > 2}


def prolog(goal: str, timeout: int = 240) -> subprocess.CompletedProcess:
    return subprocess.run(
        ["swipl", "-q", "--on-warning=status", "--on-error=status",
         "-l", str(PATHS_PL), "-g", goal],
        cwd=ROOT, capture_output=True, text=True, timeout=timeout)


def candidate_count(text: str) -> int:
    goal = ("use_module(hermes(strategy_recognizer), [recognize_strategies/2]), "
            f'recognize_strategies("{text}", Cs), length(Cs, N), '
            "format('~w~n', [N]), halt.")
    out = prolog(goal)
    if out.returncode != 0:
        raise RuntimeError(f"recognize failed for {text!r}:\n{out.stderr}")
    return int(out.stdout.strip().splitlines()[-1])


def main() -> int:
    for path in (BUILDER, ATTESTED, DB, RECOGNIZER):
        if not path.exists():
            print(f"FAIL: {path} does not exist", file=sys.stderr)
            return 1

    errors: list[str] = []
    text = ATTESTED.read_text(encoding="utf-8")
    phrases = PHRASE_RE.findall(text)
    utterances = UTTERANCE_RE.findall(text)
    if not phrases:
        print("FAIL: no attested_phrase/6 rows parsed", file=sys.stderr)
        return 1

    actions: dict[tuple[str, str], set[str]] = collections.defaultdict(set)
    for path in sorted(TABLES.glob("*.pl")):
        for family, signature, _, action, _ in TRANS_RE.findall(
                path.read_text(encoding="utf-8")):
            actions[(family, signature)].add(action)

    connection = sqlite3.connect(f"file:{DB}?mode=ro", uri=True)
    try:
        corpus_keys = {row[0] for row in connection.execute(
            "select distinct bibtex_key from articles where bibtex_key is not null")}
    finally:
        connection.close()

    shared_action_labels = collections.Counter()
    for key, labels in actions.items():
        for label in labels:
            shared_action_labels[label] += 1

    widened = 0
    for family, signature, action, body, citation, register, shared in phrases:
        where = f"{family}/{signature}/{action}"
        if register != "analyst":
            errors.append(
                f"{where}: register is {register}; the corpus supplies what "
                "researchers call a step, and claiming student voice for it would "
                "put a citation behind something it does not warrant")
        if (family, signature) not in actions:
            errors.append(f"{where}: no such machine in the transition tables")
            continue
        if action not in actions[(family, signature)]:
            errors.append(f"{where}: that machine has no such action")
            continue
        unescaped = citation.replace("\\'", "'")
        if unescaped not in corpus_keys:
            errors.append(
                f"{where}: cites '{unescaped}', which is not a bibtex_key in the "
                "corpus")
        phrase_words = content_words(" ".join(
            w.strip().strip("'") for w in body.split(",")))
        label_words = content_words(action.replace("_", " "))
        claimed = {w.strip() for w in shared.split(",") if w.strip()}
        if not claimed:
            errors.append(f"{where}: attachment claims no shared words")
        recomputed = phrase_words & label_words
        if not claimed <= recomputed:
            errors.append(
                f"{where}: attachment claims {sorted(claimed)} shared, and the "
                f"phrase and label actually share {sorted(recomputed)}")
        if shared_action_labels[action] > 1:
            widened += 1

    for family, signature, quote, citation in utterances:
        if (family, signature) not in actions:
            errors.append(
                f"attested_utterance for {family}/{signature}, which has no machine")
        if "'" not in quote and '"' not in quote and "\\\"" not in quote:
            errors.append(
                f"{family}/{signature}: an utterance row with no quotation in it")

    if "attested_phrase" not in RECOGNIZER.read_text(encoding="utf-8"):
        errors.append(
            "hermes/strategy_recognizer.pl does not consult attested_phrase/6, so "
            "the cited phrases are unconsumed")

    # regeneration
    import shutil, tempfile
    workdir = Path(tempfile.mkdtemp(prefix="attested-phrases-"))
    try:
        first = workdir / "one.pl"
        second = workdir / "two.pl"
        for target in (first, second):
            out = subprocess.run(
                [sys.executable, str(BUILDER), "--output", str(target)],
                cwd=ROOT, capture_output=True, text=True, timeout=600)
            if out.returncode != 0:
                errors.append(f"builder failed: {out.stderr.strip()[:300]}")
                break
        else:
            if first.read_bytes() != ATTESTED.read_bytes():
                errors.append(
                    "the builder rerun is not byte-identical to the committed "
                    f"{ATTESTED.relative_to(ROOT)}; run "
                    f"python3 {BUILDER.relative_to(ROOT)}")
            if first.read_bytes() != second.read_bytes():
                errors.append("two builder runs disagree")
    finally:
        shutil.rmtree(workdir, ignore_errors=True)

    try:
        noise = candidate_count("purple bicycle tuesday")
        analyst = candidate_count("jump through ten and decompose the other addend")
    except RuntimeError as exc:
        print(f"FAIL: {exc}", file=sys.stderr)
        return 1
    if noise != 0:
        errors.append(f"unrelated text no longer abstains ({noise} candidates)")
    if analyst == 0:
        errors.append(
            "literature wording still returns nothing; the cited surfaces are not "
            "reaching the recognizer")

    if errors:
        print(f"FAIL: {len(errors)} problem(s):", file=sys.stderr)
        for error in errors[:20]:
            print(f"  - {error}", file=sys.stderr)
        if len(errors) > 20:
            print(f"  ... and {len(errors) - 20} more", file=sys.stderr)
        return 1

    keys = {c.replace("\\'", "'") for *_, c, _, _ in
            [(f, s, a, b, c, r, sh) for f, s, a, b, c, r, sh in phrases]}
    print(f"PASS regeneration: {BUILDER.name} rerun is byte-identical, twice")
    print(f"PASS every one of the {len(phrases)} rows cites a bibtex_key the "
          "corpus holds")
    print("PASS every attachment's shared words are recomputed from the phrase "
          "and the action's own label")
    print("PASS every row is register(analyst); no citation is made to carry a "
          "claim about student voice")
    print("PASS literature wording now recognizes, and unrelated text still abstains")
    print()
    print("Sourced from data/research/research_shared.db:")
    print(f"  cited phrase rows                : {len(phrases)}")
    print(f"  distinct phrase attachments      : "
          f"{len({(f, s, a, b) for f, s, a, b, _, _, _ in phrases})}")
    print(f"  signatures reached               : "
          f"{len({(f, s) for f, s, *_ in phrases})} of {len(actions)}")
    print(f"  actions reached                  : "
          f"{len({(f, s, a) for f, s, a, *_ in phrases})}")
    print(f"  distinct papers cited            : {len(keys)}")
    print(f"  quoted student utterances kept   : {len(utterances)}")
    print(f"  rows whose action name recurs elsewhere (the stated widening) : {widened}")
    print()
    print("PASS attested_phrases check")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
