#!/usr/bin/env python3
"""Build the deterministic lesson-topic fact cache."""

from __future__ import annotations

import argparse
import json
import os
import subprocess
import tempfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
COVERAGE_PATH = ROOT / "curriculum/im/coverage/im_coverage.json"
EXPECTED_LESSONS = 1317
HEADER = (
    "% Generated by scripts/research/build_lesson_topics_cache.py; "
    "do not hand-edit.\n"
)
PROLOG_GOAL = """
use_module(library(http/json)),
use_module(im_lessons(lesson_monitoring)),
json_read_dict(user_input, Request),
get_dict(lessons, Request, LessonStrings),
maplist(atom_string, LessonCodes, LessonStrings),
forall(
    member(Code, LessonCodes),
    (
        lesson_monitoring:compute_lesson_topics(Code, Topics),
        format('lesson_topics_cached(~q, ~q).~n', [Code, Topics])
    )
),
halt
""".replace("\n", " ")


def fail(message: str) -> "NoReturn":
    raise SystemExit(f"build_lesson_topics_cache.py: {message}")


def lesson_codes() -> list[str]:
    try:
        coverage = json.loads(COVERAGE_PATH.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError) as exc:
        fail(f"cannot read {COVERAGE_PATH}: {exc}")
    published = [row.get("lesson") for row in coverage.get("published_lessons", [])]
    extras = coverage.get("encoded_but_unpublished", [])
    codes = published + extras
    if not all(isinstance(code, str) and code for code in codes):
        fail("coverage contains a missing or non-string lesson code")
    if len(codes) != len(set(codes)):
        fail("coverage contains duplicate lesson codes")
    if len(codes) != EXPECTED_LESSONS:
        fail(f"expected {EXPECTED_LESSONS} lesson codes, found {len(codes)}")
    return sorted(codes)


def build_facts(codes: list[str]) -> str:
    command = [
        "swipl",
        "-q",
        "--on-warning=status",
        "--on-error=status",
        "-l",
        "paths.pl",
        "-g",
        PROLOG_GOAL,
    ]
    try:
        completed = subprocess.run(
            command,
            cwd=ROOT,
            input=json.dumps({"lessons": codes}),
            text=True,
            capture_output=True,
            check=False,
        )
    except FileNotFoundError:
        fail("swipl is required to build the lesson-topic cache")
    if completed.returncode != 0:
        detail = completed.stderr.strip() or f"swipl exited {completed.returncode}"
        fail(detail)
    facts = completed.stdout
    if facts.count("\n") != len(codes):
        fail(f"expected {len(codes)} generated facts")
    return HEADER + facts


def write_atomic(output: Path, content: str) -> None:
    output.parent.mkdir(parents=True, exist_ok=True)
    descriptor, temporary_name = tempfile.mkstemp(
        dir=output.parent,
        prefix=f".{output.name}.",
        text=True,
    )
    temporary = Path(temporary_name)
    try:
        with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as stream:
            stream.write(content)
        temporary.replace(output)
    except BaseException:
        temporary.unlink(missing_ok=True)
        raise


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()
    output = args.output if args.output.is_absolute() else ROOT / args.output
    codes = lesson_codes()
    write_atomic(output, build_facts(codes))
    print(f"wrote {len(codes)} lesson-topic facts to {output}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
