#!/usr/bin/env python3
"""Resolve the retired proposal queues by deterministic quality bands.

Corpus signature anchors enter the attributed store only when the signature's
best mechanically clear candidate is in the strong sampled band and no
candidate in that signature carries a displacement, score-tie, or fan-surplus
defect. Grade 7-8 lesson proposals have no deterministic quality band, so every
lesson record remains queryable as mechanically held.
"""
from __future__ import annotations

import argparse
import hashlib
import json
from collections import Counter, defaultdict
from pathlib import Path
from typing import Any

ROOT = Path(__file__).resolve().parents[2]
CORPUS = ROOT / "data/research/corpus_binding_proposals.json"
DIAGNOSTICS = ROOT / "data/research/corpus_binding_diagnostics.json"
UNITS = ROOT / "data/research/grade78_pairing_proposals.jsonl"
OUTPUT = ROOT / "knowledge/index/admitted_review_proposals.pl"
GENERATED = "date(2026,8,20)"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def atom(value: Any) -> str:
    text = str(value)
    if text and (text[0].islower() and all(c.islower() or c.isdigit() or c == "_" for c in text)):
        return text
    return "'" + text.replace("\\", "\\\\").replace("'", "\\'") + "'"


def string(value: Any) -> str:
    return '"' + str(value).replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n") + '"'


def atoms(values: list[Any]) -> str:
    return "[" + ", ".join(atom(value) for value in values) + "]"


def diagnostic_identity(row: dict[str, Any]) -> str:
    return (
        f"corpus_candidate:{row['row_type']}:{row['row_id']}:"
        f"{row['family']}/{row['signature']}"
    )


def group_band(rows: list[tuple[dict[str, Any], dict[str, Any]]]) -> tuple[str, str]:
    clear = [row for row, diag in rows if diag["reviewable"]]
    defects = {
        defect["kind"]
        for _row, diag in rows
        for defect in diag.get("defects", [])
    }
    if not clear:
        return "held_no_clear", "no_mechanically_clear_candidate"
    if "displacement" in defects:
        return "held_rank_0", "rank_0_displacement"
    if defects & {"score_tie", "fan_surplus"}:
        return "held_rank_1", "rank_1_score_tie_or_fan_surplus"
    best = max(float(row["score"]) for row in clear)
    if best <= 3.5:
        return "held_rank_2", "rank_2_low_sampled_band"
    if best < 4.5:
        return "held_rank_3", "rank_3_between_sampled_bands"
    return "admitted_rank_4", "rank_4_strong_sampled_band"


def corpus_anchor(row: dict[str, Any], band: str) -> str:
    return (
        "anchor(source_file('data/research/corpus_binding_proposals.json'), "
        f"source_sha256('{sha256(CORPUS)}'), "
        "diagnostic_file('data/research/corpus_binding_diagnostics.json'), "
        f"diagnostic_sha256('{sha256(DIAGNOSTICS)}'), score({row['score']}), "
        f"score_band({band}), citation({atom(row['bibtex_key'])}), "
        f"excerpt({string(row['excerpt'])}))"
    )


def corpus_testimony() -> str:
    return (
        "testimony(scoring('scripts/research/map_corpus_to_automata.py'), "
        "triage('scripts/research/build_review_diagnostics.py'), "
        f"{GENERATED})"
    )


def render() -> tuple[str, dict[str, Any]]:
    proposals = json.loads(CORPUS.read_text(encoding="utf-8"))["proposals"]
    diagnostics = json.loads(DIAGNOSTICS.read_text(encoding="utf-8"))["diagnostics"]
    diagnostic_by_id = {row["identity"]: row for row in diagnostics}
    if len(diagnostic_by_id) != len(diagnostics):
        raise ValueError("duplicate diagnostic identity")

    grouped: dict[tuple[str, str], list[tuple[dict[str, Any], dict[str, Any]]]] = defaultdict(list)
    for row in proposals:
        identity = diagnostic_identity(row)
        if identity not in diagnostic_by_id:
            raise ValueError(f"missing diagnostic for {identity}")
        grouped[(row["family"], row["signature"])].append(
            (row, diagnostic_by_id[identity])
        )

    lines = [
        "/** <module> Mechanically resolved review proposals",
        " *",
        " * Generated by scripts/research/promote_review_proposals.py. Do not edit",
        " * by hand. Strong, defect-free sampled corpus bands are admitted as",
        " * attributed signature anchors. Lower or defective corpus bands remain",
        " * queryable as held rows. The grade 7-8 proposal source records no",
        " * deterministic quality band, so all of its rows are held.",
        " */",
        ":- module(admitted_review_proposals,",
        "          [ admitted_signature_anchor/9,",
        "            held_signature_anchor/9,",
        "            held_unit_recognition_proposal/6,",
        "            review_proposal_admission_summary/1,",
        "            check_admitted_review_proposals/0",
        "          ]).",
        ":- discontiguous admitted_signature_anchor/9, held_signature_anchor/9.",
        "",
    ]

    bands: Counter[str] = Counter()
    admitted = held = 0
    for key in sorted(grouped):
        group = grouped[key]
        disposition, reason = group_band(group)
        bands[reason] += len(group)
        for row, diag in sorted(group, key=lambda item: (item[0]["row_type"], item[0]["row_id"])):
            defects = sorted({d["kind"] for d in diag.get("defects", [])})
            fields = (
                f"{atom(row['family'])}, {atom(row['signature'])}, "
                f"{atom(row['row_type'])}, {row['row_id']}, {atom(row['role'])}, "
                f"evidence({atoms(row['evidence'])}), {corpus_anchor(row, reason)}, "
                f"{corpus_testimony()}"
            )
            if disposition == "admitted_rank_4" and diag["reviewable"]:
                admitted += 1
                lines.append(
                    "admitted_signature_anchor(" + fields + ", "
                    "receipt(mechanical_admission([domain_agreement, no_displacement, "
                    "unique_best_score, no_fan_surplus, strong_sampled_band])))."
                )
            else:
                held += 1
                lines.append(
                    "held_signature_anchor(" + fields + ", "
                    f"held({reason}, defects({atoms(defects)})))."
                )
    lines.append("")

    unit_rows = [
        json.loads(line)
        for line in UNITS.read_text(encoding="utf-8").splitlines()
        if line.strip()
    ]
    unit_sha = sha256(UNITS)
    for line_number, row in enumerate(unit_rows, start=1):
        pairings = []
        for pairing in row.get("pairings", []):
            pairings.append(
                "pairing(%s, %s, %s, %s)"
                % (
                    atom(pairing.get("machine", "")),
                    atom(pairing.get("confidence", "")),
                    string(pairing.get("reason", "")),
                    atom(str(pairing.get("was_candidate", False)).lower()),
                )
            )
        lines.append(
            "held_unit_recognition_proposal("
            f"{atom(row['lesson'])}, [{', '.join(pairings)}], {string(row.get('gap', ''))}, "
            "anchor(source_file('data/research/grade78_pairing_proposals.jsonl'), "
            f"source_sha256('{unit_sha}'), jsonl_line({line_number})), "
            "testimony(model_proposal('scripts/research/propose_middle_school_pairings.py'), "
            f"{GENERATED}), held(no_mechanical_band))."
        )

    source_total = len(proposals) + len(unit_rows)
    held_total = held + len(unit_rows)
    band_dict = ", ".join(f"{key}:{value}" for key, value in sorted(bands.items()))
    lines[17:17] = [
        "review_proposal_admission_summary(",
        "    summary{",
        f"      source_rows: {source_total},",
        f"      admitted: {admitted}, held: {held_total},",
        f"      signature_anchor: summary{{source_rows:{len(proposals)}, admitted:{admitted}, held:{held}, by_band:dict{{{band_dict}}}}},",
        "      unit_recognition_set: summary{source_rows:%d, admitted:0, "
        "held:%d, by_band:dict{no_mechanical_band:%d}}"
        % (len(unit_rows), len(unit_rows), len(unit_rows)),
        "    }).",
        "",
    ]
    lines.extend(CHECK_SOURCE.splitlines())
    lines.append("")
    summary = {
        "source_rows": source_total,
        "admitted": admitted,
        "held": held_total,
        "signature_anchor": {"source_rows": len(proposals), "admitted": admitted, "held": held, "by_band": dict(bands)},
        "unit_recognition_set": {"source_rows": len(unit_rows), "admitted": 0, "held": len(unit_rows), "by_band": {"no_mechanical_band": len(unit_rows)}},
    }
    return "\n".join(lines), summary


CHECK_SOURCE = r'''%! check_admitted_review_proposals is det.
check_admitted_review_proposals :-
    findall(F-S-T-I, admitted_signature_anchor(F,S,T,I,_,_,_,_,_), AdmittedIds),
    findall(F-S-T-I, held_signature_anchor(F,S,T,I,_,_,_,_,_), HeldIds),
    append(AdmittedIds, HeldIds, CorpusIds),
    sort(CorpusIds, UniqueCorpusIds),
    length(CorpusIds, CorpusCount), length(UniqueCorpusIds, CorpusCount),
    findall(L, held_unit_recognition_proposal(L,_,_,_,_,_), UnitIds),
    sort(UnitIds, UniqueUnitIds),
    length(UnitIds, UnitCount), length(UniqueUnitIds, UnitCount),
    forall(admitted_signature_anchor(_,_,_,_,_,_,
               anchor(_,_,_,_,_,score_band(rank_4_strong_sampled_band),_,_),_,
               receipt(mechanical_admission(Checks))),
           ( memberchk(domain_agreement, Checks),
             memberchk(no_displacement, Checks),
             memberchk(unique_best_score, Checks),
             memberchk(no_fan_surplus, Checks),
             memberchk(strong_sampled_band, Checks) )),
    review_proposal_admission_summary(Summary),
    get_dict(signature_anchor, Summary, CorpusSummary),
    get_dict(source_rows, CorpusSummary, CorpusCount),
    get_dict(unit_recognition_set, Summary, UnitSummary),
    get_dict(source_rows, UnitSummary, UnitCount),
    get_dict(admitted, Summary, AdmittedCount), length(AdmittedIds, AdmittedCount),
    get_dict(held, Summary, HeldCount), length(HeldIds, CorpusHeldCount),
    HeldCount is CorpusHeldCount + UnitCount,
    SourceCount is CorpusCount + UnitCount,
    format('check_admitted_review_proposals: ~d admitted, ~d held, ~d source rows~n',
           [AdmittedCount, HeldCount, SourceCount]).
'''


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output", type=Path, default=OUTPUT)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    rendered, summary = render()
    if args.check:
        if not args.output.is_file() or args.output.read_text(encoding="utf-8") != rendered:
            raise SystemExit(f"{args.output} is stale; regenerate with this script")
    else:
        args.output.parent.mkdir(parents=True, exist_ok=True)
        args.output.write_text(rendered, encoding="utf-8")
    print(json.dumps(summary, indent=1, sort_keys=True))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
